### PR TITLE
fix(Text input): Added aria-expanded

### LINKED ISSUE #9305: Bug - TextInput - aria-expanded not set
**Describe the problem**

The [Accessibility](https://pf5.patternfly.org/components/forms/form-control#accessibility) table for the `TextInput` component suggests that the `aria-expanded` attribute should be set, however when using the flag `isExpanded` it is not.

### PR DESCRIPTION
**Pull request by tlabaj**
**What**: Closes #9305

### CODE REVIEW

File: packages/react-core/src/components/TextInput/TextInput.tsx [hunk 1]
```diff
@@ -215,6 +215,7 @@ export class TextInputBase extends React.Component<TextInputProps, TextInputStat
           type={type}
           value={this.sanitizeInputValue(value)}
           aria-invalid={props['aria-invalid'] ? props['aria-invalid'] : validated === ValidatedOptions.error}
+          aria-expanded={isExpanded}
```
Comment (thatblindgeye) [inline packages/react-core/src/components/TextInput/TextInput.tsx:218]: This is more to do with the default value of the isExpanded prop, but the default value should be undefined rather than false. Right now every instance of a Textinput is going to render with the `aria-expanded` attribute due to the default `false` value, but we would only want that if the text input has some sort of expanding functionality.

**Review by thatblindgeye — CHANGES_REQUESTED** [review]
In addition to below comment + Slack convo, Core would need to be updated to include:

- aria-expanded should be either true or false (not just true as currently in the Core docs) if the text input has any form of expanding functionality
- aria-controls must be set (similar to our Select typeahead example) if aria-expanded is passed in
- role="combobox" must be set if aria-expanded is passed in

Though ultimately this info would live in the a11y docs in Org, so it depends if we want to have that info in the Core docs for now and then just remove it once we do add proper a11y docs for TextInput in Org

File: packages/react-core/src/components/TextInput/TextInput.tsx [hunk 2]
```diff
@@ -26,15 +26,22 @@ export enum TextInputReadOnlyVariant {
   plain = 'plain'
 }
 
+interface TextinputExpandedObj {
+  isExpanded: boolean;
+  ariaControls: string;
+}
```
Comment (thatblindgeye) [inline packages/react-core/src/components/TextInput/TextInput.tsx:32]: Can we do the following:

- (nit) update the name to `TextInputExpandedObj` (input is lowercased currently)
- export the interface
- add it to the props table
- add descriptions for the props

Not sure if it's common in other components, but also thinking the `ariaControls` should be kebab cased like other basic aria props (`aria-labelledby` and such), but not a blocker

File: packages/react-core/src/components/TextInput/TextInput.tsx [hunk 3]
```diff
@@ -26,15 +26,22 @@ export enum TextInputReadOnlyVariant {
...
+
 export interface TextInputProps
   extends Omit<React.HTMLProps<HTMLInputElement>, 'onChange' | 'onFocus' | 'onBlur' | 'disabled' | 'ref'>,
     OUIAProps {
   /** Additional classes added to the text input. */
   className?: string;
   /** Flag to show if the text input is disabled. */
   isDisabled?: boolean;
-  /** Flag to apply expanded styling */
+  /** @deprecated Flag to apply expanded styling */
```
Comment (thatblindgeye) [inline packages/react-core/src/components/TextInput/TextInput.tsx:41]:
```suggestion
  /** @deprecated Flag to apply expanded styling. expandedProps should now be used instead. */
```

File: packages/react-core/src/components/TextInput/TextInput.tsx [hunk 4]
```diff
@@ -26,15 +26,22 @@ export enum TextInputReadOnlyVariant {
...
   isExpanded?: boolean;
+  /** Prop to apply expanded styling to the text input and link it toe the element it is controlling. This should be used when the input controls a menu and tha menu is expanded. */
```
Comment (thatblindgeye) [inline packages/react-core/src/components/TextInput/TextInput.tsx:43]:
```suggestion
  /** Prop to apply expanded styling to the text input and link it to the element it is controlling. This should be used when the input controls a menu and that menu is expandable. */
```

File: packages/react-core/src/components/TextInput/TextInput.tsx [hunk 5]
```diff
@@ -193,6 +201,9 @@ export class TextInputBase extends React.Component<TextInputProps, TextInputStat
     } = this.props;
 
     const hasStatusIcon = ['success', 'error', 'warning'].includes(validated);
+    const ariaExpandedProps = expandedProps?.isExpanded
+      ? { 'aria-expanded': expandedProps?.isExpanded, 'aria-controls': expandedProps?.ariaControls, role: 'combobox' }
+      : {};
```
Comment (thatblindgeye) [inline packages/react-core/src/components/TextInput/TextInput.tsx:206]:
```suggestion
    const ariaExpandedProps = expandedProps
      ? { 'aria-expanded': expandedProps.isExpanded, 'aria-controls': expandedProps.ariaControls, role: 'combobox' }
      : {};
```

We'll want these props added as long as expandedProps is passed rather than only when `isExpanded` is true.

File: packages/react-core/src/components/TextInput/TextInput.tsx [hunk 6]
```diff
@@ -215,6 +226,7 @@ export class TextInputBase extends React.Component<TextInputProps, TextInputStat
           type={type}
           value={this.sanitizeInputValue(value)}
           aria-invalid={props['aria-invalid'] ? props['aria-invalid'] : validated === ValidatedOptions.error}
+          {...(expandedProps?.isExpanded && { ...ariaExpandedProps })}
```
Comment (thatblindgeye) [inline packages/react-core/src/components/TextInput/TextInput.tsx:229]: We should be able to just spread ariaExpandedProps here without the `expandedProps.isExpanded &&...` since we're checking that when defining ariaExpandedProps

File: packages/react-core/src/components/TextInput/__tests__/TextInput.test.tsx [hunk 7]
```diff
@@ -124,4 +124,13 @@ describe('TextInput', () => {
...
   });
+
+  test('has aria-expanded set to true when ariaProps.isExpanded is true', () => {
+    render(<TextInput expandedProps={{isExpanded: true, ariaControls: 'test'}}  aria-label="isExpanded"/>);
+
+    const input = screen.getByLabelText('isExpanded');
+    expect(input).toHaveAttribute('aria-expanded', 'true');
+    expect(input).toHaveAttribute('role', 'combobox');
+    expect(input).toHaveAttribute('aria-controls', 'test');
+  });
```
Comment (thatblindgeye) [inline packages/react-core/src/components/TextInput/__tests__/TextInput.test.tsx:135]: I might lean towards having this split up to 3 separate tests rather than checking  that all 3 attributes are present.

For the role test, we'd also be able to do `const input = screen.getByRole('combobox')` as well, then just check that it's visible/in the document

**Review by thatblindgeye — CHANGES_REQUESTED** [review]

File: packages/react-core/src/components/TextInput/__tests__/TextInput.test.tsx (hunk 7 above)
Comment (tlabaj) [reply packages/react-core/src/components/TextInput/__tests__/TextInput.test.tsx:135]: I don't know that it is worth it to re-render the same thing to check for different attributes?

**Review by thatblindgeye — APPROVED** [review]
Looks good! For the test comment above, only nit would be the test description could be updated to better reflect what's being tested ("Passes expandedProps to internal input" or something along those lines?), but that and/or splitting them out isn't a blocker

**Review by kmcfaul — APPROVED** [review]
