### PR TITLE
fix(aboutmodal): set a customize aria-label to the close button

### LINKED ISSUE #3855: AboutModal:  aria-label on the close button can not be overridden
**Describe the issue. What is the expected and unexpected behavior?**
The aria-label in the About Modal is hard coded.  The consumer should be able to override it.

### PR DESCRIPTION
**Pull request by boaz0**
**What**: Closes #3855

### CODE REVIEW

File: packages/react-core/src/components/AboutModal/AboutModalBoxCloseButton.tsx [hunk 1]
```diff
@@ -9,15 +9,18 @@ export interface AboutModalBoxCloseButtonProps extends React.HTMLProps<HTMLDivEl
   className?: string;
   /** A callback for when the close button is clicked  */
   onClose?: () => void;
+  /** set aria label on the close button */
```
Comment (tlabaj) [inline packages/react-core/src/components/AboutModal/AboutModalBoxCloseButton.tsx]: Can you update this to be sentence case please.

File: packages/react-core/src/components/AboutModal/AboutModalContainer.tsx [hunk 2]
```diff
@@ -37,6 +37,8 @@ export interface AboutModalContainerProps extends React.HTMLProps<HTMLDivElement
   ariaLabelledbyId: string;
   /** id to use for About Modal Box aria described by  */
   ariaDescribedById: string;
+  /** set aria label to the close button */
```
Comment (tlabaj) [inline packages/react-core/src/components/AboutModal/AboutModalContainer.tsx]: Sentence case here too please.
