### PR TITLE
fix(Select): grouped Select generates invalid HTML

### LINKED ISSUE #4917: Invalid HTML in grouped menus
In grouped menus, the list items need to be wrapped in a `<ul>`. Noticed this in the grouped single and grouped typeahead examples.

Screen Shot 2020-09-30 at 2 54 05 PM

### PR DESCRIPTION
**Pull request by KKoukiou**
Fixes #4917

### CODE REVIEW

**Review by nicolethoen — COMMENTED** [review]
The dividers are not wrapped in an `li` tag.
I'm a little afraid to comment that, and i don't know if it's invalid HTML or not without looking it up.
If we need to wrap the dividers, we need to make sure that the keyboard interactions still work in the typeahead variants.

**Review by redallen — APPROVED** [review]

File: packages/react-core/src/components/Select/SelectGroup.tsx [hunk 1]
```diff
@@ -20,11 +20,11 @@ export const SelectGroup: React.FunctionComponent<SelectGroupProps> = ({
...
 }: SelectGroupProps) => (
-  <div {...props} className={css(styles.selectMenuGroup, className)}>
-    <div className={css(styles.selectMenuGroupTitle)} id={titleId} aria-hidden>
-      {label}
-    </div>
-    {children}
-  </div>
+  <li {...props} className={css(styles.selectMenuGroupTitle, className)} id={titleId}>
+    {label}
+    <ul className={css(styles.selectMenuGroup)} role="listbox">
```
Comment (jschuler) [inline packages/react-core/src/components/Select/SelectGroup.tsx:25]: I think you should only change that `children` is wrapped by `<ul className={css(styles.selectMenuGroup)} role="listbox">`, and leave the outer elements the way they were

**Review by jschuler — CHANGES_REQUESTED** [review]

File: packages/react-core/src/components/Select/SelectGroup.tsx (hunk 1 above)
Comment (KKoukiou) [reply packages/react-core/src/components/Select/SelectGroup.tsx:25]: That's what the issue description suggests to do, but if you read the specification of what can be child of UL is not contain divs.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ul

SelectGroups is direct child of UI, and should not contain any divs in other words.

**Comment by KKoukiou** [comment]
> The dividers are not wrapped in an `li` tag.
> I'm a little afraid to comment that, and i don't know if it's invalid HTML or not without looking it up.
> If we need to wrap the dividers, we need to make sure that the keyboard interactions still work in the typeahead variants.

Good catch, it's essentially the same problem, do you want me to fix it within this PR, on send another one?
(this fix is a standalone so I suggest to not block it on fixing more things)

File: packages/react-core/src/components/Select/SelectGroup.tsx (hunk 1 above)
Comment (jschuler) [reply packages/react-core/src/components/Select/SelectGroup.tsx:25]: The DOM should look similar to this (copied from Core example):
Screen Shot 2020-10-01 at 1 43 16 PM

Comment (jschuler) [reply packages/react-core/src/components/Select/SelectGroup.tsx:25]: Also the changes break the styling a bit, additional indentation etc
https://patternfly-react-pr-4919.surge.sh/components/select#grouped-checkbox-input

Comment (KKoukiou) [reply packages/react-core/src/components/Select/SelectGroup.tsx:25]: Ack I see it now in the HTML docs. I will adjust it tomorrow.
Thanks for the review.

Comment (KKoukiou) [reply packages/react-core/src/components/Select/SelectGroup.tsx:25]: I wonder if it's a concious decision though that nested ul li were not used in the HTML docs.

For me it makes sense that the outer items would be also a list (ul) since there indeed part of a list.

@mcarrano I guess you can answer this one :)  For example this https://patternfly-react-pr-4919.surge.sh/components/select/#grouped-single

File: packages/react-core/src/components/Select/SelectGroup.tsx [hunk 2]
```diff
@@ -20,11 +20,11 @@ export const SelectGroup: React.FunctionComponent<SelectGroupProps> = ({
   titleId = '',
   ...props
 }: SelectGroupProps) => (
-  <div {...props} className={css(styles.selectMenuGroup, className)}>
```
Comment (mcoker) [inline packages/react-core/src/components/Select/SelectGroup.tsx:23]: This was fine as it is. The structure should be

```
div.selectMenuGroup
    div.selectMenuGroupTitle
    ul
        li
        li
        ....
```

You can see the basic structure in the favorites example, except the `li`'s in the favorites are `li.pf-c-select__menu-wrapper` and they should be `li.pf-c-select__menu-item` in non-favorites lists.

File: packages/react-core/src/components/Select/SelectGroup.tsx (hunk 1 above)
Comment (mcarrano) [reply packages/react-core/src/components/Select/SelectGroup.tsx:25]: @mcoker can you answer the question above?

Comment (mcoker) [reply packages/react-core/src/components/Select/SelectGroup.tsx:25]: @jschuler is right with the screenshot posted above. I left the same basic comment here - https://github.com/patternfly/patternfly-react/pull/4919#discussion_r498446371

FWIW you can find the same basic structure in the dropdown, or any menu with groups/titles https://www.patternfly.org/v4/components/dropdown/react/with-groups/

```
div/section.section
    div/h1-h6.section-title
    ul
        li
        li
        ....
```

**Review by jschuler — APPROVED** [review]
LGTM

**Comment by KKoukiou** [comment]
> LGTM

I needed to rebase - had merge conflicts. Sorry :(

**Review by mcoker — APPROVED** [review]
lgtm! 🤩

**Review by redallen — APPROVED** [review]
