### PR TITLE
fix(inline-styles): remove inject and Stylesheet.parse inline references

### LINKED ISSUE #2606: Avoid inline-styling to meet  tighter content-security-policy
To make use of the patternfly-react in projects with higher security demands, like the Cockpit (www.cockpit-project.org), modifications/use of style HTML element attribute must be avoided.

I tried to import Table component, and I got the following warning in the browser:
```

  | insert | @ | index.esm.js:198
-- | -- | -- | --
  | insertRule | @ | index.esm.js:242
  | toSheet | @ | index.js:16
  | ruleSheet | @ | index.js:44
  | H | @ | stylis.esm.js:526
  | B | @ | stylis.esm.js:588
  | stylis | @ | index.esm.js:407
  | insert | @ | index.esm.js:415
  | injectGlobal | @ | index.esm.js:441
  | inject | @ | StyleSheet.js:45
  | ./node_modules/@patternfly/react-core/dist/esm/layouts/Toolbar/Toolbar.js | @ | Toolbar.js:38
  | __webpack_require__ | @ | bootstrap:19
  | ./node_modules/@patternfly/react-core/dist/esm/layouts/Toolbar/index.js | @ | index.js:1
  | __webpack_require__ | @ | bootstrap:19
  | ./node_modules/@patternfly/react-core/dist/esm/layouts/index.js | @ | index.js:1
  | __webpack_require__ | @ | bootstrap:19
  | ./node_modules/@patternfly/react-core/dist/esm/index.js | @ | index.js:1
  | __webpack_require__ | @ | bootstrap:19
  | ./node_modules/@patternfly/react-table/dist/esm/components/Table/ActionsColumn.js | @ | ActionsColumn.js:1
  | __webpack_require__ | @ | bootstrap:19
  | ./node_modules/@patternfly/react-table/dist/esm/components/Table/index.js | @ | index.js:1
  | __webpack_require__ | @ | bootstrap:19
  | ./node_modules/@patternfly/react-table/dist/esm/components/index.js | @ | index.js:1
  | __webpack_require__ | @ | bootstrap:19
  | ./node_modules/@patternfly/react-table/dist/esm/index.js | @ | index.js:1
  | __webpack_require__ | @ | bootstrap:19
  | ./pkg/machines/components/vmDisksTab.jsx | @ | vmDisksTab.jsx:1
  | __webpack_require__ | @ | bootstrap:19
  | ./pkg/machines/components/vmDisksTabLibvirt.jsx | @ | vmDisksTabLibvirt.jsx:1
  | __webpack_require__ | @ | bootstrap:19
  | ./pkg/machines/components/vm/vm.jsx | @ | vm.jsx:1
  | __webpack_require__ | @ | bootstrap:19
  | ./pkg/machines/hostvmslist.jsx | @ | hostvmslist.jsx:1
  | __webpack_require__ | @ | bootstrap:19
  | ./pkg/machines/app.jsx | @ | machines.js:294799
  | __webpack_require__ | @ | bootstrap:19
  | ./pkg/machines/index.js | @ | machines.js:305312
  | __webpack_require__ | @ | bootstrap:19
  | 5 | @ | machines.js:309979
  | __webpack_require__ | @ | bootstrap:19
  | (anonymous) | @ | bootstrap:83
  | (anonymous) | @ | bootstrap:83
```

Looks like that some of your component are injecting styles into the html.
```
[kkoukiou@sequoia patternfly-react]$ git grep 'inject()'
packages/patternfly-4/react-core/src/layouts/Toolbar/Toolbar.tsx:toolbarCss.inject();
packages/patternfly-4/react-core/src/layouts/Toolbar/ToolbarGroup.tsx:toolbarCss.inject();
packages/patternfly-4/react-core/src/layouts/Toolbar/ToolbarItem.tsx:toolbarCss.inject();
packages/patternfly-4/react-core/src/layouts/Toolbar/ToolbarSection.tsx:toolbarCss.inject();
packages/patternfly-4/react-inline-edit-extension/src/components/InlineEdit/ConfirmButtons.js:inlineEditCss.inject();
packages/patternfly-4/react-inline-edit-extension/src/components/InlineEdit/editableRowWrapper.js:inlineEditCss.inject();
packages/patternfly-4/react-styles/README.md:styles.inject();
packages/patternfly-4/react-styles/src/StyleSheet.d.ts:  inject(): void;
packages/patternfly-4/react-styles/src/StyleSheet.js:      // style.__inject();
packages/patternfly-4/react-styles/src/utils.d.ts:  __inject(): void;
packages/patternfly-4/react-styles/src/utils.js:    __inject() {
packages/patternfly-4/react-topology/src/components/TopologyControlBar/TopologyControlBar.tsx:topologyControlbarCss.inject();
packages/patternfly-4/react-topology/src/components/TopologySideBar/TopologySideBar.tsx:topologySideBarCss.inject();
packages/patternfly-4/react-topology/src/components/TopologyView/TopologyView.tsx:topologyViewCss.inject();
```

Can we use css for that?

### PR DESCRIPTION
**Pull request by priley86**
**What**:
Closes #2606 

cc: @redallen 

**Additional issues**:

### CODE REVIEW

File: packages/patternfly-4/react-core/scripts/copyStyles.js [hunk 1]
```diff
@@ -41,3 +44,20 @@ copySync(join(pfDir, 'assets/fonts'), join(stylesDir, 'assets/fonts'), {
...
+
+// Copy component css
+const srcDir = join('./src');
+const distDirs = [join('./dist/js'), join('./dist/esm'), join('./dist/umd')];
+
+const files = glob.sync('**/*.css', {
+  cwd: srcDir
+});
+
+files.forEach(file => {
```
Comment (dgutride) [inline packages/patternfly-4/react-core/scripts/copyStyles.js]: I'm concerned about adding any support for inline/required css directly to react-core.  Maybe we can consider the use of CSS directly an antipattern and make sure we don't make it easy for people to do.  For now, can we put this CSS directly into react-styles instead so we don't add the ability for direct inclusion through react-core?

Comment (priley86) [reply packages/patternfly-4/react-core/scripts/copyStyles.js]: ok, will try changing this to something more like:
```
import '@patternfly/react-styles/css/components/Tooltip/popover-base-styles.css';
```
as a next step...

Comment (priley86) [reply packages/patternfly-4/react-core/scripts/copyStyles.js]: updated! PTAL @dgutride
