### PR TITLE
fix(Drawer): initial width doesn't respect min/max widths

### LINKED ISSUE #5278: Resizable drawer: initial size doesn't adhere to min/max size props

### PR DESCRIPTION
**Pull request by kmcfaul**
**What**: Closes #5278 & #5280

Adds a new `defaultSize` prop to control starting width for resizable drawers. 

A resizable drawer will start at `defaultSize`, or `minSize` if `defaultSize` is undefined and `minSize` is given, or the default drawer width if neither property is given.

Added default and min sizes to the examples to address #5280 (because our examples, which focus the drawer content, was also causing trouble for the scrolling).

### CODE REVIEW

**Review by tlabaj — CHANGES_REQUESTED** [review]
Looks good. Can you update the integration app and add a test for this please.

**Review by jschuler — APPROVED** [review]

**Review by tlabaj — DISMISSED** [review]

**Review by jessiehuff — APPROVED** [review]
LGTM! :)

**Comment by kmcfaul** [comment]
Added default and min sizes for our resizable examples because the code, which focuses the drawer panel content on expansion, was also causing the bug in #5280 by scrolling. 

@mcoker I noticed while adding min sizes that for a left expanding resizable drawer, if the min size is too small, the splitter will disappear into the panel before hitting the min width. I think this is because the splitter is after the panel content (which gets the min width)? If you decrease the left-drawer's `minSize` to `150` from `200`, you can see the behavior.

**Review by tlabaj — APPROVED** [review]

**Comment by mcoker** [comment]
@kmcfaul 

> If you decrease the left-drawer's minSize to 150 from 200, you can see the behavior.

It looks like if we add the `.pf-c-drawer__panel-main` element adjacent to the splitter in resizable drawers, that should fix this problem.

Also for resizable drawers, we need to update the var we use to customize the width from `--pf-c-drawer__panel--FlexBasis` to `--pf-c-drawer__panel--m-resizable--FlexBasis`. We only apply changes to that var if they're above the mobile layout breakpoint.

**Comment by kmcfaul** [comment]
For clarity, the changes @mcoker suggests I have ready to go pending another core bump, but these don't impact this PR and can be added in a follow up if necessary. This PR should be ready to go in.

File: packages/react-core/src/components/Drawer/DrawerPanelContent.tsx [hunk 1]
```diff
@@ -17,8 +17,10 @@ export interface DrawerPanelContentProps extends React.HTMLProps<HTMLDivElement>
   isResizable?: boolean;
   /** Callback for resize end. */
   onResize?: (width: number, id: string) => void;
-  /** The minimum size of a resizable drawer, in pixels. Defaults to the starting width of the drawer. */
+  /** The minimum size of a resizable drawer, in pixels. Defaults to 0. */
   minSize?: number;
+  /** The starting size of a resizable drawer, in pixels. Defaults to minSize. */
```
[the remark this answers is not in the document]
Comment (kmcfaul) [reply packages/react-core/src/components/Drawer/DrawerPanelContent.tsx:22]: Oh nice catch for this bug. The code isn't setting the style because 0 === false for the check to add it. I'll fix the logic.

**Comment by kmcfaul** [comment]
Last big update for this PR, pulling in the latest core changes which fixes #5283 as well as updates how min and max size are set and controlled.

File: packages/react-core/src/components/Drawer/DrawerPanelContent.tsx [hunk 2]
```diff
@@ -17,17 +17,19 @@ export interface DrawerPanelContentProps extends React.HTMLProps<HTMLDivElement>
   isResizable?: boolean;
   /** Callback for resize end. */
   onResize?: (width: number, id: string) => void;
-  /** The minimum size of a resizable drawer, in pixels. Defaults to the starting width of the drawer. */
+  /** The minimum size of a drawer, in pixels. */
   minSize?: number;
-  /** The maximum size of a resizable drawer, in pixels. Defaults to the max width of the parent container. */
+  /** The starting size of a resizable drawer, in pixels. */
+  defaultSize?: number;
```
Comment (mcoker) [inline packages/react-core/src/components/Drawer/DrawerPanelContent.tsx:23]: is there a requirement for this to be in pixels? The var doesn't care what the unit is - px, %, em vw, etc... and that works with the CSS that keeps it within the `minSize`/`maxSize`

Comment (kmcfaul) [reply packages/react-core/src/components/Drawer/DrawerPanelContent.tsx:23]: I could change it to a string property. The user would have to specify `px` or `%` in that case. Would that be okay?

Comment (kmcfaul) [reply packages/react-core/src/components/Drawer/DrawerPanelContent.tsx:23]: I had it in pixels so I could limit how much the `mousemove` would calculate and set a new size (throwing out the sizes outside the min/max). But since that's being done in CSS I can probably remove them.

**Comment by kmcfaul** [comment]
Updated `minSize`, `maxSize`, and `defaultSize` to `string` type, to support % boundaries. Removed code-side checking of boundaries because CSS maintains them. Updated docs.

**Comment by mcoker** [comment]
Just a nit but looks like there are 2 "Stacked content body elements" examples. Also I believe the "basic" and "panel on right", and "inline" and "inline panel on right" and are the same?

**Review by mcoker — APPROVED** [review]
LGTM! Great work @kmcfaul!! 🥳

**Comment by tlabaj** [comment]
Just need a rebase than it can go in.

**Review by tlabaj — APPROVED** [review]

**Review by evwilkin — APPROVED** [review]
LGTM
