### PR TITLE
fix(table): Specify button type to avoid unwanted form submits

### LINKED ISSUE #4251: Tables with sortable columns inside table cause unwanted submits
SortableColumn component renders html button without type specified.

Buttons without specified type attribute are treated as 'submit' buttons by browsers. This causes issues when a table with sortable columns is used inside a form as the form is submitted by clicking the sort buttons.

### PR DESCRIPTION
**Pull request by jtomasek**
Buttons without specified type attribute are treated as 'submit' buttons by browsers. This causes issues when a table with sortable columns is used inside a form as the form is submitted by clicking the sort buttons.

This change sets the button type to 'button' which establishes correct behaviour.

**What**: Closes #4251

### CODE REVIEW

File: packages/react-table/src/components/Table/SortColumn.tsx [hunk 1]
```diff
@@ -30,7 +30,12 @@ export const SortColumn: React.FunctionComponent<SortColumnProps> = ({
     SortedByIcon = ArrowsAltVIcon;
   }
   return (
-    <button {...props} className={css(className, styles.tableButton)} onClick={event => onSort && onSort(event)}>
+    <button
+      {...props}
```
Comment (mareklibra) [inline packages/react-table/src/components/Table/SortColumn.tsx:34]: Would it make sense to let the user change the type via SortColumn props?

Comment (jtomasek) [reply packages/react-table/src/components/Table/SortColumn.tsx]: Done

**Comment by jtomasek** [comment]
I've changed SortColumn definition such that the type is 'button' by default and it can be overridden by providing new type via props.

**Comment by redallen** [comment]
Rebased on `master` since `v4` is about to be deleted.

File: packages/react-table/src/components/Table/SortColumn.tsx [hunk 2]
```diff
@@ -7,7 +7,7 @@ import styles from '@patternfly/react-styles/css/components/Table/table';
 import { SortByDirection } from './Table';
 import { TableText } from './TableText';
 
-export interface SortColumnProps extends React.HTMLAttributes<HTMLButtonElement> {
+export interface SortColumnProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
```
Comment (redallen) [inline packages/react-table/src/components/Table/SortColumn.tsx:10]: What does this change do exactly? I think the old type is correct for `<button {...props}>`

File: packages/react-table/src/components/Table/SortColumn.tsx [hunk 3]
```diff
@@ -30,7 +30,12 @@ export const SortColumn: React.FunctionComponent<SortColumnProps> = ({
     SortedByIcon = ArrowsAltVIcon;
   }
   return (
-    <button {...props} className={css(className, styles.tableButton)} onClick={event => onSort && onSort(event)}>
+    <button
+      type="button"
```
Comment (redallen) [inline packages/react-table/src/components/Table/SortColumn.tsx:34]: If you want to make `type="button"` a default prop, do:
```
  sortDirection = '',
  type = 'button',
  ...props
}: SortColumnProps
```
...
`<button type={type}`
instead.

File: packages/react-table/src/components/Table/SortColumn.tsx (hunk 2 above)
Comment (jtomasek) [reply packages/react-table/src/components/Table/SortColumn.tsx:10]: React.HTMLAttributes is a common subset of all html element attributes, therefore it does not include button specific ones. For better explanation check: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/36505#issuecomment-549394273

File: packages/react-table/src/components/Table/SortColumn.tsx (hunk 3 above)
Comment (jtomasek) [reply packages/react-table/src/components/Table/SortColumn.tsx]: Done

File: packages/react-table/src/components/Table/SortColumn.tsx (hunk 2 above)
Comment (redallen) [reply packages/react-table/src/components/Table/SortColumn.tsx:10]: Wonderful, thanks for the explanation!

File: packages/react-table/src/components/Table/SortColumn.tsx (hunk 1 above)
Comment (seanforyou23) [reply packages/react-table/src/components/Table/SortColumn.tsx:35]: Do we also need to register the new type prop in `SortColumnProps` interface? I see the default value type = 'button', but maybe we need also something like `type?: 'button' | 'submit' | 'reset';` in the interface?

**Comment by redallen** [comment]
Will merge after RC2.
