### PR TITLE
fix(pageheader): use the correct type for the page context

### LINKED ISSUE #4549: Adding isManagedSidebar causes warnings
**Describe the issue. What is the expected and unexpected behavior?**
Adding isManagedSidebar prop causes warnings/errors
in header
```
index.js:2177 Warning: React does not recognize the `isManagedSidebar` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `ismanagedsidebar` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in header (created by Context.Consumer)
    in PageHeader (created by VerticalPage)
    in div (created by Page)
    in Page (created by VerticalPage)
```
and in the sidebar
```
Warning: React does not recognize the `isManagedSidebar` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `ismanagedsidebar` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in div (created by Context.Consumer)
    in PageSidebar (created by VerticalPage)
    in div (created by Page)
    in Page (created by VerticalPage)
    in VerticalPage (created by ErrorBoundary)
```
**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

just add `isManagedSidebar` to the example here: 
https://github.com/patternfly/patternfly-react/blob/master/packages/react-core/src/components/Page/examples/Page.md
```js
     <PageHeader
        isManagedSidebar
        logo="Logo"
        logoProps={logoProps}
        headerTools={<PageHeaderTools>header-tools</PageHeaderTools>}
        showNavToggle
        isNavOpen={isNavOpen}
        onNavToggle={this.onNavToggle}
      />
```
**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
This is a bug

### PR DESCRIPTION
**Pull request by boaz0**
**What**: Closes #4549 

`PageContext.Consumer` returns a children that is a function. And that function's argument is the values set in the `PageContext`.
However, in `PageHeader` there was a mistake that assumed the function's argument is `PageHeaderProps`. Which made the `PageHeaderProps` to have `isManagedSidebar` even though it's not used and caused a confusion.

This patch fixes that mistake.

This also solves the warning that were mentioned in #4549.

//cc @dtaylor113 @redallen

### CODE REVIEW

File: packages/react-core/src/components/Page/Page.tsx [hunk 1]
```diff
@@ -9,7 +9,18 @@ export enum PageLayouts {
   horizontal = 'horizontal'
 }
 
-const PageContext = React.createContext({});
+export interface PageCtx {
```
[the remark this answers is not in the document]
Comment (boaz0) [reply packages/react-core/src/components/Page/Page.tsx:12]: Sure! No problem! Thanks for the review

**Comment by boaz0** [comment]
@jschuler done

File: packages/react-core/src/components/Page/PageHeader.tsx [hunk 2]
```diff
@@ -22,11 +22,6 @@ export interface PageHeaderProps extends React.HTMLProps<HTMLDivElement> {
   showNavToggle?: boolean;
   /** True if the side nav is shown  */
   isNavOpen?: boolean;
-  /**
-   * If true, manages the sidebar open/close state and there is no need to pass the isNavOpen boolean into
-   * the sidebar component or add a callback onNavToggle function into the PageHeader component
-   */
-  isManagedSidebar?: boolean;
```
Comment (tlabaj) [inline packages/react-core/src/components/Page/PageHeader.tsx:29]: In order to not break consumers who may have added this prop, can we add it back at mark it as deprecated with a console warning.

Comment (boaz0) [reply packages/react-core/src/components/Page/PageHeader.tsx:29]: sure! :+1:
