### PR TITLE
perf(react-styles): remove emotion, fix types

### LINKED ISSUE #2919: Avoid inline-styling to meet tighter content-security-policy
@priley86 This was reported first here - https://github.com/patternfly/patternfly-react/issues/2606
And this was the fix PR https://github.com/patternfly/patternfly-react/pull/2653

But using the versions that are supposed to have this fix:
-    "@patternfly/react-core": "3.86.2",
-    "@patternfly/react-table": "2.16.16

Don't seem to remove the inline style warnings.

Maybe there are still some remainders?
```
  | makeStyleTag | @ | index.esm.js:145
-- | -- | -- | --
  | inject | @ | index.esm.js:167
  | createEmotion | @ | index.esm.js:265
  | (anonymous) | @ | index.esm.js:5
  | ./node_modules/emotion/dist/index.esm.js | @ | index.esm.js:17
  | __webpack_require__ | @ | bootstrap:19
  | ./node_modules/@patternfly/react-styles/dist/esm/StyleSheet.js | @ | StyleSheet.js:1
  | __webpack_require__ | @ | bootstrap:19
  | ./node_modules/@patternfly/react-styles/dist/esm/index.js | @ | index.js:1
  | __webpack_require__ | @ | bootstrap:19
  | ./node_modules/@patternfly/react-core/dist/esm/components/AboutModal/AboutModal.js | @ | AboutModal.js:1
  | __webpack_require__ | @ | bootstrap:19
  | ./node_modules/@patternfly/react-core/dist/esm/components/AboutModal/index.js | @ | index.js:1
  | __webpack_require__ | @ | bootstrap:19
  | ./node_modules/@patternfly/react-core/dist/esm/components/index.js | @ | index.js:1
  | __webpack_require__ | @ | bootstrap:19
  | ./node_modules/@patternfly/react-core/dist/esm/index.js | @ | index.js:1
  | __webpack_require__ | @ | bootstrap:19
  | ./node_modules/@patternfly/react-table/dist/esm/components/Table/ActionsColumn.js | @ | ActionsColumn.js:1
  | __webpack_require__ | @ | bootstrap:19
  | ./node_modules/@patternfly/react-table/dist/esm/components/Table/index.js | @ | index.js:1
  | __webpack_require__ | @ | bootstrap:19
  | ./node_modules/@patternfly/react-table/dist/esm/components/index.js | @ | index.js:1
  | __webpack_require__ | @ | bootstrap:19
  | ./node_modules/@patternfly/react-table/dist/esm/index.js | @ | index.js:1
  | __webpack_require__ | @ | bootstrap:19
  | ./pkg/machines/components/vmDisksTab.jsx | @ | vmDisksTab.jsx:1
  | __webpack_require__ | @ | bootstrap:19
  | ./pkg/machines/components/vmDisksTabLibvirt.jsx | @ | vmDisksTabLibvirt.jsx:1
  | __webpack_require__


```

### PR DESCRIPTION
**Pull request by redallen**
**What**: Part of breaking change release. Closes #2919.

I also took the opportunity to remove react-styles'
```js
export function getModifier(styleObj, modifier, defaultModifier) {
  if (!styleObj) {
    return null;
  }

  const modifiers = styleObj.modifiers || styleObj;
  return modifiers[modifier] || modifiers[camelcase(modifier)] || defaultModifier;
}
```
which was really just circumventing type issues for `styles.modifiers[modifierString]`. This took changing the type of `modifierString` in many components and brought up some bugs with unused or incorrect `modifierString`s which I think improves our overall type quality.

I also removed our Jest CSS renderer living in react-styles which was designed for our old webpack loader CSS-in-JS solution. This reduced test time to 45s from 3m.

### @patternfly/react-styles
- No longer reexports functions from `emotion`
- Remove all exports except for the `css` function and CSS-in-JS stylesheets in the `css` folder
### @patternfly/react-core
- Replaced `[BackgroundImageSrc.{sm,xs2x,sm,sm2x,lg}]` with strings `'sm' | 'xs2x' | 'sm' | 'sm2x' | 'lg'`
- Removed always ignored `[BackgroundImageSrc.filter]` for new `filter` prop of type `ReactNode`

### CODE REVIEW

File: packages/react-core/src/components/BackgroundImage/BackgroundImage.tsx [hunk 1]
```diff
@@ -48,52 +48,24 @@ export const BackgroundImage: React.FunctionComponent<BackgroundImageProps> = ({
...
-            <feFuncB type="table" tableValues="0.086274509803922 0.43921568627451" />
-            <feFuncA type="table" tableValues="0 1" />
-          </feComponentTransfer>
-        </filter>
-      </svg>
-    </div>
-  );
-};
+}: BackgroundImageProps) => (
+  <div className={css(styles.backgroundImage, className)} {...props}>
```
Comment (dlabrecq) [inline packages/react-core/src/components/BackgroundImage/BackgroundImage.tsx]: Did we introduce a breaking change here? 

The `cssVariables` const and exported `BackgroundImageSrc` enum appear to be unused.

This was in place was so devs didn't need to provide a src path. I recall this was difficult to nail down, but maybe that's available via core CSS now?

Comment (redallen) [reply packages/react-core/src/components/BackgroundImage/BackgroundImage.tsx]: Yep, this is a problem that needs addressing.

This whole PR is a breaking change, though, so I'll find a solution and push it once the rest looks good.

Comment (redallen) [reply packages/react-core/src/components/BackgroundImage/BackgroundImage.tsx]: I found inline styles works great: no need for emotion.

File: packages/react-core/src/components/DataList/DataList.tsx [hunk 2]
```diff
@@ -33,9 +34,10 @@ export const DataList: React.FunctionComponent<DataListProps> = ({
   'aria-label': ariaLabel,
   selectedDataListItemId = '',
   onSelectDataListItem,
+  isCompact = false,
   ...props
 }: DataListProps) => {
-  const isSelectable = !isUndefined(onSelectDataListItem);
+  const isSelectable = onSelectDataListItem !== undefined;
```
Comment (ddonahue007) [inline packages/react-core/src/components/DataList/DataList.tsx]: Why this change? More curious than anything. Using lodash seems like the pattern we follow through patternfly. Is there a benefit for this change?

Comment (redallen) [reply packages/react-core/src/components/DataList/DataList.tsx]: We do not list lodash as a dependency for react-core, and the few calls we make to it are for simple helpers that we can implement ourselves (I literally copied their implementation of `isUndefined` which is just `x === undefined`). The benefits are smaller bundle sizes, making #3836 easier, and one less dependency to track.

File: packages/react-core/src/components/BackgroundImage/BackgroundImage.tsx [hunk 3]
```diff
@@ -1,98 +1,70 @@
...
   xs: string;
   xs2x: string;
   sm: string;
   sm2x: string;
   lg: string;
-  filter?: string;
 }
 
+const defaultFilter = (
+  <filter className="test123">
```
Comment (jschuler) [inline packages/react-core/src/components/BackgroundImage/BackgroundImage.tsx]: more descriptive class name?

File: packages/react-core/src/components/BackgroundImage/BackgroundImage.tsx [hunk 4]
```diff
@@ -1,98 +1,70 @@
...
-            0 0 0 1 0"
-          />
-          <feComponentTransfer colorInterpolationFilters="sRGB" result="duotone">
-            <feFuncR type="table" tableValues="0.086274509803922 0.43921568627451" />
-            <feFuncG type="table" tableValues="0.086274509803922 0.43921568627451" />
-            <feFuncB type="table" tableValues="0.086274509803922 0.43921568627451" />
-            <feFuncA type="table" tableValues="0 1" />
-          </feComponentTransfer>
-        </filter>
+        {React.cloneElement(filter, { id: filterId })}
```
Comment (jschuler) [inline packages/react-core/src/components/BackgroundImage/BackgroundImage.tsx]: why assign an id?

File: packages/react-core/src/components/Card/Card.tsx [hunk 5]
```diff
@@ -8,7 +8,7 @@ export interface CardProps extends React.HTMLProps<HTMLElement> {
   /** Additional classes added to the Card */
   className?: string;
   /** Sets the base component to render. defaults to article */
-  component?: keyof JSX.IntrinsicElements;
```
Comment (jschuler) [inline packages/react-core/src/components/Card/Card.tsx]: this is rendered as DOM element like 'div', should not be react node

File: packages/react-core/src/components/Card/CardBody.tsx [hunk 6]
```diff
@@ -8,7 +8,7 @@ export interface CardBodyProps extends React.HTMLProps<HTMLDivElement> {
   /** Additional classes added to the Card Body */
   className?: string;
   /** Sets the base component to render. defaults to div */
-  component?: keyof JSX.IntrinsicElements;
```
Comment (jschuler) [inline packages/react-core/src/components/Card/CardBody.tsx]: same comment here, it needs to be a valid DOM element

File: packages/react-core/src/components/Card/CardFooter.tsx [hunk 7]
```diff
@@ -8,7 +8,7 @@ export interface CardFooterProps extends React.HTMLProps<HTMLDivElement> {
   /** Additional classes added to the Footer */
   className?: string;
   /** Sets the base component to render. defaults to div */
-  component?: keyof JSX.IntrinsicElements;
```
Comment (jschuler) [inline packages/react-core/src/components/Card/CardFooter.tsx]: same comment here, it needs to be a valid DOM element

File: packages/react-core/src/components/ChipGroup/Chip.tsx [hunk 8]
```diff
@@ -91,6 +91,7 @@ class Chip extends React.Component<ChipProps & InjectedOuiaProps, ChipState> {
         <Tooltip position={tooltipPosition} content={children}>
           <Component
             className={css(styles.chip, isReadOnly && styles.modifiers.readOnly, className)}
+            tabIndex="0"
```
Comment (jschuler) [inline packages/react-core/src/components/ChipGroup/Chip.tsx]: why this?

File: packages/react-core/src/components/DataList/DataList.tsx [hunk 9]
```diff
@@ -15,6 +14,8 @@ export interface DataListProps extends React.HTMLProps<HTMLUListElement> {
   onSelectDataListItem?: (id: string) => void;
   /* Id of DataList item currently selected */
   selectedDataListItemId?: string;
+  /** Flag indicating if DataList should have compact styling */
+  isCompact?: boolean;
```
Comment (jschuler) [inline packages/react-core/src/components/DataList/DataList.tsx]: looks like a feature addition to me, perhaps better in a separate PR?

File: packages/react-core/src/components/ChipGroup/ChipGroupToolbarItem.tsx [hunk 10]
```diff
@@ -19,47 +20,93 @@ export interface ChipGroupToolbarItemProps extends React.HTMLProps<HTMLUListElem
...
+      onClick,
+      tooltipPosition,
+      ...rest
+    } = this.props;
+
+    if (React.Children.count(children)) {
+      const renderChipGroup = (id: string, HeadingLevel: any) => (
+        <ul className={css(styles.chipGroup, styles.modifiers.toolbar, className)} {...rest}>
+          <li>
+            {this.state.isTooltipVisible ? (
```
Comment (jschuler) [inline packages/react-core/src/components/ChipGroup/ChipGroupToolbarItem.tsx]: feature changes should be in a separate PR

Comment (redallen) [reply packages/react-core/src/components/ChipGroup/ChipGroupToolbarItem.tsx]: This change comes from merging `master` into `v4`.

File: packages/react-core/src/components/DataList/DataList.tsx (hunk 9 above)
Comment (redallen) [reply packages/react-core/src/components/DataList/DataList.tsx]: This change comes from merging `master` into `v4`.

File: packages/react-core/src/components/ChipGroup/ChipGroupToolbarItem.tsx (hunk 10 above)
Comment (redallen) [reply packages/react-core/src/components/ChipGroup/ChipGroupToolbarItem.tsx]: This change comes from merging `master` into `v4`.

File: packages/react-core/src/components/ChipGroup/Chip.tsx (hunk 8 above)
Comment (redallen) [reply packages/react-core/src/components/ChipGroup/Chip.tsx]: This change comes from merging `master` into `v4`.

File: packages/react-core/src/components/Card/Card.tsx (hunk 5 above)
Comment (redallen) [reply packages/react-core/src/components/Card/Card.tsx]: In our implementation, we do `<Component>` which compiles to `React.createElement(Component)` where `Component` is of type `React.ReactNode`. We use `React.ReactNode` which is inclusive of `keyof JSX.IntrinsicElements` so it's not a breaking change.

File: packages/react-core/src/components/BackgroundImage/BackgroundImage.tsx (hunk 3 above)
Comment (redallen) [reply packages/react-core/src/components/BackgroundImage/BackgroundImage.tsx]: Good catch, will remove.

File: packages/react-core/src/components/BackgroundImage/BackgroundImage.tsx (hunk 4 above)
Comment (redallen) [reply packages/react-core/src/components/BackgroundImage/BackgroundImage.tsx]: To allow multiple background filters on the same page.

File: packages/react-core/src/components/Card/Card.tsx (hunk 5 above)
Comment (jschuler) [reply packages/react-core/src/components/Card/Card.tsx]: that means you could pass `component={<Alert title="test" />}` which would not fare well here

Comment (redallen) [reply packages/react-core/src/components/Card/Card.tsx]: Sure, this is outside the scope of this PR anyways.

File: packages/react-core/src/components/DataToolbar/DataToolbarChipGroupContent.tsx [hunk 11]
```diff
@@ -58,27 +58,25 @@ export class DataToolbarChipGroupContent extends React.Component<DataToolbarChip
...
-          className={css(collapseListedFilters && getModifier(styles, 'hidden'))}
+          className={css(collapseListedFilters && styles.modifiers.hidden)}
           {...(collapseListedFilters && { hidden: true })}
           {...(collapseListedFilters && { 'aria-hidden': true })}
         />
         {collapseListedFilters && numberOfFilters > 0 && !isExpanded && (
-          <DataToolbarGroup
-            className={css(getModifier(styles, 'toggle-group-summary'), 'pf-m-filters-applied-message')}
-          >
+          <DataToolbarGroup>
```
Comment (jschuler) [inline packages/react-core/src/components/DataToolbar/DataToolbarChipGroupContent.tsx]: just making sure the removal of class here was intended

File: packages/react-core/src/components/DataToolbar/DataToolbarChipGroupContent.tsx [hunk 12]
```diff
@@ -58,27 +58,25 @@ export class DataToolbarChipGroupContent extends React.Component<DataToolbarChip
...
             <DataToolbarItem>{numberOfFilters} filters applied</DataToolbarItem>
           </DataToolbarGroup>
         )}
         {showClearFiltersButton && !isExpanded && (
-          <DataToolbarItem className={css(getModifier(styles, 'clear'))}>
+          <DataToolbarItem>
```
Comment (jschuler) [inline packages/react-core/src/components/DataToolbar/DataToolbarChipGroupContent.tsx]: and here

File: packages/react-core/src/components/DataToolbar/DataToolbarExpandableContent.tsx [hunk 13]
```diff
@@ -55,10 +55,10 @@ export class DataToolbarExpandableContent extends React.Component<DataToolbarExp
       <div className={css(styles.dataToolbarExpandableContent, className)} ref={expandableContentRef} {...props}>
         <DataToolbarGroup />
         {numberOfFilters > 0 && (
-          <DataToolbarGroup className={getModifier(styles, 'chip-container')}>
+          <DataToolbarGroup className={styles.modifiers.chipContainer}>
             <DataToolbarGroup ref={chipContainerRef} />
             {showClearFiltersButton && (
-              <DataToolbarItem className={css(getModifier(styles, 'clear'))}>
+              <DataToolbarItem>
```
Comment (jschuler) [inline packages/react-core/src/components/DataToolbar/DataToolbarExpandableContent.tsx]: and here

File: packages/react-core/src/components/Modal/ModalContent.tsx [hunk 14]
```diff
@@ -7,6 +7,7 @@ const FocusTrap: any = require('focus-trap-react');
 
 import styles from '@patternfly/react-styles/css/layouts/Bullseye/bullseye';
 import titleStyles from '@patternfly/react-styles/css/components/Title/title';
+import modalStyles from '@patternfly/react-styles/css/components/ModalBox/modal-box';
```
Comment (jschuler) [inline packages/react-core/src/components/Modal/ModalContent.tsx]: is this import used?

File: packages/react-core/src/components/OverflowMenu/OverflowMenu.tsx [hunk 15]
```diff
@@ -55,12 +55,10 @@ export class OverflowMenu extends React.Component<OverflowMenuProps, OverflowMen
...
 
   render() {
+    // eslint-disable-next-line @typescript-eslint/no-unused-vars
     const { className, breakpoint, children, ...props } = this.props;
     return (
-      <div
-        {...props}
-        className={css(styles.overflowMenu, getModifier(styles.modifiers, `showOn ${breakpoint}`), className)}
-      >
+      <div {...props} className={css(styles.overflowMenu, className)}>
```
Comment (jschuler) [inline packages/react-core/src/components/OverflowMenu/OverflowMenu.tsx]: breakpoint class `showOn..` missing

File: packages/react-core/src/components/Progress/Progress.tsx [hunk 16]
```diff
@@ -19,7 +19,7 @@ export interface ProgressProps extends Omit<React.HTMLProps<HTMLDivElement>, 'si
   /** Where the measure percent will be located. */
   measureLocation?: 'outside' | 'inside' | 'top' | 'none';
   /** Status variant of progress. */
-  variant?: 'danger' | 'success' | 'info';
+  variant?: 'danger' | 'success';
```
Comment (jschuler) [inline packages/react-core/src/components/Progress/Progress.tsx]: making sure this is intended

File: packages/react-core/src/components/Progress/Progress.tsx [hunk 17]
```diff
@@ -91,10 +92,10 @@ export class Progress extends React.Component<ProgressProps> {
         {...additionalProps}
         className={css(
           styles.progress,
-          getModifier(styles, variant, ''),
-          getModifier(styles, measureLocation, ''),
-          getModifier(styles, measureLocation === ProgressMeasureLocation.inside ? ProgressSize.lg : size, ''),
-          !title && getModifier(styles, 'singleline', ''),
+          styles.modifiers[variant],
+          ['inside', 'outside'].includes(measureLocation) && styles.modifiers[measureLocation as 'inside' | 'outside'],
+          measureLocation === 'inside' && styles.modifiers[ProgressSize.lg],
```
Comment (jschuler) [inline packages/react-core/src/components/Progress/Progress.tsx]: `: size` dropped off

File: packages/react-core/src/components/Progress/Progress.tsx [hunk 18]
```diff
@@ -40,7 +40,7 @@ export class Progress extends React.Component<ProgressProps> {
   static defaultProps: ProgressProps = {
     className: '',
     measureLocation: ProgressMeasureLocation.top,
-    variant: ProgressVariant.info,
+    variant: null,
```
Comment (jschuler) [inline packages/react-core/src/components/Progress/Progress.tsx]: so by default it will not set a variant class right

File: packages/react-core/src/components/DataToolbar/DataToolbarChipGroupContent.tsx (hunk 11 above)
Comment (redallen) [reply packages/react-core/src/components/DataToolbar/DataToolbarChipGroupContent.tsx]: Yep, these classes no longer exist in core! @mattnolting can you check that our datatoolbar examples aren't missing classes? https://patternfly-react-pr-3886.surge.sh/documentation/react/components/datatoolbar

File: packages/react-core/src/components/Tooltip/Tooltip.tsx [hunk 19]
```diff
@@ -149,7 +149,10 @@ export class Tooltip extends React.Component<TooltipProps> {
     } = this.props;
     const content = (
       <div
-        className={css(!enableFlip && getModifier(styles, position, styles.modifiers.top), className)}
+        className={css(
+          !enableFlip && (styles.modifiers[position as keyof typeof styles.modifiers] || styles.modifiers.top),
```
Comment (jschuler) [inline packages/react-core/src/components/Tooltip/Tooltip.tsx]: maybe make this the same as Popover?
`!enableFlip && (styles.modifiers[position as 'top' | 'bottom' | 'left' | 'right'] || styles.modifiers.top)`

File: packages/react-core/src/components/Wizard/WizardToggle.tsx [hunk 20]
```diff
@@ -52,10 +52,11 @@ export const WizardToggle: React.FunctionComponent<WizardToggleProps> = ({
     }
   }
   return (
-    <>
+    <React.Fragment>
       <button
         onClick={() => onNavToggle(!isNavOpen)}
         className={css(styles.wizardToggle, isNavOpen && 'pf-m-expanded')}
+        aria-label="Wizard toggle"
```
Comment (jschuler) [inline packages/react-core/src/components/Wizard/WizardToggle.tsx]: no prop for this?

File: packages/react-core/src/components/Modal/ModalContent.tsx (hunk 14 above)
Comment (redallen) [reply packages/react-core/src/components/Modal/ModalContent.tsx]: Nope, and I don't remember adding it. Good catch.

File: packages/react-core/src/components/OverflowMenu/OverflowMenu.tsx (hunk 15 above)
Comment (redallen) [reply packages/react-core/src/components/OverflowMenu/OverflowMenu.tsx]: Based on the implementation of `getModifier` since there was a space like `showOn ${breakpoint}` rather than `showOn${breakpoint}` the class was never getting added. I'm preserving this (maybe broken?) behavior for now.

File: packages/react-core/src/components/Progress/Progress.tsx (hunk 16 above)
Comment (redallen) [reply packages/react-core/src/components/Progress/Progress.tsx]: Yep! `styles.modifiers.info` doesn't exist, so it should be removed from the type.

File: packages/react-core/src/layouts/Bullseye/Bullseye.tsx [hunk 21]
```diff
@@ -8,7 +8,7 @@ export interface BullseyeProps extends React.HTMLProps<HTMLDivElement> {
   /** additional classes added to the Bullseye layout */
   className?: string;
   /** Sets the base component to render. defaults to div */
-  component?: keyof JSX.IntrinsicElements;
+  component?: React.ReactNode;
```
Comment (jschuler) [inline packages/react-core/src/layouts/Bullseye/Bullseye.tsx]: I don't think this is valid, strings that are rendered as tag should be one of the IntrinsicElements only, ReactNode can be `ReactElement | ReactText | ReactFragment | ReactPortal | boolean | null | undefined`

File: packages/react-core/src/components/Progress/Progress.tsx (hunk 18 above)
Comment (redallen) [reply packages/react-core/src/components/Progress/Progress.tsx]: Yep! `ProgressVariant.info` didn't exist and was doing nothing.

File: packages/react-core/src/layouts/Level/Level.tsx [hunk 22]
```diff
@@ -18,10 +17,7 @@ export const Level: React.FunctionComponent<LevelProps> = ({
   children = null,
   ...props
 }: LevelProps) => (
-  <div
-    {...props}
-    className={css(styles.level, gutter && getGutterModifier(styles, gutter, styles.modifiers.gutter), className)}
-  >
+  <div {...props} className={css(styles.level, gutter && styles.modifiers.gutter, className)}>
```
Comment (jschuler) [inline packages/react-core/src/layouts/Level/Level.tsx]: previously it was returning `gutter-${size}` where size is one of sm, md, lg

File: packages/react-core/src/components/Progress/Progress.tsx (hunk 17 above)
Comment (redallen) [reply packages/react-core/src/components/Progress/Progress.tsx]: Good catch! `styles.modifiers.[sm,lg]` do exist.

File: packages/react-docs/gatsby-config.js [hunk 23]
```diff
@@ -52,6 +52,7 @@ module.exports = {
           '**/public',
           '**/test-helpers',
           /.*react-styles.*/,
+          /.*react-styled-system.*/,
```
Comment (jschuler) [inline packages/react-docs/gatsby-config.js]: this got removed

File: packages/react-core/src/components/OverflowMenu/OverflowMenu.tsx (hunk 15 above)
Comment (redallen) [reply packages/react-core/src/components/OverflowMenu/OverflowMenu.tsx]: Double checked with core styles, and overflow menu does NOT have breakpoint modifiers. It has it's own JS implementation for the breakpoints in `handleResize`, so this is safe to remove.

File: packages/react-core/src/layouts/Level/Level.tsx (hunk 22 above)
Comment (redallen) [reply packages/react-core/src/layouts/Level/Level.tsx]: Gutters haven't had sizes for over a year now. They're either on or off.

File: packages/react-docs/gatsby-config.js (hunk 23 above)
Comment (redallen) [reply packages/react-docs/gatsby-config.js]: Good catch!

File: packages/react-core/src/components/Tooltip/Tooltip.tsx (hunk 19 above)
Comment (redallen) [reply packages/react-core/src/components/Tooltip/Tooltip.tsx]: I like `'top' | 'bottom' | 'left' | 'right'` more than `keyof typeof styles.modifiers`, so I'll try that!

File: packages/react-core/src/components/Wizard/WizardToggle.tsx (hunk 20 above)
Comment (redallen) [reply packages/react-core/src/components/Wizard/WizardToggle.tsx]: Good catch, I added it to pass our a11y-tests which were previously not picking it up.

File: packages/react-core/src/components/DataToolbar/DataToolbarChipGroupContent.tsx (hunk 11 above)
Comment (mattnolting) [reply packages/react-core/src/components/DataToolbar/DataToolbarChipGroupContent.tsx]: Confirmed, not in core
