### PR TITLE
bug(Select): expose height and max height props for Menu content

### LINKED ISSUE #9847: Bug - Select - cannot change MenuContent properties
**Describe the problem**
It's currently not possible to pass props from `<Select>` down to a `<MenuContent>` (e.g. `maxMenuHeight`)
[This line](https://github.com/patternfly/patternfly-react/blob/main/packages/react-core/src/components/Select/Select.tsx#L161) seems to be culprit

**How do you reproduce the problem?**
[codesandbox here](https://codesandbox.io/p/sandbox/vibrant-bas-kjrzvq)

**Expected behavior**
Expected to be able to adjust the menu content via props

**Is this issue blocking you?**
Not blocking, a `<SelectList>` can be wrapped in a `<Panel>` which can be adjusted.

### PR DESCRIPTION
**Pull request by tlabaj**
**What**: Closes #9847 

**Additional issues**:

### CODE REVIEW

File: packages/react-core/src/components/Select/Select.tsx [hunk 1]
```diff
@@ -70,6 +70,10 @@ export interface SelectProps extends MenuProps, OUIAProps {
   role?: string;
   /** Additional properties to pass to the popper */
   popperProps?: SelectPopperProps;
+  /** Height of the menu */
+  menuHeight?: string;
+  /** Maximum height of menu */
+  maxMenuHeight?: string;
```
Comment (thatblindgeye) [inline packages/react-core/src/components/Select/Select.tsx:76]: Could we also expose the `isScrollable` prop to pass to Menu, since that would have to be used when the actual menu height is greater than the menuHeight/maxMenuHeight props? It can be passed in fine, just isn't exposed in Select's prop table.

Also, I think it was mentioned maybe during the backlog meeting, but do we want to expose these props in Dropdown as well? Not a blocker here, but would be worth doing at some point

Comment (tlabaj) [reply packages/react-core/src/components/Select/Select.tsx:76]: Yup.  I can open a dropdown.  I will add the additional prop.

Comment (tlabaj) [reply packages/react-core/src/components/Select/Select.tsx:76]: @thatblindgeye technically they can spread the `isScrollable`, but i can add it so it is documented.

Comment (tlabaj) [reply packages/react-core/src/components/Select/Select.tsx]: Opened follow up issue for dropdown #10083

File: packages/react-core/src/components/Select/Select.tsx [hunk 2]
```diff
@@ -70,6 +70,12 @@ export interface SelectProps extends MenuProps, OUIAProps {
   role?: string;
   /** Additional properties to pass to the popper */
   popperProps?: SelectPopperProps;
+  /** Height of the select menu */
+  menuHeight?: string;
+  /** Maximum height of select menu */
+  maxMenuHeight?: string;
+  /** Indicates if the select menu should be srollable */
```
Comment (thatblindgeye) [inline packages/react-core/src/components/Select/Select.tsx:77]:
```suggestion
  /** Indicates if the select menu should be scrollable */
```

**Review by thatblindgeye — APPROVED** [review]
Nit spelling below, otherwise LGTM

**Review by kmcfaul — APPROVED** [review]
lgtm!
