### PR TITLE
fix(ApplicationLauncher): Adjust cypress test

### LINKED ISSUE #2243: Fix Application Launcher cypress Tests
The Application Launcher Cypress test has a commented out test that should be fixed.  The last test should also assert that the selection works.

### PR DESCRIPTION
**Pull request by jessiehuff**
Fixes #2243

### CODE REVIEW

File: packages/patternfly-4/react-core/src/components/Page/PageHeader.d.ts [hunk 1]
```diff
@@ -7,7 +7,7 @@ export interface PageHeaderProps extends HTMLProps<HTMLDivElement> {
   toolbar?: ReactNode;
   avatar?: ReactNode;
   topNav?: ReactNode;
-  linkComponent?: ReactNode;
+  logoComponent?: ReactNode;
```
Comment (redallen) [inline packages/patternfly-4/react-core/src/components/Page/PageHeader.d.ts]: This one is my fault, sorry!

Comment (tlabaj) [reply packages/patternfly-4/react-core/src/components/Page/PageHeader.d.ts]: why is prop name changing here?

Comment (jessiehuff) [reply packages/patternfly-4/react-core/src/components/Page/PageHeader.d.ts]: Zack asked me to include this based on: https://github.com/patternfly/patternfly-react/pull/2117
