### PR TITLE
fix(datetimepicker): try using toLocaleTimeString

### LINKED ISSUE #3507: PF3 DateTimePicker jest tests failing on master
Date formatting is inconsistent across Node versions.

https://circleci.com/gh/patternfly/patternfly-react/22406?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

### PR DESCRIPTION
**Pull request by redallen**
**What**: Closes #3507 and fixes tests on master

**Additional issues**:

### CODE REVIEW

File: packages/patternfly-3/patternfly-react/src/components/DateTimePicker/TimeHelpers.js [hunk 1]
```diff
@@ -11,10 +11,10 @@ export const getDateFromTime = time => {
 };
 
 export const formatTime = (time, locale = 'en-US') => {
-  const options = { hour: '2-digit', minute: '2-digit' };
+  const options = { hour: 'numeric', minute: '2-digit' };
   const parsedTime = getDateFromTime(time);
   if (Date.parse(parsedTime)) {
-    return parsedTime.toLocaleString(locale, options);
+    return parsedTime.toLocaleTimeString(locale, options);
```
Comment (redallen) [inline packages/patternfly-3/patternfly-react/src/components/DateTimePicker/TimeHelpers.js]: I could revert this to match `DateTimePicker.js`, but meh.
