### PR TITLE
fix(ToastNotificationList): ensures timeout on dismissal and not onhover

### LINKED ISSUE #172: ToastNotificationList: Removing last toast notification removes auto-dismiss feature
If I close the last toast notification in the list via the close button, the other notifications do not auto-dismiss after the timer delay period expires.

### PR DESCRIPTION
**Pull request by AllenBW**
closes #172

https://AllenBW.github.io/patternfly-react/

So when you entered (before this pr) a notification list and dismiss the last notification, you exit the bounds of the list without doing a mouseLeave (which is a big deal, because without this, toast dismissal was never unpaused)  

The fix, is to unpause whenever the notificationlist changes (which it does when a toast is dismissed), BUT to not unpause while we are mouse(d)over notificationlist

🌮🥑💃

### CODE REVIEW

File: src/components/ToastNotification/ToastNotificationList.js [hunk 1]
```diff
@@ -25,6 +30,12 @@ class ToastNotificationList extends React.Component {
     onMouseLeave && onMouseLeave();
   }
 
+  onMouseOver() {
+    this.setState({ paused: true });
+    const { onMouseOver } = this.props;
+    onMouseOver && onMouseOver();
```
Comment (priley86) [inline src/components/ToastNotification/ToastNotificationList.js]: so i think these can finally simplify these to just `onMouseOver()` calls now (due to the noop). No longer need the `&&` I don't think. We added that bit in just to simplify the syntax...

**Comment by priley86** [comment]
awesome! The whole enchilada of toast notifications happening here!

@jeff-phillips-18 does this fix the issue noted? I tested the storybook and the timeouts/pause appear function correctly.

File: src/components/ToastNotification/ToastNotificationList.js (hunk 1 above)
Comment (priley86) [reply src/components/ToastNotification/ToastNotificationList.js]: was totally an old convention that we've since updated... I will make note of this in some coding conventions wiki i'm starting next week... was trying to "lint away" as many as I could first though! But will just be trying to continue to update a code convention doc soon... ;)

**Comment by jeff-phillips-18** [comment]
Appears to fix the issue. Thanks @AllenBW

**Comment by priley86** [comment]
Nice job! Will merge this after we resolve #199
