### PR TITLE
fix(AlertGroup): update AlertGroupInline to not use child index as a key

### LINKED ISSUE #7877: Bug - AlertGroup - AlertGroupInline usage of index as key causes issues when alert order is reversed
When Alerts in an AlertGroup are added from the top rather than the bottom `AlertGroupInline`'s usage of child index as a key causes Alerts to be removed in reverse order on timeout.

### PR DESCRIPTION
**Pull request by wise-king-sullyman**
**What**: Closes #7877 

**Additional issues**:

Needed for #7843 

Note: I added an integration test rather than unit tests as I couldn't identify a good way to unit test either side of the Alert/AlertGroup/AlertGroupInline interaction. This is because Alert doesn't *do* anything with `uniqueId` and `AlertGroupInline` just applies it as a `key`.

### CODE REVIEW

File: packages/react-core/src/components/AlertGroup/AlertGroupInline.tsx [hunk 1]
```diff
@@ -18,8 +19,8 @@ export const AlertGroupInline: React.FunctionComponent<AlertGroupProps> = ({
     className={css(styles.alertGroup, className, isToast ? styles.modifiers.toast : '')}
     {...rest}
   >
-    {React.Children.toArray(children).map((Alert: React.ReactNode, index: number) => (
-      <li key={index}>{Alert}</li>
+    {React.Children.toArray(children).map((alert, index) => (
+      <li key={(alert as React.ReactElement<AlertProps>).props?.uniqueId || index}>{alert}</li>
```
Comment (tompsota) [inline packages/react-core/src/components/AlertGroup/AlertGroupInline.tsx:23]: I've been thinking if it is the best solution to add the `uniqueId` prop as it is intended only for 'internal' use. Also, it may be a bit confusing for the user when the expected behavior of the alert depends on prop that is optional. 

What if we generated e.g. uuid and used it as key instead? This would however require either to use [a 3rd party package](https://www.npmjs.com/package/uuid) or write a generator, I've seen a couple of good implementations for example [here](https://stackoverflow.com/a/21963136). 

I'm aware that there are some drawbacks when using uuids. Therefore I'll be fine also with `uniqueId` prop, but wanted to bring up the other option too :)

**Review by tompsota — APPROVED** [review]

File: packages/react-core/src/components/Alert/Alert.tsx [hunk 2]
```diff
@@ -73,6 +73,8 @@ export interface AlertProps extends Omit<React.HTMLProps<HTMLDivElement>, 'actio
   isExpandable?: boolean;
   /** Adds accessible text to the alert Toggle */
   toggleAriaLabel?: string;
+  /** Uniquely identifies the alert */
+  uniqueId?: string;
```
Comment (tlabaj) [inline packages/react-core/src/components/Alert/Alert.tsx:77]: Why not k=just use id?

**Review by tlabaj — APPROVED** [review]
LGTM
