### PR TITLE
fix(About modal): Refactor about modal to reuse the modal component

### LINKED ISSUE #6614: About Modal: Refactor to be built with the modal component
Follow up to https://github.com/patternfly/patternfly/issues/4526

Per https://github.com/patternfly/patternfly/pull/5216/files, the `.pf-c-about-modal-box` component is no longer styled as its own modal, and is now a regular element/box. This update allows us to place the about modal component in the existing modal component. This is similar to how a wizard behaves when inside of a modal.

The update from core is to remove the following attributes from the about modal, since they will now be on the modal component
  * `role="dialog"`
  * `aria-modal="true"`
  * `aria-label[ledby]`
  * `aria-describedby`

We're using a large modal in the core demo, but I imagine that can be configurable by the user, similar to the existing wizard in a modal. Though I think it begs the question - if it's more composable to be used with the `<Modal>` (instead of shipping with the `<Modal>`):
* Should it be called `<AboutModal>`? Or should we take "modal" out of the name?
* Could it be used outside of a `<Modal>`?

cc @mcarrano @mceledonia @tlabaj - opinions on the usage/naming above?

### PR DESCRIPTION
**Pull request by tlabaj**
**What**: Closes #6614

### CODE REVIEW

**Review by mcarrano — COMMENTED** [review]
This looks good, but just a couple of questions...

* I see there is a slight shift in the width when I go between this and the current implementation. I don't think that will be a problem, but wanted to check with @mcoker about whether this is expected.
* Also, I know we are planning to update the background image, too. Should that happen as part of this PR or be separate?

File: packages/react-core/src/components/AboutModal/AboutModalBox.tsx [hunk 1]
```diff
@@ -5,16 +5,13 @@ import styles from '@patternfly/react-styles/css/components/AboutModalBox/about-
...
-  className?: string;
 }
 
 export const AboutModalBox: React.FunctionComponent<AboutModalBoxProps> = ({
   children,
-  className = '',
   ...props
 }: AboutModalBoxProps) => (
-  <div role="dialog" aria-modal="true" className={css(styles.aboutModalBox, className)} {...props}>
+  <div className={css(styles.aboutModalBox)} {...props}>
```
Comment (mcoker) [inline packages/react-core/src/components/AboutModal/AboutModalBox.tsx:14]: it looks like you used to be able to pass `className` to this component via `<AboutModal className>` - doesn't look like it works anymore. Is that intentional?

**Comment by mcoker** [comment]
@mcarrano 

> I see there is a slight shift in the width when I go between this and the current implementation. I don't think that will be a problem, but wanted to check with @mcoker about whether this is expected.

Yep - the width comes from the modal now, so it's slightly different - 70em (now) vs 77em (previous). The about modal width now matches the wizard in a modal width, since both widths come from the modal.

> Also, I know we are planning to update the background image, too. Should that happen as part of this PR or be separate?

Separate, @mattnolting has a core PR up for that.

**Review by mcoker — COMMENTED** [review]
LGTM, just one question.

File: packages/react-core/src/components/AboutModal/AboutModalBox.tsx (hunk 1 above)
Comment (tlabaj) [reply packages/react-core/src/components/AboutModal/AboutModalBox.tsx]: I mistakenly removed that when i was cleaning up.  I added it back now.

**Review by mcarrano — APPROVED** [review]
Thanks for answering my questions @mcoker . I approve then.

**Review by mcoker — APPROVED** [review]
🚀

File: packages/react-core/src/components/AboutModal/AboutModalBoxHeader.tsx [hunk 2]
```diff
@@ -4,21 +4,18 @@ import styles from '@patternfly/react-styles/css/components/AboutModalBox/about-
 import { Title } from '../Title';
 
 export interface AboutModalBoxHeaderProps extends React.HTMLProps<HTMLDivElement> {
-  /** additional classes added to the button  */
-  className?: string;
-  /** Name of the Product  */
+  /** Name of the product  */
   productName?: string;
-  /** id to used for Modal Box header  */
+  /** Id to used for about modal box header  */
```
Comment (thatblindgeye) [inline packages/react-core/src/components/AboutModal/AboutModalBoxHeader.tsx:9]:
```suggestion
  /** Id to use for about modal box header  */
```

File: packages/react-core/src/components/AboutModal/AboutModal.tsx [hunk 3]
```diff
@@ -36,114 +38,59 @@ export interface AboutModalProps {
...
+  children,
+  className,
+  isOpen = false,
+  onClose = (_e): any => undefined,
+  productName = '',
+  trademark = '',
+  backgroundImageSrc = '',
+  brandImageSrc,
+  brandImageAlt,
+  noAboutModalBoxContentContainer = false,
```
Comment (thatblindgeye) [inline packages/react-core/src/components/AboutModal/AboutModal.tsx:51]: This could be a followup issue, but would we want to rename this prop to align with our other props? `hasAboutModalBoxContentContainer` (or shorten to `hasContentContainer`), and invert the logic (default to true, then inside AboutModalBoxContent apply the wrapper div when true and just the `children` when false)

**Review by thatblindgeye — CHANGES_REQUESTED** [review]
Mix of nits, requests, and a couple questions below, but it's looking good!

**Review by thatblindgeye — APPROVED** [review]
Looks good! Left one comment above unresolved but it isn't a blocker.

**Review by mmenestr — APPROVED** [review]

**Review by kmcfaul — COMMENTED** [review]
Getting a console error from Modal on the surge for the "Without product name" and "Custom background image" examples (needs an aria-label/aria-labelledby). The surge is also not showing or finding the default background image, but I'm not sure if that's a bug or just the surge.

Code refactor lgtm. Just want to update the two examples so they don't show an error.

**Comment by tlabaj** [comment]
@kmcfaul I am not seeing the errors...  Is there something you did to generate them?

**Comment by thatblindgeye** [comment]
I'm also seeing the errors Katie mentioned when I open the modals for those two examples. From the "Without product name" example in the surge preview:

Console errors for example

**Review by kmcfaul — APPROVED** [review]
