### PR TITLE
fix(Slider): Updated slider to work in RTL. 

### LINKED ISSUE #9593: Slider - RTL support
Dragging the slider position moves it in the inverse direction as expected, for example, in the Discrete example, if I drag the slider to 200, it positions at zero. And if I drag it to 50, it goes to 150, etc. Same experience with clicking the slider at an exact position. The values are RTL, but the behavior is still LTR.

### PR DESCRIPTION
**Pull request by tlabaj**
Updated slider to work in RTL. Deprecated` rightActions` and `leftActions` props, added `endActions` and `startActions` props to replace them.

**What**: Closes #9593

### CODE REVIEW

File: packages/react-core/src/components/Slider/Slider.tsx [hunk 1]
```diff
@@ -182,7 +194,11 @@ export const Slider: React.FunctionComponent<SliderProps> = ({
     e.stopPropagation();
     e.preventDefault();
 
-    diff = e.clientX - thumbRef.current.getBoundingClientRect().left;
+    if (isRTL) {
+      diff = thumbRef.current.getBoundingClientRect().left - e.clientX;
```
Comment (thatblindgeye) [inline packages/react-core/src/components/Slider/Slider.tsx:198]: I'm noticing a small bug when trying to drag the slider thumb via mouse and RTL enabled (but only for a continuous slider, where there's no "snapping" value). Maybe hard to tell from the video, but basically what I'm doing is clicking down and holding, and just *barely* moving my mouse; no matter what the thumb value jumps up by 2:


https://github.com/patternfly/patternfly-react/assets/70952936/baafb6d4-d031-4c6c-88b3-82346a307b9a

From what I can tell making the following update fixes it (a similar update would have to be made on line ~211 within the handleTouchStart):

```suggestion
      diff = thumbRef.current.getBoundingClientRect().right - e.clientX;
```

**Review by mcoker — APPROVED** [review]
🐸👍

**Review by thatblindgeye — APPROVED** [review]

**Review by wise-king-sullyman — APPROVED** [review]
🎉
