### PR TITLE
fix(Tabs): enable tabs scroll button for small window

### LINKED ISSUE #5175: Tab overflow disabled for small windows
In Cost management, we noticed that the tab overflow controls stop working at small window sizes. When the browser window is resized a bit larger, the controls begin working, again.

I can repeatedly resize the window to see the controls are enabled / disabled. Although I can scroll side to side using the mouse, but the prev / next buttons are unusable.

Looking at the inspector, the size of the container is roughly 350px.

chrome-capture (5)

### PR DESCRIPTION
**Pull request by DaoDaoNoCode**
**What**: Closes #5175 
This issue is because there the button only scrolls left or right when the tab is totally inside the view. However, when the window is small, the tab content could even be longer than the list width, which makes it can never find the element in the view. To solve the problem, I created a new optional prop named `strict` and made a judgment on the element width and the container width, if the container width is smaller than the element width and the `strict` is not set, we treat it as part in view. Only when strict mode is set, we will not take the element width and container width into consideration, which brings more flexibility to the function.
Also, I update the bounding to make it more precise to judge whether an element is in view when the element width is not an integer. And add a debounce to the scroll function.

### CODE REVIEW

File: packages/react-core/src/components/Tabs/Tabs.tsx [hunk 1]
```diff
@@ -178,7 +179,7 @@ export class Tabs extends React.Component<TabsProps, TabsState> {
     }
   }
 
-  handleScrollButtons = () => {
+  handleScrollButtons = _.debounce(() => {
```
Comment (jeffpuzzo) [inline packages/react-core/src/components/Tabs/Tabs.tsx:182]: Echoing what I've been told recently here, which is lodash isn't something we want as a dependency going forward; https://github.com/patternfly/patternfly-react/issues/6553.

So I would suggest using `setTimeout` instead to accomplish the debouncing of this operation.

**Review by dlabrecq — COMMENTED** [review]
Other than the Lodash issue, it LGTM

File: packages/react-core/src/components/Tabs/Tabs.tsx (hunk 1 above)
Comment (DaoDaoNoCode) [reply packages/react-core/src/components/Tabs/Tabs.tsx:182]: @jeffpuzzo Thanks, I will remove the use of lodash.

File: packages/react-core/src/helpers/util.ts [hunk 2]
```diff
@@ -39,24 +39,25 @@ export function debounce(this: any, func: (...args: any[]) => any, wait: number)
  * @param {HTMLElement} container  The container to check if the element is in view of.
  * @param {HTMLElement} element    The element to check if it is view
  * @param {boolean} partial   true if partial view is allowed
+ * @param {boolean} strict    true if strict mode is set, never consider the container width and element width
  *
  * @returns { boolean } True if the component is in View.
  */
-export function isElementInView(container: HTMLElement, element: HTMLElement, partial: boolean) {
+export function isElementInView(container: HTMLElement, element: HTMLElement, partial: boolean, strict?: boolean) {
```
Comment (jeffpuzzo) [inline packages/react-core/src/helpers/util.ts:46]: I'm thinking it might be better to default this value to false, so `strict: boolean = false` so we don't have to count on undefined being checked correctly down below.

**Comment by jeffpuzzo** [comment]
Do we know how this `strict` param might impact `NavList` (which is also using this helper)?

Also, do we know of any use-cases where we would want `strict` to be "true" and controllable by developers via a prop?

**Comment by DaoDaoNoCode** [comment]
> Do we know how this `strict` param might impact `NavList` (which is also using this helper)?

Yes, the same problem also exists on `NavList`, you could check this example https://www.patternfly.org/v4/components/navigation#horizontal-only-in-pageheader and set the width to very small. So this could also help solve the issue in `NavList`.

> Also, do we know of any use-cases where we would want `strict` to be "true" and controllable by developers via a prop?
Currently, my answer is no. But I prefer to keep this prop. If they want to check whether an element is inside a container in the future in some other situations this could help.

File: packages/react-core/src/helpers/util.ts (hunk 2 above)
Comment (DaoDaoNoCode) [reply packages/react-core/src/helpers/util.ts:46]: Will update, thanks!

**Comment by jeffpuzzo** [comment]
Thanks for clarifying!

**Review by jeffpuzzo — APPROVED** [review]

**Review by nicolethoen — APPROVED** [review]
