### PR TITLE
fix: fix broken image links

### LINKED ISSUE #3925: Integration demo app - broken image links
**Describe the issue. What is the expected and unexpected behavior?**

Several svg images in the demo-app-ts don't display correctly.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

Start the demo app.

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

Bug.

**What is your product and what release version are you targeting?**

None.

### PR DESCRIPTION
**Pull request by michpetrov**
**What**: Closes #3925

**Master PR**: #3926

### CODE REVIEW

File: packages/react-integration/demo-app-ts/src/components/AppHeader/AppHeader.tsx [hunk 1]
```diff
@@ -1,8 +1,8 @@
 import React from 'react';
 import { Avatar, Brand, PageHeader } from '@patternfly/react-core';
 import { AppToolbar } from '../AppToolbar/AppToolbar';
-const imgBrand = '../../assets/images/imgBrand.svg';
-const imgAvatar = '../../assets/images/imgAvatar.svg';
+const imgBrand = require('../../assets/images/imgBrand.svg');
```
Comment (jschuler) [inline packages/react-integration/demo-app-ts/src/components/AppHeader/AppHeader.tsx]: not a fan of seeing require statements here. How about an alternate approach:

1. create a `custom.d.ts` file in the demo-app-ts dir.
2. content:
```
declare module '*.svg' {
  const content: string;
  export default content;
}
```
3. Add to the tsconfig.json file
`"files": [ "custom.d.ts" ]`

4. Now you can use
`import imgBrand from '../../assets/images/imgBrand.svg'`

Comment (michpetrov) [reply packages/react-integration/demo-app-ts/src/components/AppHeader/AppHeader.tsx]: From my point of view that seems to introduce more "entropy", for a lack of a better word. But I'll refactor it.
