### PR TITLE
fix(Select): fix panel issue

### LINKED ISSUE #3768: Select: Panel example inaccessible by keyboard
**Describe the issue. What is the expected and unexpected behavior?**
When navigating to the panel example, if you press enter or space on the panel, you get the following error: 
Screen Shot 2020-02-18 at 10 34 34 AM

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
This is a bug.

### PR DESCRIPTION
**Pull request by DaoDaoNoCode**
**What**: Closes #3768

### CODE REVIEW

**Comment by DaoDaoNoCode** [comment]
@redallen PTAL, thanks.

File: packages/react-core/src/components/Select/Select.tsx [hunk 1]
```diff
@@ -548,10 +548,12 @@ export class Select extends React.Component<SelectProps & OUIAProps, SelectState
             hasClearButton={hasOnClear}
           >
             {customContent && (
-              <div className={css(styles.selectToggleWrapper)}>
-                {toggleIcon && <span className={css(styles.selectToggleIcon)}>{toggleIcon}</span>}
-                <span className={css(styles.selectToggleText)}>{placeholderText}</span>
-              </div>
+              <React.Fragment>
```
Comment (seanforyou23) [inline packages/react-core/src/components/Select/Select.tsx:551]: Is the fragment necessary?

Comment (DaoDaoNoCode) [reply packages/react-core/src/components/Select/Select.tsx:551]: No, it's not necessary. I will remove it, thanks.
