### PR TITLE
fix(types): popover, tooltip, and helper types fixes

### LINKED ISSUE #1340: PF4 - helpers/popover/tooltip type definitions
These were missed in some previous PRs but found while integration testing downstream in OpenShift. It seems a few definitions were slightly off with the version of `@types/react` in place.

```
ERROR in /home/dtaylor/repos/openshift/origin/src/github.com/openshift/console/frontend/node_modules/@patternfly/react-core/dist/js/components/Avatar/Avatar.d.ts
(1,8): Module '"/home/dtaylor/repos/openshift/origin/src/github.com/openshift/console/frontend/node_modules/@types/react/index"' has no default export.

ERROR in /home/dtaylor/repos/openshift/origin/src/github.com/openshift/console/frontend/node_modules/@patternfly/react-core/dist/js/components/Popover/Popover.d.ts
(1,29): Module '"/home/dtaylor/repos/openshift/origin/src/github.com/openshift/console/frontend/node_modules/@types/react/index"' has no exported member 'Element'. Did you mean 'CElement'?

ERROR in /home/dtaylor/repos/openshift/origin/src/github.com/openshift/console/frontend/node_modules/@patternfly/react-core/dist/js/components/Popover/Popover.d.ts
(12,51): Type '"children"' does not satisfy the constraint '"interactive" | "boundary" | "content" | "size" | "wait" | "flip" | "sticky" | "touch" | "multipl...'.

ERROR in /home/dtaylor/repos/openshift/origin/src/github.com/openshift/console/frontend/node_modules/@patternfly/react-core/dist/js/components/Tooltip/Tooltip.d.ts
(12,51): Type '"content" | "children"' does not satisfy the constraint '"interactive" | "boundary" | "content" | "size" | "wait" | "flip" | "sticky" | "touch" | "multipl...'.
  Type '"children"' is not assignable to type '"interactive" | "boundary" | "content" | "size" | "wait" | "flip" | "sticky" | "touch" | "multipl...'.

ERROR in /home/dtaylor/repos/openshift/origin/src/github.com/openshift/console/frontend/node_modules/@patternfly/react-core/dist/js/helpers/GenerateId/GenerateId.d.ts
(8,42): Cannot find name 'GenerateId'.
```

### PR DESCRIPTION
**Pull request by priley86**
**What**:
fixes #1340 

`Element` is not currently exported in the version of `@types/react` used here, so updating with `ReactElement`. Also, `Omit<Props>` is incorrectly extending the interface for these components (which internally render div's). Updating to `HTMLProps<HTMLDivElement>` respectively.

**Additional issues**:

### CODE REVIEW

File: packages/patternfly-4/react-core/src/helpers/GenerateId/GenerateId.d.ts [hunk 1]
```diff
@@ -5,6 +5,6 @@ export interface GenerateIdProps {
   children(id: string): ReactNode;
 }
 
-declare const GenerateId: ComponentClass<GenerateId>;
+declare const GenerateId: ComponentClass<GenerateIdProps>;
```
Comment (priley86) [inline packages/patternfly-4/react-core/src/helpers/GenerateId/GenerateId.d.ts]: this was a miss on my part - did not see the error in my IDE for some reason, but only see it in the built dist downstream...
