### PR TITLE
fix(overflowmenu-dropdown-item): allow to pass dropdown item props

### LINKED ISSUE #4372: Should be able to pass any DropdownItem props to OverflowMenuDropdownItem
Should be able to pass any DropdownItem props to OverflowMenuDropdownItem

### PR DESCRIPTION
**Pull request by boaz0**
**What**: Closes #4372 

//cc @jschuler

### CODE REVIEW

File: packages/react-core/src/components/OverflowMenu/OverflowMenuDropdownItem.tsx [hunk 1]
```diff
@@ -14,12 +12,13 @@ export interface OverflowMenuDropdownItemProps extends React.HTMLProps<HTMLDivEl
...
   isShared = false,
-  index
+  index,
+  ...additionalProps
 }: OverflowMenuDropdownItemProps) => (
   <OverflowMenuContext.Consumer>
     {value =>
       (!isShared || value.isBelowBreakpoint) && (
-        <DropdownItem component="button" index={index}>
+        <DropdownItem component="button" index={index} {...additionalProps}>
```
Comment (dlabrecq) [inline packages/react-core/src/components/OverflowMenu/OverflowMenuDropdownItem.tsx:21]: I'd rather be explicit about what props are passed down Vs anything random. The issue is only asking for DropdownItem props to be passed thru. Can we destructure the valid props here?

Comment (boaz0) [reply packages/react-core/src/components/OverflowMenu/OverflowMenuDropdownItem.tsx:21]: I don't think we can, dropdown items props extends `HTMLDivElement` and that one contains much much more props.
Unless, we do not need to pass `HTMLDivElement` props, I believe we can do that explicitly.

Comment (dlabrecq) [reply packages/react-core/src/components/OverflowMenu/OverflowMenuDropdownItem.tsx:21]: Looking at other components, it appears props are passed thru without any validation.
