### PR TITLE
Fix #431 : Add href paths to VerticalNav menuItems

### LINKED ISSUE #431: Vertical nav doesn't work with turbolinks
It seems that passing a href prop triggres 
```javascript
window.location = href
```
which doesn't work with turbolinks.

Is there an option to edit [this anchor tag](https://github.com/patternfly/patternfly-react/pull/88/files#diff-d249da5334100a824baed07361d25e37R307) with the item's href ?

### PR DESCRIPTION
**Pull request by glekner**
**What**:
Fix #431 
This will help Turbolinks in Foreman/Angular in Katello to better handle navigations in their own products. The default behaviour is to still prevent the default behaviour of the `href` if an `onItemClicked` function is provided. We want an option to not prevent it.

**Storybook**:
[Link to Storybook](https://rawgit.com/gilad215/patternfly-react/verticalnav-href-storybook/index.html?knob-Max%20Shown=5&knob-Leeway=2&selectedKind=patternfly-react%2FNavigation%2FVertical%20Navigation&selectedStory=Items%20as%20Objects&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)

Try `Ipsum -> Item 3-B` for demonstration

### CODE REVIEW

**Comment by glekner** [comment]
@mturley I changed the condition to take care of another use case where only an `href` prop is provided. If you can approve again that would be great

File: packages/patternfly-3/patternfly-react/src/components/VerticalNav/VerticalNavItemHelper.js [hunk 1]
```diff
@@ -82,18 +82,15 @@ class BaseVerticalNavItemHelper extends React.Component {
 
   onItemClick = event => {
     const { primary, secondary, tertiary } = this.getContextNavItems();
-    const { isMobile, updateNavOnItemClick, idPath } = this.props;
-    const { href, onClick } = this.navItem();
-    event.preventDefault();
+    const { isMobile, preventHref, updateNavOnItemClick, idPath } = this.props;
+    const { onClick } = this.navItem();
+    if (preventHref && !!onClick) event.preventDefault();
```
Comment (jeff-phillips-18) [inline packages/patternfly-3/patternfly-react/src/components/VerticalNav/VerticalNavItemHelper.js]: Could you format this with the `then` in a new block?

Comment (jeff-phillips-18) [reply packages/patternfly-3/patternfly-react/src/components/VerticalNav/VerticalNavItemHelper.js]: if asked to not prevent using the href, why prevent it when there is an onClick?

File: packages/patternfly-3/patternfly-react/src/components/VerticalNav/VerticalNavItemHelper.js [hunk 2]
```diff
@@ -82,18 +82,15 @@ class BaseVerticalNavItemHelper extends React.Component {
...
     updateNavOnItemClick(primary, secondary, tertiary, this.idPath(), idPath); // Clears all mobile selections
     if (isMobile) {
       this.onMobileSelection(primary, secondary, tertiary); // Applies new mobile selection here
     }
     this.setActive();
     onClick && onClick(primary, secondary, tertiary);
-    if (href) {
-      window.location = href; // Note: This should become router-aware later on.
-    }
   };
```
Comment (jeff-phillips-18) [inline packages/patternfly-3/patternfly-react/src/components/VerticalNav/VerticalNavItemHelper.js]: Should this remain when not preventHref?

File: packages/patternfly-3/patternfly-react/src/components/VerticalNav/VerticalNavItemHelper.js [hunk 3]
```diff
@@ -266,7 +263,7 @@ class BaseVerticalNavItemHelper extends React.Component {
         // NOTE onItemBlur takes a boolean, we want to prevent it being passed a truthy event.
         onMouseLeave={e => this.onItemBlur(false)}
       >
-        <a href="#" onClick={this.onItemClick}>
+        <a href={href} onClick={this.onItemClick}>
```
Comment (jeff-phillips-18) [inline packages/patternfly-3/patternfly-react/src/components/VerticalNav/VerticalNavItemHelper.js]: items not setting href may not show the link correctly, seems to be working ok though (likely styled to always have the pointer cursor)/

File: packages/patternfly-3/patternfly-react/src/components/VerticalNav/VerticalNavItemHelper.js (hunk 1 above)
Comment (glekner) [reply packages/patternfly-3/patternfly-react/src/components/VerticalNav/VerticalNavItemHelper.js]: If asked to not prevent (`preventHref: false`) then it won't be prevented.
Because `preventHref` is default as `true`, I want to make sure there is an onClick prop aswell so if the `href` is prevented there is a function to call

File: packages/patternfly-3/patternfly-react/src/components/VerticalNav/VerticalNavItemHelper.js (hunk 2 above)
Comment (glekner) [reply packages/patternfly-3/patternfly-react/src/components/VerticalNav/VerticalNavItemHelper.js]: seems unnecessary because the `<a>` has the `href` now
