### PR TITLE
fix(generate tokens): prefix tokens with a t_

### LINKED ISSUE #10985: generateTokens script  should prfeix tokens with t
**Please describe the issue**

generateTokens script  should prfeix tokens with t

From slack [thread](https://redhat-internal.slack.com/archives/C04JTH3LQF6/p1726077029798309?thread_ts=1724272824.821169&cid=C04JTH3LQF6)

WARNING in ./node_modules/@patternfly/react-tokens/dist/esm/chart_global_Fill_Color_white.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* /Users/talton/github/ansible/aap-ui/node_modules/@patternfly/react-tokens/dist/esm/chart_global_Fill_Color_white.js
    Used by 1 module(s), i. e.
    /Users/talton/github/ansible/aap-ui/node_modules/@patternfly/react-tokens/dist/esm/index.js
* /Users/talton/github/ansible/aap-ui/node_modules/@patternfly/react-tokens/dist/esm/chart_global_fill_color_white.js
    Used by 1 module(s), i. e.
    /Users/talton/github/ansible/aap-ui/node_modules/@patternfly/react-tokens/dist/esm/index.js

[1:50](https://redhat-internal.slack.com/archives/C04JTH3LQF6/p1726077053454759?thread_ts=1724272824.821169&cid=C04JTH3LQF6)
WARNING in ./node_modules/@patternfly/react-tokens/dist/esm/index.js 4803:0-72
export 'chart_global_label_margin' (reexported as 'chart_global_label_margin') was not found in './chart_global_label_margin' (possible exports: chart_global_label_Margin, default)
[1:54](https://redhat-internal.slack.com/archives/C04JTH3LQF6/p1726077274496249?thread_ts=1724272824.821169&cid=C04JTH3LQF6)
Both of those were tokens errors for tokens that we are not using, but are part of the PF libs.

Dan
  [Yesterday at 2:21 PM](https://redhat-internal.slack.com/archives/C04JTH3LQF6/p1726078860070239?thread_ts=1724272824.821169&cid=C04JTH3LQF6)
Looks like the react-tokens/dist/esm/index.d.ts file contains both exports below
export { chart_global_label_Margin } from './chart_global_label_Margin';
export { chart_global_label_margin } from './chart_global_label_margin';
The filename is chart_global_label_margin, while chart_global_label_Margin is the default export
The index.d.ts file contains a lot of duplication like that (edited)

### PR DESCRIPTION
**Pull request by tlabaj**
**What**: Closes #10985 

A issue was noticed that react-token created chart token exports that differed  by one uppercase character. example 
`export { chart_global_label_Margin } from './chart_global_label_Margin';
export { chart_global_label_margin } from './chart_global_label_margin';
`

To test pull down this branch, build and look at the `react-tokens` `dist` directory.

**eg. of token before change**
image

**after change**

image

@thatblindgeye could we write code mod for this?

### CODE REVIEW

**Review by mcoker — APPROVED** [review]
LGTM! I did have to do a search and replace for `@patternfly/react-tokens/dist/esm/global_` with `@patternfly/react-tokens/dist/esm/t_global_` in `react-core/src` and `react-charts/src` to get the build to work but the `t_*` tokens look to have all generated correctly 👍

File: packages/react-tokens/scripts/generateTokens.mjs [hunk 1]
```diff
@@ -10,7 +10,7 @@ const version = 'v6';
 
 // Helpers
 const formatCustomPropertyName = (key) =>
-  key.replace(`--pf-${version}-`, '').replace('--pf-t--', '').replace(/-+/g, '_');
+  key.replace(`--pf-${version}-`, '').replace('--pf-t--', 't_').replace(/-+/g, '_');
```
Comment (dlabrecq) [inline packages/react-tokens/scripts/generateTokens.mjs:13]: How does prefixing with "t_" resolve the issue with multiple exports? 

I'm also curious why the version has been removed?

Comment (dlabrecq) [reply packages/react-tokens/scripts/generateTokens.mjs:13]: I built this branch locally and still see duplicates. The only difference now is one file is prefixed with "t_".

For example:
packages/react-tokens/dist/esm/chart_global_label_Margin.js
packages/react-tokens/dist/esm/t_chart_global_label_margin.js

Comment (tlabaj) [reply packages/react-tokens/scripts/generateTokens.mjs:13]: @dlabrecq the `packages/react-tokens/dist/esm/chart_global_label_Margin.js` is the variable.
the `packages/react-tokens/dist/esm/t_chart_global_label_margin.js` is the token.

@mcoker can add more context from a css perspective as to why they are named the same.

Comment (mcoker) [reply packages/react-tokens/scripts/generateTokens.mjs:13]: Hey @dlabrecq. The original bug is because the PF CSS has variables named very similarly like these two - `--pf-v6-chart-global--label--Margin` and `--pf-t--chart--global--label--margin`. The react-tokens package parses the PF CSS, finds all of our variables, and creates a react-token for each one with a name based based off of what the CSS variable name is. Most of the PF CSS vars fit into 4 categories:
* Components - `--pf-v6-c-[component]` creates a react token like `c_[component]`
* Layouts - `--pf-v6-l-[layout]`, creates `l_[layout]`
* Charts - `--pf-v6-chart-[color/global/axis/bar/etc]`, creates `chart_[color/global/axis/bar/etc]`
* Tokens, aka global vars - `--pf-t--[color/global/chart/etc]`, creates `[color/global/chart/etc]_`

So for the vars reference above, `--pf-v6-chart-global--label--Margin` and `--pf-t--chart--global--label--margin`, the resulting tokens are `chart_global_label_Margin` and `chart_global_label_margin`. There are a bunch of ways we could address that, but since the CSS token vars (`--pf-t--[...]`) are always prefixed with `-t--`, prefixing the react token filename with `t_[...]` solves this problem and follows the format of other prefixed vars/tokens in PF (`--pf-v6-c` and `--pf-v6-l`).

Comment (dlabrecq) [reply packages/react-tokens/scripts/generateTokens.mjs:13]: Thanks for the explanation. I didn't realize we wanted to expose both tokens and variables in this package

**Review by dlabrecq — APPROVED** [review]

**Review by evwilkin — APPROVED** [review]
LGTM - thanks for the notes on testing and the additional context from @mcoker

**Review by dlabaj — APPROVED** [review]

**Comment by dlabaj** [comment]
@tlabaj Can you link the org PR and then we can merge this.
