### PR TITLE
Bug fix: change key generation field for tree view

### LINKED ISSUE #5558: Allow an id/key to be passed down to the TreeViewList to avoid react warning
**Describe the issue. What is the expected and unexpected behavior?**

Inside the TreeViewList component, I need to be able to pass in an id/key so that react doesn't warn about a missing key.
**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

**What is your product and what release version are you targeting?**

image

### PR DESCRIPTION
**Pull request by ibolton336**
Since name is of type Reac.ReactNode, I propose we use the item.id to generate the key. 

**What**: Closes #5558

**Additional issues**:

### CODE REVIEW

**Review by redallen — APPROVED** [review]

**Review by redallen — DISMISSED** [review]

File: packages/react-core/src/components/TreeView/TreeView.tsx [hunk 1]
```diff
@@ -87,7 +87,7 @@ export const TreeView: React.FunctionComponent<TreeViewProps> = ({
     <TreeViewList isNested={isNested} onSearch={onSearch} searchProps={searchProps}>
       {data.map(item => (
         <TreeViewListItem
-          key={item.name.toString()}
+          key={item.id.toString()}
```
Comment (nicolethoen) [inline packages/react-core/src/components/TreeView/TreeView.tsx:90]: The only issue I see here, is that the id is not a required field, but the name is a required field on the TreeViewDataItem. So maybe it can use the id unless it's undefined? And if so, then use the name?

**Review by redallen — APPROVED** [review]
