### PR TITLE
Menu: Let consumer add SearchInput/TextInput

### LINKED ISSUE #5153: Menu component: replace SearchInput with TextInput
**Describe the issue. What is the expected and unexpected behavior?**
This issue follows the discussion here: https://github.com/patternfly/patternfly-react/pull/4847#discussion_r523275762

For the original issue that was opened to implement the menu component, see #4712.

The `<SearchInput>` component should be replaced with `<TextInput>` in the filterable menu variant, per @mcoker and @mcarrano.

### PR DESCRIPTION
**Pull request by jenny-s51**
**What**: Closes #5153 and #5205

**Additional issues**: #4712

### CODE REVIEW

File: packages/react-core/src/components/TextInput/TextInput.tsx [hunk 1]
```diff
@@ -180,7 +180,7 @@ export class TextInputBase extends React.Component<TextInputProps> {
           styles.formControl,
           validated === ValidatedOptions.success && styles.modifiers.success,
           validated === ValidatedOptions.warning && styles.modifiers.warning,
-          (iconVariant || customIconUrl) && styles.modifiers.icon,
+          (iconVariant !== 'search' || customIconUrl) && styles.modifiers.icon,
```
Comment (jschuler) [inline packages/react-core/src/components/TextInput/TextInput.tsx:183]: Also needs a check to see if it is defined otherwise it will always add the icon style
```suggestion
          ((iconVariant && iconVariant !== 'search') || customIconUrl) && styles.modifiers.icon,
```

File: packages/react-core/src/components/Menu/Menu.tsx [hunk 2]
```diff
@@ -76,25 +73,7 @@ class MenuBase extends React.Component<MenuProps, MenuState> {
...
-                    this.setState({ searchInputValue: '' });
-                    onSearchInputChange(event, '');
-                  }}
-                />
-              </div>
-              <Divider />
-            </React.Fragment>
-          )}
-          <div className={css(styles.menuContent)}>{children}</div>
+          <MenuContent>{children}</MenuContent>
```
Comment (jschuler) [inline packages/react-core/src/components/Menu/Menu.tsx:76]: Doesn't the input have to be outside of the `MenuContent` ? If so then this should just be `{children}` and consumer will have to pass
```
<Menu>
  <MenuInput><TextInput /></MenuInput>
  <MenuContent>
     <MenuList>...</MenuList>
  </MenuContent>
</Menu>
```

**Review by jschuler — CHANGES_REQUESTED** [review]

File: packages/react-core/src/components/Menu/MenuInput.tsx [hunk 3]
```diff
@@ -0,0 +1,18 @@
...
+
+export interface MenuInputProps extends React.HTMLProps<HTMLElement> {
+  /** Items within input */
+  children?: React.ReactNode;
+  /** Forwarded ref */
+  innerRef?: React.Ref<any>;
+}
+
+const MenuInputBase: React.FunctionComponent<MenuInputProps> = ({ children }: MenuInputProps) => (
+  <div className={styles.menuSearch}>{children}</div>
```
Comment (jschuler) [inline packages/react-core/src/components/Menu/MenuInput.tsx:12]: I think I also saw Core nesting `pf-c-menu__search-input` here, is that needed @mcoker ?

File: packages/react-core/src/components/Menu/examples/Menu.md [hunk 4]
```diff
@@ -174,19 +174,79 @@ class MenuWithFiltering extends React.Component {
...
+      <Menu onSelect={this.onSelect} activeItemId={activeItem}>
+        <MenuInput>
+          <TextInput
+            value={input}
+            aria-label="filterable-example-with-text-input"
+            iconVariant="search"
+            type="search"
+            onChange={value => this.handleTextInputChange(value, 'input')}
+          />
+        </MenuInput>
```
Comment (jschuler) [inline packages/react-core/src/components/Menu/examples/Menu.md:211]: Also needs the `Divider` back in both examples

File: packages/react-core/src/components/Menu/MenuInput.tsx (hunk 3 above)
Comment (mcoker) [reply packages/react-core/src/components/Menu/MenuInput.tsx:12]: @jschuler it's not necessary, but having that element makes it easier for us to style the text input relative to other things we might add to the menu search element.

**Review by jschuler — APPROVED** [review]
snapshots needs to be fixed, otherwise LGTM

File: packages/react-core/src/components/Menu/MenuContent.tsx [hunk 5]
```diff
@@ -0,0 +1,19 @@
...
+  innerRef?: React.Ref<any>;
+}
+
+const MenuContentBase: React.FunctionComponent<MenuContentProps> = ({ children }: MenuContentProps) => (
+  <div className={css(styles.menuContent)}>{children}</div>
+);
+
+export const MenuContent = React.forwardRef((props: MenuContentProps, ref: React.Ref<HTMLElement>) => (
+  <MenuContentBase {...props} innerRef={ref} />
+));
```
Comment (karelhala) [inline packages/react-core/src/components/Menu/MenuContent.tsx:18]: You are not doing anything with the `innerRef` prop, this way we'd just block the ref forwarding. Plus any additional props will be ignored and for instance custom class would be impossible to add. You can also simplify this by using the `div` directly
```suggestion
export const MenuContent = React.forwardRef((props: MenuContentProps, ref: React.Ref<HTMLElement>) => (
  <div {...props} className={css(styles.menuContent, props.className)} ref={ref} />
));
```

File: packages/react-core/src/components/Menu/MenuInput.tsx [hunk 6]
```diff
@@ -0,0 +1,18 @@
...
+);
+
+export const MenuInput = React.forwardRef((props: MenuInputProps, ref: React.Ref<HTMLElement>) => (
+  <MenuInputBase {...props} innerRef={ref} />
+));
```
Comment (karelhala) [inline packages/react-core/src/components/Menu/MenuInput.tsx:17]: Same as above, not really needed to add new component
```suggestion
export const MenuInput = React.forwardRef((props: MenuInputProps, ref: React.Ref<HTMLElement>) => (
  <div {...props} className={css(styles.menuSearch, props.className)} ref={ref} />
));
```

**Review by karelhala — COMMENTED** [review]
Looking good! I like the example with plain TextInput it shows the prefered way and allows for easy example that consumers can use whatever they want to show there.

**Comment by jenny-s51** [comment]
Thank you for your helpful feedback @karelhala ! I've applied your suggestions

**Review by karelhala — APPROVED** [review]

**Review by tlabaj — APPROVED** [review]
This looks good Jenny!

**Review by jschuler — APPROVED** [review]
