### PR TITLE
fix(truncate) tooltip shows without truncation

### LINKED ISSUE #10053: Bug - Truncate - tooltip also shows when there is no actual truncation
The [Truncate](https://www.patternfly.org/components/truncate) component always has a active tooltip for its content, even when there is no actual need for truncation:

image

Such a tooltip doesn't contribute anything to the user experience, but is an annoyance especially if there are many of them.

It would be great if `Truncate` would only have a tooltip when truncation does actually take place.

Alternatively, as a lesser alternative, a property would be welcome that allows the programmer to disable the tooltip completely.

### PR DESCRIPTION
**Pull request by Dominik-Petrik**
**What**: Closes #10053 

**Additional issues**: I have also added `hidden` prop to the `Tooltip` component which is useful both for this issue and in general

### CODE REVIEW

File: packages/react-core/src/components/Tooltip/Tooltip.tsx [hunk 1]
```diff
@@ -136,6 +136,8 @@ export interface TooltipProps extends Omit<React.HTMLProps<HTMLDivElement>, 'con
   id?: string;
   /** CSS fade transition animation duration */
   animationDuration?: number;
+  /** Determines whether the tooltip is hidden regardless of visibility **/
+  hidden?: boolean;
```
Comment (thatblindgeye) [inline packages/react-core/src/components/Tooltip/Tooltip.tsx:140]: I'm not sure whether we should introduce this prop, mainly because we already have an "isVisible" prop for manual control of a Tooltip.

Rather than needing to create this prop, we could just conditionally return either the  "full" Truncate content (if there is no truncation; basically everything that is currently being passed to Tooltip) or the "full" Truncate content wrapped in the Tooltip (if there is truncation).

We do something similar in ModalBoxTitle.

**Review by thatblindgeye — COMMENTED** [review]
Very nice 😎 One nit, though, is that rather than using the ResizeObserver constructor, we could try to use our `getResizeObserver` helper instead. The WizardBody component and the JumpsLinksWithDrawer demo are two examples that are using it in functional components.

**Review by thatblindgeye — APPROVED** [review]
