### PR TITLE
fix(LogViewer): update search function

### LINKED ISSUE #6590: Update search function for log viewer
**Describe the issue. What is the expected and unexpected behavior?**
Based on the comment here https://github.com/patternfly/patternfly-react/pull/6576#issuecomment-966563766. We should better update the search function of the log viewer. Currently, if there are several search words on the same row, they will be treated as one result. Instead of this behavior, we should show a single result for every searched keyword, which makes more sense.

### PR DESCRIPTION
**Pull request by DaoDaoNoCode**
**What**: Closes #6590 

Only highlight the searched keyword, but not the keywords on the same row.

### CODE REVIEW

File: packages/react-log-viewer/src/LogViewer/LogViewer.tsx [hunk 1]
```diff
@@ -188,12 +188,12 @@ const LogViewerBase: React.FunctionComponent<LogViewerProps> = memo(
...
+    const scrollToRowInFocus = (searchedRowIndex: searchedKeyWordType) => {
       setRowInFocus(searchedRowIndex);
-      logViewerRef.current.scrollToItem(searchedRowIndex, 'center');
+      logViewerRef.current.scrollToItem(searchedRowIndex.rowIndex, 'center');
       // use this method to scroll to the right
       // if the keyword is out of the window when wrapping text
-      if (!isWrapText) {
+      if (!isTextWrapped) {
         setTimeout(() => {
           const element = document.querySelector('.pf-c-log-viewer__string.pf-m-current');
```
Comment (jschuler) [inline packages/react-log-viewer/src/LogViewer/LogViewer.tsx:198]: do you have a ref to the logviewer parent?
would be better to use querySelector on the parent ref. I am thinking of the case where there are 2 log viewers on the same page, if you search on the second one it will cause the window to jump up to the first one otherwise

**Review by jschuler — APPROVED** [review]
nice work @DaoDaoNoCode !

**Review by tlabaj — APPROVED** [review]
Thank you!
