### PR TITLE
fix(checkbox): set checked if onChanged is not the default

### LINKED ISSUE #2036: Checkbox regression (uncontrolled version)
I just realized that my change https://github.com/patternfly/patternfly-react/pull/1929 causes a regression in the uncontrolled version.

The `isChecked` prop is set to false which is then making the uncontrolled version being controlled.
Need to check if the user wants to make it controlled or not by verifying if `onChange` was set too. If not, then the `checked` prop in input should not be set.

### PR DESCRIPTION
**Pull request by boaz0**
**What**:

fixes #2036 

This change checks whether `onChange` is set by the user.
If it does, it means the component is controlled by the user. In this case, the input `checked` props should be set by `isChecked/checked` props passed to `Checkbox`. Otherwise, set input `checked` only if `checked` is true or false or `isChecked` is true (because `isChecked` is Boolean TS by default sets it to false).

### CODE REVIEW

File: packages/patternfly-4/react-core/src/components/Checkbox/Checkbox.tsx [hunk 1]
```diff
@@ -54,14 +54,18 @@ export class Checkbox extends React.Component<CheckboxProps> {
       isChecked,
       label,
       checked,
+      defaultChecked,
```
Comment (redallen) [inline packages/patternfly-4/react-core/src/components/Checkbox/Checkbox.tsx]: [Default checked](https://www.w3schools.com/jsref/prop_checkbox_defaultchecked.asp) support! :+1:

**Comment by boaz0** [comment]
Thank you @redallen @dlabaj @tlabaj! :smile:
