### PR TITLE
fix(Menu): remove rogue scrollbar from drilldown menus

### LINKED ISSUE #6842: Drilldown menu: unnecessary scroll bar in sub menus
Each MenuList has top and bottom padding.
In the case of a Drilldown menu, each sub level of a MenuList is rendered as a child of the MenuList. It results in nested MenuLists. To prevent the top and bottom padding from stacking (and growing too large). MenuLists which are children of other MenuLists have their padding zeroed out (see the screen shot below).

Screen Shot 2022-01-20 at 12 48 34 PM

This causes for the calculation of the height of the Menu in `MenuContent.tsx`'s `refCallback` around line 21 to be incorrect. The sub MenuList's clientHeight does not include the padding of it's parent MenuList so it thinks that the rendered sub menu is shorter than it actually is, causing the contents to overflow and create a scrollbar.

### PR DESCRIPTION
**Pull request by nicolethoen**
**What**: Closes #6842

unfortunately, the top/bottom padding for the MenuContent is = 0.5rem, so it makes the calculation complicated and dependent on font size. And when I try to load the value of the variable into react for possible calcluations, even that 0.5rem value is overridden by a subsequent rule so I cannot import the variable value directly into the component using react-tokens.
(i.e. `import c_menu__list_PaddingTop from '@patternfly/react-tokens/dist/esm/c_menu__list_PaddingTop';` returns the wrong value).

so for now, I use the default value of 16px, which is what the padding top and bottom defaults to with no custom overrides. Not sure if there is an alternate option right now...

### CODE REVIEW

**Comment by jeffpuzzo** [comment]
I haven't tested this out, but here's something else to try since I agree in that hardcoding the pixels for padding isn't ideal:

```
const parentMenuList = el.closest(`.${styles.menuList}`);
const parentMenuListStyles = window.getComputedStyle(parentMenuList);

const paddingOffset = parseFloat(
  parentMenuListStyles.getPropertyValue('padding-top') + 
  parentMenuListStyles.getPropertyValue('padding-bottom')
);

const clientHeight = !!parentMenuList ? el.clientHeight + paddingOffset : el.clientHeight;
```

**Review by jeffpuzzo — APPROVED** [review]
If the suggestion mentioned doesn't work out, I did verify the existing change solves issue and am ok with it if no other alternatives to a hardcoded padding value exist.

**Review by kmcfaul — APPROVED** [review]

File: packages/react-core/src/components/Menu/MenuContent.tsx [hunk 1]
```diff
@@ -21,8 +21,33 @@ export const MenuContent = React.forwardRef((props: MenuContentProps, ref: React
...
+
+      if (rootMenuList) {
+        const rootMenuListStyles = getComputedStyle(rootMenuList);
+        const rootMenuListPaddingOffset =
+          parseFloat(rootMenuListStyles.getPropertyValue('padding-top').replace(/px/g, '')) +
+          parseFloat(rootMenuListStyles.getPropertyValue('padding-bottom').replace(/px/g, '')) +
+          parseFloat(
+            getComputedStyle(rootMenuList.parentElement)
+              .getPropertyValue('border-bottom-width')
+              .replace(/px/g, '')
```
Comment (thatblindgeye) [inline packages/react-core/src/components/Menu/MenuContent.tsx:44]: For these lines, is this just to take into account that 1px bottom-border that is on the example page rather than the menu itself?

Mainly asking as I was just wondering whether a top border should be taken into account as well.

**Review by thatblindgeye — APPROVED** [review]
Looks good! Just had a clarifying comment below.

File: packages/react-core/src/components/Menu/MenuContent.tsx (hunk 1 above)
Comment (nicolethoen) [reply packages/react-core/src/components/Menu/MenuContent.tsx:44]: In fact, the border is applied to the bottom of the root menu's `MenuContent` when it's in a nav.
```
.pf-c-nav .pf-c-menu:first-child > .pf-c-menu__content {
    border-bottom: var(--pf-c-nav--c-menu__item--before--BorderBottomWidth) solid var(--pf-c-nav--c-menu__item--before--BorderBottomColor);
}
```

**Review by mattnolting — APPROVED** [review]
👍  This looks right to me. Side note, the drilldown has a scrollbar when actively drilling in to a menu. We need to address that: https://github.com/patternfly/patternfly/issues/4748
