### PR TITLE
fix(nav): Allow nav to expand by prop change

### LINKED ISSUE #1016: NavExpandable does not expand or collapse programmatically
If the NavExpandable component prop `isActive` is set to true, it would be great to have an option to expand it automatically. 

Setting the value of `isExpanded` to true or false does not expand or collapse the nav list items. When NavToggle is manually selected, it calls `this.setState({ value: !value });` from within `handleToggle`. This successfully toggles the NavExpandable open and close. We would like to be able to set the value of `isExpanded` programmatically by passing/setting props. Currently, this option isn't available.

nav bug

### PR DESCRIPTION
**Pull request by ibolton336**
**What**: fixes #1016 

**Additional issues**:

### CODE REVIEW

**Comment by rhamilto** [comment]
@ibolton336, this fix appears to have introduced a bug where previously expanded sections that have been collapsed are re-expanded on next navigate.

yikrsqwdlu

cc: @spadgett, @janwright73

File: packages/patternfly-4/react-core/src/components/Nav/NavToggle.js [hunk 1]
```diff
@@ -20,7 +20,11 @@ class NavToggle extends React.Component {
   state = {
     value: this.props.defaultValue
   };
-
+  componentWillReceiveProps(nextProps) {
```
Comment (priley86) [inline packages/patternfly-4/react-core/src/components/Nav/NavToggle.js]: this lifecycle method is soon to be deprecated. It works with our target version of React, but I recommend looking at `getDerivedStateFromProps` and `componentDidUpdate`.

https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops
https://egghead.io/lessons/react-refactor-componentwillreceiveprops-to-getderivedstatefromprops-in-react-16-3
