### PR TITLE
fix(table): Adds support for custom dataLabel prop on table header

### LINKED ISSUE #2941: PF4 react-table colums (title) to support jsx (also in collapsed view)
Pretty pretty please, would be great if pf-table didn't hate this

this kinda thing
```
    const [cols] = useState([
        { title: intl.formatMessage(messages.rulesTableColumnTitleRule), transforms: [sortable] },
        { title: intl.formatMessage(messages.rulesTableColumnTitleAdded), transforms: [sortable, cellWidth(15)] },
        { title: intl.formatMessage(messages.rulesTableColumnTitleTotalrisk), transforms: [sortable] },
        { title: intl.formatMessage(messages.rulesTableColumnTitleSystems), transforms: [sortable] },
        { title: <><AnsibeTowerIcon size='md' /> {intl.formatMessage(messages.rulesTableColumnTitleAnsible)}</>, transforms: [sortable] }
    ]);
```
throws this warning (it doesn't enjoy the `<><AnsibeTowerIcon size='md' />...</>`
Screen Shot 2019-09-16 at 3 10 23 PM

also, it doesn't collapse very well, displays fallback rather than the column name

Screen Shot 2019-09-16 at 3 08 48 PM

what it oughta look like

Screen Shot 2019-09-16 at 3 09 00 PM

### PR DESCRIPTION
**Pull request by AllenBW**
fixes #2941

but just in case you don't want to read the issue....  tl;dr: when collapsed table shows a very undesired `column-foo` when jsx is used as the table header.  So lets allow for a custom data-label attribute to be passed when a dev wants to do this, so they can avoid the erum, undesired collapsed header

#### just in case yah wanta see what we're attempting to fix... (top is collapsed, bottom is expanded)
Screen Shot 2019-09-30 at 2 53 17 PM
Screen Shot 2019-09-30 at 2 53 30 PM

### CODE REVIEW

File: packages/patternfly-4/react-table/src/components/Table/utils/headerUtils.tsx [hunk 1]
```diff
@@ -59,14 +59,16 @@ const generateCell = ({ cellFormatters, cellTransforms, columnTransforms, cell }
...
+ * @param {*} column to be shown in header - either string or object with title, transformers and formatters (for cells as well).
  * @param {*} extra additional object with callbacks for specific formatters.
  * @param {*} key cell key to be shown in data-key.
  * @param {*} props additional props for each cell.
  * @returns {*} object with property, extraParams, header, cell and props.
  */
 const mapHeader = (column: ICell, extra: any, key: number, ...props: any) => {
   const title = (column.hasOwnProperty('title') ? column.title : column) as string | ICell;
+  const dataLabel = (column.hasOwnProperty('dataLabel') ? column.dataLabel : typeof title === 'string' ? title : `column-${key}`) as string | ICell;
+  console.error(dataLabel);
```
Comment (redallen) [inline packages/patternfly-4/react-table/src/components/Table/utils/headerUtils.tsx]: Remove console logging.

Comment (AllenBW) [reply packages/patternfly-4/react-table/src/components/Table/utils/headerUtils.tsx]: yup, good call 🤗

**Comment by AllenBW** [comment]
@redallen any chance i can get another review from yah? we (insights app) would like to try n get this in (and use it) before this friday if possible

**Comment by AllenBW** [comment]
@redallen @tlabaj  ya'll rocked my thursday, thank you 🙇‍♀ 
Screen Shot 2019-10-03 at 9 06 58 AM
Screen Shot 2019-10-03 at 9 07 07 AM
