### PR TITLE
Breaking modal variant

### LINKED ISSUE #3900: PF4 Modal: Combine the isLarge and isSmall prop into one variant prop.
**Describe the issue. What is the expected and unexpected behavior?**
PF4 Modal: Combine the isLarge and isSmall prop into one variant prop since the can not be applied at the same time.
**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

**What is your product and what release version are you targeting?**

### PR DESCRIPTION
**Pull request by kmcfaul**
**What**: Closes #3900

## Breaking changes
1. Collapses the `isLarge` and `isSmall` properties into a single `variant` property. To maintain the current behavior, set the `variant` property to `large` or `small`, or use the newly added `ModalVariant` enum as `ModalVariant.large` or `ModalVariant.small`.

### CODE REVIEW

**Comment by tlabaj** [comment]
can you update the descriptions of all you breaking change PRs to have a description of the changes in this format.  Zach will run a script to create a document.  Thanks!

## Breaking changes
1. Removes deprecated prop `dropdownItems`.  the prop `items` should be used instead
2.  other changes

File: packages/react-core/src/components/Modal/ModalBox.tsx [hunk 1]
```diff
@@ -7,10 +7,8 @@ export interface ModalBoxProps extends React.HTMLProps<HTMLDivElement> {
   children: React.ReactNode;
   /** Additional classes added to the ModalBox */
   className?: string;
-  /** Creates a large version of the ModalBox */
-  isLarge?: boolean;
-  /** Creates a small version of the ModalBox. */
-  isSmall?: boolean;
+  /** Variant of the modal */
+  variant?: 'large' | 'medium' | 'small';
```
Comment (tlabaj) [inline packages/react-core/src/components/Modal/ModalBox.tsx]: Isn't what you have here as `medium` the default which is full width?  Maybe call it `full` or `default`?
cc @mcoker

Comment (kmcfaul) [reply packages/react-core/src/components/Modal/ModalBox.tsx]: I'll change it to `default`
