### PR TITLE
fix(Table): added ActionsColumn prop to control close on click

### LINKED ISSUE #8971: Table - ActionsColumn: a11y violation in actions menu when triggering modal
**Is this a new component or an extension of an existing one?**

ActionsColumn

**Describe the feature**

When testing in ODH, this a11y violation was raised: https://docs.deque.com/issue-help/1.0.0/en/focus-modal-not-returned

If the consumer toggles a modal open via the actions menu kebab, the kebab is closed but it should remain open and the triggering element should retain focus when the modal is closed. 

**The focus MUST be purposely moved or set (via JavaScript) onto the appropriate element when the user's action requires a change of context or location for effective keyboard or touch interaction.**

**The focus MUST NOT become lost or reset to the top of the page, except when loading or re-loading a page.**

TODO: Update the ActionsColumn dropdown logic to support the isOpen state on the kebab when an item is selected.

### PR DESCRIPTION
**Pull request by thatblindgeye**
**What**: Closes #8971 

Tested adding logic to open a Modal upon clicking an action item with the new `shouldCloseOnClick: false` and it works fine. Only thing is that `event.stopPropagation()` has to be called in whatever logic controls closing the Modal itself, so that will have to be handled by the consumer.

Another thing is that clicking with mouse when a modal is open will close the dropdown toggle, but that should be expected behavior since the `onOpenChange` callback controls closing the dropdown on click outside/Escape press. Without it the dropdown won't close unless an action item is clicked.

To test on the [table with actions example](https://patternfly-react-pr-10179.surge.sh/components/table#actions):

1. Add the following code at the top of the export of the example code:
    ```
      const [isModalOpen, setIsModalOpen] = React.useState(false);
      const handleModalToggle = (e) => {
        e.stopPropagation();
        setIsModalOpen(!isModalOpen);
      };
    ```
2. To one of the `defaultActions` action item objects, update the `onClick` to `onClick: handleModalToggle` and add `shouldCloseOnClick: false` as another property
3. Add a Modal to the imports from react-core and then return a `<Modal>` after the closing `</Table>` tag:
    ```
      <Modal
        title="Basic modal"
        isOpen={isModalOpen}
        onClose={handleModalToggle}
      >
        Modal content
      </Modal>
    ```
4. Use keyboard to trigger the Modal open and to close it

**Additional issues**:

### CODE REVIEW

**Review by jenny-s51 — COMMENTED** [review]
Looks great @thatblindgeye ! Keyboard behavior works as expected and focus is returned to the item that toggles the modal 🎉

I'm wondering, in general, when a modal is toggled, is the expected behavior that the modal overlay freezes the underlying UI state and disables any pointer events beneath it? 

If the modal is opened with a mouse, is there a way to prevent any pointer events from closing the dropdown, so we can still return the focus back to it even when a consumer clicks somewhere on the screen?

**Comment by thatblindgeye** [comment]
@jenny-s51 that's a really good question. The [dialog pattern from the ARIA authoring practices guide](https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/) mentions, "Windows under a modal dialog are inert. That is, users cannot interact with content outside an active dialog window." I feel like what is happening in this situation is kinda muddy. Technically we're not interacting *with* the dropdown, some logic is just firing based on us clicking within the `window`. At the same time, though, it does make me ponder if we should prevent such logic from firing since it's logic tied to something outside the dialog window.

I threw a couple things together locally that achieves the result you'd be looking for I think. 

- The first required adding an `event` param to the Dropdown's `onOpenChange` prop (so it becomes `event, isOpen`), then within ActionsColumn updating the Dropdown that gets rendered so within its `onOpenChange` we only call `setIsOpen` if `event.target.closest` doesn't find a specific selector (I just checked for the backdrop component). This would probably still be a bit limiting unless we allow consumers to customize some selector within ActionsColumn (plus naming that I imagine would be difficult)
- The other was simply adding something like a `preventOnOpenChange` prop in ActionsColumn, and setting its value to be the same as the Modal's `isOpen` value. When the modal isn't open clicking outside the dropdown menu/toggle closes it like normal, but when the modal is open the dropdown menu won't close due to outside click/Escape press. My worry with that is that it could be used outside this specific use-case, resulting in less accessible action dropdowns in tables that just never close via keyboard/outside click like they're meant to.

**Review by jenny-s51 — APPROVED** [review]
> * The other was simply adding something like a `preventOnOpenChange` prop in ActionsColumn, and setting its value to be the same as the Modal's `isOpen` value. When the modal isn't open clicking outside the dropdown menu/toggle closes it like normal, but when the modal is open the dropdown menu won't close due to outside click/Escape press. 

Your proposed solutions are very helpful @thatblindgeye - thank you for your time and efforts investigating this. Following our team discussion in PF office hours today, we'll lean towards the approach you and @kmcfaul proposed (quoted above), and will plan on implementing this on the product side to keep the toggle behavior consistent for both keyboard and mouse users.

LGTM! 🚀

File: packages/react-table/src/components/Table/ActionsColumn.tsx [hunk 1]
```diff
@@ -30,6 +30,8 @@ export interface ActionsColumnProps extends Omit<React.HTMLProps<HTMLElement>, '
   innerRef?: React.Ref<any>;
   /** Ref to forward to the first item in the popup menu */
   firstActionItemRef?: React.Ref<HTMLButtonElement>;
+  /** Flag indicating that the dropdown's onOpenChange callback should not be called. */
+  isOnOpenChangeDisabled?: boolean;
```
Comment (thatblindgeye) [inline packages/react-table/src/components/Table/ActionsColumn.tsx:34]: Per above I've added this prop. From what I can tell since ActionsColumn has its own isOpen state, being able to pass a custom onOpenChange callback wouldn't be as easy without introducing other props to customize things, and at that point I'd wonder if it wouldjust make more sense to allow passing a custom Dropdown itself (rather than right now we only really allow a custom `actionsToggle`)

**Review by nicolethoen — APPROVED** [review]
