### PR TITLE
fix(SkipToContent): Updated markup

### LINKED ISSUE #8260: Skip to content and button style conflict
Placeholder for core work in https://github.com/patternfly/patternfly/issues/4972

### PR DESCRIPTION
**Pull request by nicolethoen**
**What**: Closes #8260

Moves the `pf-c-skip-to-content` class off of the `Button` and onto a div wrapping the `Button`.

### CODE REVIEW

**Review by thatblindgeye — APPROVED** [review]

**Review by kmcfaul — APPROVED** [review]

**Review by gitdallas — APPROVED** [review]

File: packages/react-core/src/components/SkipToContent/SkipToContent.tsx [hunk 1]
```diff
@@ -32,14 +32,16 @@ export class SkipToContent extends React.Component<SkipToContentProps> {
...
     return (
-      <a
-        {...rest}
-        className={css(buttonStyles.button, buttonStyles.modifiers.primary, styles.skipToContent, className)}
-        ref={this.componentRef}
-        href={href}
-      >
-        {children}
-      </a>
+      <div className={css(styles.skipToContent, className)}>
```
Comment (tlabaj) [inline packages/react-core/src/components/SkipToContent/SkipToContent.tsx:35]: Should we spread the props on the div now?

File: packages/react-core/src/components/SkipToContent/SkipToContent.tsx [hunk 2]
```diff
@@ -32,14 +32,16 @@ export class SkipToContent extends React.Component<SkipToContentProps> {
...
+        <a
+          {...rest}
+          className={css(buttonStyles.button, buttonStyles.modifiers.primary)}
+          ref={this.componentRef}
+          href={href}
+        >
+          {children}
+        </a>
```
Comment (mcoker) [inline packages/react-core/src/components/SkipToContent/SkipToContent.tsx:43]: Could this use the button component instead of manually applying the styles?

```suggestion
        <Button
          {...rest}
          ref={this.componentRef}
          component="a"
          href={href}
          variant="primary"
        >
          {children}
        </Button>
```

**Review by mcoker — COMMENTED** [review]
LGTM - a question about using the button component. Also there is a `show` prop that says it's used for demo purposes - do we have a use case for that or could we remove it?

**Review by thatblindgeye — APPROVED** [review]
Just a snapshot update/and a linting error that needs to be resolved, otherwise looks good

File: packages/react-core/src/components/SkipToContent/SkipToContent.tsx [hunk 3]
```diff
@@ -1,45 +1,28 @@
...
-  };
-  componentRef = React.createRef<HTMLAnchorElement>();
+export const SkipToContent: React.FunctionComponent<SkipToContentProps> = ({
+  children = null,
+  className = '',
+  href,
+  ...props
+}: SkipToContentProps) => (
+  <div className={css(styles.skipToContent, className)} {...props}>
+    <Button variant={ButtonVariant.primary} component='a' href={href}>
```
Comment (mcoker) [inline packages/react-core/src/components/SkipToContent/SkipToContent.tsx:22]:
```suggestion
    <Button variant={ButtonVariant.primary} component="a" href={href}>
```

**Review by mcoker — APPROVED** [review]
LGTM other than the linting
