### PR TITLE
fix(Accordion): set button type, update prop extension

### LINKED ISSUE #5661: Button in AccordionToggle submits form
**Describe the issue. What is the expected and unexpected behavior?**

In `AccordionToggle`, the Button isn't explicitly set with type "button", which makes it a "submit" type by default (may depend on browsers). It is of course not expected that expanding or collapsing an accordion item would submit a parent form.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

https://codesandbox.io/s/epic-dirac-o87of?file=/index.js

Expanding or collapsing accordion would trigger the "submitted" alert.

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

It's a bug. There's a workaround, since the `AccordionToggle` props are passed down to button, it's possible to write:

```jsx
            <AccordionToggle
              onClick={() => {
                onToggle("ex-toggle1");
              }}
              isExpanded={this.state.expanded === "ex-toggle1"}
              id="ex-toggle1"
              type="button"
            >
```

In typescript however, the AccordionToggleProps wouldn't allow to pass an extra props, so it has to be cast as `any` first.

**What is your product and what release version are you targeting?**

Product is the openshift console. Tested with several versions: 4.101.2 (used in openshift console) and 4.106.2 in codesandbox.
Tested on Firefox 87 and Chrome 89.

### PR DESCRIPTION
**Pull request by kmcfaul**
**What**: Closes #5661

@tlabaj I'm not sure, but would this be considered a breaking change? It sets a default, but the default probably shouldn't be `submit` for this component.

### CODE REVIEW

**Comment by kmcfaul** [comment]
Added a FileUpload demo to integration @tlabaj 

Upon testing, it looks like the `onClick` passed to the FileUploadField actually does nothing because it gets set on the div (and wasn't triggering). I adjusted the `onClick` to pass to FileUploadField's text area directly as a callback, and added a property to FileUploadField as well. @metalice Is this the behavior of the onClick you were looking for?

**Review by tlabaj — APPROVED** [review]
This should be fine.  We have made the same update in other components.

**Comment by tlabaj** [comment]
@mattnolting core may need a similar update

File: packages/react-core/src/components/Accordion/AccordionToggle.tsx [hunk 1]
```diff
@@ -4,7 +4,8 @@ import styles from '@patternfly/react-styles/css/components/Accordion/accordion'
 import AngleRightIcon from '@patternfly/react-icons/dist/js/icons/angle-right-icon';
 import { AccordionContext } from './AccordionContext';
 
-export interface AccordionToggleProps extends Omit<React.HTMLProps<HTMLButtonElement>, 'type'> {
+export interface AccordionToggleProps
+  extends React.DetailedHTMLProps<React.ButtonHTMLAttributes<HTMLButtonElement>, HTMLButtonElement> {
```
Comment (nicolethoen) [inline packages/react-core/src/components/Accordion/AccordionToggle.tsx:8]: I have not seen this before but a quick google search says something about DetailedHTMLProps including ref and key as props? Should we be extending this in all our function components? Can you point me to why you made this update?

Comment (kmcfaul) [reply packages/react-core/src/components/Accordion/AccordionToggle.tsx:8]: I made the update because of the `type` prop. Without it passing 'submit' or 'reset' or 'button' gives an error (it's parsing as a string instead of one of the enum). I've seen it in a couple of components, but I'm unsure which extension we should use over.

Comment (nicolethoen) [reply packages/react-core/src/components/Accordion/AccordionToggle.tsx:8]: okay. I'll keep it in my back pocket as a possible remedy for other typescript errors/warnings in the future.

**Review by nicolethoen — APPROVED** [review]

**Review by dlabrecq — APPROVED** [review]

**Review by mattnolting — APPROVED** [review]
Perfect! 🎉
