### PR TITLE
fix(Chip/Label): update structure to work with core updates

### LINKED ISSUE #8454: Chip/label - update structure elements
Placeholder for https://github.com/patternfly/patternfly/issues/5199 and https://github.com/patternfly/patternfly/issues/5335

Just along the lines of adding some sort of container to put the close button in instead of just placing it as a child with no sort of component identifier. Also require `.pf-c-chip-group__main`. Though it may already be required, it looks that from https://github.com/patternfly/patternfly-react/blob/main/packages/react-core/src/components/ChipGroup/ChipGroup.tsx, but mentioning it just to confirm it's required since it's now required in core.

### PR DESCRIPTION
**Pull request by gitdallas**
**What**: Closes #8454

### CODE REVIEW

File: packages/react-core/src/components/Label/Label.tsx [hunk 1]
```diff
@@ -183,17 +183,19 @@ export const Label: React.FunctionComponent<LabelProps> = ({
   const LabelComponent = (isOverflowLabel ? 'button' : 'span') as any;
 
   const button = closeBtn ? (
-    closeBtn
+    <span className={css(styles.labelActions)}>closeBtn</span>
```
Comment (thatblindgeye) [inline packages/react-core/src/components/Label/Label.tsx:186]:
```suggestion
    <span className={css(styles.labelActions)}>{closeBtn}</span>
```

**Review by thatblindgeye — CHANGES_REQUESTED** [review]

File: packages/react-core/src/components/Label/Label.tsx (hunk 1 above)
Comment (gitdallas) [reply packages/react-core/src/components/Label/Label.tsx]: whoops - couldn't find any example of this being used, do we know if anyone using a custom close button?

Comment (thatblindgeye) [reply packages/react-core/src/components/Label/Label.tsx]: Yeah I had to pass the closeBtn prop in manually to test it. Only use case I can think of is something along the lines of wanting to use a trash can icon instead of the `x`

File: packages/react-core/src/components/Label/Label.tsx [hunk 2]
```diff
@@ -183,17 +183,19 @@ export const Label: React.FunctionComponent<LabelProps> = ({
...
+        type="button"
+        variant="plain"
+        onClick={onClose}
+        aria-label={closeBtnAriaLabel || `Close ${children}`}
+        {...closeBtnProps}
+      >
+        <TimesIcon />
+      </Button>
+    </span>
   );
```
Comment (wise-king-sullyman) [inline packages/react-core/src/components/Label/Label.tsx:199]: Super small non blocking nit: to get rid of the duplicate span I would wrap the whole button in the span, i.e. something like


```js
const defaultButton = (
    <Button
        type="button"
        variant="plain"
        onClick={onClose}
        aria-label={closeBtnAriaLabel || `Close ${children}`}
        {...closeBtnProps}
      >
        <TimesIcon />
    </Button>
)

const button = (
    <span className={css(styles.labelActions)}>
        {closeBtn || defaultButton}
    </span>
)

**Review by wise-king-sullyman — APPROVED** [review]
LGTM, one non blocking nit:

**Review by tlabaj — COMMENTED** [review]
lgtm other than suggestion Austin made.

**Review by tlabaj — APPROVED** [review]

**Review by mcoker — CHANGES_REQUESTED** [review]
Just one thing - looks like the overflow chip is its own thing and needs `styles.chipContent` around the text, too - https://github.com/patternfly/patternfly-react/blob/7dee099816b17b93e7f9263a564040b0b0a563aa/packages/react-core/src/components/Chip/Chip.tsx#L117

Screenshot 2023-03-03 at 12 26 06 PM

File: packages/react-core/src/components/Label/Label.tsx (hunk 1 above)
Comment (evwilkin) [reply packages/react-core/src/components/Label/Label.tsx]: FYI per request from @mcoker I checked the projects we currently track and found `closeBtnAriaLabel` and `closeBtnProps` but no use of just `closeBtn`.  Here is the list of files with the props mentioned above:

```
- Migration-Toolkit-for-Containers/src/app/home/pages/PlansPage/components/Wizard/MigrationOptions/MigrationOptionsForm.tsx
- Kogito/packages/pmml-editor/src/editor/components/DataDictionary/PropertiesLabels/PropertiesLabels.tsx
- Kogito/packages/pmml-editor/src/editor/components/MiningSchema/MiningSchemaFieldLabels/MiningSchemaFieldLabels.tsx
- Infinispan/src/app/Caches/Create/Features/IndexedCacheConfigurator.tsx
- Cockpit-machines/src/components/common/stateIcon.jsx
```

**Review by mcoker — APPROVED** [review]
LGTM!
