### PR TITLE
fix(Select-next,Dropdown-next): updated logic for keyboard interaction

### LINKED ISSUE #8124: Select-next,Dropdown-next: Space should open menu & focus first item
Currently only `Enter` is working to both open the menu and focus the first item. `Space` can open the menu but isn't focusing the item.

### PR DESCRIPTION
**Pull request by thatblindgeye**
**What**: Closes #8124

[Dropdown next preview](https://patternfly-react-pr-8496.surge.sh/components/dropdown/react-next)
[Select next preview](https://patternfly-react-pr-8496.surge.sh/components/select/react-next)

For the additional issue noted in the link above regarding adding `role="option"` to the underlying MenuItem, a `role="listbox"` and `aria-multiselectable` would need to be added to MenuList and `aria-selected` to MenuItem in order to make things more accessible.

I pushed one possible implementation where a consumer would just need to pass in `selectVariant` with a value of "single" or "multi" (works for either Next Select or just a plain Menu component), with that adding all the necessary attributes under the hood. 

The alternative wouldn't really change anything for Next Select (consumer would still just have to pass in a prop to determine whether it's a single or multi select and everything else would be done under the hood), but when using the Menu components themselves to set something up similar to our "Option single select" and "Option multi select" examples, the `role` would need to be manually passed into MenuItem and MenuList.

**Additional issues**:

### CODE REVIEW

File: packages/react-core/src/components/Menu/Menu.tsx [hunk 1]
```diff
@@ -63,6 +63,8 @@ export interface MenuProps extends Omit<React.HTMLAttributes<HTMLDivElement>, 'r
   ouiaId?: number | string;
   /** Set the value of data-ouia-safe. Only set to true when the component is in a static state, i.e. no animations are occurring. At all other times, this value must be false. */
   ouiaSafe?: boolean;
+  /** @beta The variant of a non-checkbox menu. Determines whether one or more items can be selected. */
+  selectVariant?: 'single' | 'multi';
```
Comment (kmcfaul) [inline packages/react-core/src/components/Menu/Menu.tsx:67]: Can the description mention specifically that the role and aria props are being manipulated by this prop?  Maybe I'm thinking too much of the original select but currently it sounds like to me that the prop should be changing functionality / handling of selection when it doesn't.

Everything else lgtm.

**Review by nicolethoen — APPROVED** [review]
VO and keyboard work as expected! LGTM

File: packages/react-core/src/components/Menu/Menu.tsx (hunk 1 above)
Comment (tlabaj) [reply packages/react-core/src/components/Menu/Menu.tsx:67]: Yes agree with Katie.  The prop name is a little misleading. I am trying to think i there is a better name...

**Review by wise-king-sullyman — APPROVED** [review]

File: packages/react-core/src/components/Menu/Menu.tsx (hunk 1 above)
Comment (thatblindgeye) [reply packages/react-core/src/components/Menu/Menu.tsx:67]: Yeah the prop name I wasn't totally sure on. `ariaSelection` could maybe fit a little more, but there are non ARIA attributes being set. selectionType is another one, though may not be better than selectVariant.

I can push an update to the description and see if that would help a bit, though definitely open to updating the prop name as well if we can land on one that's more fitting.

Comment (thatblindgeye) [reply packages/react-core/src/components/Menu/Menu.tsx:67]: @tlabaj @kmcfaul what about, "Determines the roles and ARIA attributes for a non-checkbox menu. Only pass in if one or more menu items can be selected." as a description?

Comment (kmcfaul) [reply packages/react-core/src/components/Menu/Menu.tsx:67]: Sounds good for the description. Name-wise I haven't been able to think of a better fitting name. `roleAriaType` maybe, but that's a bit unclear still. `roleAndAriaType`?

Comment (thatblindgeye) [reply packages/react-core/src/components/Menu/Menu.tsx:67]: Maybe using `aria-multiselectable` as the prop for Menu and having to pass in true or false? If the prop is undefined,  the Menu isn't a non-checkbox select menu, otherwise true or false could still set the role and ARIA attributes, with the actual boolean setting the `aria-multiselectable` attribute itself. Or maybe `ariaSelectionType` to keep the `"single" | "multi"` typing.

Comment (thatblindgeye) [reply packages/react-core/src/components/Menu/Menu.tsx:67]: That could work... For role we could have it be to set the MenuList role, so either listbox or menu, with that determining the role of MenuItem (if `role="listbox"` then MenuItem would have `role="option"` set).;

@tlabaj wdyt?

Comment (tlabaj) [reply packages/react-core/src/components/Menu/Menu.tsx:67]: Yes, I think that would be much more intuitive.  Good idea.

Comment (thatblindgeye) [reply packages/react-core/src/components/Menu/Menu.tsx]: @kmcfaul @tlabaj updated! Had to also add a role prop for Select Next so that a checkbox select could have `role="menu"` set on it (with the default being `role="listbox"`)

@nicolethoen would you mind taking another pass in VO?

File: packages/react-core/src/components/Menu/examples/MenuOptionSingleSelect.tsx [hunk 2]
```diff
@@ -12,9 +12,9 @@ export const MenuOptionSingleSelect: React.FunctionComponent = () => {
   };
 
   return (
-    <Menu onSelect={onSelect} activeItemId={activeItem} selected={selectedItem}>
+    <Menu role="listbox" onSelect={onSelect} activeItemId={activeItem} selected={selectedItem}>
```
Comment (nicolethoen) [inline packages/react-core/src/components/Menu/examples/MenuOptionSingleSelect.tsx:15]: Can we note the use of `listbox` in the text above these two updated examples? since erin has written such beautiful documentation for our Menu examples 😊

**Review by nicolethoen — COMMENTED** [review]
VO sounds good to me

**Review by tlabaj — APPROVED** [review]
LGTM

**Review by kmcfaul — APPROVED** [review]
LGTM!
