### PR TITLE
feat(react-core): bump core and fix build

### LINKED ISSUE #3678: Nav/Sidebar: update to be dark theme by default, add light-theme opt-in
Placeholder for https://github.com/patternfly/patternfly-next/issues/2602

### LINKED ISSUE #3685: Rename expandable component
https://github.com/patternfly/patternfly-next/issues/1828

### LINKED ISSUE #4071: Chip - remove pf-m-read-only from isReadOnly variant
For reference, the core PR: https://github.com/patternfly/patternfly/pull/2941

The `.pf-m-read-only` class was only for styling in core, and it's no longer needed as you can simply remove the close button. So we can remove that class from being applied when `isReadOnly` is true, and just show the close button.

Looks like the `isReadOnly && styles.modifiers.readOnly` bit in these lines

https://github.com/patternfly/patternfly-react/blob/43348f29d59689a3077ee9c5f90164cbd9bf23dd/packages/react-core/src/components/ChipGroup/Chip.tsx#L104

https://github.com/patternfly/patternfly-react/blob/43348f29d59689a3077ee9c5f90164cbd9bf23dd/packages/react-core/src/components/ChipGroup/Chip.tsx#L81

### LINKED ISSUE #4087: Page sidebar/vertical nav breakpoint changed
https://github.com/patternfly/patternfly/pull/2962/

We changed the breakpoint at which the vertical nav is hidden. This also introduced some page component chrome spacing changes so that the horizontal spacers in the header, sidebar, page sections, and certain components in the page section (tables, data-lists, tabs, wizard) become more compact at this new breakpoint (this was pre-existing behavior at the old breakpoint, just updated to happen at the new breakpoint instead).

I don't believe this will require any changes in react, but I would like to verify just in case there is some logic with the page component toggle that referenced the old breakpoint, and just as a general smoke test to make sure everything behaves correctly after pulling in this update.

Update - after doing some more investigation, looks like the managed sidebar code will need to be updated - https://github.com/patternfly/patternfly-react/blob/a5fcf88b90eaa5001e23d0cc8f456b504a6b3809/packages/react-core/src/components/Page/Page.tsx#L104

### PR DESCRIPTION
**Pull request by redallen**
**What**: Bump core for v4 2020.05 release. Peer programmed with @mcoker and this PR does the minimum required to get the new version building due to renamed/removed classes upstream. Required for much of 2020.06 milestone work.

Yes, the navigation is styled entirely wrong on the docs site. This will be prioritized upstream in patternfly-org after this change is in and `master` gets merged into `v4` sometime later this week.

Closes #4087
Closes #4071
Closes #3685
Closes #3678

## Breaking changes
**Button:** Remove isHover and isFocus props, all instances of them should be removed from your application.
**Chip:** Remove isReadOnly prop, all instances of it should be removed from your application.
**Dropdown:** Remove isHover and isFocus props from Toggle, KebabToggle, and DropdownToggle. All instances of them should be removed from your application.
**Select:**
- Remove isFocus prop from SelectOption, all instances of it should be removed from your application.
- Remove isFocus and isHovered props from SelectToggle, all instances of them should be removed from your application.

**Expandable:**
- Rename component to ExpandableSection, all instances in your application should be renamed.
- Remove isFocus and isHovered props from ExpandableSection, all instances of them should be removed from your application.

**Label:** Remove isCompact prop from Label, all instances of it should be removed from your application.
**Options menu:** Remove isFocused and isHovered prop from OptionsMenuToggle and OptionsMenuToggleWithText, all instances of it should be removed from your application.
**Context selector:** Remove isHover prop from ContextSelectorItem. Remove isHovered and isFocused props from ContextSelectorToggle. All instances of these should be removed from your application.
**Nav:** Change default theme to dark. Use theme="light" if you wish to use the light variant.
**Skip to content:** Remove component prop in favor of anchor tag, all instances of it should be removed from your application.
**Datatoolbar:** Remove separator variant, all instances of it should be removed from your application.
**Wizard:** Remove isFullHeight and isFullWidth props, all instances of them should be removed from your application.
**Page:** Change default theme to dark. Use theme="light" if you wish to use the light variant.

### CODE REVIEW

File: packages/react-core/src/components/ContextSelector/ContextSelectorToggle.tsx [hunk 1]
```diff
@@ -20,11 +20,7 @@ export interface ContextSelectorToggleProps {
   onEnter?: () => void;
   /** Element which wraps toggle */
   parentRef?: any;
-  /** Forces focus state */
-  isFocused?: boolean;
```
Comment (jschuler) [inline packages/react-core/src/components/ContextSelector/ContextSelectorToggle.tsx:24]: Also breaking:
ContextSelectorToggle: Removed isHovered and isFocused props

File: packages/react-core/src/components/DataToolbar/DataToolbarItem.tsx [hunk 2]
```diff
@@ -18,10 +18,9 @@ export enum DataToolbarItemVariant {
 export interface DataToolbarItemProps extends React.HTMLProps<HTMLDivElement> {
   /** Classes applied to root element of the data toolbar item */
   className?: string;
-  /** A type modifier which modifies spacing specifically depending on the type of item */
+  /** TODO: Support 'separator' element as a <Divider component="div" variant="horizontal" />. A type modifier which modifies spacing specifically depending on the type of item */
   variant?:
     | DataToolbarItemVariant
-    | 'separator'
```
Comment (jschuler) [inline packages/react-core/src/components/DataToolbar/DataToolbarItem.tsx:24]: Maybe your breaking change notes should specifically call out DataToolbarItem instead of DataToolbar?

File: packages/react-core/src/components/DataToolbar/DataToolbarItem.tsx [hunk 3]
```diff
@@ -18,10 +18,9 @@ export enum DataToolbarItemVariant {
 export interface DataToolbarItemProps extends React.HTMLProps<HTMLDivElement> {
   /** Classes applied to root element of the data toolbar item */
   className?: string;
-  /** A type modifier which modifies spacing specifically depending on the type of item */
+  /** TODO: Support 'separator' element as a <Divider component="div" variant="horizontal" />. A type modifier which modifies spacing specifically depending on the type of item */
```
Comment (dlabrecq) [inline packages/react-core/src/components/DataToolbar/DataToolbarItem.tsx:21]: There does not appear to be a replacement for the Datatoolbar separator variant. Is that happening in a separate PR?

File: packages/react-core/src/components/ExpandableSection/ExpandableSection.tsx [hunk 4]
```diff
@@ -19,36 +19,30 @@ export interface ExpandableProps {
...
+  /** TODO: Use once core reimplements. Forces active state */
   isActive?: boolean;
 }
 
-interface ExpandableState {
+interface ExpandableSectionState {
   isExpanded: boolean;
 }
 
-export class Expandable extends React.Component<ExpandableProps, ExpandableState> {
```
Comment (jschuler) [inline packages/react-core/src/components/ExpandableSection/ExpandableSection.tsx:34]: Your notes say it got renamed to ExpandableContent, but it's ExpandableSection

File: packages/react-core/src/components/ExpandableSection/ExpandableSection.tsx [hunk 5]
```diff
@@ -69,8 +63,7 @@ export class Expandable extends React.Component<ExpandableProps, ExpandableState
   render() {
     const {
       onToggle: onToggleProp,
-      isFocused,
```
Comment (jschuler) [inline packages/react-core/src/components/ExpandableSection/ExpandableSection.tsx:72]: notes should mention removal of isFocused and isHovered

File: packages/react-core/src/components/DataToolbar/DataToolbarItem.tsx (hunk 3 above)
Comment (redallen) [reply packages/react-core/src/components/DataToolbar/DataToolbarItem.tsx:21]: Yep! This PR is just aiming to fix the build and move in the right direction for future work this sprint.

Another major thing left unimplemented is Tab/Nav horizontal scrolling.

File: packages/react-core/src/components/Page/PageSidebar.tsx [hunk 6]
```diff
@@ -23,7 +23,7 @@ export const PageSidebar: React.FunctionComponent<PageSidebarProps> = ({
   className = '',
   nav,
   isNavOpen = true,
-  theme = 'light',
+  theme = 'dark',
```
Comment (jschuler) [inline packages/react-core/src/components/Page/PageSidebar.tsx:26]: Breaking change, defaults to dark now

**Comment by jschuler** [comment]
Chipgroup toolbar examples look a bit broken now

Left before, right after

Screen Shot 2020-04-23 at 10 30 05 AM

File: packages/react-core/src/components/DataToolbar/DataToolbarItem.tsx (hunk 2 above)
Comment (redallen) [reply packages/react-core/src/components/DataToolbar/DataToolbarItem.tsx:24]: We're planning on adding support back DataToolbarItem's variant="separator" once Divider implements variant="horizontal".

**Comment by redallen** [comment]
@jschuler Yep, it's supposed to be broken now! I believe we have an issue open to implement the core changes.

cc @mcoker

**Comment by jschuler** [comment]
Static alert groups don't look right

Screen Shot 2020-04-23 at 10 32 39 AM

**Comment by redallen** [comment]
I believe those are supposed to change since they look different on http://patternfly-v4.surge.sh/documentation/core/components/alertgroup now.

**Comment by jschuler** [comment]
Some spacing issues in ExpandableSection

Screen Shot 2020-04-23 at 10 44 39 AM

**Comment by jschuler** [comment]
@redallen The static alert groups on the Core v4 preview site look different, i.e. no background color

**Comment by jschuler** [comment]
Horizontal form example doesn't have the info text under the input

Screen Shot 2020-04-23 at 10 47 27 AM

**Comment by jschuler** [comment]
Label looks different compared to the Core v4 preview site
Screen Shot 2020-04-23 at 10 49 39 AM

**Comment by jschuler** [comment]
There is a very small difference with the spacing between the label and the inputs, maybe it's in the form too i only just noticed in the Login page

React
Screen Shot 2020-04-23 at 10 52 40 AM

Core
Screen Shot 2020-04-23 at 10 52 49 AM

**Comment by jschuler** [comment]
Modals look off

Screen Shot 2020-04-23 at 10 54 57 AM

**Comment by jschuler** [comment]
Nav looks visually different, has left colored border for example vs Core
 https://patternfly-react-pr-4116.surge.sh/documentation/react/components/nav
https://patternfly-react-v4.surge.sh/documentation/react/components/nav

**Comment by mcoker** [comment]
@jschuler thanks for the feedback! So far each of the issues you've found are to be expected and we have open issues for each of them to resolve this sprint.

**Comment by jschuler** [comment]
@redallen @mcoker OK, the code change looks fine to me, but there are a lot of visual issues. So LGTM for code

**Comment by tlabaj** [comment]
Nice work Zack.
