### PR TITLE
fix: Do not handle modified clicks on VerticalNav links

### LINKED ISSUE #4783: VerticalNav links ignore the modified clicks
**Describe the issue. What is the expected and unexpected behavior?**

Links in VerticalNav open in a current tab instead of in a new one when using ctrl+click. Same for new window and shift+click.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

This is reproducible when we pass `onNavigate` prop which should handle the navigation:

```js
import React from "react";
import { Route, Router } from "react-router-dom";
import { createBrowserHistory } from 'history';
import { VerticalNav } from 'patternfly-react';

const Foo = (props) => <div>Foo</div>;
const Bar = (props) => <div>Bar</div>;

const items = [
  { title: 'foo', href: '/foo' },
  { title: 'bar', href: '/bar' },
]

const history = createBrowserHistory();

const App = (props) => {
 
  return (
    <React.Fragment>
      <VerticalNav
        items={items}
        onNavigate={({ href }) => history.push(href)}

      />
      <Router history={history}>
        <Route exact path="/foo" component={Foo} />
        <Route exact path="/bar" component={Bar} />
      </Router>
    </React.Fragment>
  );
};
```
`onItemClick` in `VerticalNavItemHelper` does not check for modified clicks and does not pass original click event to `onNavigate` click handler.

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

Bug, no workaround known.

**What is your product and what release version are you targeting?**

https://projects.theforeman.org/issues/29020

### PR DESCRIPTION
**Pull request by xprazak2**
**What:** Closes #4783

VerticalNav should not prevent default and call onClick handler
when user wishes to open a link from vertical navigation in another tab
and uses ctrl+click.

**Additional issues**: https://projects.theforeman.org/issues/29020

### CODE REVIEW

**Comment by tlabaj** [comment]
Can you please link the related issue in the PattenFly Repo.

**Comment by xprazak2** [comment]
I linked the related issue.

File: packages/patternfly-react/src/components/VerticalNav/VerticalNavItemHelper.js [hunk 1]
```diff
@@ -80,11 +80,17 @@ class BaseVerticalNavItemHelper extends React.Component {
...
   };
 
+  eventModified = event => !!(event.metaKey || event.altKey || event.ctrlKey || event.shiftKey);
+
   onItemClick = event => {
     const { primary, secondary, tertiary } = this.getContextNavItems();
     const { isMobile, preventHref, updateNavOnItemClick, idPath } = this.props;
     const { onClick } = this.navItem();
 
+    if (this.eventModified(event)) {
```
Comment (jschuler) [inline packages/patternfly-react/src/components/VerticalNav/VerticalNavItemHelper.js:90]: instead of this can you not just set the `preventHref` prop to false?

**Review by jschuler — CHANGES_REQUESTED** [review]

File: packages/patternfly-react/src/components/VerticalNav/VerticalNavItemHelper.js (hunk 1 above)
Comment (xprazak2) [reply packages/patternfly-react/src/components/VerticalNav/VerticalNavItemHelper.js:90]: Setting `preventHref` to false does not take care of the issue entirely. While it opens the link in new tab, it also changes location of current tab because the`onItemClick` handler continues its execution.

Comment (redallen) [reply packages/patternfly-react/src/components/VerticalNav/VerticalNavItemHelper.js:90]: Right, we wrote this component to do exactly that. Can you add a new `preventUpdate` prop to do this instead? Consumers may wish for modifier keys like shift and alt to do other things.

This first lines of `onItemClick` could just look like:
```tsx
const { isMobile, preventHref, updateNavOnItemClick, idPath, preventUpdate } = this.props;
if (preventUpdate) {
  return;
}
```
and you could pass `preventUpdate` instead of `preventHref`.

**Review by redallen — CHANGES_REQUESTED** [review]

**Comment by xprazak2** [comment]
Updated, I like the idea of leaving it to consumers how the modified clicks should be handled. When passing the prop we do not know anything about the click event yet, so the `preventUpdate` needs to be a function.

**Review by redallen — APPROVED** [review]
LGTM! Thank you!

**Review by jschuler — APPROVED** [review]
thanks @xprazak2 !
