### PR TITLE
bug(ClipboardCopy): change children type to string

### LINKED ISSUE #9711: Bug - Clipboard Copy - children typed as ReactNode, but not actually fully compatible with that type
**Describe the problem**
Trying to pass a non number/string/array as the child of an expandable clipboard copy results in it being stringified to `[object Object]` in the "preview" area.

**How do you reproduce the problem?**
https://codesandbox.io/s/dazzling-kare-yh9prw?file=/index.tsx

**Expected behavior**
Either the type of `children` should be updated to reflect what is actually fully supported, or we should fix the component to actually support the possible inputs of `children` as it is currently typed.

**Screenshots**
image

Fix should be to change the type to what is actually currently supported in the component.

### PR DESCRIPTION
**Pull request by gitdallas**
closes #9711 

the type of ReactNode isn't truly supported as anything passed in will be converted to a string. this caused confusion for at least one product.

none of the examples were attempting to use anything other than a string, and i don't imagine a use case for doing so.  I feel like the "text to copy" should actually have been placed in a different prop (`text`, `textToCopy`, ?) instead of using `children`, but this would be a breaking change.

the product that came across this was attempting to create a "header/title/summary" of the text to be copied, this will be possible via https://github.com/patternfly/patternfly-react/pull/9713

### CODE REVIEW

File: packages/react-core/src/components/ClipboardCopy/ClipboardCopy.tsx [hunk 1]
```diff
@@ -74,7 +74,7 @@ export interface ClipboardCopyProps extends Omit<React.HTMLProps<HTMLDivElement>
   /** A function that is triggered on changing the text. */
   onChange?: (event: React.FormEvent, text?: string | number) => void;
   /** The text which is copied. */
-  children: React.ReactNode;
+  children: string;
```
Comment (thatblindgeye) [inline packages/react-core/src/components/ClipboardCopy/ClipboardCopy.tsx:77]: Would we want to update the onCopy and clipboardCopyFunc params so that `text` is `string | number` similar to the onChange prop while we're at it?

Comment (gitdallas) [reply packages/react-core/src/components/ClipboardCopy/ClipboardCopy.tsx:77]: could make it `string`, not sure why we have `| number` there. It's always going to be a string even if it is a number.

**Comment by gitdallas** [comment]
in setting the state in the constructor... it checks for an array. I'm not sure why this is needed? Even in the example of using "array", it is doing the joining in the example code rather than the component itself.

Okay to just remove this?

File: packages/react-core/src/components/ClipboardCopy/ClipboardCopyExpanded.tsx [hunk 2]
```diff
@@ -6,7 +6,6 @@ import { PickOptional } from '../../helpers/typeUtils';
 
 export interface ClipboardCopyExpandedProps extends Omit<ClipboardCopyProps, 'onChange'> {
   className?: string;
-  children: React.ReactNode;
```
Comment (thatblindgeye) [inline packages/react-core/src/components/ClipboardCopy/ClipboardCopyExpanded.tsx:9]: Did you mean to remove this?

**Review by thatblindgeye — COMMENTED** [review]
Looks good, just one question below. I'd defer to @tlabaj regarding removing the array logic internal to ClipboardCopy. I'm also unsure when an array would be passed in, and that change was only implemented [a year ago](https://github.com/patternfly/patternfly-react/pull/6971/files).

File: packages/react-core/src/components/ClipboardCopy/ClipboardCopyExpanded.tsx (hunk 2 above)
Comment (gitdallas) [reply packages/react-core/src/components/ClipboardCopy/ClipboardCopyExpanded.tsx:9]: yep - it matches ClilpboardCopyProps now

**Review by thatblindgeye — APPROVED** [review]

**Review by kmcfaul — APPROVED** [review]

File: packages/react-core/src/components/ClipboardCopy/ClipboardCopyExpanded.tsx (hunk 2 above)
Comment (tlabaj) [reply packages/react-core/src/components/ClipboardCopy/ClipboardCopyExpanded.tsx:9]: Since the type is changing , we can remove the array logic.  However I wonder if this would break people who using the component like mentioned in the issue that resulted in adding array logic. https://github.com/patternfly/patternfly-react/issues/6863

**Review by kmcfaul — APPROVED** [review]

**Review by tlabaj — APPROVED** [review]

**Comment by rhamilto** [comment]
This is a breaking change for OpenShift console where 
```
          <ClipboardCopy variant={ClipboardCopyVariant.inlineCompact}>
            <ExternalLink href={url} text={url} />
          </ClipboardCopy>
```
is used.

**Comment by tlabaj** [comment]
Hi @rhamilto we will revert the breaking change.

**Comment by jamestalton** [comment]
This is a breaking change for Ansible. We need to use the copy component but have the test copied be one value and the displayed test be inside a <Truncate>.

**Comment by gitdallas** [comment]
@jamestalton - would you be able to use the [expansion variant](https://www.patternfly.org/components/clipboard-copy#expanded) as a workaround?

**Comment by jamestalton** [comment]
We are using the copy block in table columns. The inline version does not support expansion plus I don't think we need it.

image
