### PR TITLE
fix(Switch): updated a11y by removing dynamic labeling

### LINKED ISSUE #10645: Bug - Switch - accessibility issues due to dynamic labeling
**Describe the problem**
Followup to https://github.com/patternfly/patternfly/issues/6347. tldr is that Switch is currently not accessible due to us allowing dynamic labels when the Switch is checked or not checked. This can cause confusion as the context will be different, e.g. if the label is "Enable option" and labelOff is "Disable option", when checked the switch's accessible name is "Enable option, checked" which conveys that clicking the switch will mean the option is disabled, but when unchecked the accessible name is "Disable option, unchecked", which conveys that clicking the switch will disable the option).

The label text should not be dynamic based on the switch's checked state.

**How do you reproduce the problem?**
Provide steps to reproduce. A [codesandbox](https://codesandbox.io/s/serverless-cherry-q9t3f ) demonstrating the problem is appreciated.

**Expected behavior**
A clear and concise description of the expected behavior.

**Is this issue blocking you?**
List the workaround if there is one.

**Screenshots**
If applicable, add screenshots to help explain the issue.

**What is your environment?**

**What is your product and what release date are you targeting?**

**Any other information?**

### PR DESCRIPTION
**Pull request by thatblindgeye**
**What**: Closes #10645 

Codemod issue: https://github.com/patternfly/pf-codemods/issues/672

**Additional issues**:

### CODE REVIEW

File: packages/react-core/src/components/Switch/Switch.tsx [hunk 1]
```diff
@@ -12,10 +12,12 @@ export interface SwitchProps
...
   /** Additional classes added to the switch */
   className?: string;
-  /** Text value for the visible label when on */
+  /** Text value for the visible label */
   label?: React.ReactNode;
-  /** Text value for the visible label when off */
-  labelOff?: React.ReactNode;
+  /** Adds an accessible name to the switch when the label prop is not passed, and must describe the isChecked="true" state. */
+  'aria-label'?: string;
+  /** Adds an accessible name to the switch via a list of referenced id's. The computed accessible name must describe the isChecked="true" state. */
```
Comment (mcoker) [inline packages/react-core/src/components/Switch/Switch.tsx:19]: Not necessarily a suggestion, but I wonder if someone will think it needs to be a list of id's (versus being able to use a single id) the way it's worded currently?

```suggestion
  /** Adds an accessible name to the switch via referenced id(s). The computed accessible name must describe the isChecked="true" state. */
```

**Review by mcoker — APPROVED** [review]
LGTM! One question - if there is no label, aria-label, and aria-labelledby, we have a console.error, but we still apply `aria-labelledby="[switch-id]-label"`, which wouldn't work out of the box since no `label` was passed. Just want to make sure that's preferred over not applying `aria-labelledby`?

**Review by nicolethoen — COMMENTED** [review]
VO and keyboard look good!

I think it may be worth even just a sentence somewhere in the Switch docs to ensure that the consumer knows that they need to consider a11y and wire things up correctly to be a11y compliant. Maybe directing them to the a11y docs or just calling out the most common scenario - something like that?

**Review by nicolethoen — APPROVED** [review]

File: packages/react-core/src/components/Switch/Switch.tsx [hunk 2]
```diff
@@ -30,8 +32,6 @@ export interface SwitchProps
   isDisabled?: boolean;
   /** A callback for when the switch selection changes. (event, isChecked) => {} */
   onChange?: (event: React.FormEvent<HTMLInputElement>, checked: boolean) => void;
-  /** Adds accessible text to the switch, and should describe the isChecked="true" state. When label is defined, aria-label should be set to the text string that is visible when isChecked is true. */
-  'aria-label'?: string;
   /** Flag to reverse the layout of toggle and label (toggle on right). */
```
Comment (tlabaj) [inline packages/react-core/src/components/Switch/Switch.tsx:35]: can you update the text while in there. Or we can open a follow up issue.  For RTL purposes it should say "end" rather than right".  I would advocate for actually changing the name to better align with other components. Maybe `togglePosition`.  we can introduce a new prop post v5.  i can add new issue for that.

File: packages/react-core/src/components/Switch/Switch.tsx [hunk 3]
```diff
@@ -48,15 +48,18 @@ class Switch extends React.Component<SwitchProps & OUIAProps, { ouiaStateId: str
...
     onChange: () => undefined as any
   };
 
   constructor(props: SwitchProps & OUIAProps) {
     super(props);
-    if (!props.label && !props['aria-label']) {
+    if (!props.label && !props['aria-label'] && !props['aria-labelledby']) {
       // eslint-disable-next-line no-console
-      console.error('Switch: Switch requires either a label or an aria-label to be specified');
+      console.error(
```
Comment (tlabaj) [inline packages/react-core/src/components/Switch/Switch.tsx:60]: I would as unit test for this.  That can be follow up.  If we want to get this in.

**Review by tlabaj — APPROVED** [review]
