### PR TITLE
fix(Popover): Refactor popover header

### LINKED ISSUE #8456: Popover - add structural elements for header/title
placeholder for core work https://github.com/patternfly/patternfly/issues/4123

A title component just sits in the popover and serves as the popover title. This should be structured like the modal with popover header/title elements.

### PR DESCRIPTION
**Pull request by tlabaj**
**What**: Closes #8456

### CODE REVIEW

File: packages/react-core/src/components/Popover/PopoverHeader.tsx [hunk 1]
```diff
@@ -31,23 +30,17 @@ export const PopoverHeader: React.FunctionComponent<PopoverHeaderProps> = ({
...
-}: PopoverHeaderProps) => {
-  const HeadingLevel = titleHeadingLevel;
-
-  return icon || alertSeverityVariant ? (
-    <header className={css('pf-c-popover__header', className)} id={id} {...props}>
-      <HeadingLevel className={css(styles.popoverTitle)}>
-        {icon && <PopoverHeaderIcon>{icon}</PopoverHeaderIcon>}
+}: PopoverHeaderProps) => (
+  <header className={css('pf-c-popover__header', className)} id={id} {...props}>
+    <div className={css(styles.popoverTitle, icon && 'pf-m-icon')}>
```
Comment (thatblindgeye) [inline packages/react-core/src/components/Popover/PopoverHeader.tsx:35]: There's a difference in Core compared to React regarding the `id` here. In the latest Core update, `id` is placed on the `div.pf-c-popover__title` rather than `header.pf-c-popover__header`.

File: packages/react-core/src/components/Popover/PopoverHeader.tsx [hunk 2]
```diff
@@ -31,23 +30,17 @@ export const PopoverHeader: React.FunctionComponent<PopoverHeaderProps> = ({
...
   ...props
-}: PopoverHeaderProps) => {
-  const HeadingLevel = titleHeadingLevel;
-
-  return icon || alertSeverityVariant ? (
-    <header className={css('pf-c-popover__header', className)} id={id} {...props}>
-      <HeadingLevel className={css(styles.popoverTitle)}>
-        {icon && <PopoverHeaderIcon>{icon}</PopoverHeaderIcon>}
+}: PopoverHeaderProps) => (
+  <header className={css('pf-c-popover__header', className)} id={id} {...props}>
```
Comment (thatblindgeye) [inline packages/react-core/src/components/Popover/PopoverHeader.tsx:34]:
```suggestion
  <header className={css(styles.popoverHeader, className)} id={id} {...props}>
```

**Review by thatblindgeye — CHANGES_REQUESTED** [review]

**Review by gitdallas — APPROVED** [review]

File: packages/react-core/src/components/Popover/PopoverHeader.tsx (hunk 1 above)
Comment (thatblindgeye) [reply packages/react-core/src/components/Popover/PopoverHeader.tsx]: For the `id` prop in PopoverHeader, it should be passed to `<div className={css(styles.popoverTitle, icon && 'pf-m-icon')}>` rather than PopoverHeaderText sub-component.

Core:

Core Popover header

Surge preview:

Preview Popover header

File: packages/react-core/src/components/Popover/PopoverHeader.tsx [hunk 3]
```diff
@@ -31,23 +30,17 @@ export const PopoverHeader: React.FunctionComponent<PopoverHeaderProps> = ({
...
-
-  return icon || alertSeverityVariant ? (
-    <header className={css('pf-c-popover__header', className)} id={id} {...props}>
-      <HeadingLevel className={css(styles.popoverTitle)}>
-        {icon && <PopoverHeaderIcon>{icon}</PopoverHeaderIcon>}
+}: PopoverHeaderProps) => (
+  <header className={css(styles.popoverHeader, className)} {...props}>
+    <div className={css(styles.popoverTitle)}>
+      {icon && <PopoverHeaderIcon>{icon}</PopoverHeaderIcon>}
+      <PopoverHeaderText headingLevel={titleHeadingLevel} id={id}>
```
Comment (mcoker) [inline packages/react-core/src/components/Popover/PopoverHeader.tsx:37]: This is fine but should it be `<PopoverHeaderTitleText>`? That will match the core class. It's named that way to try and avoid naming conflicts if we introduce something like a subtitle in the header.

**Review by mcoker — CHANGES_REQUESTED** [review]
Looks like the `id` was moved to the title text element - it should go on the title element instead. Otherwise lgtm!

https://github.com/patternfly/patternfly-react/blob/0cd69981f5b962b038dd08ea0308965e4023c531/packages/react-core/src/components/Popover/PopoverHeader.tsx#L35

**Review by thatblindgeye — APPROVED** [review]

**Review by tlabaj — COMMENTED** [review]
LGTM

**Review by mcoker — APPROVED** [review]

**Review by nicolethoen — APPROVED** [review]
