### PR TITLE
fix(expandable-section): pass expandable value to onToggle

### LINKED ISSUE #4412: ExpandableSection#onToggle should include the expand / collapsed state
**Describe the issue. What is the expected and unexpected behavior?**
`ExpandableSection` has an `onToggle` function however it does not have a parameter indicating which state the component is in: expanded or collapsed.

This is a request to supply the current state as a parameter to `onToggle`.

This would be useful to know so that clients wishing to lazy load content can do so here.

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
enhancement

Work around is to wrap the ExpandableSection and always use controlled state such that a new callback function with the expand / collapse param can be provided.

**What is your product and what release version are you targeting?**
OpenShift Console 4.6

### PR DESCRIPTION
**Pull request by boaz0**
**What**: Closes #4412 

//cc @christianvogt

### CODE REVIEW

File: packages/react-core/src/components/ExpandableSection/ExpandableSection.tsx [hunk 1]
```diff
@@ -42,7 +42,8 @@ export class ExpandableSection extends React.Component<ExpandableSectionProps, E
     toggleText: '',
     toggleTextExpanded: '',
     toggleTextCollapsed: '',
-    onToggle: (): any => undefined,
+    // eslint-disable-next-line @typescript-eslint/no-unused-vars
+    onToggle: (_isOpen): void => undefined,
```
Comment (dlabrecq) [inline packages/react-core/src/components/ExpandableSection/ExpandableSection.tsx:46]: Curious why an underscore is used? I kind of expect the compiler would have a conflict here.

Can we rename this as `isOpen`?

Comment (boaz0) [reply packages/react-core/src/components/ExpandableSection/ExpandableSection.tsx:46]: Yes, we can do that, it's just what WebStorm suggested me to call it.

File: packages/react-core/src/components/ExpandableSection/ExpandableSection.tsx [hunk 2]
```diff
@@ -18,7 +18,7 @@ export interface ExpandableSectionProps {
   /** Text that appears in the toggle when collapsed (will override toggleText if both are specified; used for uncontrolled expandable with dynamic toggle text) */
   toggleTextCollapsed?: string;
   /** Callback function to toggle the expandable content */
-  onToggle?: () => void;
+  onToggle?: (isOpen: boolean) => void;
```
Comment (tlabaj) [inline packages/react-core/src/components/ExpandableSection/ExpandableSection.tsx:21]: Can we just call this parameter `isExpanded`
Can we make the parameter optional, otherwise this would be a breaking change.

File: packages/react-core/src/components/ExpandableSection/ExpandableSection.tsx [hunk 3]
```diff
@@ -80,9 +81,8 @@ export class ExpandableSection extends React.Component<ExpandableSectionProps, E
     // uncontrolled
     if (isExpanded === undefined) {
       propOrStateIsExpanded = this.state.isExpanded;
-      onToggle = () => {
-        onToggleProp();
-        this.setState(prevState => ({ isExpanded: !prevState.isExpanded }));
+      onToggle = isOpen => {
+        this.setState({ isExpanded: isOpen }, () => onToggleProp(this.state.isExpanded));
```
Comment (tlabaj) [inline packages/react-core/src/components/ExpandableSection/ExpandableSection.tsx:85]: We should only do this is `isOpen/isExpanded` is provided, otherwise we should what we were doing before.

**Comment by dlabrecq** [comment]
Linter failed

File: packages/react-core/src/components/ExpandableSection/ExpandableSection.tsx [hunk 4]
```diff
@@ -18,7 +18,7 @@ export interface ExpandableSectionProps {
   /** Text that appears in the toggle when collapsed (will override toggleText if both are specified; used for uncontrolled expandable with dynamic toggle text) */
   toggleTextCollapsed?: string;
   /** Callback function to toggle the expandable content */
-  onToggle?: () => void;
+  onToggle?: (isExpanded: boolean) => void;
```
Comment (tlabaj) [inline packages/react-core/src/components/ExpandableSection/ExpandableSection.tsx:21]: In order to not break consumers this argument needs to be optional.
```suggestion
  onToggle?: (isExpanded?: boolean) => void;
```

File: packages/react-core/src/components/ExpandableSection/ExpandableSection.tsx [hunk 5]
```diff
@@ -80,9 +81,8 @@ export class ExpandableSection extends React.Component<ExpandableSectionProps, E
     // uncontrolled
     if (isExpanded === undefined) {
       propOrStateIsExpanded = this.state.isExpanded;
-      onToggle = () => {
-        onToggleProp();
-        this.setState(prevState => ({ isExpanded: !prevState.isExpanded }));
+      onToggle = isExpanded => {
```
Comment (tlabaj) [inline packages/react-core/src/components/ExpandableSection/ExpandableSection.tsx:84]: We need to account for the case when isExpanded is not provided.

File: packages/react-core/src/components/ExpandableSection/ExpandableSection.tsx (hunk 4 above)
Comment (christianvogt) [reply packages/react-core/src/components/ExpandableSection/ExpandableSection.tsx:21]: This is correct:
```
 onToggle?: (isExpanded: boolean) => void;
```

You want to specify that `isExpanded` is always provided as a boolean value. By using `isExpanded?` the type becomes `boolean | undefined`. But a boolean value is always provided.

Clients are free to ignore this param as per the previous implementation.

File: packages/react-core/src/components/ExpandableSection/ExpandableSection.tsx (hunk 5 above)
Comment (christianvogt) [reply packages/react-core/src/components/ExpandableSection/ExpandableSection.tsx:84]: `isExpanded` here is _always_ provided because on line `110` is where this function is called and it supplies a boolean param.

Comment (tlabaj) [reply packages/react-core/src/components/ExpandableSection/ExpandableSection.tsx:84]: @boaz @christianvogt I know this is a day off for some I can fix linting error so we can this into the release.

File: packages/react-core/src/components/ExpandableSection/ExpandableSection.tsx (hunk 4 above)
Comment (tlabaj) [reply packages/react-core/src/components/ExpandableSection/ExpandableSection.tsx:21]: Yup I see that.

File: packages/react-core/src/components/ExpandableSection/ExpandableSection.tsx (hunk 1 above)
Comment (redallen) [reply packages/react-core/src/components/ExpandableSection/ExpandableSection.tsx]: Underscores usually represent unused variables.

**Comment by boaz0** [comment]
Thank you @tlabaj - I am sorry I was unavailable yesterday but I see you did a good job!
