### PR TITLE
fix(Notification Drawer): Added screen reader text for notification drawer item read state

### LINKED ISSUE #5889: Notification read/unread state should be indicated to screen reader in notification drawer
**Describe the issue. What is the expected and unexpected behavior?**
When read/unread state changes in notification drawer, there should be an indication to screen readers what has changed. (Sighted users can see that the styling changes, but there is no indication to screen reader users.) We could likely provide a label or screen reader text to add this context.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
Test notification drawer with VO and notice that when notification is read, there is no new information given to screen readers.

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug

### PR DESCRIPTION
**Pull request by tlabaj**
**What**: Closes #5889

### CODE REVIEW

File: packages/react-core/src/components/NotificationDrawer/NotificationDrawerListItem.tsx [hunk 1]
```diff
@@ -13,6 +13,8 @@ export interface NotificationDrawerListItemProps extends React.HTMLProps<HTMLLIE
   isRead?: boolean;
   /**  Callback for when a list item is clicked */
   onClick?: (event: any) => void;
+  /** Read state screen reader text */
```
Comment (thatblindgeye) [inline packages/react-core/src/components/NotificationDrawer/NotificationDrawerListItem.tsx:16]:
```suggestion
  /** Visually hidden text that conveys the current read state of the notification list item */
```

File: packages/react-core/src/components/NotificationDrawer/NotificationDrawerListItem.tsx [hunk 2]
```diff
@@ -54,6 +65,7 @@ export const NotificationDrawerListItem: React.FunctionComponent<NotificationDra
       onClick={(e) => onClick(e)}
       onKeyDown={onKeyDown}
     >
+      <span className="pf-v5-screen-reader">{readStateSRText}</span>
```
Comment (thatblindgeye) [inline packages/react-core/src/components/NotificationDrawer/NotificationDrawerListItem.tsx:68]: We'll most likely need an `aria-live="polite"` added somewhere, as right now there's no indication that anything has changed when marking a notification as read. Personally I lean a bit more towards adding it to the `pf-v5-c-notification-drawer__header-status` element (line ~45 of NotificationDrawerHeader), so that the current count is announced when updated. Doing that would:

- provide users the context of the read status of the current notification item when traversing through the list from this `readStateSRText`
- alert users that the notification they are on is marked as read by the announcement of "[number] unread" from the notification drawer header.

**Review by thatblindgeye — CHANGES_REQUESTED** [review]
This is looking good. Had some comments below.

This can be a followup, but we should update the notification titles to more generic titles rather than "Unread notification title" since the read state will be announced by this PR going in. This is more for the examples/demos that track the read state of the notifications.

File: packages/react-core/src/components/NotificationDrawer/NotificationDrawerListItem.tsx (hunk 2 above)
Comment (tlabaj) [reply packages/react-core/src/components/NotificationDrawer/NotificationDrawerListItem.tsx:68]: @jessiehuff I would be interested in your opinion here as well.  I know we talked about a couple of different options.

Comment (jessiehuff) [reply packages/react-core/src/components/NotificationDrawer/NotificationDrawerListItem.tsx:68]: When testing on VO, I noticed that when I "read" a notification, the screen reader does currently say that specific notification is read. (It looks like from your comment that that was true for you as well. Though it might be wise to check this in other screen readers like JAWS.) If I'm understanding correctly, we're thinking of making the "2 unread" notifications the live region and then updating that text every time a user reads a notification? I suppose that as long as the live region is set to polite, that wouldn't be too bad because then it ideally should let the user get through the notification they're on before informing them of what they have left. I think that could make sense to me.

**Review by thatblindgeye — APPROVED** [review]
Just snapshots need updating, the other failure should pass upon re-running

File: packages/react-core/src/components/NotificationDrawer/NotificationDrawerListItem.tsx [hunk 3]
```diff
@@ -52,6 +63,7 @@ export const NotificationDrawerListItem: React.FunctionComponent<NotificationDra
...
```
Comment (gitdallas) [inline packages/react-core/src/components/NotificationDrawer/NotificationDrawerListItem.tsx:66]: could remove 44-52 and do this

```suggestion
      <span className="pf-v5-screen-reader">{readStateScreenReaderText || (isRead ? 'read' : 'unread')}</span>
```

**Review by gitdallas — APPROVED** [review]
lgtm, just a comment to remove some lines if you want

**Review by kmcfaul — APPROVED** [review]
