### PR TITLE
fix(CodeEditor): prevent focus loss (#12211)

### LINKED ISSUE #12211: Bug - CodeEditor - Loses focus and cursor position when typing first character with isUploadEnabled
## Describe the bug

When using `CodeEditor` with `isUploadEnabled={true}` (or with a custom `emptyState` prop), typing the first character in an empty editor causes:

1. The Monaco editor to lose focus
2. The cursor position to jump back to position 0
3. A visible flicker as the component remounts

This makes it impossible to type continuously in an empty editor - users must click back into the editor after every first keystroke, and text appears in reverse order (typing "abc" results in "cba").

## Steps to reproduce

1. Render a `CodeEditor` with `isUploadEnabled={true}`:
   ```tsx
   <CodeEditor
     isUploadEnabled
     isCopyEnabled
     isDownloadEnabled
     onCodeChange={(code) => console.log(code)}
     code=""
     height="300px"
   />
   ```
2. Click "Start from scratch" to dismiss the empty state and open the editor
3. Type a character (e.g., "a")
4. **Observe**: Focus is lost, you cannot continue typing
5. Click back into the editor, type another character
6. **Observe**: The new character appears at position 0, before the previous character

You can also use Image Builder's "First Boot Script" step to see the bug live. See also https://issues.redhat.com/browse/HMS-9956

## Expected behavior

The editor should maintain focus and cursor position when typing, allowing continuous text input. Typing "abc" should result in "abc", not "cba".

## Root cause analysis

In `CodeEditor.tsx` (around line 599), the render logic uses conditional JSX based on whether the code is empty:

```tsx
{(isUploadEnabled || emptyState) && !value ? (
  // Branch A: Container with Dropzone, shows empty state OR editor
  <div {...getRootProps()}>
    ...
  </div>
) : (
  // Branch B: Different container structure
  <>
    ...
  </>
)}
```

When `value` transitions from `""` (empty) to `"a"` (non-empty):
1. The condition `!value` changes from `true` to `false`
2. React sees completely different JSX structures (Branch A vs Branch B)
3. React unmounts the entire Branch A subtree and mounts Branch B
4. The Monaco editor instance is destroyed and recreated
5. All editor state is lost, including focus and cursor position

The inner condition at line 608 (`(showEmptyState || emptyState) && !value`) correctly handles showing/hiding the empty state vs editor within the same container, but the outer condition causes the entire container to switch.

## Environment

- @patternfly/react-code-editor version: 6.4.0 (and likely all recent versions)
- React version: 18.x
- Browser: All browsers affected (Chrome, Firefox, Safari)
- OS: All platforms

## Additional context

This bug affects any application using CodeEditor with file upload functionality (`isUploadEnabled`), which is a common use case for script editors, configuration editors, and code snippet inputs.

The fix is straightforward: remove `&& !value` from the outer condition so the container structure remains stable regardless of whether the code is empty or not. The inner condition already handles the empty state display correctly.

---

**Jira Issue:** [PF-3433](https://issues.redhat.com/browse/PF-3433)

### PR DESCRIPTION
**Pull request by ochosi**
### Problem

When using `CodeEditor` with `isUploadEnabled={true}`, typing the first character causes the Monaco editor to lose focus and cursor position.

### Solution

Remove `&& !value` from the outer conditional at line 599. The outer branch should only depend on whether upload/emptyState features are enabled, not on current code content. The inner condition already handles empty state display correctly.

I have verified the fix locally by running [image-builder-frontend](github.com/osbuild/image-builder-frontend) linked against the patched patternfly-react.

**What**: Closes #12211

**Additional issues**: https://issues.redhat.com/browse/HMS-9956 (Bug surfacing in Image Builder)

## Summary by CodeRabbit

* **Style**
  * Editor container now renders consistently across upload-enabled, empty, loading, and populated states, improving layout stability.

* **Refactor**
  * Component layout unified so header, main area, and upload UI keep a consistent structure regardless of content presence.

* **Tests**
  * Updated tests to reflect the adjusted DOM structure and traversal depth.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx [hunk 1]
```diff
@@ -619,15 +620,16 @@ export const CodeEditor = ({
                 </div>
               </div>
             ) : (
-              <>
+              /* No upload/emptyState: use consistent container structure */
+              <div className={css(styles.codeEditorContainer)}>
```
Comment (kmcfaul) [inline packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx]: This div should be removed, the container is only needed for CodeEditors with upload enabled or those containing an empty state.

File: packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx [hunk 2]
```diff
@@ -596,7 +596,8 @@ export const CodeEditor = ({
             )}
             ref={ref}
           >
-            {(isUploadEnabled || emptyState) && !value ? (
+            {isUploadEnabled || emptyState ? (
+              /* Upload/EmptyState enabled: wrap in Dropzone container */
```
Comment (kmcfaul) [inline packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx]: Nit/nonblocking: remove comments

File: packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx (hunk 1 above)
Comment (ochosi) [reply packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx]: Makes sense, I dropped the div.
