### PR TITLE
fix(Page & PageHeader): adds optional "role" prop

### LINKED ISSUE #2580: Configurable roles for Page and PageHeader
Currently, these components default to `role="main"` and `role="banner"` respectively. These are sensible defaults, but shouldn't be hardcoded. We shouldn't assume that Patternfly layouts are always used at the root of an application. It's a feature that the page markup/styling is nestable, so we need to make sure users can customize these settings in these cases.

An immediate example is within our integration test application.

Screen Shot 2019-07-23 at 4 31 13 PM

Generally, the banner role should only be used for the outermost header of an application. Similarly, there should only be a single main role and it should be the outermost container for the app's dynamic content.

### PR DESCRIPTION
**Pull request by jenny-s51**
**What**: Closes #2580. 

**Additional issues**: Following a discussion with @seanforyou23, it was decided that instead of removing the `role` attribute entirely (as was done in #3499), we should instead allow the user to optionally configure it using a prop.

### CODE REVIEW

File: packages/patternfly-4/react-core/src/components/Page/Page.tsx [hunk 1]
```diff
@@ -147,7 +155,13 @@ export class Page extends React.Component<PageProps, PageState> {
           {skipToContent}
           {header}
           {sidebar}
-          <main role="main" id={mainContainerId} className={css(styles.pageMain)} tabIndex={-1} aria-label={mainAriaLabel}>
+          <main
+            role={isRoleSet ? role : undefined}
```
Comment (dlabrecq) [inline packages/patternfly-4/react-core/src/components/Page/Page.tsx]: I'm confused as to why isRoleSet is necessary as a prop? Considering role is undefined by default, there wouldn't need to test it here. I don't see an example how this is used, unless I'm missing something?

Comment (jenny-s51) [reply packages/patternfly-4/react-core/src/components/Page/Page.tsx]: Yes @dlabrecq that makes sense, you're right. We'd probably never need the prop so I removed it -- thank you for clarifying

File: packages/patternfly-4/react-core/src/components/Page/Page.tsx [hunk 2]
```diff
@@ -63,7 +65,8 @@ export class Page extends React.Component<PageProps, PageState> {
     isManagedSidebar: false,
     defaultManagedSidebarIsOpen: true,
     onPageResize: (): void => null,
-    mainContainerId: null as string
+    mainContainerId: null as string,
+    role: undefined as string
```
Comment (tlabaj) [inline packages/patternfly-4/react-core/src/components/Page/Page.tsx]: Should this default to `main` rather that undefined?

Comment (jenny-s51) [reply packages/patternfly-4/react-core/src/components/Page/Page.tsx]: AXE sometimes throws an error when it's set to `main`, so @seanforyou23 and I decided it was better to remove the default and have the user configure it to whatever they prefer, rather than having it be hard-coded.

Comment (tlabaj) [reply packages/patternfly-4/react-core/src/components/Page/Page.tsx]: @jessiehuff the core doc say this attribute is required.  Is that not the case,  do the docs need to be updated? https://pf4.patternfly.org/documentation/core/components/page#accessibility

Comment (jessiehuff) [reply packages/patternfly-4/react-core/src/components/Page/Page.tsx]: @tlabaj I think with this change, the docs would need updated to reflect it. :)

Comment (tlabaj) [reply packages/patternfly-4/react-core/src/components/Page/Page.tsx]: @jenny-s51  can you open issue in core please

Comment (jenny-s51) [reply packages/patternfly-4/react-core/src/components/Page/Page.tsx]: @tlabaj yes!
