### PR TITLE
DataListAction: convert to Functional Component

### LINKED ISSUE #4489: DataListAction should be converted to Functional Component
**Describe the issue. What is the expected and unexpected behavior?**
DataListAction. has a state that is never used.  It also has an onSelect and onToggle function that are not used.  These should be removed and the component should be functional instead os class.  This is a breaking change since the state is exported.

### PR DESCRIPTION
**Pull request by KKoukiou**
Fixes #4489

### CODE REVIEW

File: packages/react-core/src/components/DataList/DataListAction.tsx [hunk 1]
```diff
@@ -27,44 +27,20 @@ export interface DataListActionProps extends Omit<React.HTMLProps<HTMLDivElement
...
-}
+export const DataListAction: React.FunctionComponent<DataListActionProps> = ({
+  children,
+  className,
+  visibility,
+  /* eslint-disable @typescript-eslint/no-unused-vars */
+  id,
+  'aria-label': ariaLabel,
+  'aria-labelledby': ariaLabelledBy,
+  isPlainButtonAction,
```
Comment (jschuler) [inline packages/react-core/src/components/DataList/DataListAction.tsx:38]: Would be great to update this section. The isPlainButtonAction prop is used and the other three either don't have to be destructured or should be explicitly mapped in the div

Comment (KKoukiou) [reply packages/react-core/src/components/DataList/DataListAction.tsx:38]: sure, I was just wondering if these aria-labels are desired there or should be instead deprecated and not used as properties at all.
Because I think it's common to use aria-label with div element but then they need role as well.

**Review by redallen — CHANGES_REQUESTED** [review]
LGTM, just need to fix the duplicate `id`s for [this example](https://patternfly-react-pr-4947.surge.sh/components/data-list/react/checkboxes-actions-and-additional-cells/)

File: packages/react-core/src/components/DataList/DataListAction.tsx (hunk 1 above)
Comment (KKoukiou) [reply packages/react-core/src/components/DataList/DataListAction.tsx:38]: So I initially implemented to pass these 'props' but the tests caught, that in the scenario, when we have 2 actions for the same item which appear conditionally on the UI according to the screen size, then we end up with duplicate Ids, which is html dom validity violation.

Then we could of course provide different 'id's per action, but that would make card the 'aria-labelled-by' asignment.

Anyway, let's take a look into that into another PR. @redallen

**Review by redallen — APPROVED** [review]

**Review by kmcfaul — APPROVED** [review]

**Review by redallen — APPROVED** [review]
