### PR TITLE
Fix for drop target highlight, group label position on drag

### LINKED ISSUE #7220: Bug - Topology - Nodes are not given the highlight modifier when they are a drop target
**Describe the problem**
When a node is a valid drop target for the current drag operation, it should be given the `pf-m-highlight` modifier.

**How do you reproduce the problem?**
Drag an edge that is droppable on some nodes

**Expected behavior**
The valid drop target nodes have the `pf-m-highlight` modifier.

**Is this issue blocking you?**
Yes

**What is your product and what release date are you targeting?**
OpenShift Console, 4.11

### LINKED ISSUE #7221: Bug - Topology - Group labels move during a regroup operation of a child node
**Describe the problem**
When dragging a node that belongs to a group, if you change to a regroup operation, the node moves outside the group correctly, but if you move it lower than the lowest group node, the group label moves to the dragged group.

**How do you reproduce the problem?**
Do a regroup drag of a node within a group and move it below the group.

**Expected behavior**
The group remains the same, the label remains positioned as if the node was in its original location.

**Is this issue blocking you?**
Yes

**Screenshots**
bad-group

**What is your product and what release date are you targeting?**
OpenShift Console, 4.11

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
**What**: 
Fixes #7220 
Fixes #7221 

Adds appropriate modifiers on groups and nodes based on the current drag operation.
Don't update group label when a drag operation is in process.

/cc @christianvogt

### CODE REVIEW

File: packages/react-topology/src/components/groups/DefaultGroupExpanded.tsx [hunk 1]
```diff
@@ -121,6 +121,9 @@ const DefaultGroupExpanded: React.FunctionComponent<DefaultGroupExpandedProps> =
   const hullPadding = React.useCallback((point: PointWithSize | PointTuple) => (point[2] || 0) + padding, [padding]);
 
   const points: (PointWithSize | PointTuple)[] = React.useMemo(() => {
+    if (droppable) {
+      return prevPoints.current;
+    }
```
Comment (christianvogt) [inline packages/react-topology/src/components/groups/DefaultGroupExpanded.tsx:126]: If `prevPoints.current` hasn't been defined, you should still run this function completely.

**Review by nicolethoen — APPROVED** [review]

**Review by kmcfaul — APPROVED** [review]

**Review by christianvogt — APPROVED** [review]
