### PR TITLE
fix(alert): add display name to the close action button

### LINKED ISSUE #4415: AlertActionCloseButton doesn't have displayName
It seems that `AlertActionCloseButton` does not have `displayName` property set.
ping @redallen

Related to: 
https://github.com/patternfly/patternfly-react/pull/4388
https://github.com/patternfly/patternfly-react/issues/4369

### PR DESCRIPTION
**Pull request by boaz0**
**What**: Closes #4415 

//cc @redallen @PanSpagetka

### CODE REVIEW

File: packages/react-core/src/components/Alert/AlertActionCloseButton.tsx [hunk 1]
```diff
@@ -35,3 +35,4 @@ export const AlertActionCloseButton = ({
     )}
   </AlertContext.Consumer>
 );
+AlertActionCloseButton.displayName = 'AlertActionCloseButton';
```
Comment (redallen) [inline packages/react-core/src/components/Alert/AlertActionCloseButton.tsx:38]: On line 17 can we type `AlertActionCloseButton` as a `React.FunctionComponent<AlertActionCloseButtonProps>` like all our other components as well? That's why the linter didn't pick it up...

Comment (boaz0) [reply packages/react-core/src/components/Alert/AlertActionCloseButton.tsx:38]: Done :+1:
