### PR TITLE
fix(Toolbar): deleteChip expects categoryKey as string

### LINKED ISSUE #3552: DataToolbarFilter: categoryName label required to delete chips
The `categoryName` prop of `DataToolbarFilter` is used to display the category name in the chip. In the example below, the "Project" category (i.e., chip) is a localizable string.

Screen Shot 2020-01-22 at 8 13 49 PM

When the chip is deleted, the same string is provided as the `type` variable to callback.

Screen Shot 2020-01-22 at 8 15 31 PM

In the filterable table demo below, the `type` is converted using `toLowerCase()`. However, considering that  this is a localizable label, we cannot use that approach to store filter values an array.

Screen Shot 2020-01-22 at 8 26 54 PM

I don't want the localizable "Project" label here, but some ID (e.g., 'project'). (All my filter and menu options are based on IDs.) Perhaps a `categoryID` prop would be helpful here?

### PR DESCRIPTION
**Pull request by nicolethoen**
Closes #3552

### CODE REVIEW

File: packages/react-core/src/components/Toolbar/ToolbarFilter.tsx [hunk 1]
```diff
@@ -67,21 +67,23 @@ export class ToolbarFilter extends React.Component<ToolbarFilterProps, ToolbarFi
   render() {
     const { children, chips, deleteChipGroup, deleteChip, categoryName, showToolbarItem, ...props } = this.props;
     const { isExpanded, chipGroupContentRef } = this.context;
+    const categoryKey = typeof categoryName === 'string' ? categoryName : categoryName.key;
```
Comment (dlabrecq) [inline packages/react-core/src/components/Toolbar/ToolbarFilter.tsx:70]: Thinking we should test `typeof ToolbarChipGroup` before returning `categoryName.key`? (It's possible that `key` may not be defined for the given `categoryName` object.) That way, the string could be returned as the default.

Comment (nicolethoen) [reply packages/react-core/src/components/Toolbar/ToolbarFilter.tsx:70]: The only types valid for categoryName is string or ToolbarChipGroup which requires a key. So it should be safe

Comment (dlabrecq) [reply packages/react-core/src/components/Toolbar/ToolbarFilter.tsx:70]: Although categoryName is typed, users can provide a different object using `any` (e.g., categoryName={myObject as any}). I'm just advocating that it's safer to test for the ToolbarChipGroup type first and default to string; thus, avoiding a potential undefined exception.

Comment (dlabrecq) [reply packages/react-core/src/components/Toolbar/ToolbarFilter.tsx:70]: Although `categoryName` is typed, users can still provide a different object (e.g., `categoryName={myObject as any}`). I'm just advocating that it's safer to test for the `ToolbarChipGroup` interface first (since you're already using `typeof`) and default to string; thus, avoiding a potential undefined exception.
