### PR TITLE
fix(Wizard): added prop to focus content on next/back

### LINKED ISSUE #10249: Bug - Wizard - Keyboard Navigation - High Visibility Accessibility issue
**Describe the problem**
Unable to navigate through the Wizard component using the keyboard.

This is an issue with 
- [ ] Patternfly 5  

**Please give a clear and concise description of the problem. Which components are affected?**
On navigating the Wizard component through the keyboard, upon clicking the next/previous buttons, the focus remains on the wizard footer buttons even though there are interactive elements in the wizard's panel/body.

**How do you reproduce the problem?**
https://www.patternfly.org/2022.05/components/wizard/#anchors-for-nav-items
wizard issue

In this example, on navigating to the third step, the focus directly moves to the `Next` button at the bottom even though there is an interactive element `Join the conversation` in the panel.

**Expected behaviour**
Upon clicking the next/previous buttons, the focus should move to either the first interactive element in the wizard's main panel or (if there are no interactive elements) the main panel itself so that the user can navigate through the wizard easily

**Is this issue blocking you?**
The issue is blocking one of the highest-priority items.

**Screenshots**
If applicable, add screenshots to help explain the issue.

**What is your environment?**
- OS: Mac OS Sonoma 14.3
- Browser: Chrome
- Version: 122.0.6261.129 (Official Build) (x86_64)

**What is your product and what release date are you targeting?**
Customer Portal

**Any other information?**

### PR DESCRIPTION
**Pull request by thatblindgeye**
**What**: Closes #10249

Some comments on changes below

**Additional issues**:

### CODE REVIEW

File: packages/react-core/src/components/Wizard/Wizard.tsx [hunk 1]
```diff
@@ -55,6 +55,10 @@ export interface WizardProps extends React.HTMLProps<HTMLDivElement> {
   onSave?: (event: React.MouseEvent<HTMLButtonElement>) => void | Promise<void>;
   /** Callback function to close the wizard */
   onClose?: (event: React.MouseEvent<HTMLButtonElement>) => void;
+  /** @beta Flag indicating whether the wizard content should be focused after the onNext or onBack callbacks
+   * are called.
+   */
+  shouldFocusContentOnNextOrBack?: boolean;
```
Comment (jessiehuff) [inline packages/react-core/src/components/Wizard/Wizard.tsx:61]: A little nit picky, but I find this name a little confusing. Is there something that we could use that would be a little clearer?

File: packages/react-core/src/components/Wizard/Wizard.tsx [hunk 2]
```diff
@@ -85,6 +91,11 @@ export const Wizard = ({
     }
   }, [startIndex]);
 
+  const focusMainContentElement = () =>
+    setTimeout(() => {
+      wrapperRef?.current?.focus && wrapperRef.current.focus();
+    }, 0);
```
[the remark this answers is not in the document]
Comment (jessiehuff) [reply packages/react-core/src/components/Wizard/Wizard.tsx:97]: Definitely curious about what scenario we could have that wouldn't include a main. If we went the `aria-live` route this would be necessary. However, maybe it's ok if we avoid using `aria-live` for now. I typically see live regions used for things like updates/status, alerts, logs, etc. Like [this article talks about](https://www.boia.org/blog/what-are-aria-live-regions), live regions typically aren't used for interactive content (and I imagine we'd expect wizard content to be interactive often). Based on our discussion, I agree that it probably makes sense to omit `aria-live` for now and rely on the announcement of the shifted focus.

File: packages/react-core/src/components/Wizard/Wizard.tsx (hunk 1 above)
Comment (thatblindgeye) [reply packages/react-core/src/components/Wizard/Wizard.tsx:61]: I'd definitely be in favor of updating this prop name, I just couldn't really think of a better alternative at the time 😆 `shouldFocusContentOnStepChange` wouldn't be totally accurate since technically clicking a nav item changes the step, but we don't move focus on that. `shouldFocusContent` would be shorter, but probably less clear? `shouldFocusContentOnFooterAction`?

If it matters the prop is beta, so we should be able to tweak the naming if needed.

**Review by jessiehuff — APPROVED** [review]
LGTM! Still not sure on naming, but that is not my forte. 😆

File: packages/react-core/src/components/Wizard/Wizard.tsx (hunk 1 above)
Comment (thatblindgeye) [reply packages/react-core/src/components/Wizard/Wizard.tsx:61]: @tlabaj do you have any suggestions for a potential prop name here?

Comment (tlabaj) [reply packages/react-core/src/components/Wizard/Wizard.tsx:61]: I would vote for the shorter name.  I think `shouldFocusContent` will work as long as description is clear.

File: packages/react-core/src/components/Wizard/Wizard.tsx (hunk 2 above)
[the remark this answers is not in the document]
Comment (tlabaj) [reply packages/react-core/src/components/Wizard/Wizard.tsx:97]: cc @mcoker

[the remark this answers is not in the document]
Comment (mcoker) [reply packages/react-core/src/components/Wizard/Wizard.tsx:97]: > (Note that Core does not have a bunch of empty divs with display none for steps whose content is not currently rendered, so maybe the intent was that __main element should be static and __main-body dynamically renders step content? Curious as to whether we need these empty div's rendered in React at all.)

FWIW the wizard is built very similarly to a page, so `__main` was intended to mimic the page main container. In both cases, it's more of a static, structural element of the layout, so I would expect content within it (`__main-body` elements) to re-render, or possibly attributes and stuff on `__main` to change, but not the whole element to re-render... though I suppose that would be fine as long as it didn't cause layout shifts or anything?

**Review by tlabaj — COMMENTED** [review]
Other than changing the prop name this looks good to me

**Review by tlabaj — APPROVED** [review]
