### PR TITLE
Fix Nav Flyout Accessibility

### LINKED ISSUE #7781: Bug - Nav: flyout isn't accessible
**Describe the problem**
Followup to #7772 

Currently the [Nav flyout example](https://www.patternfly.org/v4/components/navigation#flyout) shows a nav item that both is a link and contains a flyout menu. Due to how some assistive tech navigates pages, the only way to open the flyout menu may be to press Enter or Space on the nav item. The PR linked above would add that functionality in, but because links can be activated via mouse click or pressing Enter, and because VoiceOver's VO modifier + Space keyboard shortcut acts as a click event, the only way for users to open the flyout menu with VO is to press only Space (though that isn't exactly clear depending on the browser and may not be flawless).

As noted in the linked PR, two possible solutions include:

- We recommend that flyouts not be put on nav items that are also links that can be clicked, and update the flyout example accordingly. This would cause the flyout to behave more similarly to the drilldown example.
- We update the icon indicating there is a flyout menu to make it an interactive button, similar to the [W3C flyout button as toggle example](https://www.w3.org/WAI/tutorials/menus/flyout/#use-button-as-toggle).

Additionally, the difference in how to navigate the first level nav items (can only use Tab to navigate between them) and the flyout menus (can only use arrow keys) may not be immediately apparent to users navigating via only keyboard.

**How do you reproduce the problem?**
Go to either the example link above or into the [preview build nav flyout](https://patternfly-react-pr-7772.surge.sh/components/navigation/#flyout) from the linked PR, and try to navigate and operate the flyout nav example with VO.

**Expected behavior**
Nav flyouts can be clearly perceived and operated by assistive tech

**Is this issue blocking you?**
N/A

**Screenshots**
N/A

**What is your environment?**
N/A

**What is your product and what release date are you targeting?**
N/A

**Any other information?**
N/A

### PR DESCRIPTION
**Pull request by RuiBrian**
**What**: Closes #7781

**How:** Originally tried a new approach where we declare conditional props to disallow the `flyout` and `to` prop from being defined at the same time. However, this was noted to be a breaking change, so these updates were reverted. Instead, I added a `console.err` message if both `flyout` and `to` are defined.

**Notes**: This PR also fixes an existing issue where the subsequent flyout items in the flyout example cannot be opened with a keyboard (via pressing Enter or RightArrow). In the future, it may be worth refactoring the flyout example to only use the `MenuItem` component rather than `NavItem`.

**Additional issues**: N/A

### CODE REVIEW

File: packages/react-core/src/next/components/Dropdown/DropdownItem.tsx [hunk 1]
```diff
@@ -16,6 +16,22 @@ export interface DropdownItemProps extends Omit<MenuItemProps, 'ref'>, OUIAProps
...
+    }
+  | {
+      /** Target navigation link. Disallowed if flyoutMenu is defined */
+      to?: never;
+      /** Flyout menu */
+      flyoutMenu?: React.ReactElement;
+    };
+
+export type DropdownItemProps = CommonDropdownItemProps & ConditionalDropdownItemProps;
+
```
Comment (RuiBrian) [inline packages/react-core/src/next/components/Dropdown/DropdownItem.tsx:34]: Had to make this change so that the props would agree with `MenuItemProps`. Is there a better way to achieve this?

File: packages/react-core/src/next/components/Select/SelectOption.tsx [hunk 2]
```diff
@@ -19,6 +19,22 @@ export interface SelectOptionProps extends Omit<MenuItemProps, 'ref'> {
...
+    }
+  | {
+      /** Target navigation link. Disallowed if flyoutMenu is defined */
+      to?: never;
+      /** Flyout menu */
+      flyoutMenu?: React.ReactElement;
+    };
+
+export type SelectOptionProps = CommonSelectOptionProps & ConditionalSelectOptionProps;
+
```
Comment (RuiBrian) [inline packages/react-core/src/next/components/Select/SelectOption.tsx:37]: Same situation as `DropdownItem` changes

File: packages/react-core/src/components/Menu/MenuItem.tsx [hunk 3]
```diff
@@ -70,6 +66,22 @@ export interface MenuItemProps extends Omit<React.HTMLProps<HTMLLIElement>, 'onC
...
+      to?: string;
+      /** @beta Flyout menu. Disallowed if nav link is defined */
+      flyoutMenu?: never;
+    }
+  | {
+      /** Target navigation link. Disallowed if flyoutMenu is defined */
+      to?: never;
+      /** @beta Flyout menu */
+      flyoutMenu?: React.ReactElement;
+    };
```
Comment (wise-king-sullyman) [inline packages/react-core/src/components/Menu/MenuItem.tsx:81]: @tlabaj Would this change be breaking? I know it's an a11y bug, but I feel like there's a decent chance that there are consumers who followed the example and would need to make changes for the proposed type change here. Also I know that we have the beta tag on `flyoutMenu`, but we don't have it on `to`.

Genuine question as I'm not sure. A conditional type like this is a really neat idea though.

Comment (thatblindgeye) [reply packages/react-core/src/components/Menu/MenuItem.tsx:81]: Another thing that was noticed in our React huddle is that by doing this the to and flyoutMenu props are no longer rendered in the props table on the React page for the component. If anything, perhaps we can put the implementation proposed here on the backburner and discuss it further down the line?

Comment (tlabaj) [reply packages/react-core/src/components/Menu/MenuItem.tsx:81]: yes.  This would be a breaking change.
I would probably not recommend defining type this way and instead have 2 separate types and a prop that could be one or the other.
We would need to wait for the breaking change release to do this.

**Review by tlabaj — CHANGES_REQUESTED** [review]

**Review by kmcfaul — APPROVED** [review]
lgtm. 

Regarding the previous conditional prop syntax, do we want to add a note the description of the `flyoutMenu` and `to` props that they shouldn't be used together? Not a blocker for me just a thought.

**Review by kmcfaul — APPROVED** [review]

**Review by thatblindgeye — APPROVED** [review]

**Review by wise-king-sullyman — APPROVED** [review]

**Review by tlabaj — APPROVED** [review]
LGTM!  Thank you!
