### PR TITLE
fix(select): remove the custom override on width

### LINKED ISSUE #1610: Update Select Width
This was just merged in Core - https://github.com/patternfly/patternfly-next/pull/1595
It updates the width for the select to be 100%.

A while back, a custom override was added to the width of the select component-- https://github.com/patternfly/patternfly-react/pull/1277#issuecomment-460663434

But we hadn't followed up with the issue in Core. Now you can remove the custom override for the width of the select.

### PR DESCRIPTION
**Pull request by boaz0**
**What**:
This change removes `width` from `defaultProps` as `width: 100%` is set in the class.
closes #1610 
//cc @christiemolloy @kmcfaul

### CODE REVIEW

File: packages/patternfly-4/react-core/src/components/Select/Select.js [hunk 1]
```diff
@@ -42,7 +42,6 @@ const defaultProps = {
   selections: null,
   placeholderText: null,
   variant: SelectVariant.single,
-  width: '100%'
```
Comment (tlabaj) [inline packages/patternfly-4/react-core/src/components/Select/Select.js]: don't we need a default prop here since the width is not required?

Comment (boaz0) [reply packages/patternfly-4/react-core/src/components/Select/Select.js]: If I understood correctly, the `width` should be set by `pf-c-select`.
I didn't remove `width` from props in case someone wants to change that attribute, though.

Comment (jschuler) [reply packages/patternfly-4/react-core/src/components/Select/Select.js]: Probably makes more sense to default it to empty string or null, this way your check still works below

**Comment by boaz0** [comment]
Thank you all @kmcfaul, @tlabaj and @jschuler
