### PR TITLE
fix(Select): aria-describedby is added properly

### LINKED ISSUE #7251: Bug - Select Typeahead - aria-describedby is not present
**Describe the problem**
The Select component states that `aria-describedby` can be added to the Select component. When I add this to the Select component that is a typeahead variant, I expect to see `aria-describedby` added to the input `.pf-c-select__toggle-typeahead` so that any error messages we display are announced to users of assistive technology.

**How do you reproduce the problem?**
Add `aria-describedby` to the `<Select>` component.

**Expected behavior**
I expect to see `aria-describedby` added to the input `.pf-c-select__toggle-typeahead`

**Is this issue blocking you?**
No

### PR DESCRIPTION
**Pull request by tompsota**
The aria-describedby field is now added regardless of state of validation

Signed-off-by: Tomas Psota <tpsota@redhat.com>

**What**: Closes #7251

### CODE REVIEW

File: packages/react-core/src/components/Select/Select.tsx [hunk 1]
```diff
@@ -1250,7 +1250,7 @@ export class Select extends React.Component<SelectProps & OUIAProps, SelectState
         ref={this.parentRef}
         {...getOUIAProps(Select.displayName, ouiaId !== undefined ? ouiaId : this.state.ouiaStateId, ouiaSafe)}
         {...(width && { style: { width } })}
-        {...(validated !== ValidatedOptions.default && { 'aria-describedby': ariaDescribedby })}
+        {...(ariaDescribedby !== '' && { 'aria-describedby': ariaDescribedby })}
```
Comment (jenny-s51) [inline packages/react-core/src/components/Select/Select.tsx:1253]:
```suggestion
        {...(ariaDescribedby && { 'aria-describedby': ariaDescribedby })}
```

**Review by jenny-s51 — CHANGES_REQUESTED** [review]
Nice update @tompsota - I'm seeing `aria-describedby`when I enter a value for it!

Based on @jgiardino 's description in https://github.com/patternfly/patternfly-react/issues/7251, it looks like we want `aria-describedby` added to the input .pf-c-select__toggle-typeahead, whereas currently it's showing up on `pf-c-select`.

Easy fix - you should be able to relocate `{...(ariaDescribedby && { 'aria-describedby': ariaDescribedby })}` to the [typeahead](https://github.com/patternfly/patternfly-react/blob/main/packages/react-core/src/components/Select/Select.tsx#L1317-L1334) and [typeahead multi](https://github.com/patternfly/patternfly-react/blob/main/packages/react-core/src/components/Select/Select.tsx#L1344-L1357) `<input>`s.

What do you think @tompsota ?

File: packages/react-core/src/components/Select/Select.tsx [hunk 2]
```diff
@@ -1229,7 +1229,7 @@ export class Select extends React.Component<SelectProps & OUIAProps, SelectState
           className
         )}
         {...(width && { style: { width } })}
-        {...(validated !== ValidatedOptions.default && { 'aria-describedby': ariaDescribedby })}
+        {...(ariaDescribedby !== '' && { 'aria-describedby': ariaDescribedby })}
```
Comment (jenny-s51) [inline packages/react-core/src/components/Select/Select.tsx:1232]:
```suggestion
        {...(ariaDescribedby && { 'aria-describedby': ariaDescribedby })}
```

File: packages/react-core/src/components/Select/Select.tsx (hunk 1 above)
Comment (tompsota) [reply packages/react-core/src/components/Select/Select.tsx:1253]: Thanks for the comments. 

If we relocate `ariaDescribedby` to `<input>`s, we will be unable to use it with different variants of `Select` as some of them do not have inputs. 

I see 2 possibilities how to avoid this:

1. Add `aria-describedby` to `<input>`s and keep it also where it is now
2. Add new prop `typeAheadAriaDescribedBy`, apply it to `<input>`s and keep `aria-describedby` where it is now. Similarly to [typeAheadAriaLabel](https://github.com/patternfly/patternfly-react/blob/main/packages/react-core/src/components/Select/Select.tsx#L1321)

I would prefer the second option, what about you @jenny-s51?

Comment (jenny-s51) [reply packages/react-core/src/components/Select/Select.tsx:1253]: Thank you for clarifying @tompsota - I like the second option as well! It would make sense to follow this existing convention the way it's used for typeAheadAriaLabel

**Review by jenny-s51 — COMMENTED** [review]
LGTM! Looks like we just need to rebuild/update the snapshots for `Select.test.tsx`

File: packages/react-core/src/components/Select/Select.tsx [hunk 3]
```diff
@@ -1250,7 +1254,7 @@ export class Select extends React.Component<SelectProps & OUIAProps, SelectState
         ref={this.parentRef}
         {...getOUIAProps(Select.displayName, ouiaId !== undefined ? ouiaId : this.state.ouiaStateId, ouiaSafe)}
         {...(width && { style: { width } })}
-        {...(validated !== ValidatedOptions.default && { 'aria-describedby': ariaDescribedby })}
+        {...(ariaDescribedby && { 'aria-describedby': ariaDescribedby })}
```
Comment (thatblindgeye) [inline packages/react-core/src/components/Select/Select.tsx:1257]: I believe if this is moved to the `<SelectToggle>` on line 1260, the attribute would apply to the correct element.

**Review by thatblindgeye — COMMENTED** [review]
Sounds good when testing in VO! I am noticing an issue with the original `aria-describedby` prop with the non-typeahead variant in that VO doesn't announce the description, however. It looks like it's because the `aria-describedby` is being applied to the div with class `.pf-c-select` rather than the SelectToggle like the `aria-labelledby` is.

EDIT: Since this is pre-existing I'm going to open a follow up issue, so no need to make this update on this PR.

File: packages/react-core/src/components/Select/Select.tsx [hunk 4]
```diff
@@ -1319,6 +1323,7 @@ export class Select extends React.Component<SelectProps & OUIAProps, SelectState
                   aria-activedescendant={typeaheadActiveChild && typeaheadActiveChild.id}
                   id={`${selectToggleId}-select-typeahead`}
                   aria-label={typeAheadAriaLabel}
+                  aria-describedby={typeAheadAriaDescribedby}
```
Comment (thatblindgeye) [inline packages/react-core/src/components/Select/Select.tsx:1326]: It might be worth following the `aria-describedby` prop here so that the attribute doesn't get added if the prop isn't passed in:

```suggestion
                  {...(typeAheadAriaDescribedby && { 'aria-describedby': typeAheadAriaDescribedby })}
```

File: packages/react-core/src/components/Select/Select.tsx [hunk 5]
```diff
@@ -1347,6 +1352,7 @@ export class Select extends React.Component<SelectProps & OUIAProps, SelectState
                   id={`${selectToggleId}-select-multi-typeahead-typeahead`}
                   aria-label={typeAheadAriaLabel}
                   aria-invalid={validated === ValidatedOptions.error}
+                  aria-describedby={typeAheadAriaDescribedby}
```
Comment (thatblindgeye) [inline packages/react-core/src/components/Select/Select.tsx:1355]: Same here in regards to comment above.

**Review by thatblindgeye — CHANGES_REQUESTED** [review]

**Review by thatblindgeye — APPROVED** [review]

**Review by jessiehuff — APPROVED** [review]
LGTM!

**Review by jenny-s51 — APPROVED** [review]
🚀
