### PR TITLE
fix(jumplinks): fixed to always set clicked item as active

### LINKED ISSUE #6156: JumpList will not highlight last item when selected
**Describe the issue. What is the expected and unexpected behavior?**

**Expected behavior**
When clicking the last item in the JumpList we scroll to the section and it is highlighted.

**Actual behavior**
When clicking the last item in the JumpList we scroll to the section but it's not highlighted.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
1. Visit the [PatternFly documentation](https://www.patternfly.org/v4/components/jump-links)
2. Click the last item in the table of contents to the right.

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
It's a bug, it's not blocking but just a bit annoying for the user. 

**What is your product and what release version are you targeting?**
Keycloak Admin console, original issue can be found there (https://github.com/keycloak/keycloak-admin-ui/issues/960).

### PR DESCRIPTION
**Pull request by evwilkin**
**What**: Closes #6156 

This PR updates the JumpLinks to always set the clicked JumpLink as active when clicked.
- calls `setActiveIndex` in each JumpLink's `onClick` to set that link as active.
- adds `isLinkClicked` boolean variable which disables the scroll listener from also calling `setActiveIndex` and overriding the clicked link's active state when the linked section scrolls into place.
- this fixes the issue of the last JumpLink never showing as active when the linked section doesn't reach the top of the page.

### CODE REVIEW

**Review by mcarrano — APPROVED** [review]
Looks great @evwilkin !

**Review by nicolethoen — APPROVED** [review]

File: packages/react-core/src/components/JumpLinks/JumpLinks.tsx [hunk 1]
```diff
@@ -100,6 +100,8 @@ export const JumpLinks: React.FunctionComponent<JumpLinksProps> = ({
   const [scrollItems, setScrollItems] = React.useState(hasScrollSpy ? getScrollItems(children, []) : []);
   const [activeIndex, setActiveIndex] = React.useState(activeIndexProp);
   const [isExpanded, setIsExpanded] = React.useState(isExpandedProp);
+  // Boolean to disable scroll listener from overriding active state of clicked jumplink
+  const isLinkClicked = React.useRef(false);
```
Comment (tlabaj) [inline packages/react-core/src/components/JumpLinks/JumpLinks.tsx:104]: Curious why you are using a ref here instead of state for a boolean value.

Comment (kmcfaul) [reply packages/react-core/src/components/JumpLinks/JumpLinks.tsx:104]: Also curious about this

**Review by kmcfaul — APPROVED** [review]

File: packages/react-core/src/components/JumpLinks/JumpLinks.tsx (hunk 1 above)
Comment (evwilkin) [reply packages/react-core/src/components/JumpLinks/JumpLinks.tsx:104]: @tlabaj @kmcfaul I did try using state with a boolean originally, but it wasn't working as expected - I'm not sure if either the `scrollSpy` was triggering before the state had finished updating, or if the state boolean was getting reset on rerender.

Either way, it does work as coded with `useRef` which [persists values across renders](https://reactjs.org/docs/hooks-reference.html#useref) or if I pull the boolean out of the component completely as a standalone variable, which I'm happy to switch to if that's preferred.

Comment (kmcfaul) [reply packages/react-core/src/components/JumpLinks/JumpLinks.tsx:104]: After talking it through with Evan - this is a recommended pattern from the react docs https://reactjs.org/docs/hooks-reference.html#useref to store mutable instance fields (similar to how a private variable exists in a class). 

It can also work as a boolean stored outside the component. I'm good with either implementation
