### PR TITLE
fix(dropdown): Delay setting focus on first item to prevent inadvertent scroll

### LINKED ISSUE #10896: Bug - Select - Opening a select that is in a scrollable which is not the body causes screen to jump
**Describe the problem**
Opening a select that is in a scrollable which is not the body causes screen to jump if the menu would go off the screen.

**How do you reproduce the problem?**
https://codesandbox.io/p/sandbox/festive-fire-9dhpjs?workspaceId=eea9ed0c-da74-4627-b8e0-631826ffcb34
Scroll down to value 22 and open the select.

**Expected behavior**
The menu should open leaving the scrollable in the same position.

**Is this issue blocking you?**
Yes

**What is your product and what release date are you targeting?**
RHOAI - already released

**Any other information?**

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
**What**: 
Closes #10896 

**Description**:
Add a slight delay before setting focus on the first dropdown item when `shouldFocusFirstItemOnOpen` is set. This gives enough time for the popover to be shown in the correct location so the scrollable doesn't scroll to the invalid location.

### CODE REVIEW

File: packages/react-core/src/components/Dropdown/Dropdown.tsx [hunk 1]
```diff
@@ -127,7 +127,7 @@ const DropdownBase: React.FunctionComponent<DropdownProps> = ({
             'li button:not(:disabled),li input:not(:disabled),li a:not([aria-disabled="true"])'
           );
           firstElement && (firstElement as HTMLElement).focus();
-        }, 0);
+        }, 10);
```
Comment (thatblindgeye) [inline packages/react-core/src/components/Dropdown/Dropdown.tsx:130]: @tlabaj wdyt about using a (beta) prop for this timeout amount? Wondering just based on how this issue has come up several times if we can rely on a static timeout without the potential to have to slowly increase it if the issue comes up again.

**Review by thatblindgeye — COMMENTED** [review]
This does look to work when testing the Table with actions example. In v5 org i can replicate the scroll jump bug in that example, but in this PR I haven't been able to (trying to open the kebab menu with the page scrolled to various points).

File: packages/react-core/src/components/Dropdown/Dropdown.tsx (hunk 1 above)
Comment (tlabaj) [reply packages/react-core/src/components/Dropdown/Dropdown.tsx:130]: Yes.  we can do that as follow up.

**Review by thatblindgeye — APPROVED** [review]
