### PR TITLE
fix(Dropdown): Set a random id for dropdown item if id is not given

### LINKED ISSUE #3549: DropdownItems have bad id, cause console warnings
Using DropdownItems creates items with duplicate invalid id settings causing warnings in the console:

```
t-s:1 [DOM] Found 7 elements with non-unique id #: (More info: https://goo.gl/9p2vKq) 
<button tabindex=​"-1" type=​"button" class=​"pf-c-dropdown__menu-item" id>​…​
<button tabindex=​"-1" type=​"button" class=​"pf-c-dropdown__menu-item" id>​…
<button tabindex=​"-1" type=​"button" class=​"pf-c-dropdown__menu-item" id>​…
<button tabindex=​"-1" type=​"button" class=​"pf-c-dropdown__menu-item" id>​…
<button tabindex=​"-1" type=​"button" class=​"pf-c-dropdown__menu-item" id>​…
<button tabindex=​"-1" type=​"button" class=​"pf-c-dropdown__menu-item" id>​…
<button tabindex=​"-1" type=​"button" class=​"pf-c-dropdown__menu-item" id>​…
```

### PR DESCRIPTION
**Pull request by boaz0**
**What**: Closes #3549 

//cc @jeff-phillips-18

### CODE REVIEW

**Comment by jeff-phillips-18** [comment]
Could we simply not set the id if not given? So either remove the default props for `id` and `componentId` or, if linter doesn't allow it, then do:

`id={id || undefined}`

**Comment by boaz0** [comment]
@jeff-phillips-18 - yes, that makes more sense. Thanks for the feedback.

File: packages/patternfly-4/react-core/src/components/Dropdown/InternalDropdownItem.tsx [hunk 1]
```diff
@@ -4,6 +4,9 @@ import { DropdownContext } from './dropdownConstants';
 import { KEY_CODES, KEYHANDLER_DIRECTION } from '../../helpers/constants';
 import { Tooltip } from '../Tooltip';
 import styles from '@patternfly/react-styles/css/components/Dropdown/dropdown';
+import GenerateId from '../../helpers/GenerateId/GenerateId';
+
+let currentId = 0;
```
Comment (jeff-phillips-18) [inline packages/patternfly-4/react-core/src/components/Dropdown/InternalDropdownItem.tsx]: This change is no longer needed.

File: packages/patternfly-4/react-core/src/components/Dropdown/InternalDropdownItem.tsx [hunk 2]
```diff
@@ -66,8 +66,8 @@ export class InternalDropdownItem extends React.Component<InternalDropdownItemPr
       keyHandler: () => {},
       sendRef: () => {}
     },
-    id: '',
-    componentID: '',
+    id: null,
+    componentID: null,
```
Comment (dlabrecq) [inline packages/patternfly-4/react-core/src/components/Dropdown/InternalDropdownItem.tsx]: Instead of setting this to null, couldn't we just not set a default? That is, remove this from `defaultProps`.

We shouldn't need to test `componentID || undefined` because it would already be undefined.

Comment (jeff-phillips-18) [reply packages/patternfly-4/react-core/src/components/Dropdown/InternalDropdownItem.tsx]: that was my thought as well, but if i recall the lint settings require optional props to have defaults, though `undefined` may be a valid default 🤷‍♂

Comment (dlabaj) [reply packages/patternfly-4/react-core/src/components/Dropdown/InternalDropdownItem.tsx]: yeah if you remove the default props here then it will just default to undefined and be fine.
