### PR TITLE
fix(select): option with description on active display only value

### LINKED ISSUE #4502: Typeahead selector displays options with descriptions incorrectly
**Describe the issue. What is the expected and unexpected behavior?**
In the typeahead example: On the select menu shown clicking on the down arrow allows to go through the options.
Once an option is "active" it is colored in gray and its value is shown in the input. However, when the option has description, the description is shown with the value in the input box. In addition, the option is not colored in gray like any other option.

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
I believe it's a bug and no work-around exists.

**What is your product and what release version are you targeting?**
3.153.3

### PR DESCRIPTION
**Pull request by boaz0**
**What**: Closes #4502

### CODE REVIEW

File: packages/react-core/src/components/Select/Select.tsx [hunk 1]
```diff
@@ -409,6 +419,7 @@ export class Select extends React.Component<SelectProps & OUIAProps, SelectState
       menuAppendTo,
       ...props
     } = this.props;
+    console.log('active state', this.state.typeaheadActiveChild)
```
Comment (dlabrecq) [inline packages/react-core/src/components/Select/Select.tsx:422]: Please remove this console message

File: packages/react-core/src/components/Select/Select.tsx [hunk 2]
```diff
@@ -303,13 +310,16 @@ export class Select extends React.Component<SelectProps & OUIAProps, SelectState
         } else {
           nextIndex = getNextIndex(typeaheadCurrIndex, position, this.refCollection);
         }
+        const hasDescriptionElm = Boolean(this.refCollection[nextIndex].classList.contains('pf-m-description'));
+        const optionTextElm = hasDescriptionElm ? this.refCollection[nextIndex].firstElementChild as HTMLElement: this.refCollection[nextIndex]
+        console.log(optionTextElm)
```
Comment (jenny-s51) [inline packages/react-core/src/components/Select/Select.tsx:315]: delete this log statement
