### PR TITLE
fix(Drawer): expand only onTransitionEnd of the drawer

### LINKED ISSUE #8510: Bug - Drawer - expandable section inside the panel content causes drawer's onExpand to be fired
**Describe the problem**
When an expandable section is placed inside the panelContent prop of the drawer and the user expands or collapses the expandable section, the onExpand method for the drawer is fired.

This is unexpected and since the onExpand is used to put focus on the drawer when opened, having onExpand called when the drawer is already open causes the focus to move (and possibly browser scroll) to behave unexpectedly. 

**How do you reproduce the problem?**
Place an expandable section inside the panel content prop of the drawer. Expand the drawer and then expand/collapse the expandable section.  This will cause the onExpand method from the drawer to be fired.

See https://codesandbox.io/s/stupefied-pasteur-tmt5ud?file=/index.tsx for an example.  

**Expected behavior**
The onExpand is triggered only when the drawer is expanded.

**Is this issue blocking you?**
The only workaround I could come up with is adding another state variable to determine when onExpand should be triggered or not. Using isExpanded didn't work because isExpanded is always true when onExpand is called.

**Screenshots**
See https://codesandbox.io/s/stupefied-pasteur-tmt5ud?file=/index.tsx for an example.  

**What is your environment?**
OS: [e.g. iOS]: Any (I tested using a macbook pro using OS 11.7.1)
Browser [e.g. chrome, safari]: Any (I tested using chrome 108.0.5359.124 )

**What is your product and what release date are you targeting?**
OCM

**Any other information?**

### PR DESCRIPTION
**Pull request by MariaAga**
**What**: Closes #8510

can be tested by replacing `packages/react-core/src/components/Drawer/examples/DrawerStackedContentBodyElements.tsx` with: https://codesandbox.io/s/drawerstackedcontentbodyelements-t8v58c?file=/index.tsx
and seeing that `onExpand` counter is not growing when `Show more` is clicked

### CODE REVIEW

File: packages/react-core/src/components/Drawer/DrawerPanelContent.tsx [hunk 1]
```diff
@@ -261,10 +261,12 @@ export const DrawerPanelContent: React.FunctionComponent<DrawerPanelContentProps
           )}
           ref={panel}
           onTransitionEnd={(ev) => {
-            if (!hidden && ev.nativeEvent.propertyName === 'transform') {
-              onExpand();
+            if ((ev.target as HTMLElement).id === (id || panelId)) {
```
Comment (thatblindgeye) [inline packages/react-core/src/components/Drawer/DrawerPanelContent.tsx:264]: An alternative to this:

```suggestion
            if ((ev.target as HTMLElement) === panel.current) {
```

Not really sure how common an issue it'd be, but one thing I noticed when checking if the target id === the component id/panelId is that if we have something like the following:

```
<DrawerPanelContent id="tester">
```

Then if within the drawer if some element like an expandable toggle would be the target *and* have that same ID, it causes the original bug to resurface. In the clip below I just added `id="tester"` to `.pf-c-expandable-section__toggle-icon` via dev tools since I don't believe we could pass an ID to that exact element otherwise, but I'm more imagining a scenario where some custom expandable toggle is used instead.


https://user-images.githubusercontent.com/70952936/225942700-22a5cbbb-e6eb-4223-9c5f-b61bb9b50e06.mov

Checking whether the target === the panel.current with the same setup as the above clip:


https://user-images.githubusercontent.com/70952936/225943008-1151c3a7-57b5-4243-9501-de06a4a0bcbc.mov

Personally I might lean more towards checking the target against the panel ref since ID duplication can happen, but like I said I'm not sure how common this would actually be. What do you think, @MariaAga ?

**Review by thatblindgeye — COMMENTED** [review]
This looks great! Just had a comment below that I'd appreciate your feedback on

File: packages/react-core/src/components/Drawer/DrawerPanelContent.tsx (hunk 1 above)
Comment (MariaAga) [reply packages/react-core/src/components/Drawer/DrawerPanelContent.tsx]: Yeah I think its better to be safer, changed it

**Review by thatblindgeye — APPROVED** [review]
🎉 Looks like there's just a snapshot that needs to be updated. @wise-king-sullyman was that issue with Timestamp tests resolved or is it still finicky?

**Comment by MariaAga** [comment]
rebased and now tests are green

**Comment by tlabaj** [comment]
> 🎉 Looks like there's just a snapshot that needs to be updated. @wise-king-sullyman was that issue with Timestamp tests resolved or is it still finicky?

I disabled the timestamp test that was problematic.

**Review by tlabaj — APPROVED** [review]
