### PR TITLE
[ISSUE-6350] - allow onSelect to prevent the default behavior of toggling node collapse

### LINKED ISSUE #6350: TreeView: Allow onSelect to determine if TreeViewItem node is expanded
**Describe the issue. What is the expected and unexpected behavior?**
Currently there is no programmatic way to prevent a node from be expanded.

I would like to propose that we listen to the return of the `onSelect` callback, if provided, and if it returns a value of `false` do not expand the node.

The onClick behavior in TreeViewListItem would change as follows:
```
              onClick={(evt: React.MouseEvent) => {
                if (!hasCheck) {
                  const expand = onSelect ? onSelect(evt, itemData, parentItem) : true;
                  if (children && expand !== false) {
                    setIsExpanded(!internalIsExpanded);
                  }                  
                }
              }}
```

Further it would be nice to have the capability of `locking` the expansion of an entire tree or subtree.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
[CodeSandbox](https://codesandbox.io/s/epic-volhard-lrid3?file=/index.js)

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
This would be an enhancement.

**What is your product and what release version are you targeting?**
Catalog Manager, no particular target release

### PR DESCRIPTION
**Pull request by steverhoades**
The proposed usage would allow for the onSelect method to call `evt.preventDefault()` to prevent the nodes from toggling. This is useful for determining programmatically whether a node should be collapsed. Further, it allows for the tree to be expanded and locked by the integrator.

**What**: Closes #6350 

**Additional issues**: None

### CODE REVIEW

File: packages/react-core/src/components/TreeView/TreeViewListItem.tsx [hunk 1]
```diff
@@ -186,10 +186,10 @@ export const TreeViewListItem: React.FunctionComponent<TreeViewListItemProps> =
               )}
               onClick={(evt: React.MouseEvent) => {
                 if (!hasCheck) {
-                  if (children) {
+                  onSelect && onSelect(evt, itemData, parentItem);
+                  if (children && evt.isDefaultPrevented() !== true) {
```
Comment (kmcfaul) [inline packages/react-core/src/components/TreeView/TreeViewListItem.tsx:190]: If I'm following this correctly, expansion would be prevented if `evt.preventDefault()` is called within the user-defined `onSelect` right? If so, then could you please update the `onSelect` property description to reflect the new behavior interaction?

**Review by redallen — APPROVED** [review]

**Review by nicolethoen — APPROVED** [review]

**Review by kmcfaul — APPROVED** [review]
