### PR TITLE
fix(Alert): Make Alert consistent with core

### LINKED ISSUE #1286: Update alert/alert-group with a11y changes from core
From this PR - https://github.com/patternfly/patternfly-next/pull/1257/files

* We're no longer using "notification" language in alerts, it's all just "alert" now. I would just search for the word notification and change it to alert in this component.
* The `aria-label` for the close button has been updated to be more descriptive. You can look on core for examples. Here's the docs, you can also find listed on the component page. 

> `aria-label="Close Success alert: Success alert title"` | `.pf-c-button.pf-m-plain` | Indicates the close button. Please provide descriptive text to ensure assistive technologies clearly state which alert is being closed.

* The `.pf-u-screen-reader` screen reader text should also say "Alert" at the end, so instead of "Info:" it would be "Info alert:" (as an example)
    * just an aside, any instance of `.pf-u-screen-reader` should be `.pf-screen-reader` now. You shouldn't have to use any utility class in react now.
* There is a random `>` in the danger alert examples in the workspace

### PR DESCRIPTION
**Pull request by rebeccaalpert**
I updated the aria-label for the close button and the screen reader text to be more descriptive and removed the caret in the Danger Alert example. I also replaced all instances of "notification" with "alert" and updated the Alert snapshots.

Fixes #1286.

### CODE REVIEW

**Comment by rebeccaalpert** [comment]
Hey @mcoker - When I get rid of the utility class import and use {css(styles.screenReader)} instead, there are no styles applied. It looks like we're on Patternfly-Next release. 1.0.167 - were the utility classes removed after that release, or should I be using a different identifier for the styles?

**Comment by mcoker** [comment]
@rebeccaalpert sorry I'm not too familiar with the react syntax, but the class `.pf-screen-reader` is a global class that's found in the PF4 core base stylesheet. It was added a while ago and should be a part of `1.0.167`. This may be a follow-up issue, too, assuming we can make this change for all components currently using the accessibility utility stylesheet:

```
dist/esm/components/Alert/Alert.js:import accessibleStyles from "../../@patternfly/patternfly-next/utilities/Accessibility/accessibility.css.js";
dist/esm/components/Nav/NavExpandable.js:import a11yStyles from "../../@patternfly/patternfly-next/utilities/Accessibility/accessibility.css.js";
dist/esm/demos/PageLayout/examples/PageLayoutDefaultNav.js:import accessibleStyles from "../../../@patternfly/patternfly-next/utilities/Accessibility/accessibility.css.js";
dist/esm/demos/PageLayout/examples/PageLayoutSimpleNav.js:import accessibleStyles from "../../../@patternfly/patternfly-next/utilities/Accessibility/accessibility.css.js";
dist/esm/demos/PageLayout/examples/PageLayoutExpandableNav.js:import accessibleStyles from "../../../@patternfly/patternfly-next/utilities/Accessibility/accessibility.css.js";
dist/esm/demos/PageLayout/examples/PageLayoutHorizontalNav.js:import accessibleStyles from "../../../@patternfly/patternfly-next/utilities/Accessibility/accessibility.css.js";
dist/esm/demos/PageLayout/examples/PageLayoutGroupsNav.js:import accessibleStyles from "../../../@patternfly/patternfly-next/utilities/Accessibility/accessibility.css.js";
dist/esm/demos/PageLayout/examples/PageLayoutManualNav.js:import accessibleStyles from "../../../@patternfly/patternfly-next/utilities/Accessibility/accessibility.css.js";
dist/umd/components/Alert/Alert.js:    define(["exports", "react", "@patternfly/react-styles", "prop-types", "../../@patternfly/patternfly-next/components/Alert/alert.css.js", "../../@patternfly/patternfly-next/utilities/Accessibility/accessibility.css.js", "./AlertIcon", "../../internal/util", "./AlertActionCloseButton", "./AlertActionLink"], factory);
dist/umd/components/Alert/Alert.js:    factory(exports, require("react"), require("@patternfly/react-styles"), require("prop-types"), require("../../@patternfly/patternfly-next/components/Alert/alert.css.js"), require("../../@patternfly/patternfly-next/utilities/Accessibility/accessibility.css.js"), require("./AlertIcon"), require("../../internal/util"), require("./AlertActionCloseButton"), require("./AlertActionLink"));
dist/js/components/Alert/Alert.js:var _accessibilityCss = _interopRequireDefault(require("../../@patternfly/patternfly-next/utilities/Accessibility/accessibility.css.js"));
dist/js/components/Nav/NavExpandable.js:var _accessibilityCss = _interopRequireDefault(require("../../@patternfly/patternfly-next/utilities/Accessibility/accessibility.css.js"));
dist/js/demos/PageLayout/examples/PageLayoutDefaultNav.js:var _accessibilityCss = _interopRequireDefault(require("../../../@patternfly/patternfly-next/utilities/Accessibility/accessibility.css.js"));
dist/js/demos/PageLayout/examples/PageLayoutSimpleNav.js:var _accessibilityCss = _interopRequireDefault(require("../../../@patternfly/patternfly-next/utilities/Accessibility/accessibility.css.js"));
dist/js/demos/PageLayout/examples/PageLayoutExpandableNav.js:var _accessibilityCss = _interopRequireDefault(require("../../../@patternfly/patternfly-next/utilities/Accessibility/accessibility.css.js"));
dist/js/demos/PageLayout/examples/PageLayoutHorizontalNav.js:var _accessibilityCss = _interopRequireDefault(require("../../../@patternfly/patternfly-next/utilities/Accessibility/accessibility.css.js"));
dist/js/demos/PageLayout/examples/PageLayoutGroupsNav.js:var _accessibilityCss = _interopRequireDefault(require("../../../@patternfly/patternfly-next/utilities/Accessibility/accessibility.css.js"));
dist/js/demos/PageLayout/examples/PageLayoutManualNav.js:var _accessibilityCss = _interopRequireDefault(require("../../../@patternfly/patternfly-next/utilities/Accessibility/accessibility.css.js"));
src/components/Alert/Alert.js:import accessibleStyles from '@patternfly/patternfly-next/utilities/Accessibility/accessibility.css';
src/components/Nav/NavExpandable.js:import a11yStyles from '@patternfly/patternfly-next/utilities/Accessibility/accessibility.css';
src/demos/PageLayout/examples/PageLayoutDefaultNav.js:import accessibleStyles from '@patternfly/patternfly-next/utilities/Accessibility/accessibility.css';
src/demos/PageLayout/examples/PageLayoutSimpleNav.js:import accessibleStyles from '@patternfly/patternfly-next/utilities/Accessibility/accessibility.css';
src/demos/PageLayout/examples/PageLayoutExpandableNav.js:import accessibleStyles from '@patternfly/patternfly-next/utilities/Accessibility/accessibility.css';
src/demos/PageLayout/examples/PageLayoutHorizontalNav.js:import accessibleStyles from '@patternfly/patternfly-next/utilities/Accessibility/accessibility.css';
src/demos/PageLayout/examples/PageLayoutGroupsNav.js:import accessibleStyles from '@patternfly/patternfly-next/utilities/Accessibility/accessibility.css';
src/demos/PageLayout/examples/PageLayoutManualNav.js:import accessibleStyles from '@patternfly/patternfly-next/utilities/Accessibility/accessibility.css';
```

**Comment by dmiller9911** [comment]
@mcoker @rebeccaalpert the screen reader class now being part of the base breaks the react implementation. You can just hard code the class since we tell users to import the base CSS, but this is not a good long term solution. Doing it this way breaks all of the safety the pf-react build system provides. This has saved us in the past and I think it is invaluable. Sadly since that class also doesn't follow the pattern of pf-(l|c|u)-{name} the Babel plugin won't even pick it up. What we're the reasons for making this class act different than others?

**Comment by mcoker** [comment]
hey @dmiller9911. This was a result of removing all instances of utility classes from components that ship in core, so that react doesn't have to include a utility class for a component by default. The unique classname was basically to replicate what we used before, `.sr-only`, which came from FontAwesome, only to add `.pf-` to it so that the var name is scoped to PF4.

If including the a11y utility is fine, I think it's OK. The only downside I see is that the a11y utility includes a bunch of responsive modifiers that you don't need simply to hide elements visually, which we do in a number of components. Do you have a suggestion for how we could better include this class, or think it's OK to import the a11y utility for components that need to hide elements visually?

**Comment by rebeccaalpert** [comment]
Address PR feedback.

File: packages/patternfly-4/react-core/src/components/Alert/AlertActionCloseButton.js [hunk 1]
```diff
@@ -17,13 +17,13 @@ const propTypes = {
...
+  'aria-label': '',
   className: '',
   onClose: () => undefined,
-  'aria-label': 'Close'
 };
 
-const AlertActionCloseButton = ({ className, onClose, 'aria-label': ariaLabel, ...props }) => (
-  <Button variant={ButtonVariant.plain} onClick={onClose} aria-label={ariaLabel} {...props}>
+const AlertActionCloseButton = ({ className, onClose, 'aria-label': ariaLabel, title, variantLabel, ...props }) => (
+  <Button variant={ButtonVariant.plain} onClick={onClose} aria-label={ariaLabel ? ariaLabel : `Close ${variantLabel} alert: ${title}`} {...props}>
```
Comment (tlabaj) [inline packages/patternfly-4/react-core/src/components/Alert/AlertActionCloseButton.js]: This wont work.  You need to either set the default to null or check for the empty string.

Comment (rebeccaalpert) [reply packages/patternfly-4/react-core/src/components/Alert/AlertActionCloseButton.js]: I'm dumb. Amended the commit to reflect this.
