### PR TITLE
fix(Select): Fix select crash

### LINKED ISSUE #6384: bug(Select): Grouped options typeahead with loadingVariant: spinner  crashes the component
**Describe the issue. What is the expected and unexpected behavior?**
As the issue title says. Happens only when onFilter is not set. 

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
https://codesandbox.io/s/admiring-napier-56byo?file=/index.js

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
bug

Stacktrace:
```
Select/this.getDisplay/item<@https://4skoq.csb.app/node_modules/
patternfly/react-core/dist/esm/components/Select/Select.js:324:185
Select/this.getDisplay@https://4skoq.csb.app/node_modules/
patternfly/react-core/dist/esm/components/Select/Select.js:324:171
childFilter@https://4skoq.csb.app/node_modules/
```

### PR DESCRIPTION
**Pull request by tlabaj**
**What**: Closes #6384 

**Additional issues**:

### CODE REVIEW

**Review by nicolethoen — APPROVED** [review]
This is impressive! A one line fix full test suite. 
A good example. We should try and continue addressing select issues like this - to better protect against regressions in the future!

**Comment by wise-king-sullyman** [comment]
I feel like I'm probably misunderstanding something, but undoing your change to `Select.tsx` doesn't make the integration tests you added fail, is that intentional?

**Comment by tlabaj** [comment]
> I feel like I'm probably misunderstanding something, but undoing your change to `Select.tsx` doesn't make the integration tests you added fail, is that intentional?

Good catch.  I actually added the wrong demo and test to this PR.

**Review by wise-king-sullyman — APPROVED** [review]

File: packages/react-integration/demo-app-ts/src/components/demos/SelectDemo/SelectViewMoreTypeaheadGroupedDemo.tsx [hunk 1]
```diff
@@ -0,0 +1,176 @@
...
+    isOpen: false,
+    selected: [] as string[],
+    numOptions: 1,
+    isLoading: false,
+    isCreatable: false,
+    newOptions: false,
+    inputValuePersisted: false
+  };
+
+  options = [
```
Comment (wise-king-sullyman) [inline packages/react-integration/demo-app-ts/src/components/demos/SelectDemo/SelectViewMoreTypeaheadGroupedDemo.tsx:34]: Per our discussion on slack, `options` should be managed in the state since we have option creation functionality.

**Review by wise-king-sullyman — CHANGES_REQUESTED** [review]

**Review by wise-king-sullyman — APPROVED** [review]
Looks great!

**Review by nicolethoen — APPROVED** [review]
