### PR TITLE
fix(Select): improve type consistency in `onSelect`

### LINKED ISSUE #11361: SelectOption.value and Select.selected has "any" type, but Select.onSelect has "(..., string | number)"
When looking at the `SelectOption.value` and `Select.selected` properties, I got the impression that one can use any JavaScript value to identify select options, and it indeed works as expected.

But it doesn't type-check: The `Select.onSelect` property wants a function that takes `string | number`. I had expected it to also use `any`.

We have our own variant of your SimpleSelect template, and we would like to make it generic in the type of the option value. This seems to work, except for this little niggle about the type of `Select.onSelect`.

### PR DESCRIPTION
**Pull request by logonoff**
**What**: Closes #11361

Non-breaking change to loosen the expected type of `onSelect`'s `value` parameter, to match `SelectOptionProps`

**Additional issues**:

This PR wold allow for the removal of a bunch of `ts-expect-error`s I added in openshift/console#14783

### CODE REVIEW

**Review by wise-king-sullyman — COMMENTED** [review]
Would this be a breaking change? If consumers are expecting that their onSelect callback will be only a string or number and have logic/typing set up to only handle those types would this result in errors?

**Comment by logonoff** [comment]
> Would this be a breaking change? If consumers are expecting that their onSelect callback will be only a string or number and have logic/typing set up to only handle those types would this result in errors?

Since this is loosening a type, nothing should break as users of the callback can continue to use only strings or numbers as before

File: packages/react-core/src/components/Select/Select.tsx [hunk 1]
```diff
@@ -56,7 +57,7 @@ export interface SelectProps extends MenuProps, OUIAProps {
   /** @beta Flag indicating the first menu item should be focused after opening the menu. */
   shouldFocusFirstItemOnOpen?: boolean;
   /** Function callback when user selects an option. */
-  onSelect?: (event?: React.MouseEvent<Element, MouseEvent>, value?: string | number) => void;
+  onSelect?: (event?: React.MouseEvent<Element, MouseEvent>, value?: SelectOptionProps['value']) => void;
```
Comment (kmcfaul) [inline packages/react-core/src/components/Select/Select.tsx:38]: Menu's `onSelect` should also be updated to reference `MenuItem`'s `itemId`.

**Review by thatblindgeye — APPROVED** [review]
