### PR TITLE
fix(NumberInput): make allowEmptyInput an opt-in prop

### LINKED ISSUE #8462: NumberInput - allow empty input should be an opt-in prop
To prevent potential breaking changes.

### PR DESCRIPTION
**Pull request by gitdallas**
**What**: Closes #8462

### CODE REVIEW

File: packages/react-core/src/components/NumberInput/NumberInput.tsx [hunk 1]
```diff
@@ -51,6 +51,8 @@ export interface NumberInputProps extends React.HTMLProps<HTMLDivElement> {
   minusBtnProps?: ButtonProps;
   /** Additional properties added to the plus button */
   plusBtnProps?: ButtonProps;
+  /** Allow the user to clear out the input to an empty string (recommended) */
+  allowEmptyInput?: boolean;
```
Comment (thatblindgeye) [inline packages/react-core/src/components/NumberInput/NumberInput.tsx:55]: Should this be marked as beta?

**Review by thatblindgeye — APPROVED** [review]
Had a quick question below, but otherwise looks good!

File: packages/react-core/src/components/NumberInput/NumberInput.tsx (hunk 1 above)
Comment (gitdallas) [reply packages/react-core/src/components/NumberInput/NumberInput.tsx:55]: perhaps.. or maybe even deprecated as I believe we intend to remove it in v5 and have it as the default behavior.

@tlabaj or @nicolethoen input?

Comment (tlabaj) [reply packages/react-core/src/components/NumberInput/NumberInput.tsx:55]: I do not think deprecating it would be technically correct here especially since it is the recommend approach.  We could mark it beta... But I actually don't think it is worthwhile since we will remove it with v5 and this is the last v4 release we have planned.

Comment (nicolethoen) [reply packages/react-core/src/components/NumberInput/NumberInput.tsx:55]: We should open up a follow up issue to track. All the work on the main branch will be merged back into the v5 branch at the end of the milestone.

Comment (gitdallas) [reply packages/react-core/src/components/NumberInput/NumberInput.tsx:55]: Opened an issue: https://github.com/patternfly/patternfly-react/issues/8526

**Review by nicolethoen — APPROVED** [review]

**Review by tlabaj — APPROVED** [review]
LGTM
