### PR TITLE
fix(table): Add optional types for table column

### LINKED ISSUE #1463: Table - column configs should have optional typescript types
I noted while reviewing [Facet](https://github.com/metalkube/facet) that column configs should be optionally defined when passing transforms, cellTransforms, formatters, and cellFormatters.

https://github.com/metalkube/facet/blob/master/src/components/HostsTable.tsx#L25

### PR DESCRIPTION
**Pull request by jcaianirh**
fix #1463

**What**: column configs now optionally defined for transforms, cellTransforms, formatters, and cellFormatters

**Additional issues**:

### CODE REVIEW

File: packages/patternfly-4/react-table/src/components/Table/Table.d.ts [hunk 1]
```diff
@@ -60,10 +60,10 @@ export interface ISeparator {
 
 export interface ICell {
   title: String;
-  transfroms: Array<Function>;
-  cellTransforms: Array<Function>;
-  formatters: Array<Function>;
-  cellFormatters: Array<Function>;
+  transfroms?: Array<Function>;
```
Comment (karangarg45) [inline packages/patternfly-4/react-table/src/components/Table/Table.d.ts]: shouldn't it be `transforms` ?

Comment (dgutride) [reply packages/patternfly-4/react-table/src/components/Table/Table.d.ts]: the existing property was named transfroms - we should probably fix the naming as part of this breaking change right now

Comment (redallen) [reply packages/patternfly-4/react-table/src/components/Table/Table.d.ts]: Fixed it!
