### PR TITLE
Topology updates found necessary for Console topology upgrade

### LINKED ISSUE #7094: Provide padding settings for determination if topology nodes that are off screen are rendered.
**Describe the issue. What is the expected and unexpected behavior?**

When determining if nodes are in view and redrawn, there should be a padding allowed so that when panning nodes slightly off screen can be pre-drawn so they don't need rendering while panning making for a smoother experience. Also, for labels on nodes, icons (react nodes)should be allowed as well as images.

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Enhancement

**What is your product and what release version are you targeting?**
OpenShift Console 4.11

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
**What**:  Closes #7094

**Additional issues**:
Allows icons (react nodes) to be used for the icons shown in node labels.
Fixes default node/edge components to not require parameters that should be optional.
Adds hover styling for terminals that can be dragged.

### CODE REVIEW

**Comment by nicolethoen** [comment]
Is this still a WIP? Or ready for review?

**Comment by jeff-phillips-18** [comment]
This is ready, missed the `Save` button before :(

**Comment by jeff-phillips-18** [comment]
Update to edge styles for selected and hover states:

image

**Comment by jeff-phillips-18** [comment]
Updated node decorator locations:

image

**Comment by jeff-phillips-18** [comment]
@nicolethoen @tlabaj @christianvogt This is ready for final reviews. Thanks!

File: packages/react-topology/src/Visualization.ts [hunk 1]
```diff
@@ -28,6 +29,25 @@ export class Visualization extends Stateful implements Controller {
...
+
+  @observable.ref
+  private viewPaddingSettings: ViewPaddingSettings = {
+    paddingPercentage: 50
+  };
+
+  @computed
+  private get viewPadding(): number {
+    if (this.viewPaddingSettings.paddingPercentage) {
+      const { width: viewWidth, height: viewHeight } = this.graph.getBounds();
```
Comment (christianvogt) [inline packages/react-topology/src/Visualization.ts:43]: `this.graph` may be `undefined`

File: packages/react-topology/src/Visualization.ts [hunk 2]
```diff
@@ -28,6 +29,25 @@ export class Visualization extends Stateful implements Controller {
...
+  private viewConstraintsEnabled: boolean = true;
+
+  @observable.ref
+  private viewPaddingSettings: ViewPaddingSettings = {
+    paddingPercentage: 50
+  };
+
+  @computed
+  private get viewPadding(): number {
+    if (this.viewPaddingSettings.paddingPercentage) {
```
Comment (christianvogt) [inline packages/react-topology/src/Visualization.ts:42]: nit (to reduce observable touches)
```suggestion
    const { padding, paddingPercentage } = this.viewPaddingSettings;
    if (paddingPercentage) {
```

File: packages/react-topology/src/components/edges/terminals/DefaultConnectorTerminal.tsx [hunk 3]
```diff
@@ -59,6 +59,9 @@ const DefaultConnectorTerminal: React.FC<EdgeConnectorArrowProps> = ({
     default:
       return null;
   }
+  if (!Terminal) {
+    return null;
+  }
```
Comment (christianvogt) [inline packages/react-topology/src/components/edges/terminals/DefaultConnectorTerminal.tsx:64]: Do this check as early as possible in this function.

File: packages/react-topology/src/types.ts [hunk 4]
```diff
@@ -142,6 +142,18 @@ export interface ScaleDetailsThresholds {
   medium: number;
 }
 
+type Never<Type> = { [K in keyof Type]?: never };
+type EitherNotBoth<TypeA, TypeB> = (TypeA & Never<TypeB>) | (TypeB & Never<TypeA>);
+
+interface ViewPaddingPixels {
+  padding: number; // Set this to Number.POSITIVE_INFINITY to bypass the checks
```
Comment (christianvogt) [inline packages/react-topology/src/types.ts:149]: This comment `// Set this to Number.POSITIVE_INFINITY to bypass the checks` is no longer relevant correct?

**Review by tlabaj — COMMENTED** [review]
LGTM.

**Comment by christianvogt** [comment]
/lgtm

edge hover and selected edge hover states need to be addressed as there's no difference between them

**Review by tlabaj — APPROVED** [review]

File: packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/components/StyleNode.tsx [hunk 5]
```diff
@@ -32,7 +32,7 @@ const ICON_PADDING = 20;
 type StyleNodeProps = {
   element: Node;
   getCustomShape?: (node: Node) => React.FC<ShapeProps>;
-  getShapeDecoratorCenter?: (quadrant: TopologyQuadrant, node: Node, radius?: number) => { x: number; y: number };
+  getShapeDecoratorCenter?: (quadrant: TopologyQuadrant, node: Node) => { x: number; y: number };
```
Comment (nicolethoen) [inline packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/components/StyleNode.tsx:35]: Is it possible this is a change that could break some products?

File: packages/react-topology/src/components/groups/DefaultGroupExpanded.tsx [hunk 6]
```diff
@@ -61,14 +69,15 @@ export function computeLabelLocation(points: PointWithSize[]): PointWithSize {
...
+  className,
   element,
   collapsible,
   selected,
   onSelect,
   hover,
   label,
   secondaryLabel,
-  showLabel,
+  showLabel = true,
```
Comment (nicolethoen) [inline packages/react-topology/src/components/groups/DefaultGroupExpanded.tsx:80]: is this changing a default behavior? Could that be unwelcome/breaking for some products

Comment (jeff-phillips-18) [reply packages/react-topology/src/components/groups/DefaultGroupExpanded.tsx:80]: Previous change changed it so this should be fixing anything that got inadvertently changed before.

File: packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/components/StyleNode.tsx (hunk 5 above)
Comment (jeff-phillips-18) [reply packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/components/StyleNode.tsx:35]: I don't think so, tit wasn't being used at all so I can't see why anyone would have passed it. If they did, it will be caught at compile time so shouldn't be a big issue.

**Review by nicolethoen — APPROVED** [review]
