### PR TITLE
fix(loginForm): adds autoFocus to username input

### LINKED ISSUE #1954: Expose Refs to Input Fields to Allow Focusing
Related Issue: https://github.com/patternfly/patternfly-react/issues/816

I would like to autofocus the username input on the Login form, but currently this is not a supported feature. Without access to refs, the only solution around this is to manipulate the actual DOM.

### PR DESCRIPTION
**Pull request by jenny-s51**
Closes #1954.

### CODE REVIEW

File: packages/patternfly-4/react-core/src/components/LoginPage/LoginForm.tsx [hunk 1]
```diff
@@ -71,7 +71,7 @@ export const LoginForm: React.FunctionComponent<LoginFormProps> = ({
       {helperText}
     </FormHelperText>
     <FormGroup label={usernameLabel} isRequired isValid={isValidUsername} fieldId="pf-login-username-id">
-      <TextInput
+      <TextInput autoFocus
```
Comment (redallen) [inline packages/patternfly-4/react-core/src/components/LoginPage/LoginForm.tsx]: Can we add a `noFocus` prop in case a consumer doesn't want this new behaviour? Otherwise, nice find!!!
