### PR TITLE
fix(Toolbar filter): Fixed null exception in Toolbar filter

### LINKED ISSUE #12267: Regression - [ToolbarFilter] - [chipGroupContentRef.current is null] #10857
**Describe the problem**
[Original bug](https://github.com/patternfly/patternfly-react/issues/10857)[
Original fix](https://github.com/patternfly/patternfly-react/pull/11227)
[Commit that reintroduced the bug ](https://github.com/patternfly/patternfly-react/commit/4be50c9)

---

**Jira Issue:** [PF-3725](https://redhat.atlassian.net/browse/PF-3725)

### PR DESCRIPTION
**Pull request by tlabaj**
**What**: Closes #12267

## Summary
Fixes a crash in `ToolbarFilter` when label portal targets are missing or not yet mounted ([#12267](https://github.com/patternfly/patternfly-react/issues/12267)).
## Changes
- **Collapsed listed filters:** Portal only when `labelGroupContentRef.current.firstElementChild` resolves to a real node (fixes incorrect `!== null` checks vs `undefined`).
- **Toolbar content consumer:** Use safe access for `labelContainerRef` so default / unset context does not throw on first render.
## Tests
- Added `ToolbarFilter.test.tsx` for default context and `labelGroupContentRef.current === null` while collapsed.

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved ToolbarFilter stability so it no longer errors when internal references are missing or when rendered in different expanded/collapsed states, preventing render-time failures.

* **Tests**
  * Added tests confirming ToolbarFilter renders reliably both inside and outside toolbar contexts and when certain internal conditions are null.

* **Chores**
  * No public API or exported entities were changed.

### CODE REVIEW

**Review by kmcfaul — APPROVED** [review]

File: packages/react-core/src/components/Toolbar/ToolbarFilter.tsx [hunk 1]
```diff
@@ -130,26 +130,29 @@ class ToolbarFilter extends Component<ToolbarFilterProps, ToolbarFilterState> {
     ) : null;
 
     if (!_isExpanded && this.state.isMounted) {
+      const collapsedLabelPortalTarget = labelGroupContentRef?.current?.firstElementChild ?? null;
       return (
         <Fragment>
           {showToolbarItem && <ToolbarItem {...props}>{children}</ToolbarItem>}
-          {labelGroupContentRef?.current?.firstElementChild !== null &&
-            ReactDOM.createPortal(labelGroup, labelGroupContentRef.current.firstElementChild)}
+          {collapsedLabelPortalTarget != null && ReactDOM.createPortal(labelGroup, collapsedLabelPortalTarget)}
```
Comment (dlabaj) [inline packages/react-core/src/components/Toolbar/ToolbarFilter.tsx]: Should this be !==

File: packages/react-core/src/components/Toolbar/ToolbarFilter.tsx [hunk 2]
```diff
@@ -130,26 +130,29 @@ class ToolbarFilter extends Component<ToolbarFilterProps, ToolbarFilterState> {
...
-              expandableLabelContainerRef.current &&
-              ReactDOM.createPortal(labelGroup, expandableLabelContainerRef.current)}
-          </Fragment>
-        )}
+        {({ labelContainerRef }) => {
+          const labelContainer = labelContainerRef?.current ?? null;
+          return (
+            <Fragment>
+              {showToolbarItem && <ToolbarItem {...props}>{children}</ToolbarItem>}
+              {labelContainer != null && ReactDOM.createPortal(labelGroup, labelContainer)}
```
Comment (dlabaj) [inline packages/react-core/src/components/Toolbar/ToolbarFilter.tsx]: Same here.

**Review by dlabaj — CHANGES_REQUESTED** [review]
One minor comment.

**Review by dlabaj — APPROVED** [review]
