### PR TITLE
fix(table): update v5 to v6 for docs, description list, draggable, Th

### LINKED ISSUE #10904: v5 still used throughout react
v5 is still hard coded into many React files, most frequently in example markdown files in the `cssPrefix` front matter causing the CSS tables not to generate correctly at the bottom of those react docs pages, but also used within some component code such as the Th component where an old v5 screen reader class is applied, causing the screen reader text content to be visible on the page:

https://github.com/patternfly/patternfly-react/blob/v6/packages/react-table/src/components/Table/Th.tsx#L233

### PR DESCRIPTION
**Pull request by evwilkin**
Closes #10904 

This PR replaces `v5` with `v6` for component docs (used in example frontmatter `cssPrefix` for CSS Variables table), adds a handful of these `cssPrefix`es where they were missing to match Core docs, and updates `v5` to `v6` as well as within component code in:
- Description list ([component](https://github.com/patternfly/patternfly-react/pull/10968/files?file-filters%5B%5D=.tsx&show-viewed-files=true#diff-33ae5c9143876589442d4c58c81af6cd0dc9bc627bcf2358cb8da1953737a121R10) & [test](https://github.com/patternfly/patternfly-react/pull/10968/files?file-filters%5B%5D=.tsx&show-viewed-files=true#diff-c67f347b8997b3189704c0172b831a770011f984efb42ef07fa8e931c91d4caa))
- [Draggable](https://github.com/patternfly/patternfly-react/pull/10968/files?file-filters%5B%5D=.tsx&show-viewed-files=true#diff-ca0ef75b36cf6b33f56b9cadde8b046814933154d0bda2358f0d4434da5ec9edR7)
- [Th](https://github.com/patternfly/patternfly-react/pull/10968/files?file-filters%5B%5D=.tsx&show-viewed-files=true#diff-6e8015d83ce8730186ed92aa1aff27a224df98b4412488a90487793f83d9d8d6R233)

### CODE REVIEW

File: packages/react-core/src/components/DescriptionList/DescriptionList.tsx [hunk 1]
```diff
@@ -7,7 +7,7 @@ import cssGridTemplateColumnsMin from '@patternfly/react-tokens/dist/esm/c_descr
 import cssHorizontalTermWidth from '@patternfly/react-tokens/dist/esm/c_description_list_m_horizontal__term_width';
 
 const cssTermWidth = {
-  name: '--pf-v5-c-description-list__term-width'
+  name: '--pf-v6-c-description-list__term-width'
```
Comment (tlabaj) [inline packages/react-core/src/components/DescriptionList/DescriptionList.tsx:10]: can we reference the object here.
e.g. `\`${styles.descriptionList}___term-width\``
that way we will not have to update it manually next major release.

File: packages/react-core/src/demos/ProgressStepperDemo.md [hunk 2]
```diff
@@ -45,7 +45,7 @@ ProgressStepperDemo = () => {
         <br />
       </StackItem>
       <StackItem>
-        <div className="pf-v5-screen-reader" aria-live="polite">
+        <div className="pf-v6-screen-reader" aria-live="polite">
```
Comment (tlabaj) [inline packages/react-core/src/demos/ProgressStepperDemo.md:48]: There is an object defined for this in the `@patternfly/react-styles/css/utilities/Accessibility`
If you don't update it in your PR, that is ok because I have an [issue](https://github.com/patternfly/patternfly-react/issues/10955) open to update this throughout the code base.

File: packages/react-core/src/deprecated/components/DragDrop/Draggable.tsx [hunk 3]
```diff
@@ -4,7 +4,7 @@ import styles from '@patternfly/react-styles/css/components/DragDrop/drag-drop';
 import { DroppableContext } from './DroppableContext';
 import { DragDropContext } from './DragDrop';
 // import cssDraggingBackgroundColor from '@patternfly/react-tokens/dist/esm/c_draggable_m_dragging_BackgroundColor';
-const cssDraggingBackgroundColor = { name: '--pf-v5-c-draggable--m-dragging--BackgroundColor' };
+const cssDraggingBackgroundColor = { name: '--pf-v6-c-draggable--m-dragging--BackgroundColor' };
```
Comment (tlabaj) [inline packages/react-core/src/deprecated/components/DragDrop/Draggable.tsx:7]: sme comment here about referencing the object.

**Review by tlabaj — CHANGES_REQUESTED** [review]

File: packages/react-core/src/components/DescriptionList/__tests__/DescriptionList.test.tsx [hunk 4]
```diff
@@ -137,7 +137,7 @@ test(`Renders style when isHorizontal and horizontalTermWidthModifier is set`, (
 test.skip(`Renders style when termWidth is set`, () => {
   render(<DescriptionList aria-label="list" isHorizontal termWidth="30px" />);
   expect(screen.getByLabelText('list')).toHaveStyle({
-    '--pf-v5-c-description-list__term--width': '30px'
+    '--pf-v6-c-description-list__term--width': '30px'
```
Comment (thatblindgeye) [inline packages/react-core/src/components/DescriptionList/__tests__/DescriptionList.test.tsx:140]: Same as Titani's comments above, we can use the styles object here instead of hardcoding

File: packages/react-core/src/components/DescriptionList/__tests__/DescriptionList.test.tsx [hunk 5]
```diff
@@ -124,21 +124,21 @@ test(`Renders style when isHorizontal and horizontalTermWidthModifier is set`, (
...
-    '--pf-v6-c-description-list--m-horizontal__term--width-on-xl': '30ch',
-    '--pf-v6-c-description-list--m-horizontal__term--width-on-2xl': '35ch'
-  });
+  const listStyles = {};
+  listStyles[`--${styles.descriptionList}--m-horizontal__term--width`] = '12ch';
+  listStyles[`--${styles.descriptionList}--m-horizontal__term--width-on-sm`] = '15ch';
+  listStyles[`--${styles.descriptionList}--m-horizontal__term--width-on-md`] = '20ch';
+  listStyles[`--${styles.descriptionList}--m-horizontal__term--width-on-lg`] = '28ch';
+  listStyles[`--${styles.descriptionList}--m-horizontal__term--width-on-xl`] = '30ch';
+  listStyles[`--${styles.descriptionList}--m-horizontal__term--width-on-2x`] = '35ch';
```
Comment (thatblindgeye) [inline packages/react-core/src/components/DescriptionList/__tests__/DescriptionList.test.tsx:133]:
```suggestion
  listStyles[`--${styles.descriptionList}--m-horizontal__term--width-on-2xl`] = '35ch';
```

**Review by thatblindgeye — APPROVED** [review]
