### PR TITLE
fix(DatePicker): updated logic for parsing and focus management

### LINKED ISSUE #9721: Bug - [DatePicker] - [JavaScript error thrown when an invalid date is given]
**Describe the problem**

In Cockpit we have a test where we enter an invalid date into the date picker which leads to no date being selected when opening the datePicker:

image

When I add a breakpoint to the line above of where the exception happens, I noticed the focusTrap basically tries to execute

```
document.querySelector('.pf-v5-c-calendar-month__dates-cell.pf-m-selected'); 
```
Which returns null.

I've found out that reverting [this commit](https://github.com/patternfly/patternfly-react/commit/3707ffb2d8) no longer throws a JavaScript error.

**How do you reproduce the problem?**

I've had issues with reproducing the problem in a codesandbox, our [Datepicker usage](https://github.com/cockpit-project/cockpit/blob/main/pkg/lib/serverTime.js#L598) is a bit non-trivial.

**Expected behavior**

A component should never throw an JavaScript exception.

**Is this issue blocking you?**

Currently we have no workaround, except disabling the test for now.

**What is your environment?**
 - OS: Linux
 - Browser chrome
 - Version

### PR DESCRIPTION
**Pull request by thatblindgeye**
**What**: Closes #9721

**Additional issues**:

### CODE REVIEW

File: packages/react-core/src/components/DatePicker/DatePicker.tsx [hunk 1]
```diff
@@ -98,7 +98,7 @@ const DatePickerBase = (
     className,
     locale = undefined,
     dateFormat = yyyyMMddFormat,
-    dateParse = (val: string) => val.split('-').length === 3 && new Date(`${val}T00:00:00`),
+    dateParse = (val: string) => (val.split('-').length === 3 ? new Date(`${val}T00:00:00`) : new Date(undefined)),
```
Comment (thatblindgeye) [inline packages/react-core/src/components/DatePicker/DatePicker.tsx:101]: This resolves the issue mentioned here https://github.com/patternfly/patternfly-react/issues/9721#issuecomment-1752874585 regarding the return type of this prop. This basically just ensures that a Date type is always returned without really changing the outcome (instead of false we just get an invalid date object which should have the same effect).

**Review by nicolethoen — APPROVED** [review]
LGTM :)

File: packages/react-core/src/components/DatePicker/DatePicker.tsx (hunk 1 above)
Comment (mfrances17) [reply packages/react-core/src/components/DatePicker/DatePicker.tsx:101]: this should work fine - i'm approving as is. but i do think the point about forward slashes is valid, and if we don't add it as part of this, it probably makes sense to capture it in another issue.

**Review by mfrances17 — APPROVED** [review]
LGTM
