### PR TITLE
fix(Pagination): default page should be 1

### LINKED ISSUE #9165: Bug - Pagination - Default `page` renders negative first index
**Describe the problem**
When omitting prop `page` (default value is 0) the first index is `(0 - 1) * perPage + 1;` -> `1 - perPage` a negative number.

**How do you reproduce the problem?**
```jsx
<Pagination itemCount={25} />
```

**Expected behavior**
First index should be 0.

**Is this issue blocking you?**
Set `page={1}´.

**Screenshots**
image

**What is your environment?**
`@patternfly/react-core@4.276.8`

**Any other information?**
The existing Pagination snapshots already confirm this bug:
https://github.com/patternfly/patternfly-react/blob/ff94267709508525b7fe8dd1da0b7ea6a33854aa/packages/react-core/src/components/Pagination/__tests__/__snapshots__/Pagination.test.tsx.snap#L2081

### PR DESCRIPTION
**Pull request by MariaAga**
**What**: Closes #9165

I'm not sure why the default is set to 0 here: https://github.com/patternfly/patternfly-react/pull/3383
but users cant type in 0 anyway because of: 
https://github.com/patternfly/patternfly-react/blob/1da6f5e5ad3c3665e0022693a5ce9de2588aa136/packages/react-core/src/components/Pagination/Navigation.tsx#L100

### CODE REVIEW

**Review by gitdallas — APPROVED** [review]
lgtm, wonder if we should add an offset example though

**Review by jenny-s51 — CHANGES_REQUESTED** [review]
@MariaAga this is looking good! Seems like the [indeterminate example](https://patternfly-react-pr-9201.surge.sh/components/pagination/#indeterminate) is now getting set to "1 -20 of 0" but it should be ["1 - 20 of many"](https://patternfly-react-pr-9201.surge.sh/components/pagination/#indeterminate) - can we update this so it sets the toggle text correctly?

**Comment by MariaAga** [comment]
@jenny-s51 I fixed it here: https://github.com/patternfly/patternfly-react/pull/9203

**Review by jenny-s51 — APPROVED** [review]

File: packages/react-core/src/components/Pagination/Pagination.tsx [hunk 1]
```diff
@@ -210,8 +210,8 @@ export const Pagination: React.FunctionComponent<PaginationProps> = ({
     ofWord: 'of'
   },
   firstPage = 1,
-  page: pageProp = 0,
-  offset = 0,
+  page: pageProp = 1,
+  offset = null,
```
Comment (tlabaj) [inline packages/react-core/src/components/Pagination/Pagination.tsx:214]: could this be undefined?

Comment (MariaAga) [reply packages/react-core/src/components/Pagination/Pagination.tsx:214]: Other props in Pagination also have a default value of null like `itemsStart = null,  itemsEnd = null,`
and usually its not recomended to set values to `undefined`

**Review by tlabaj — APPROVED** [review]
Lgtm
