### PR TITLE
fix(login): Add union types for backgroundImgSrc

### LINKED ISSUE #1235: PF4: LoginPage.d.tx: backgroundImgSrc type needs to accept 'string' or BackgroundImageSrcMap
Reported by the Kiali development team:
The Login Component has the attribute backgroundImgSrc to set background images, in LoginPage.d.ts is defined like string and in the storybook the type is

const images = {
 [BackgroundImageSrc.lg]: '/assets/images/pfbg_1200.jpg',
 [BackgroundImageSrc.sm]: '/assets/images/pfbg_768.jpg',
 [BackgroundImageSrc.sm2x]: '/assets/images/pfbg_768@2x.jpg',
 [BackgroundImageSrc.xs]: '/assets/images/pfbg_576.jpg',
 [BackgroundImageSrc.xs2x]: '/assets/images/pfbg_576@2x.jpg',
 [BackgroundImageSrc.filter]: '/assets/images/background-filter.svg#image_overlay'
};

So this show the next error

Type '{ [BackgroundImageSrc.lg]: string; [BackgroundImageSrc.sm]: string; [BackgroundImageSrc.sm2x]: string; [BackgroundImageSrc.xs]: string; [BackgroundImageSrc.xs2x]: string; [BackgroundImageSrc.filter]: string; }' is not assignable to type 'string'.

So is the storybook wrong ? I think that should be type

export const BackgroundImageSrc: {
xs: 'xs';
xs2x: 'xs2x';
sm: 'sm';
sm2x: 'sm2x';
lg: 'lg';
filter: 'filter';
};

Like BackgroundImage
@jschuler reviewed - Typescript issue: the LoginPage.d.ts backgroundImgSrc type should not just be ‘string’, should be ‘string’ or BackgroundImageSrcMap

### PR DESCRIPTION
**Pull request by ibolton336**
**What**:
closes #1235 

**Additional issues**:

### CODE REVIEW

**Comment by ibolton336** [comment]
> Do we have to update the js file...

@dlabaj @tlabaj Good catch - just updated JS types

File: packages/patternfly-4/react-core/src/components/LoginPage/LoginPage.js [hunk 1]
```diff
@@ -25,7 +25,7 @@ const propTypes = {
   /** Additional classes added to the LoginPage. */
   className: PropTypes.string,
   /** Attribute that specifies the URL of the brand image for the LoginPage */
-  brandImgSrc: PropTypes.string,
+  brandImgSrc: PropTypes.oneOfType([PropTypes.string, PropTypes.object]),
```
Comment (jschuler) [inline packages/patternfly-4/react-core/src/components/LoginPage/LoginPage.js]: wrong prop? Should be updating backgroundImgSrc. Also, instead of object would be better to use shape:
```
PropTypes.shape({
      xs: PropTypes.string,
      xs2x: PropTypes.string,
      sm: PropTypes.string,
      sm2x: PropTypes.string,
      lg: PropTypes.string,
      filter: PropTypes.string
    })
```

**Comment by ibolton336** [comment]
Should be all good now @dlabaj @jschuler

**Comment by tlabaj** [comment]
@ibolton336  Can you please rebase again please.  Some changes were made in Master to fix failing Build. Thanks.

**Comment by dlabaj** [comment]
LGTM
