### PR TITLE
fix(Nav): allow RTL scrolling

### LINKED ISSUE #9607: Nav - Horizontal scrolling broken in RTL
Scrolling in [horizontal and tertiary navs](https://patternfly-react-pr-9582.surge.sh/components/navigation#horizontal-subnav) does not work in RTL.

### PR DESCRIPTION
**Pull request by kmcfaul**
**What**: Closes #9607

### CODE REVIEW

**Review by wise-king-sullyman — APPROVED** [review]

**Review by thatblindgeye — APPROVED** [review]

File: packages/react-core/src/components/Nav/NavList.tsx [hunk 1]
```diff
@@ -14,9 +14,9 @@ export interface NavListProps
   children?: React.ReactNode;
   /** Additional classes added to the list */
   className?: string;
-  /** Aria-label for the left scroll button */
+  /** Aria-label for the back scroll button */
```
Comment (tlabaj) [inline packages/react-core/src/components/Nav/NavList.tsx:17]: can you deprecate this and the `ariaRightScroll` prop and add `ariaBackScroll` and `ariaLeftScroll` props.

**Review by tlabaj — CHANGES_REQUESTED** [review]

File: packages/react-core/src/components/Nav/NavList.tsx [hunk 2]
```diff
@@ -14,10 +14,14 @@ export interface NavListProps
   children?: React.ReactNode;
   /** Additional classes added to the list */
   className?: string;
-  /** Aria-label for the left scroll button */
+  /** @deprecated Aria-label for the left scroll button */
```
Comment (tlabaj) [inline packages/react-core/src/components/Nav/NavList.tsx:17]: Can we mention which props to use instead.

**Review by tlabaj — APPROVED** [review]
LGTM
