### PR TITLE
fix(CodeEditor): add resizeobserver to code editor

### LINKED ISSUE #6227: CodeEditor does not respond well to viewport resizes?
Even if i set `width:100%` (which i think is the default anyway), the CodeEditor component does not respond to viewport resizes. When I used monaco-editor directly (in the past), I had to install a `ResizeObserver` to instruct monaco about resizing.

You may also want to allow for users of your component to pass in a resize observer of their own, because they may have subdivided the viewport in other ways.

### PR DESCRIPTION
**Pull request by nicolethoen**
**What**: Closes #6227

This also fixes a type discrepancy in the resizeObserver and chart-resize functions
@dlabrecq, I'd love if you'd make sure I didn't create more problems by fixing the issue I found.

### CODE REVIEW

File: packages/react-charts/src/components/ChartUtils/chart-resize.tsx [hunk 1]
```diff
@@ -57,17 +56,17 @@ import { canUseDOM } from './chart-helpers';
  *   );
  * }
  *
- * @param {React.RefObject} containerRef The container reference to observe
+ * @param {Element} containerRefElement The container reference to observe
  * @param {Function} handleResize The function to call for resize events
  * @return {Function} The function used to unobserve resize events
  */
-export const getResizeObserver = (containerRef: React.RefObject<any>, handleResize: () => void) => {
+export const getResizeObserver = (containerRefElement: Element, handleResize: () => void) => {
```
Comment (dlabrecq) [inline packages/react-charts/src/components/ChartUtils/chart-resize.tsx:63]: I don't believe `Element` is the correct type (too restrictive) as this can be any `RefObject`. I see that the code editor is using `React.createRef<HTMLDivElement>();`, which is what the chart examples use. 

What was the type issue?

**Review by dlabrecq — CHANGES_REQUESTED** [review]

**Review by dlabrecq — APPROVED** [review]
After some digging, I believe the `Element` type is ok. We're using `HTMLDivElement` with the `getResizeObserver` in Cost Management.

File: packages/react-charts/src/components/ChartUtils/chart-resize.tsx [hunk 2]
```diff
@@ -38,7 +37,7 @@ import { canUseDOM } from './chart-helpers';
  * private observer: any = () => {};
  *
  * public componentDidMount() {
- *   this.observer = getResizeObserver(this.inputRef.current, this.handleResize);
+ *   this.observer = getResizeObserver(this.inputRef, this.handleResize);
```
Comment (dlabrecq) [inline packages/react-charts/src/components/ChartUtils/chart-resize.tsx:40]: In the examples, we're using `this.containerRef.current`

this.observer = getResizeObserver(this.containerRef.current, this.handleResize);

**Review by dlabrecq — CHANGES_REQUESTED** [review]

File: packages/react-charts/src/components/ChartUtils/chart-resize.tsx (hunk 2 above)
Comment (dlabrecq) [reply packages/react-charts/src/components/ChartUtils/chart-resize.tsx:40]: The code editor also uses 
`this.observer = getResizeObserver(this.ref.current, this.handleResize);`

File: packages/react-core/src/helpers/resizeObserver.tsx [hunk 3]
```diff
@@ -38,7 +37,7 @@ import { canUseDOM } from './util';
  * private observer: any = () => {};
  *
  * public componentDidMount() {
- *   this.observer = getResizeObserver(this.inputRef.current, this.handleResize);
+ *   this.observer = getResizeObserver(this.inputRef, this.handleResize);
```
Comment (dlabrecq) [inline packages/react-core/src/helpers/resizeObserver.tsx:40]: The example should use `this.inputRef.current`

File: packages/react-charts/src/components/ChartUtils/chart-resize.tsx (hunk 2 above)
Comment (nicolethoen) [reply packages/react-charts/src/components/ChartUtils/chart-resize.tsx:40]: oh - oops - i was getting turned around. At one point i tried to keep the getResizeObverver types the same, and these changes would be appropriate, but instead I changed the param types, so I should have reverted these comments.

**Review by dlabrecq — APPROVED** [review]

**Review by tlabaj — APPROVED** [review]
