### PR TITLE
fix(Truncate): remove resize observer

### LINKED ISSUE #10974: Bug - [Truncate] - remove resize observer
**Describe the problem**

I don’t believe there’s need for the `Truncate` component to be calculating whether or not to include the tooltip upfront or even on resize. The tooltip is only shown either on mouse over or on focus. Therefore it should be possible to remove the resize observer.

Furthermore, this component unmounts the children whenever the truncation state changes instead of simply marking the tooltip as hidden.

It would seem to me that a lot of performance could be gained here if a page contains many `Truncate` components susceptible to resizing.

**How do you reproduce the problem?**
Visit https://www.patternfly.org/components/truncate#default
Using inspector dev tools, to track react component re-renders.
Drag the bounding box of the truncated text such that all the text is shown and then back to truncated.

Observe the component remounts every time the threshold is met.

**Expected behavior**
Unless the content changes, the component shouldn't remount.

**Is this issue blocking you?**
No

**What is your environment?**
 - OS: mac
 - Browser chrome
 - Version 127

**What is your product and what release date are you targeting?**
RHOAI

**Any other information?**

### PR DESCRIPTION
**Pull request by gitdallas**
**What**: Closes #10974

### CODE REVIEW

**Comment by rebeccaalpert** [comment]
I'd want to make sure that https://github.com/patternfly/patternfly-react/issues/11811 still works - noting this down so I don't forget when I come back to review this.

**Comment by gitdallas** [comment]
@thatblindgeye - looks like i can set isTruncated to `false` originally and then it seems to work initially, however it won't update if something is resized.. maybe that doesn't matter as much as the performance? because i'm not sure if there is a better way to do this without adding the resizeObserver back

**Comment by thatblindgeye** [comment]
> looks like i can set isTruncated to false originally and then it seems to work initially, however it won't update if something is resized.. maybe that doesn't matter as much as the performance? because i'm not sure if there is a better way to do this without adding the resizeObserver back

I think both are important, though I don't know which (if either) is more important. That's probably a lengthier discussion. 

@christianvogt for your use case, are you taking advantage of the resizability of the Truncate component, i.e. whether the content is actually truncated or not can change depending on the viewport width or the content can be of varying length? Or is it pretty reliable that wherever Truncate is being used things will always be Truncated or always not be Truncated (like in a Table column that is always fairly narrow)?

Mainly asking because if it's the latter - and assuming using the maxCharsDisplayed prop isn't viable - I wonder if adding a prop to dictate whether the resize observer is even used would be useful (or debouncing the resize observer).

**Comment by christianvogt** [comment]
I believe when I created the original issue it was because the component was unmounting and remounting needlessly. Secondary after looking into the code I made the comment about performance and the potential to omit the resize handler. However I didn't consider the tab index case. 

For our use case I would still like the text react to container size.

File: packages/react-core/src/components/Truncate/Truncate.tsx [hunk 1]
```diff
@@ -2,8 +2,8 @@ import { Fragment, useEffect, useRef, useState, forwardRef, useImperativeHandle
 import styles from '@patternfly/react-styles/css/components/Truncate/truncate';
 import { css } from '@patternfly/react-styles';
 import { Tooltip, TooltipPosition, TooltipProps } from '../Tooltip';
-import { getReferenceElement } from '../../helpers';
```
Comment (thatblindgeye) [inline packages/react-core/src/components/Truncate/Truncate.tsx:5]: There's some logic involving this and the `subParentRef` that upon being removed looks to have broken the [truncated Clipboard copy example](https://pf-react-pr-12055.surge.sh/components/clipboard-copy#inline-compact-with-truncation), the truncated text no longer triggers the tooltip on focus now.

**Comment by rebeccaalpert** [comment]
Looks like https://github.com/patternfly/patternfly-react/issues/11811 still works, woo!

File: packages/react-core/src/components/Truncate/__tests__/Truncate.test.tsx [hunk 2]
```diff
@@ -242,3 +242,21 @@ describe('Truncation with maxCharsDisplayed', () => {
...
+
+  render(
+    <Truncate
+      content="This is a very long piece of content that should be truncated when the container is too small"
+      tooltipProps={{ triggerRef: mockTriggerRef }}
+    />
+  );
+
+  // Simulate keyboard focus on the external trigger element
+  fireEvent.focus(mockTriggerRef.current);
```
Comment (thatblindgeye) [inline packages/react-core/src/components/Truncate/__tests__/Truncate.test.tsx:257]: Could we instead import `userEvent` and utilize that to handle the focusing in this test?

Comment (gitdallas) [reply packages/react-core/src/components/Truncate/__tests__/Truncate.test.tsx:257]: i think `fireEvent` might actually be right here as it's how it would come into the Truncate component, rather than being a full integration test. currently the mockTriggerRef isn't actually rendered as part of the DOM to tab to. could update the .current and check, but now i'm thinking maybe that would be better tested in the clipboardcopy

Comment (thatblindgeye) [reply packages/react-core/src/components/Truncate/__tests__/Truncate.test.tsx:257]: Yeah maybe worth trying to see if wew can put this sort of test in ClipboardCopy, though having it live in Truncate could make sense if we were ever to use it in other components in the same way we are in ClipboardCopy. 

Not a blocker for me, otherwise things lgtm here

**Comment by gitdallas** [comment]
@thatblindgeye added a clipboardcopy/truncate integration test.. separate file as i was having trouble not using the mock in the existing 😆

File: packages/react-core/src/components/ClipboardCopy/__tests__/ClipboardCopyTruncateIntegration.test.tsx [hunk 3]
```diff
@@ -0,0 +1,34 @@
+import { render, screen } from '@testing-library/react';
+import userEvent from '@testing-library/user-event';
+import { ClipboardCopy, ClipboardCopyVariant } from '../ClipboardCopy';
+
+// This test file uses the real Truncate component for integration testing, instead of a mock
+
+describe('ClipboardCopy Truncate Integration', () => {
```
Comment (wise-king-sullyman) [inline packages/react-core/src/components/ClipboardCopy/__tests__/ClipboardCopyTruncateIntegration.test.tsx]: Nit: It feels weird to wrap a single test in a describe block?

File: packages/react-core/src/components/ClipboardCopy/__tests__/ClipboardCopyTruncateIntegration.test.tsx [hunk 4]
```diff
@@ -0,0 +1,34 @@
+import { render, screen } from '@testing-library/react';
+import userEvent from '@testing-library/user-event';
+import { ClipboardCopy, ClipboardCopyVariant } from '../ClipboardCopy';
+
+// This test file uses the real Truncate component for integration testing, instead of a mock
```
Comment (wise-king-sullyman) [inline packages/react-core/src/components/ClipboardCopy/__tests__/ClipboardCopyTruncateIntegration.test.tsx:5]: It also feels weird in general having this test of ClipboardCopy integration for a change that we're making in Truncate 🤔 

That being said I don't _dislike_ this test, and I don't know better way of doing it after some quick poking around, so I won't block over it.
