### PR TITLE
fix(Banner): add screen reader text

### LINKED ISSUE #5890: Banner examples need screen reader text/label indicating the context
**Describe the issue. What is the expected and unexpected behavior?**
The banner component uses color to communicate information/context to users. This information/context is not given to screen reader users who cannot see the color. Since we allow users to add any different types of context (for example, Gov't systems uses these to indicate whether the information on a page is classified or not), we should at least provide an example in which the context is provided through a label or screen reader text.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
Go to the [banner documentation](https://www.patternfly.org/v4/components/banner) and notice that the colors can potentially indicate state such as success, danger, etc. 

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Example bug

### PR DESCRIPTION
**Pull request by bartoval**
**What**: Closes #5890

### CODE REVIEW

File: packages/react-core/src/components/Banner/Banner.tsx [hunk 1]
```diff
@@ -11,12 +11,15 @@ export interface BannerProps extends React.HTMLProps<HTMLDivElement> {
   variant?: 'default' | 'info' | 'danger' | 'success' | 'warning';
   /** If set to true, the banner sticks to the top of its container */
   isSticky?: boolean;
+  /** Text announced by screen reader when variant is set to indicate the type of banner*/
+  screenReaderText?: string;
```
Comment (thatblindgeye) [inline packages/react-core/src/components/Banner/Banner.tsx:15]: Thinking some slight tweaking of the prop description could be done here, since the variant will always be set and to mention what the default is:

"Text announced by screen readers to indicate the type of banner. Defaults to `${variant} banner` if this prop is not passed in.".

**Review by thatblindgeye — COMMENTED** [review]
Looks good! Just had a small suggestion/comment below, let me know what you think.

File: packages/react-core/src/components/Banner/Banner.tsx (hunk 1 above)
Comment (bartoval) [reply packages/react-core/src/components/Banner/Banner.tsx]: Thanks!
Now it's more clear 👍🏼

**Review by thatblindgeye — APPROVED** [review]

**Review by jessiehuff — APPROVED** [review]
LGTM! Thanks! 🙂

File: packages/react-core/src/components/Banner/Banner.tsx [hunk 2]
```diff
@@ -11,12 +11,15 @@ export interface BannerProps extends React.HTMLProps<HTMLDivElement> {
   variant?: 'default' | 'info' | 'danger' | 'success' | 'warning';
   /** If set to true, the banner sticks to the top of its container */
   isSticky?: boolean;
+  /** Text announced by screen readers to indicate the type of banner. Defaults to ${variant} banner if this prop is not passed in */
```
Comment (tlabaj) [inline packages/react-core/src/components/Banner/Banner.tsx:14]: Nit
```suggestion
  /** Text announced by screen readers to indicate the type of banner. Defaults to "${variant} banner" if this prop is not passed in */
```

**Review by tlabaj — COMMENTED** [review]
Looks great!  Just one little nit.

**Review by tlabaj — APPROVED** [review]
