### PR TITLE
fix(LoginPage): allow brand props passthrough make brand optional

### LINKED ISSUE #11970: Bug - LoginPage - Brand does not allow props passage down
**Describe the problem**
Guillaume Moutier reports that he wants to make the brand bigger on the login page. While Brand does allow you to pass heights and widths, the LoginPage does not allow props passage to the Brand component it specifies: https://github.com/patternfly/patternfly-react/blob/main/packages/react-core/src/components/LoginPage/LoginPage.tsx#L68

**How do you reproduce the problem?**
Look at https://github.com/patternfly/patternfly-react/blob/main/packages/react-core/src/components/LoginPage/LoginPage.tsx#L68. No props can be passed to Brand except the defined ones.

**Expected behavior**
Allow props passage down to Brand.

**Is this issue blocking you?**
Advised consumer he can probably use CSS instead.

---

**Jira Issue:** [PF-2561](https://issues.redhat.com/browse/PF-2561)

### LINKED ISSUE #11984: Bug - LoginPage - Brand is always created even if optional attributes empty
**Describe the problem**
brandImgSrc and brandImgAlt are marked as optional LoginPage props, but the Brand component gets created anyway: https://github.com/patternfly/patternfly-react/blob/main/packages/react-core/src/components/LoginPage/LoginPage.tsx#L68

Brent Dunn reported on PatternFly Slack that "An empty string ("") was passed to the src attribute" was being logged when these are omitted: https://codesandbox.io/p/devbox/dreamy-fog-qrqy95 

**How do you reproduce the problem?**
https://codesandbox.io/p/devbox/dreamy-fog-qrqy95 

**Expected behavior**
Optional props should optionally render component.

**Is this issue blocking you?**
Not urgent

**What is your product and what release date are you targeting?**
Not urgent

### PR DESCRIPTION
**Pull request by fallmo**
#### Changes:
- Allow LoginPage consumers to pass BrandProps and forward them to the brand image. (Closes #11970)
- Avoid rendering the Brand when brand props are not provided. (Closes #11984)

## Summary by CodeRabbit

* **New Features**
  * Login page accepts a new brandImgProps object for extended brand image attributes (src, alt, class, aria-*); brand only displays when an image source or image props are provided, and brandImgProps takes precedence when both are supplied.

* **Tests**
  * Added tests for brand rendering, attribute handling, and precedence behavior.

* **Documentation**
  * Example docs updated to demonstrate brandImgProps usage.

### CODE REVIEW

**Review by thatblindgeye — COMMENTED** [review]
LGTM! Similar to a comment I left on your Tabs PR, but would you feel comfortable adding some unit tests for these changes?

**Comment by fallmo** [comment]
> LGTM! Similar to a comment I left on your Tabs PR, but would you feel comfortable adding some unit tests for these changes?

Yes, certainly

**Review by nicolethoen — APPROVED** [review]

**Comment by fallmo** [comment]
Hi @thatblindgeye , just following up. Is there anything else you’d like me to change? Thanks!

File: packages/react-core/src/components/LoginPage/examples/LoginPageBasic.tsx [hunk 1]
```diff
@@ -114,8 +114,7 @@ export const SimpleLoginPage: React.FunctionComponent = () => {
   return (
     <LoginPage
       footerListVariants={ListVariant.inline}
-      brandImgSrc={brandImg}
-      brandImgAlt="PatternFly logo"
+      brandImgProps={{ src: brandImg, alt: 'PatternFly logo', className: 'pf-m-hover' }}
```
Comment (thatblindgeye) [inline packages/react-core/src/components/LoginPage/examples/LoginPageBasic.tsx]:
```suggestion
      brandImgProps={{ src: brandImg, alt: 'PatternFly logo' }}
```

**Review by thatblindgeye — APPROVED** [review]
