### PR TITLE
feat(Select): add examples, add popper interface, fix focus

### LINKED ISSUE #8874: Select - enhance the examples available on the newly promoted Select Next implementation
In order to better show parity between the new/next Select that is being promoted for PatternFly 5, we should enhance the examples available. My recommendations are as follows:

- For "Single" example, allow ability to add an icon and show as disabled as in the old Select component.
- For "Checkbox" example, allow for adding an optional badge to the toggle as in https://patternfly-react-pr-8825.surge.sh/components/menus/select/react-deprecated#checkbox-select-with-custom-badge 
- For Typeahead, it would be useful to include some, if not all of the options that are demonstrated in the old Select examples:
Screenshot 2023-03-28 at 2 16 34 PM

We should also include documentation of these examples as well as an explanation that deprecated examples not seen here can be constructed using a composable approach. I can open a separate issue for that. Perhaps additional demos should be added to cover some of these cases (at least the most common ones)?

### PR DESCRIPTION
**Pull request by kmcfaul**
**What**: Closes #8874

Updates examples in Select:
- adds disabled state checkbox to basic example
- adds divider to select group

Adds examples to Select:
- option variation example
- view more example
- creatable typeahead example
- creatable multitypeahead example
- checkbox multitypeahead example

Other changes:
- Adds footer example to menu examples.
- Adds blurb over props pointing to Menu documentation for additional props, and adds commonly used props directly to the Select props.
- Adds an interface that includes commonly used popper props for select and included the interface in the docs.
- Fixes a description spelling mistake in menu.
- Forwards ref through SelectOption to enable view more

Addressing #8985
- Fixes the toggle focus with Esc/Tab - added a preventDefault that was interfering with Tab
- Adds toggle ref to the selection callback to allow a user to focus the toggle after a selection (since the toggle ref is not controlled or set by the user). Alternately, if having the callback param isn't desired I could swap to a `shouldCloseOnSelect` flag that triggers the focusing internally

Notes:
- ARIA disabled styling is not present on menu currently, so that variation was not included on the option variation example. I have a local stash adding an `isAriaDisabled` flag similar to other components that include the prop, but the style modifier doesn't exist on menu.
- As the default behavior of Select is to have `tab` close the menu, the "menu with footer" example was added to the custom menus page instead so the tab behavior can be controlled.

### CODE REVIEW

File: packages/react-core/src/components/Select/examples/SelectViewMore.tsx [hunk 1]
```diff
@@ -0,0 +1,151 @@
...
+            {...(!isLoading && { isLoadButton: true })}
+            {...(isLoading && { isLoading: true })}
+            onClick={onViewMoreClick}
+            itemId="loader"
+            ref={viewMoreRef}
+          >
+            {isLoading ? <Spinner size="lg" /> : 'View more'}
+          </SelectOption>
+        )}
+      </SelectList>
```
Comment (thatblindgeye) [inline packages/react-core/src/components/Select/examples/SelectViewMore.tsx:148]: This is probably fine. Only possible issue that I wouldn't block over would be that this gets announced as though it were an option to select. The text content would probably provide enough context. An alternative might be using a Button outside of the SelectList, though that would require settingup additional keyboard handling in the example.

File: packages/react-core/src/demos/ComposableMenu/examples/MenuWithFooter.tsx [hunk 2]
```diff
@@ -0,0 +1,82 @@
...
+  const menu = (
+    <Menu ref={menuRef} id="menu-with-footer" onSelect={onSelect} selected={selected}>
+      <MenuContent>
+        <MenuList>
+          <MenuItem itemId="Option 1">Option 1</MenuItem>
+          <MenuItem itemId="Option 2">Option 2</MenuItem>
+          <MenuItem itemId="Option 3">Option 3</MenuItem>
+        </MenuList>
+      </MenuContent>
+      <MenuFooter></MenuFooter>
```
Comment (thatblindgeye) [inline packages/react-core/src/demos/ComposableMenu/examples/MenuWithFooter.tsx:78]:
```suggestion
      <MenuFooter>Footer content</MenuFooter>
```

Right now it just looks like a large gap of empty space.

**Review by thatblindgeye — CHANGES_REQUESTED** [review]

**Comment by nicolethoen** [comment]
> * ARIA disabled styling is not present on menu currently, so that variation was not included on the option variation example. I have a local stash adding an `isAriaDisabled` flag similar to other components that include the prop, but the style modifier doesn't exist on menu.

Sounds like this should be a post v5 core issue? Could you open one?

File: packages/react-core/src/components/Select/examples/Select.md [hunk 3]
```diff
@@ -3,35 +3,71 @@ id: Select
...
 
 ## Examples
 
 ### Single
 
 ```ts file="./SelectBasic.tsx"
+
+```
+
+### Option variations
```
[the remark this answers is not in the document]
Comment (kmcfaul) [reply packages/react-core/src/components/Select/examples/Select.md:21]: Sure I will update the description.

For the other feedback:
- Both single typeaheads behave this way currently, but I can update them to stop filtering after a selection (currently the examples use the input value to do filtering - the filter value just needs to be tracked in a separate state). 
- I added it there because Select's built-in `tab` behavior is incompatible with the example (`tab` needs to have its default behavior rather than close the select). Since this PR I updated Dropdown/Menu to allow customization of those closing keys, so I can add that update here as well and move it back into Select.

[the remark this answers is not in the document]
Comment (kmcfaul) [reply packages/react-core/src/components/Select/examples/Select.md:21]: The other reason for adding the demo to custom menus was because things like MenuSearch and MenuFooter lay outside the MenuContent, but in Select and Dropdown the MenuContent is internal so the extra children would be under the content instead of outside it. I think this is only a DOM difference though, without affecting keyboard or visual behavior.

File: packages/react-core/src/components/Select/Select.tsx [hunk 4]
```diff
@@ -4,6 +4,25 @@ import { Menu, MenuContent, MenuProps } from '../Menu';
...
+  minWidth?: string | 'trigger';
+  /** Maximum width of the popper. If the value is "trigger", it will set the max width to the select toggle's width */
+  maxWidth?: string | 'trigger';
+  /** Enable to flip the popper when it reaches the boundary */
+  enableFlip?: boolean;
+}
+
+/**
+ * See the Menu documentation for additional props that may be passed.
+ */
```
[the remark this answers is not in the document]
Comment (kmcfaul) [reply packages/react-core/src/components/Select/Select.tsx:24]: Good call. I'll also add a blurb to the Dropdown page PR.

File: packages/react-core/src/components/Select/examples/SelectViewMore.tsx (hunk 1 above)
Comment (kmcfaul) [reply packages/react-core/src/components/Select/examples/SelectViewMore.tsx:148]: Is the announcement due to the `role="menuitem"` that `MenuItem` places on its element? We may be able to get around the announcing without having to re-wire keyboard handling by exposing `role` as a prop and passing in a role manually with the view more option. Do you think changing the role would work?

**Comment by kmcfaul** [comment]
@nicolethoen Opened https://github.com/patternfly/patternfly/issues/5528 to track the aria-disabled styling.

**Review by nicolethoen — APPROVED** [review]

File: packages/react-core/src/components/Select/examples/SelectViewMore.tsx (hunk 1 above)
Comment (thatblindgeye) [reply packages/react-core/src/components/Select/examples/SelectViewMore.tsx:148]: Removing/changing the role would flag an error in Axe. Since the Select is using a listbox role, it has to contain children with the "option" role.

I'd be fine with this as-is and revisit it. One possible alternative would be doing something similar to what you did in #9014 and add the view more button to a footer.

Comment (kmcfaul) [reply packages/react-core/src/components/Select/examples/SelectViewMore.tsx:148]: Adding the button to the footer would change the keyboard behavior a decent amount is the drawback, because the footer is navigated to via `tab` and wouldn't focus the next item in the list.

File: packages/react-core/src/components/Select/Select.tsx [hunk 5]
```diff
@@ -16,10 +35,16 @@ export interface SelectProps extends MenuProps, OUIAProps {
...
+    event?: React.MouseEvent<Element, MouseEvent>,
+    itemId?: string | number,
+    toggleRef?: React.RefObject<any>
+  ) => void;
   /** Callback to allow the select component to change the open state of the menu.
-   * Triggered by clicking outside of the menu, or by pressing either tab or escape. */
+   * Triggered by clicking outside of the menu, or by pressing either tab or escape (or specificed in onOpenChangeKeys). */
   onOpenChange?: (isOpen: boolean) => void;
+  /** Keys that trigger onOpenChange, defaults to tab and escape. */
+  onOpenChangeKeys?: string[];
```
Comment (thatblindgeye) [inline packages/react-core/src/components/Select/Select.tsx:47]: The comment I had left in the Menu PR would apply here and possibly require updating (depending where we land). https://github.com/patternfly/patternfly-react/pull/9014#discussion_r1184094156

**Review by thatblindgeye — CHANGES_REQUESTED** [review]
Recent updates look good, just had two other things below

File: packages/react-core/src/components/Select/Select.tsx (hunk 5 above)
Comment (kmcfaul) [reply packages/react-core/src/components/Select/Select.tsx:47]: Replied in the other PR, for others let's try to keep the conversation in one PR and I can update based on the results of that.

**Review by thatblindgeye — APPROVED** [review]

**Review by mcarrano — CHANGES_REQUESTED** [review]
@kmcfaul this looks good. Just one other small ask. Can we change the style of the button in the Footer example to a plain link-style button? While it's not really relevant from a coding standpoint, I don't think we'd want to use a primary button like this in a menu footer and people do take these examples very literal. So it should look like the below. Thanks!

Screenshot 2023-05-10 at 9 33 44 AM

**Review by mcarrano — APPROVED** [review]
Looks great. Thanks @kmcfaul !

**Review by tlabaj — COMMENTED** [review]
Something seems to have regressed with the checkbox select spacing.
cc @mcoker 

image

File: packages/react-core/src/components/Select/Select.tsx [hunk 6]
```diff
@@ -16,10 +35,16 @@ export interface SelectProps extends MenuProps, OUIAProps {
   /** Renderer for a custom select toggle. Forwards a ref to the toggle. */
   toggle: (toggleRef: React.RefObject<any>) => React.ReactNode;
   /** Function callback when user selects an option. */
-  onSelect?: (event?: React.MouseEvent<Element, MouseEvent>, itemId?: string | number) => void;
+  onSelect?: (
+    event?: React.MouseEvent<Element, MouseEvent>,
+    itemId?: string | number,
+    toggleRef?: React.RefObject<any>
```
Comment (tlabaj) [inline packages/react-core/src/components/Select/Select.tsx:41]: So the whole purpose of having the `toggle` render is so that consumer does not have to pass a ref.  I think we should not expect the consumer to use the ref in this way.  I would opt for the `shouldCloseOnSelect` prop instead.

**Review by tlabaj — CHANGES_REQUESTED** [review]
A general comment for the select examples. I think the should be updated to to use the internally generated `menuRef` ref rather than the consumer passing a ref.  I don't want the consumers to think the have to pass the ref.

File: packages/react-core/src/components/Select/Select.tsx (hunk 6 above)
Comment (kmcfaul) [reply packages/react-core/src/components/Select/Select.tsx:43]: The ref looks like it was a holdover from when we manually wired everything up and wasn't currently being used so I removed them.

I added a `shouldFocusToggleOnSelect` prop (the ref is only for that purpose as opening/closing is entirely user-side). However, the "view more" example will break with this change because it should not be focusing the toggle when the selection is the loading option, so I've left the optional property in for now and added comments to the specific example and description of the callback. Will that work? 

Or alternately we could add an optional `toggleRef` parameter (similar to how `ref` is optional and without anything passed it will default to an internal ref) and let `toggle` accept a node as well as a function to allow a user to control the toggleRef completely. What do you think?

Comment (tlabaj) [reply packages/react-core/src/components/Select/Select.tsx:43]: @thatblindgeye @nicolethoen which approach do you think is more intuitive?   I m leaning towards the first approach but i can see benefits of the second as well.

Comment (thatblindgeye) [reply packages/react-core/src/components/Select/Select.tsx:43]: I'd agree that either approach could work. I might lean more towards the toggleRef prop approach personally as it offers that flexibility and isn't tied to just onSelect being called, but considering we're mainly trying to focus the toggle "on select" I'd be fine with the PR as it is.

Just a couple of things:

- Will this require Dropdown to be updated similarly?
- For the prop description on onSelect and shouldFocusToggleOnSelect, maybe adding in some verbiage to explain that one or the other should be used and not both.

Comment (kmcfaul) [reply packages/react-core/src/components/Select/Select.tsx]: Pushed an update with the alternate method, which I can back out if necessary. I kind of like the fallback being manual control of the toggleRef instead of the callback because then a user can control focus in other circumstances as well, not just selection.

Also updated Dropdown similarly.

**Review by andrew-ronaldson — APPROVED** [review]
I saw there was a followup to fix the checkbox regression so this looks good to me.

**Review by thatblindgeye — APPROVED** [review]

File: packages/react-core/src/components/Select/Select.tsx [hunk 7]
```diff
@@ -13,13 +32,19 @@ export interface SelectProps extends MenuProps, OUIAProps {
   isOpen?: boolean;
   /** Single itemId for single select menus, or array of itemIds for multi select. You can also specify isSelected on the SelectOption. */
   selected?: any | any[];
-  /** Renderer for a custom select toggle. Forwards a ref to the toggle. */
-  toggle: (toggleRef: React.RefObject<any>) => React.ReactNode;
+  /** Select toggle. May be a direct ReactNode combined with the toggleRef property, or a renderer for a custom select toggle which forwards a ref to the toggle. */
```
Comment (tlabaj) [inline packages/react-core/src/components/Select/Select.tsx:35]: The description is not quite right.  Aren't both option a custom toggle?  I think we want to be explicit that if you do not use a renderer, you need to provide a ref.  I wonder if we should group the props somehow. Maybe an object for the react node toggle and the ref.  then the toggle prop could be either that or the renderer?

**Review by tlabaj — CHANGES_REQUESTED** [review]

File: packages/react-core/src/components/Select/Select.tsx (hunk 7 above)
Comment (kmcfaul) [reply packages/react-core/src/components/Select/Select.tsx:35]: Since there's no default I thought that "custom" was a bit redundant to state. For the required ref, I tried to convey that in `May be a direct ReactNode combined with the toggleRef property [...]` but let me try to reword that better.

Comment (kmcfaul) [reply packages/react-core/src/components/Select/Select.tsx]: @tlabaj Do the descriptions make more sense now?

File: packages/react-core/src/components/Dropdown/Dropdown.tsx [hunk 8]
```diff
@@ -27,16 +27,16 @@ export interface DropdownProps extends MenuProps, OUIAProps {
   children?: React.ReactNode;
   /** Classes applied to root element of dropdown. */
   className?: string;
-  /** Renderer for a custom dropdown toggle. Forwards a ref to the toggle. */
-  toggle: (toggleRef: React.RefObject<any>) => React.ReactNode;
+  /** Dropdown toggle. The toggle should either be a renderer function which forwards the given toggle ref, or a direct ReactNode that should be passed along with the toggleRef property. */
+  toggle: React.ReactNode | ((toggleRef: React.RefObject<any>) => React.ReactNode);
+  /** Ref of the dropdown toggle. This property should be passed when toggle is assigned a node, to enable built in basic interaction handling. */
+  toggleRef?: React.RefObject<HTMLButtonElement>;
```
Comment (tlabaj) [inline packages/react-core/src/components/Dropdown/Dropdown.tsx:33]: So when I said grouped together  in one props.  So prop that would be an objet of toggle with type react node and toggle ref.  Sou you would either use the toggle prop or the prop with the object.

Comment (kmcfaul) [reply packages/react-core/src/components/Dropdown/Dropdown.tsx:33]: I don't think we've really used that pattern much, but I can update to it if we'd rather having a single prop.

Comment (kmcfaul) [reply packages/react-core/src/components/Dropdown/Dropdown.tsx:35]: Pushed the update

Comment (tlabaj) [reply packages/react-core/src/components/Dropdown/Dropdown.tsx:35]: We have a few other places where we group related props e.g.
https://github.com/patternfly/patternfly-react/blob/2da278eeebfb3475c31e3693435a8c7f04a0edde/packages/react-core/src/components/Button/Button.tsx#L31-L38
then we use it  here
https://github.com/patternfly/patternfly-react/blob/2da278eeebfb3475c31e3693435a8c7f04a0edde/packages/react-core/src/components/Button/Button.tsx#L85-L86

nit.  Can you define the interface for the group props for consistency.

Comment (kmcfaul) [reply packages/react-core/src/components/Dropdown/Dropdown.tsx:35]: Ah that's actually probably why it looked a bit off to me, since we define the interface outside the props rather than inline. Will update!

**Review by tlabaj — APPROVED** [review]
Thanks for the updates!   LGTM

File: packages/react-core/src/components/Dropdown/Dropdown.tsx [hunk 9]
```diff
@@ -27,16 +34,16 @@ export interface DropdownProps extends MenuProps, OUIAProps {
   children?: React.ReactNode;
   /** Classes applied to root element of dropdown. */
   className?: string;
-  /** Renderer for a custom dropdown toggle. Forwards a ref to the toggle. */
-  toggle: (toggleRef: React.RefObject<any>) => React.ReactNode;
+  /** Dropdown toggle. The toggle should either be a renderer function which forwards the given toggle ref, or a direct ReactNode that should be passed along with the toggleRef property. */
+  toggle: DropdownToggleProps | ((toggleRef: React.RefObject<any>) => React.ReactNode);
+  /** Ref of the dropdown toggle. This property should be passed when toggle is assigned a node, to enable built in basic interaction handling. */
+  toggleRef?: React.RefObject<HTMLButtonElement>;
```
Comment (thatblindgeye) [inline packages/react-core/src/components/Dropdown/Dropdown.tsx:40]: This should be removed since we have the DropdownToggleProps interface

**Review by thatblindgeye — CHANGES_REQUESTED** [review]
Also have the same question as Nicole above

File: packages/react-core/src/components/Select/Select.tsx [hunk 10]
```diff
@@ -1,9 +1,35 @@
...
+  maxWidth?: string | 'trigger';
+  /** Enable to flip the popper when it reaches the boundary */
+  enableFlip?: boolean;
+}
+
+export interface SelectToggleProps {
+  /**  Select toggle node. */
+  toggleNode: React.ReactNode;
+  /** Reference to the toggle. */
+  toggleRef: React.RefObject<HTMLButtonElement>;
```
[the remark this answers is not in the document]
Comment (kmcfaul) [reply packages/react-core/src/components/Select/Select.tsx:26]: Ah right I'll update that. Initially I had the logic where it would be required but updated it a bit later and forgot to change the prop.

**Review by thatblindgeye — APPROVED** [review]
