### PR TITLE
Fix/no anonymous functions2

### LINKED ISSUE #4369: Make anonymous function components named
In all our projects, code like:
```tsx
export const AboutModalBoxCloseButton = ({
  className = '',
  onClose = () => undefined as any,
  'aria-label': ariaLabel = 'Close Dialog',
  ...props
}: AboutModalBoxCloseButtonProps) => ( ... );
```
gets compiled to anonymous CJS arrow functions:
```js
exports.AboutModalBoxCloseButton = (_a) => { ... };
```

However, for Enzyme (which uses CJS), we'd like our code to get compiled down to named components so we can write selectors like `view.find(AboutModalBoxCloseButton)`.

### ~~Named functions~~
This has been ruled out in favor of display names.

~~An alternative way to write our arrow functions to accomplish this is like:~~
```tsx
export function AboutModalBoxCloseButton({
  className = '',
  onClose = () => undefined as any,
  'aria-label': ariaLabel = 'Close Dialog',
  ...props
}: AboutModalBoxCloseButtonProps) {
  return ( ...  );
}
```
~~which gets compiled to CJS as a named function:~~
```js
function AboutModalBoxCloseButton(_a) { ... }
```

~~The types change slightly from:~~
```ts
export declare const AboutModalBoxCloseButton: React.FunctionComponent<AboutModalBoxCloseButtonProps>;
```
~~to~~
```ts
export declare function AboutModalBoxCloseButton({ className, onClose, 'aria-label': ariaLabel, ...props }: AboutModalBoxCloseButtonProps): JSX.Element;
```

~~... but these are compatible and _should_ be okay (see [blog post](https://blog.echobind.com/react-with-typescript-components-as-function-declarations-vs-function-expressions-e433ac8d6938) and [React.FC typing README](https://github.com/typescript-cheatsheets/react-typescript-cheatsheet/blob/master/README.md#function-components))~~

### Display names

An alternative way to write our arrow functions to accomplish this is like:
```tsx
export const AboutModalBoxCloseButton = ({
  className = '',
  onClose = () => undefined as any,
  'aria-label': ariaLabel = 'Close Dialog',
  ...props
}: AboutModalBoxCloseButtonProps) => ( ... );
AboutModalBoxCloseButton.displayName = 'AboutModalBoxCloseButton';
```

This works everywhere and the function name won't get obfuscated by Webpack's terser or other build tools so that React dev tools can pickup component names in our docs.

### PR DESCRIPTION
**Pull request by redallen**
**What**: Write eslint rule to enforce adding display names and add `displayName`s to 411 components missing them. Closes #4369

**Additional issues**: In favor of #4388

### CODE REVIEW

File: packages/eslint-plugin-patternfly-react/lib/rules/no-anonymous-functions.js [hunk 1]
```diff
@@ -0,0 +1,82 @@
+// https://astexplorer.net/#/gist/60c119aa79dab3a3e438cc762d21490f/e2cdd0547688a64eff1d8964156cfd8fce55d21d
+module.exports = {
+  meta: {
+    docs: {
+      description:
+        "Don't use anonmous functions without a displayName so Enzyme and React devtools show component name",
```
Comment (jschuler) [inline packages/eslint-plugin-patternfly-react/lib/rules/no-anonymous-functions.js:6]:
```suggestion
        "Don't use arrow functions or classes without a displayName so Enzyme and React devtools show component name",
```

Comment (jschuler) [reply packages/eslint-plugin-patternfly-react/lib/rules/no-anonymous-functions.js:6]: Awesome, our docs now also show the component name in react dev tools, and the snapshots as well!
