### PR TITLE
fix(Menu): focused items should scrollintoview when overflowed

### LINKED ISSUE #8595: Bug - [Select] - [When the height is limited with maxHeight and the menu overflows the elements are not scrolling into view while moving down with the keyboard]
**Describe the problem**
When limiting the height of the Select component, which makes the menu to result in overflow scroll, the item in focus should be always in view, but that's not the case.

**How do you reproduce the problem?**
[Provide steps to reproduce. A [codesandbox](https://codesandbox.io/s/serverless-cherry-q9t3f ) demonstrating the problem is appreciated.
](https://codesandbox.io/s/kind-brook-604ssd?file=/index.js)

**Expected behavior**
The li element in focus should be always in view.

**Is this issue blocking you?**
No, but there is bug report, https://bugzilla.redhat.com/show_bug.cgi?id=2034498

### PR DESCRIPTION
**Pull request by kmcfaul**
**What**: Closes #8595

When a typeahead menu is navigated using keyboard, actual focus remains on the text input while visual focus is applied to each item. When the items overflow the menu list, keyboard navigation should scroll items into focus if needed.

### CODE REVIEW

File: packages/react-core/src/components/Menu/MenuItem.tsx [hunk 1]
```diff
@@ -309,6 +309,23 @@ const MenuItemBase: React.FunctionComponent<MenuItemProps> = ({
...
+    if (isFocused && ref.current) {
+      const itemEl = ref.current;
+      const parentListEl = itemEl.parentElement;
+
+      if (parentListEl) {
+        const isAboveTop = itemEl.offsetTop - parentListEl.offsetTop < parentListEl.scrollTop;
+        const isBelowBottom = itemEl.offsetTop - parentListEl.offsetTop + itemEl.clientHeight;
+
+        if (isAboveTop || isBelowBottom) {
+          itemEl.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
```
Comment (thatblindgeye) [inline packages/react-core/src/components/Menu/MenuItem.tsx:323]: "auto" might be a better option for the behavior (unless we'd want to make this customizable/check if a user has some setting that would trigger the `prefers-reduced-motion` media query).

When testing the Select typeahead and passing `isScrollable`, this is the result when traversing through via keyboard then closing/opening after giving focus to the last option:

https://github.com/patternfly/patternfly-react/assets/70952936/8d005b61-6157-472d-993d-6678916b9c95

**Review by thatblindgeye — APPROVED** [review]

**Review by wise-king-sullyman — APPROVED** [review]

**Review by mmenestr — APPROVED** [review]
