### PR TITLE
fix(DragDropSort): fix positioning of DragOverlay

### LINKED ISSUE #10090: Bug - DragDropSort - dragged element transform inaccruate when DragDropSort is in DrawerPanelContent
**Describe the problem**

I combined the examples for Drag and Drop and Drawer with very few modifications:

- https://www.patternfly.org/components/drag-and-drop/react-next#basic-drag-and-drop-sorting-with-drag-button
- https://www.patternfly.org/components/drawer#inline-panel-at-start

```typescript
import React from 'react';
import {
  Drawer,
  DrawerPanelContent,
  DrawerContent,
  DrawerContentBody,
  DrawerHead,
  DrawerActions,
  DrawerCloseButton,
  Button
} from '@patternfly/react-core';
import {DragDropSort, DraggableObject} from "@patternfly/react-drag-drop";

export const DrawerInlinePanelStart: React.FunctionComponent = () => {
  const [isExpanded, setIsExpanded] = React.useState(true);
  const drawerRef = React.useRef<HTMLDivElement>();

  const onExpand = () => {
    drawerRef.current && drawerRef.current.focus();
  };

  const onClick = () => {
    setIsExpanded(!isExpanded);
  };

  const onCloseClick = () => {
    setIsExpanded(false);
  };

  const [items, setItems] = React.useState<DraggableObject[]>([
    { id: 'with-button-1', content: 'one' },
    { id: 'with-button-2', content: 'two' },
    { id: 'with-button-3', content: 'three' },
    { id: 'with-button-4', content: 'four' },
    { id: 'with-button-5', content: 'five' },
    { id: 'with-button-6', content: 'six' },
    { id: 'with-button-7', content: 'seven' },
    { id: 'with-button-8', content: 'eight' },
    { id: 'with-button-9', content: 'nine' },
    { id: 'with-button-10', content: 'ten' },
    { id: 'with-button-11', content: 'eleven' },
    { id: 'with-button-12', content: 'twelve' },
    { id: 'with-button-13', content: 'thirteen' },
    { id: 'with-button-14', content: 'fourteen' },
    { id: 'with-button-15', content: 'fifteen' },
    { id: 'with-button-16', content: 'sixteen' },
    { id: 'with-button-17', content: 'seventeen' },
    { id: 'with-button-18', content: 'eighteen' },
    { id: 'with-button-19', content: 'nineteen' },
    { id: 'with-button-20', content: 'twenty' },
  ]);

  const panelContent = (
    <DrawerPanelContent>
      <DrawerHead>
        <span tabIndex={isExpanded ? 0 : -1} ref={drawerRef}>
          drawer content
        </span>
        <DrawerActions>
          <DrawerCloseButton onClick={onCloseClick} />
        </DrawerActions>
      </DrawerHead>
      <DragDropSort
        items={items}
        variant="defaultWithHandle"
        onDrop={(_, newItems) => {
          setItems(newItems);
        }}
      />
    </DrawerPanelContent>
  );

  const drawerContent =
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus pretium est a porttitor vehicula. Quisque vel commodo urna. Morbi mattis rutrum ante, id vehicula ex accumsan ut. Morbi viverra, eros vel porttitor facilisis, eros purus aliquet erat,nec lobortis felis elit pulvinar sem. Vivamus vulputate, risus eget commodo eleifend, eros nibh porta quam, vitae lacinia leo libero at magna. Maecenas aliquam sagittis orci, et posuere nisi ultrices sit amet. Aliquam ex odio, malesuada sed posuere quis, pellentesque at mauris. Phasellus venenatis massa ex, eget pulvinar libero auctor pretium. Aliquam erat volutpat. Duis euismod justo in quam ullamcorper, in commodo massa vulputate.';

  return (
    <React.Fragment>
      <Button aria-expanded={isExpanded} onClick={onClick}>
        Toggle drawer
      </Button>
      <Drawer isExpanded={isExpanded} isInline position="start" onExpand={onExpand}>
        <DrawerContent panelContent={panelContent}>
          <DrawerContentBody>{drawerContent}</DrawerContentBody>
        </DrawerContent>
      </Drawer>
    </React.Fragment>
  );
};


export default DrawerInlinePanelStart;

```

**How do you reproduce the problem?**

https://github.com/jennydaman/patternfly-react-drag-drop-in-drawer

**Expected behavior**

Dragged element stays under the mouse.

**Is this issue blocking you?**

It is blocking us from using the Drag and Drop feature, but I can choose to use a different UX instead.

**Screenshots**

https://github.com/patternfly/patternfly-react/assets/20404439/d842c246-0cde-4b05-bbe1-0a21c775bf0b

**What is your environment?**
 - OS: Linux
 - Browser Chromium, Firefox
 - Version 5.2.0

### PR DESCRIPTION
**Pull request by adamviktora**
**What**: Closes #10090

Change was done based on this [comment](https://github.com/clauderic/dnd-kit/issues/464#issuecomment-1008316262) from the author of the `dnd-kit` package.

I assume that a div with `id="root"` will always be present in a React app, which I don't know if it is 100% true.

We should also do this change for V6 once DragDrop is removed from the `next` folder.

### CODE REVIEW

File: packages/react-drag-drop/src/next/components/DragDrop/DragDropSort.tsx [hunk 1]
```diff
@@ -159,7 +163,7 @@ export const DragDropSort: React.FunctionComponent<DragDropSortProps> = ({
             );
         }
       })}
-      <DragOverlay>{activeId && getDragOverlay()}</DragOverlay>
+      {canUseDOM ? ReactDOM.createPortal(dragOverlay, document.getElementById('root')) : dragOverlay}
```
Comment (thatblindgeye) [inline packages/react-drag-drop/src/next/components/DragDrop/DragDropSort.tsx:166]: I feel like it might be worth adding a prop to be able to customize the element passed to createPortal, though also may be something to wait and see if anyone mentions any issue with it. Not a blocker for me to keep this as-is, so unless anyone else would want to see that update ☑️

**Review by thatblindgeye — APPROVED** [review]

**Review by tlabaj — APPROVED** [review]
lgtm
