### PR TITLE
fix(LogViewer): fix the issue that scrollbar could compress the content of the logs

### LINKED ISSUE #6701: Log Viewer: The vertical scrollbar may compress the content of the window
**Describe the issue. What is the expected and unexpected behavior?**
The vertical scrollbar may compress the content of the window, which could cause inaccurate line numbers estimation.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

Go to any of the log viewer examples which wrap lines.
If you are a Macbook user, go to Settings->General, and set the Show scroll bars to 'Always'. You will see the log viewer list width changed and there will be some overlaps between different rows.

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug.

### PR DESCRIPTION
**Pull request by DaoDaoNoCode**
**What**: Closes #6701 
Use a small trick to prevent list width from changing when user changes setting of showing scrollbar from 'Always' to 'Automatically'.

### CODE REVIEW

**Review by jschuler — APPROVED** [review]

File: packages/react-log-viewer/src/react-window/createListComponent.ts [hunk 1]
```diff
@@ -265,6 +269,8 @@ export default function createListComponent({
             ref: innerRef,
             style: {
               height: estimatedTotalSize > height ? estimatedTotalSize : height,
+              /* eslint-disable-next-line no-nested-ternary */
+              width: isTextWrapped ? (hasLineNumbers ? width - 65 : width) : 'auto',
```
Comment (jschuler) [inline packages/react-log-viewer/src/react-window/createListComponent.ts:273]: nit: maybe in your next PR or followup you can save `65` to a variable like `lineNumbersColumnWidth`

File: packages/react-log-viewer/src/LogViewer/LogViewerRow.tsx [hunk 2]
```diff
@@ -78,6 +78,7 @@ export const LogViewerRow: React.FunctionComponent<LogViewerRowProps> = memo(({
       <span className={css(styles.logViewerIndex)}>{getRowIndex(index)}</span>
       <span
         className={css(styles.logViewerText)}
+        style={{ width: 'fit-content' }}
```
Comment (jschuler) [inline packages/react-log-viewer/src/LogViewer/LogViewerRow.tsx:81]: can this become part of patternfly core?

**Review by dlabrecq — APPROVED** [review]
