### PR TITLE
chore(pagination): fixed filter not applying in sticky example

### LINKED ISSUE #7652: Bug - Pagination - Sticky example not applying per page filter
After applying the per page filter on the sticky pagination example, the data inside doesn't get filtered out.

Jul-05-2022 09-28-38

### PR DESCRIPTION
**Pull request by gefgu**
**What**: Closes #7652

To keep the code DRY, I've refactored the build cards functionality.

Also, I've added a logic for when there are less cards in the page than the `perPage` prop.

### CODE REVIEW

File: packages/react-core/src/components/Pagination/examples/PaginationSticky.tsx [hunk 1]
```diff
@@ -5,6 +5,7 @@ export const PaginationSticky: React.FunctionComponent = () => {
   const [page, setPage] = React.useState(1);
   const [perPage, setPerPage] = React.useState(20);
```
Comment (jenny-s51) [inline packages/react-core/src/components/Pagination/examples/PaginationSticky.tsx:6]: Wondering if we should set the `perPage` value to 100 here since we probably want this demo to be scrollable by default... That way the sticky pagination functionality will be evident in the demo!
```suggestion
  const [perPage, setPerPage] = React.useState(100);
```

**Review by jenny-s51 — COMMENTED** [review]
This is looking good @gefgu ! Overall everything works as expected - thanks for helping us clean up the card logic 👌

I just had a visual nit - it seems like the cards could use exactly 24px of padding around the sides...
Screen Shot 2022-10-11 at 4 14 56 PM

This might be out of scope since this issue already existed prior to this PR.

I did some investigating, and it looks like we don't really use Cards without a `Page` layout and `PageSection` in our other demos, which is why this has never been an issue.

This is not blocking, though ultimately I think this feature might lend itself better to a full-page demo!

**Comment by gefgu** [comment]
@jenny-s51 I added the `Page` and `PageSection` to the demo. I hope this was the change you was expecting :)

**Review by nicolethoen — COMMENTED** [review]
we'd usually avoid extra components like a Page in a different component's examples if we can manage it. 

in this case, let's remove the Page and PageSection components from this example and @jenny-s51 could you open a follow up issue to create a new full page demo with a DashboardWrapper. It could be in addition to this example or replace this example but that can be up to @mcarrano.

Other than that, I think this looks good!

**Comment by thatblindgeye** [comment]
@gefgu would you be able to continue work on this PR?

**Comment by thatblindgeye** [comment]
@nicolethoen @jenny-s51  removed the Page components from the example

File: packages/react-core/src/components/Pagination/examples/PaginationSticky.tsx [hunk 2]
```diff
@@ -45,45 +36,38 @@ export const PaginationSticky: React.FunctionComponent = () => {
...
-              isSticky
-              variant={PaginationVariant.bottom}
-            >
-              <button onClick={onToggleSticky}>Toggle to top position</button>
-            </Pagination>
-          </React.Fragment>
-        )}
-      </PageSection>
-    </Page>
+  return isTopSticky ? (
```
Comment (jenny-s51) [inline packages/react-core/src/components/Pagination/examples/PaginationSticky.tsx:39]: Nice catch using a conditional here instead

**Review by jenny-s51 — APPROVED** [review]
LGTM

**Review by nicolethoen — APPROVED** [review]
