### PR TITLE
fix(Timestamp): updated logic for rendering datetime attribute

### LINKED ISSUE #7952: Bug - timestamp - datetime attribute showing the wrong date on the demo page
**Describe the problem**
When you view the demo page for the Timestamp component, the `datetime` attribute has the wrong value for most of the examples. 

image

**How do you reproduce the problem?**
Visit https://www.patternfly.org/v4/components/timestamp/ and view the `datetime` attribute in the `time` element for the timestamp examples.

**Expected behavior**
I'd expect the `datetime` attribute to have the ISO date value for the `date` prop passed in.

It's not wrong on all the examples which is kind of weird. It seems to work "Custom content" and "Custom tooltip" sections.

### PR DESCRIPTION
**Pull request by thatblindgeye**
**What**: Closes #7952

[Timestamp preview build](https://patternfly-react-pr-8205.surge.sh/components/timestamp)

Borrowed some logic from our Calendar Month component to have date state internally, which I believe may have been partly causing the original issue (updating example code from our live site causes the datetime attribute to render properly, as does clicking the Timestamp link in our sidenav, but being linked directly to the page causes the issue to occur).

Also made a slight tweak to how props were spread so that a `dateTime` prop didn't get applied to both the outter `span` and inner `time` elements.

**Additional issues**:

### CODE REVIEW

File: packages/react-core/src/components/Timestamp/Timestamp.tsx [hunk 1]
```diff
@@ -2,6 +2,7 @@ import * as React from 'react';
 import styles from '@patternfly/react-styles/css/components/Timestamp/timestamp';
 import { css } from '@patternfly/react-styles';
 import { Tooltip } from '../Tooltip';
+import { isValidDate } from '../CalendarMonth';
```
Comment (nicolethoen) [inline packages/react-core/src/components/Timestamp/Timestamp.tsx:5]: I wonder if it's worth moving this helper function out of the CalendarMonth component into a more centralized helper functions file

File: packages/react-core/src/components/Timestamp/__tests__/__snapshots__/Timestamp.test.tsx.snap [hunk 2]
```diff
@@ -4,7 +4,6 @@ exports[`Matches snapshot 1`] = `
 <DocumentFragment>
   <span
     class="pf-c-timestamp"
-    datetime="2022-01-01T00:00:00.000Z"
```
Comment (nicolethoen) [inline packages/react-core/src/components/Timestamp/__tests__/__snapshots__/Timestamp.test.tsx.snap:7]: Shouldn't there still be a datetime by default in the snapshot?

**Review by nicolethoen — COMMENTED** [review]
Is there a test to verify that the default datetime attribute is correct given a date and timezone?

File: packages/react-core/src/components/Timestamp/__tests__/__snapshots__/Timestamp.test.tsx.snap (hunk 2 above)
Comment (thatblindgeye) [reply packages/react-core/src/components/Timestamp/__tests__/__snapshots__/Timestamp.test.tsx.snap:7]: Ah yeah there still is, it's only on the `time` element now, though.

Comment (nicolethoen) [reply packages/react-core/src/components/Timestamp/__tests__/__snapshots__/Timestamp.test.tsx.snap:7]: ah - it was part of the hidden lines by github

File: packages/react-core/src/components/Timestamp/__tests__/Timestamp.test.tsx [hunk 3]
```diff
@@ -36,12 +36,31 @@ test('Renders with current date by default with default formatting', () => {
...
+});
+
 test('Renders passed in date with default formatting', () => {
   render(<Timestamp date={new Date(2022, 0, 1)} />);
 
   expect(screen.getByText('1/1/2022, 12:00:00 AM')).toBeInTheDocument();
 });
 
+test('Renders with correct datetime attribute when date is passed in', () => {
+  const passedDate = new Date(2022, 0, 1);
```
Comment (nicolethoen) [inline packages/react-core/src/components/Timestamp/__tests__/Timestamp.test.tsx:58]: Is the user timezone going to affect these tests? @gitdallas, is there a way we can easily recognize the sorts of tests you had issues with before?

Comment (gitdallas) [reply packages/react-core/src/components/Timestamp/__tests__/Timestamp.test.tsx:58]: the test that fails for me without TZ=EST is "Renders with only date when dateFormat is passed in"
image

Comment (thatblindgeye) [reply packages/react-core/src/components/Timestamp/__tests__/Timestamp.test.tsx:58]: I believe I had formatted the passed in string for those few tests due to the wonkiness that was occurring when running the tests (the tests would pass locally but fail when ran on Github).

I could update those few tests so that instead of `new Date('...EST')` the format is similar to other tests, e.g. `new Date(2022, 0, 1)`. @gitdallas do you feel that would be a viable option?

**Review by nicolethoen — APPROVED** [review]

**Review by kmcfaul — APPROVED** [review]
