### PR TITLE
fix(datalist): use drag-over modifier instead of css style

### LINKED ISSUE #5041: Class to fix data list shifting when rows are dragged
Currently we're setting an inline style of `overflow-anchor: none;` on the data-list once the dragging event starts

https://github.com/patternfly/patternfly-react/blob/196bcb84d8f4bcfba134a92dd8f058d55089c04b/packages/react-core/src/components/DataList/DataList.tsx#L316

We added a class `.pf-m-drag-over` that can be applied to the data-list while dragging instead.

https://github.com/patternfly/patternfly/pull/3574/files

cc @kmcfaul

### PR DESCRIPTION
**Pull request by boaz0**
**What**: Closes #5041 

//cc @mcoker

### CODE REVIEW

File: packages/react-core/src/components/DataList/DataList.tsx [hunk 1]
```diff
@@ -326,12 +326,10 @@ export class DataList extends React.Component<DataListProps, DataListState> {
             isCompact && styles.modifiers.compact,
             gridBreakpointClasses[gridBreakpoint],
             wrapModifier && styles.modifiers[wrapModifier],
+            dragging && styles.modifiers.dragOver,
```
Comment (mcoker) [inline packages/react-core/src/components/DataList/DataList.tsx:329]: This looks good to replace the existing behavior, but I think we need to change it so that `styles.modifiers.dragOver` is only applied while dragging, meaning it's removed once the item is dropped.

Comment (kmcfaul) [reply packages/react-core/src/components/DataList/DataList.tsx:329]: It looks like the `dragging` state needs to be updated in the drag end handler, it is removed properly on a drag cancel. It should work with that updated.

Comment (boaz0) [reply packages/react-core/src/components/DataList/DataList.tsx:329]: As @kmcfaul mentioned. `dragging` is a part of [the `DataList` state](https://github.com/patternfly/patternfly-react/blob/master/packages/react-core/src/components/DataList/DataList.tsx#L55) which is being updated to true in [`dragStart0`](https://github.com/patternfly/patternfly-react/blob/master/packages/react-core/src/components/DataList/DataList.tsx#L143-L146) and false in [`onDragCancel`](https://github.com/patternfly/patternfly-react/blob/master/packages/react-core/src/components/DataList/DataList.tsx#L162-L166). These two are being called accordingly to the events when the user clicks and holds the element or releases the element.

Comment (kmcfaul) [reply packages/react-core/src/components/DataList/DataList.tsx:329]: It should also be updated in `dragEnd0` so the style gets removed when the drag is successfully completed.

**Comment by tlabaj** [comment]
@boaz It looks like there are outstanding comments here.

**Comment by tlabaj** [comment]
@boaz0 this one still has outstanding comments.

**Comment by boaz0** [comment]
@tlabaj  sorry, I thought I fixed it. I will work on it.
Thanks.

**Review by kmcfaul — DISMISSED** [review]

**Review by tlabaj — APPROVED** [review]
lgtm

**Comment by mcoker** [comment]
Looking at this [draggable example](https://patternfly-react-pr-5119.surge.sh/components/data-list#draggable), I'm still seeing `.pf-m-drag-over` on the data list after I've stopped dragging.

**Comment by boaz0** [comment]
Um, maybe I am missing something. But this is what I have on Firefox.


https://user-images.githubusercontent.com/2453279/105348877-9b8eb900-5bf1-11eb-9453-197a9a3e37f7.mp4

**Comment by mcoker** [comment]
@boaz0 ah ok, I was testing in chrome - this is what I'm seeing


https://user-images.githubusercontent.com/35148959/105370748-830aa880-5bc9-11eb-9f0e-98a7087d7204.mp4

**Comment by boaz0** [comment]
Thanks @mcoker I will look at this more. :laughing:

**Comment by boaz0** [comment]
@mcoker do you mind review this again. I hope this fixes the problem.

**Comment by boaz0** [comment]
@mcoker do you mind reviewing this again. I hope this fixes the problem.

**Review by mcoker — APPROVED** [review]
LGTM!!

**Review by tlabaj — APPROVED** [review]

**Review by kmcfaul — APPROVED** [review]
lgtm!
