### PR TITLE
fix(Nav): Make nav items keyboard and screen reader accessible

### LINKED ISSUE #5260: Update navigation demos to show accessible experience
**Describe the issue. What is the expected and unexpected behavior?**
Currently when you navigate to the navigation demos by keyboard, you are unable to navigate to the side panel and click other links. This is likely due to the fact that the links do not have href's. However, when href's are added and the user tabs through the page, keyboard focus disappears off the page. You can determine from the link previews at the bottom left that focus is still going to these links even when the panel is closed. I believe that we could fix this by altering the items to display none when the panel is collapsed. However, we need to account for transitioned events so that if we ever add transitions, the panel items don't just disappear before the transition.

This issue was first noticed in OpenShift. When comparing it to the react demos, we noticed that our demos have the same issue. It would make sense to solve this issue in the context of PF first.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

Open [any navigation demo](https://www.patternfly.org/v4/components/navigation/react-demos/default-nav/) and attempt to navigate by keyboard. 

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug

### PR DESCRIPTION
**Pull request by jessiehuff**
**What**: Closes #5260

### CODE REVIEW

File: packages/react-core/src/components/Page/PageSidebar.tsx [hunk 1]
```diff
@@ -19,33 +19,49 @@ export interface PageSidebarProps extends React.HTMLProps<HTMLDivElement> {
...
   className = '',
   nav,
   isNavOpen = true,
   theme = 'dark',
   ...props
 }: PageSidebarProps) => (
-  <PageContextConsumer>
-    {({ isManagedSidebar, isNavOpen: managedIsNavOpen }: PageSidebarProps) => {
-      const navOpen = isManagedSidebar ? managedIsNavOpen : isNavOpen;
+  <PageSidebarContext.Provider value={{ isNavOpen }}>
```
Comment (jschuler) [inline packages/react-core/src/components/Page/PageSidebar.tsx:43]: I would bring this down a level and wrap the `{nav}` more directly, this way you would also have the definitive answer to whether the nav is open, i.e. (leaving some code out for brevity)
```
<PageContextConsumer>
  <div id="page-sidebar">
     <div className={css(styles.pageSidebarBody)}>
        <PageSidebarContext.Provider value={{ isNavOpen: navOpen }}>
          {nav}
        </PageSidebarContext.Provider>
      </div>
  </div>
</PageContextConsumer>
```

File: packages/react-core/src/components/Page/PageSidebar.tsx [hunk 2]
```diff
@@ -19,33 +19,49 @@ export interface PageSidebarProps extends React.HTMLProps<HTMLDivElement> {
   theme?: 'dark' | 'light';
 }
 
+export interface PageSidebarContextProps {
+  className: string;
+  nav: React.ReactNode;
+  isNavOpen: boolean;
```
Comment (jschuler) [inline packages/react-core/src/components/Page/PageSidebar.tsx:25]: are the other ones needed? I think only `isNavOpen` is used

File: packages/react-core/src/components/Nav/NavItem.tsx [hunk 3]
```diff
@@ -43,19 +45,27 @@ export const NavItem: React.FunctionComponent<NavItemProps> = ({
...
-      <Component
-        href={to}
-        onClick={(e: any) => context.onSelect(e, groupId, itemId, to, preventLinkDefault, onClick)}
-        className={css(styles.navLink, isActive && styles.modifiers.current, className)}
-        aria-current={isActive ? 'page' : null}
-        {...props}
-      >
-        {children}
-      </Component>
+      <PageContextConsumer>
```
Comment (jschuler) [inline packages/react-core/src/components/Nav/NavItem.tsx:52]: don't need PageContextConsumer since you have the definitive answer to isNavOpen if you make the changes in my other comment :)

File: packages/react-core/src/components/Page/PageSidebar.tsx (hunk 2 above)
Comment (jessiehuff) [reply packages/react-core/src/components/Page/PageSidebar.tsx:23]: Yup, you're right. Wasn't sure if I should leave the others in in case of future stuff, but just isNavOpen is probably better for now.

File: packages/react-core/src/components/Page/PageSidebar.tsx (hunk 1 above)
Comment (jessiehuff) [reply packages/react-core/src/components/Page/PageSidebar.tsx]: Thank you!! 😄

**Review by nicolethoen — APPROVED** [review]

**Review by jschuler — APPROVED** [review]

**Review by kmcfaul — APPROVED** [review]

**Review by tlabaj — APPROVED** [review]
lgtm
