### PR TITLE
fix(page): hide PageSideBar onClick on mobile when isManagedSidebar

### LINKED ISSUE #4480: On mobile the navigation toolbar only disappears when the "kebab" is clicked again
When a user on mobile uses the page navigation to navigate to a particular "page" the navigation bar does not hide after the navigation is complete. Nor does it disappear when the "page" that is in the background is clicked. The only way to get rid of it is by clicking the kebab item again. This is not very user friendly and not on par with other mobile websites.

### PR DESCRIPTION
**Pull request by redallen**
**What**: Closes #4480. Fixes resize event listener never detaching.

**Additional issues**: Doesn't close when nav item clicked. I think that's a bit too opinionated since designs can use side navs for more than just navigation. It's also tricky to code, but can be achieved consumer-side.

### CODE REVIEW

**Comment by dtaylor113** [comment]
Hi @redallen, do you know how I could test the PR against OpenShift?   I assume this would be in an upcoming pre-release, so I could test it then, would be nice to do before this is merged though.

**Comment by redallen** [comment]
You could checkout this PR, build it, and symlink all the `@patternfly` packages under openshift's `node_modules`.

**Review by jenny-s51 — DISMISSED** [review]
Tested on mobile - LGTM

File: packages/react-core/src/components/Page/Page.tsx [hunk 1]
```diff
@@ -107,7 +108,9 @@ export class Page extends React.Component<PageProps, PageState> {
   componentDidMount() {
     const { isManagedSidebar, onPageResize } = this.props;
     if (isManagedSidebar || onPageResize) {
-      window.addEventListener('resize', debounce(this.handleResize, 250));
+      window.addEventListener('resize', this.handleResize);
+      document.addEventListener('mousedown', this.handleClickMobile);
```
Comment (jschuler) [inline packages/react-core/src/components/Page/Page.tsx:112]: these could be attached to the ref, something like
```suggestion
      this.outerRef && this.outerRef.current && this.outerRef.current.addEventListener('mousedown', this.handleClickMobile);
```

File: packages/react-core/src/components/Page/Page.tsx [hunk 2]
```diff
@@ -116,19 +119,32 @@ export class Page extends React.Component<PageProps, PageState> {
...
+    const mobileView = this.isMobile();
     if (onPageResize) {
-      onPageResize({ mobileView, windowSize });
+      onPageResize({ mobileView, windowSize: window.innerWidth });
     }
     this.setState({ mobileView });
+  }, 250);
+
+  handleClickMobile = (ev: any) => {
+    if (this.isMobile() && this.outerRef.current) {
```
Comment (jschuler) [inline packages/react-core/src/components/Page/Page.tsx:142]: can also add an additional check here 
```suggestion
    if (this.isMobile() && !this.state.mobileIsNavOpen && this.outerRef.current) {
```

File: packages/react-core/src/components/Page/__tests__/Generated/__snapshots__/Page.test.tsx.snap [hunk 3]
```diff
@@ -5,7 +5,7 @@ exports[`Page should match snapshot (auto-generated) 1`] = `
   value={
     Object {
       "isManagedSidebar": false,
-      "isNavOpen": false,
+      "isNavOpen": true,
```
Comment (jschuler) [inline packages/react-core/src/components/Page/__tests__/Generated/__snapshots__/Page.test.tsx.snap:8]: did something else happen that i missed

**Review by jschuler — CHANGES_REQUESTED** [review]

File: packages/react-core/src/components/Page/Page.tsx (hunk 1 above)
Comment (redallen) [reply packages/react-core/src/components/Page/Page.tsx:112]: Sure, although we lose this feature for clicking below pages that don't take up `100vh`.

File: packages/react-core/src/components/Page/__tests__/Generated/__snapshots__/Page.test.tsx.snap (hunk 3 above)
Comment (redallen) [reply packages/react-core/src/components/Page/__tests__/Generated/__snapshots__/Page.test.tsx.snap:8]: The first `handleResize` was debounced 250ms. I've fixed it.

**Review by jschuler — APPROVED** [review]

**Comment by jenny-s51** [comment]
👍

**Review by jenny-s51 — APPROVED** [review]

**Review by jschuler — APPROVED** [review]
