### PR TITLE
Pagination - accept only positive whole numbers

### LINKED ISSUE #9117: Bug - Pagination - [ACM-Search] - [Page number could accept the value with wrong format in Search]
With ACM 2.8.0, for search result, to input a page number, the input could accept some value with wrong format, such as 4. , 3- , +5. And 4. will go to the page 4; +5 will go to page 5; 3- will stay at the current page. Also, only input '.' is allowed

### PR DESCRIPTION
**Pull request by MariaAga**
**What**: Closes #9117

Adding just `step={1}` solves the whole numbers part, but users could still type `-5` `3-1` so I went with an `onKeyDown` solution

### CODE REVIEW

**Review by mcarrano — APPROVED** [review]
Looks good to me. Thanks @MariaAga !

File: packages/react-core/src/components/Pagination/Navigation.tsx [hunk 1]
```diff
@@ -113,10 +113,23 @@ export class Navigation extends React.Component<NavigationProps, NavigationState
...
+      'Home',
+      'End',
+      'ArrowUp',
+      'ArrowDown'
+    ];
     if (event.key === KeyTypes.Enter) {
       const inputPage = Navigation.parseInteger(this.state.userInputPage, lastPage) as number;
       onPageInput(event, Number.isNaN(inputPage) ? (page as number) : inputPage);
       this.handleNewPage(event, Number.isNaN(inputPage) ? (page as number) : inputPage);
+    } else if (!/^\d*$/.test(event.key) && !allowedKeys.includes(event.key)) {
```
Comment (thatblindgeye) [inline packages/react-core/src/components/Pagination/Navigation.tsx:131]: Since the event key for a digit will only ever be a single character, do we need the `*` in the regex?

```suggestion
    } else if (!/^\d$/.test(event.key) && !allowedKeys.includes(event.key)) {
```

**Review by thatblindgeye — APPROVED** [review]
Looks good, just had a comment below.

**Review by nicolethoen — APPROVED** [review]
