### PR TITLE
fix(tab): Tab component properties don't show in the docs

### LINKED ISSUE #4647: Tab component is missing documentation in React
Right now, Tabs component page does not list documentation for the Tab child component. As such I cannot at a glance see what props it accepts or what the props do

### PR DESCRIPTION
**Pull request by KKoukiou**
Closes #4647

### CODE REVIEW

File: packages/react-core/src/components/Tabs/Tab.tsx [hunk 1]
```diff
@@ -19,5 +19,23 @@ export interface TabProps extends Omit<React.HTMLProps<HTMLAnchorElement | HTMLB
...
+  // eslint-disable-next-line @typescript-eslint/no-unused-vars
+  title,
+  // eslint-disable-next-line @typescript-eslint/no-unused-vars
+  eventKey,
+  // eslint-disable-next-line @typescript-eslint/no-unused-vars
+  tabContentId,
+  // eslint-disable-next-line @typescript-eslint/no-unused-vars
+  tabContentRef,
+  // eslint-disable-next-line @typescript-eslint/no-unused-vars
+  isHidden
```
Comment (redallen) [inline packages/react-core/src/components/Tabs/Tab.tsx:39]: Instead of disabling each line you can do:
```jsx
/* eslint-disable @typescript-eslint/no-unused-vars */
...
/* eslint-enable @typescript-eslint/no-unused-vars */
```

**Review by redallen — CHANGES_REQUESTED** [review]
This PR should allow `react-docgen` to get `Tab`'s props. You can also just do `propComponents: [TabProps]` in the frontmatter to get them to show.

File: packages/react-core/src/components/Tabs/Tab.tsx (hunk 1 above)
Comment (KKoukiou) [reply packages/react-core/src/components/Tabs/Tab.tsx:39]: > This PR should allow `react-docgen` to get `Tab`'s props. You can also just do `propComponents: [TabProps]` in the frontmatter to get them to show.

Unfortunately this PR did not fix the issue, therefore i did not remove the draft from it. I quickly checked it again now, and seems the return null is the issue. Returning anything else like an empty React.Fragment makes the props work.

Comment (KKoukiou) [reply packages/react-core/src/components/Tabs/Tab.tsx:39]: propComponents: [TabProps] also does not work, it does not parse the types any more with this.

**Review by redallen — APPROVED** [review]
It works, thanks!!
image

**Review by tlabaj — APPROVED** [review]
