### PR TITLE
fix(DualListSelector): added empty state to composable examples

### LINKED ISSUE #8080: Dual list - Add empty state
**Is this a new component or an extension of an existing one?**
This is for an existing component: The dual list selector.

**Describe the feature**
Would like to add an empty state to the dual list selected that appears inside the "results" box when a search is applied that doesn't match any of the options.

**Are there visuals for this feature? If applicable, please include examples for each state and for varying widths**
No visuals, but here is a description: maybe just adding a small or xs empty state using the text and icon here: https://www.patternfly.org/v4/components/empty-state#no-match-found

Let me know if you do need a mock and I can whip one up!

cc: @nicolethoen

### PR DESCRIPTION
**Pull request by nicolethoen**
**What**: Closes #8080 

The "no results" empty state message is added to the basic composable ([link for convenience](https://patternfly-react-pr-8480.surge.sh/components/dual-list-selector#composable-dual-list-selector)) and composable tree examples ([link for convenience](https://patternfly-react-pr-8480.surge.sh/components/dual-list-selector#composable-with-tree)) when a filter is applied and all the options are being filtered out.

### CODE REVIEW

File: packages/react-core/src/components/DualListSelector/DualListSelectorPane.tsx [hunk 1]
```diff
@@ -65,6 +65,8 @@ export interface DualListSelectorPaneProps {
   searchInputAriaLabel?: string;
   /** @hide Callback for updating the filtered options in DualListSelector. To be used when isSearchable is true. */
   onFilterUpdate?: (newFilteredOptions: React.ReactNode[], paneType: string, isSearchReset: boolean) => void;
+  /** Height of the list of options rendered in the pane. **/
+  listHeight?: string;
```
Comment (thatblindgeye) [inline packages/react-core/src/components/DualListSelector/DualListSelectorPane.tsx:69]: Would something along the lines of `listMinHeight`/`listMinimumHeight` be more fitting, since it's changing the minHeight in CSS?

File: packages/react-core/src/components/DualListSelector/examples/DualListSelectorComposable.tsx [hunk 2]
```diff
@@ -141,21 +145,36 @@ export const DualListSelectorComposable: React.FunctionComponent = () => {
...
+          <EmptyState variant={EmptyStateVariant.small}>
+            <EmptyStateIcon icon={SearchIcon} />
+            <Title headingLevel="h4" size="md">
+              No results found
+            </Title>
+            <EmptyStateBody>No results match the filter criteria. Clear all filters and try again.</EmptyStateBody>
+            <Button variant="link" onClick={() => onFilterChange('', true)}>
+              Clear all filters
+            </Button>
+          </EmptyState>
```
Comment (thatblindgeye) [inline packages/react-core/src/components/DualListSelector/examples/DualListSelectorComposable.tsx:160]: Nit, not a blocker: we could take this and have it returned from a `build...` function similar to the buildSort and buildSearchInput ones since both panes are using the same empty state minus the `onFilterChange` args. That could possibly be a followup at some point if we wanted to have a buildPane function similar to the composable tree example.

**Review by thatblindgeye — COMMENTED** [review]
Looks good! There's just a couple of lint errors to resolve

**Review by kmcfaul — APPROVED** [review]
lgtm!

**Comment by mmenestr** [comment]
Looks good except that there should be 16px of spacing between the body of the empty state and the button!

**Comment by nicolethoen** [comment]
@mmenestr I think it fixed it!

**Comment by mmenestr** [comment]
@nicolethoen Looks like there's too much space now, 32px instead of the wanted 16px ha!

**Comment by mmenestr** [comment]
@nicolethoen Oh I'm sorry, I was looking at the extra small empty state variation to determine the spacing. All the empty state demos are correct, so if what you're using inside the dual list is a small empty state then you can ignore my comment, 32px is correct!

**Review by mmenestr — APPROVED** [review]

**Comment by srambach** [comment]
👍  The empty state looks ok to me. FYI, the structure of the empty state will change in v5 so when that happens, we should remember that this needs to be updated as well.

**Comment by nicolethoen** [comment]
The react follow up issue for the empty state work has not been made yet. I did leave a note in the core issue to @mcoker to be sure the dual list selector is not forgotten in the follow up issue.
