### PR TITLE
chore(a11y): update a11y tests, fix a11y errors, turn on a11y coverage

### LINKED ISSUE #6615: upgrade axe-core and add a11y coverage report to github actions
Follow up to https://github.com/patternfly/patternfly/issues/4525

### PR DESCRIPTION
**Pull request by nicolethoen**
**What**: Closes #6615

I believe to see the coverage reports run, this PR needs to be merged.

### CODE REVIEW

File: packages/react-core/src/components/Button/Button.tsx [hunk 1]
```diff
@@ -37,8 +37,12 @@ export interface ButtonProps extends Omit<React.HTMLProps<HTMLButtonElement>, 'r
   isAriaDisabled?: boolean;
   /** Adds progress styling to button */
   isLoading?: boolean;
-  /** Aria-valuetext for the loading spinner */
+  /** Text describing that current loading status or progress */
```
Comment (jeffpuzzo) [inline packages/react-core/src/components/Button/Button.tsx:40]: I think maybe *that was meant to be *the here.

**Review by jeffpuzzo — APPROVED** [review]

**Review by jessiehuff — COMMENTED** [review]
I tried to go through and test each of the changes, and as always, really impressive work Nicole!!! :) 

The only question I have is with tree view. When testing out treeview, it seems like I'm not able to get to all of the elements anymore. So for example, in this screenshot with the Default example, I wasn't able to get to "Settings" or "Current" under Application 1 or "Settings" under Application 2 or even know they're there. It reads the first "Settings" for some reason but none of the others, and it never navigates to it. I'm wondering if removing the role affected that?

A1DE77DD-1C33-45C9-A7E5-2CB9B5B47256

**Comment by nicolethoen** [comment]
Let's wait to merge this until after we wrap up the current milestone

**Review by jessiehuff — APPROVED** [review]
LGTM! :)

**Review by kmcfaul — APPROVED** [review]

File: packages/react-core/src/components/Menu/MenuList.tsx [hunk 2]
```diff
@@ -14,7 +14,7 @@ export const MenuList: React.FunctionComponent<MenuListProps> = ({
   className,
   ...props
 }: MenuListProps) => (
-  <ul role="menubar" className={css(styles.menuList, className)} {...props}>
+  <ul role="menu" className={css(styles.menuList, className)} {...props}>
```
Comment (mattnolting) [inline packages/react-core/src/components/Menu/MenuList.tsx:17]: 👍

File: packages/react-core/src/components/Menu/MenuItem.tsx [hunk 3]
```diff
@@ -265,7 +265,6 @@ export const MenuItem: React.FunctionComponent<MenuItemProps> = ({
 
   return (
     <li
-      role="none"
```
Comment (mattnolting) [inline packages/react-core/src/components/Menu/MenuItem.tsx:268]: 👍

**Review by mattnolting — APPROVED** [review]
LPTM 🚀

File: packages/react-core/src/components/Menu/MenuItem.tsx [hunk 4]
```diff
@@ -275,21 +274,21 @@ export const MenuItem: React.FunctionComponent<MenuItemProps> = ({
         className
       )}
       onMouseOver={onMouseOver}
-      tabIndex={-1}
```
Comment (mattnolting) [inline packages/react-core/src/components/Menu/MenuItem.tsx:278]: 👍

**Review by thatblindgeye — CHANGES_REQUESTED** [review]

**Review by thatblindgeye — APPROVED** [review]

**Review by thatblindgeye — APPROVED** [review]

File: .github/workflows-src/partials/docs.yml [hunk 5]
```diff
@@ -21,8 +21,8 @@ docs:
...
       if: always()
-#    - name: a11y tests
-#      run: yarn serve:docs & yarn test:a11y
-#    - name: Upload a11y results
-#      run: node .github/upload-preview.js packages/react-docs/coverage
-#      if: always()
+    - name: a11y tests
+      run: yarn serve:docs & yarn test:a11y
+    - name: Upload a11y results
+      run: node .github/upload-preview.js packages/react-docs/coverage
```
Comment (mcoker) [inline .github/workflows-src/partials/docs.yml:27]: In `upload-preview.js`, this conditional adds the a11y report comment https://github.com/patternfly/patternfly-react/blob/9de508fa1e8e0588c389c29c4d478f547544856a/.github/upload-preview.js#L72-L74

It tests for `uploadFolderName === 'dist'`, where `uploadFolderName` is the last string in the argument passed (`packages/react-docs/coverage`). So we need to update the conditional in `upload-preview.js` to test for "coverage" instead of "dist".

**Review by mcoker — CHANGES_REQUESTED** [review]
Just one thing, otherwise LGTM!

**Review by thatblindgeye — APPROVED** [review]

**Review by mcoker — APPROVED** [review]
🥳
