### PR TITLE
fix(Modal, Dropdown, TreeView): updates to resolve strict TS errors

### LINKED ISSUE #7553: Bug - Modal, DropDownItem, TreeView - strict TypeScript type checking fails
**Describe the problem**
When `strict: true` type checking is enabled in TypeScript, three modules (at least) fail to compile. This seems to be due to a few uses of `... | null`, e.g. in DropDownItem:

```typescript
    tabIndex?: number | null; <-- removing the | null part makes typescript happy
```

why does patternfly have both the `?` and the `| null`? this not only seems unnecessary duplication, but... doesn't type check.

```shell
Interface 'ModalProps' incorrectly extends interface 'HTMLProps<HTMLDivElement>'.
  Types of property ''aria-labelledby'' are incompatible.
    Type 'string | null | undefined' is not assignable to type 'string | undefined'.
      Type 'null' is not assignable to type 'string | undefined'.
```

```shell
Interface 'DropdownItemProps' incorrectly extends interface 'InternalDropdownItemProps'.
  Types of property 'tabIndex' are incompatible.
    Type 'number | null | undefined' is not assignable to type 'number | undefined'.
      Type 'null' is not assignable to type 'number | undefined'.
```

```shell
Interface 'TreeViewCheckProps' incorrectly extends interface 'Partial<InputHTMLAttributes<HTMLInputElement>>'.
  Types of property 'checked' are incompatible.
    Type 'boolean | null | undefined' is not assignable to type 'boolean | undefined'.
      Type 'null' is not assignable to type 'boolean | undefined'.
```

**How do you reproduce the problem?**
Enable strict type checking.

**Expected behavior**
Strict type checking is goodness, and should work.

**Is this issue blocking you?**
The workaround is not to use strict type checking...

**Screenshots**
n/a

**What is your environment?**
 - OS: any
 - Browser any
 - Version @patternfly/react-core@4.221.3

**What is your product and what release date are you targeting?**

**Any other information?**

### PR DESCRIPTION
**Pull request by thatblindgeye**
**What**: Closes #7553 

- Made updates based on original issue
- Resolved errors of `Cannot invoke an object which is possibly 'undefined'` for optional function props that get called within components by adding optional chaining
- Few other fixes for `possibly undefined` errors by adding optional chaining or `if` blocks

**Additional issues**:

Created #7889 for potential follow-up

### CODE REVIEW

**Review by tlabaj — APPROVED** [review]
LGTM

**Review by gitdallas — APPROVED** [review]

**Review by kmcfaul — APPROVED** [review]

File: packages/react-core/src/components/Dropdown/DropdownItem.tsx [hunk 1]
```diff
@@ -40,7 +40,7 @@ export interface DropdownItemProps extends InternalDropdownItemProps, OUIAProps
   /** Custom item rendering that receives the DropdownContext */
   customChild?: React.ReactNode;
   /** tabIndex to use, null to unset it */
```
Comment (evwilkin) [inline packages/react-core/src/components/Dropdown/DropdownItem.tsx:42]: Should this description be updated now that `null` is no longer an acceptable value?

Comment (tlabaj) [reply packages/react-core/src/components/Dropdown/DropdownItem.tsx:42]: @thatblindgeye the functionality is still the same correct? The prop will still take a null value, so a null value can still be set to unset it. 
Maybe we can add unit  for a sanity check.

Comment (thatblindgeye) [reply packages/react-core/src/components/Dropdown/DropdownItem.tsx:42]: I don't get any errors when trying to pass `tabIndex={null}` in an example file. For a unit test, would we just want to check that passing in null results in no `tabindex` attribute being applied?

**Comment by kmcfaul** [comment]
Reran the failing integration job and looks likes it all good. I ran into that on one of my PRs too, it looks like something in the tabsHorizontalOverflow tests is a bit inconsistent.

File: packages/react-core/src/components/Dropdown/DropdownItem.tsx (hunk 1 above)
Comment (tlabaj) [reply packages/react-core/src/components/Dropdown/DropdownItem.tsx:42]: @thatblindgeye yes.

Comment (evwilkin) [reply packages/react-core/src/components/Dropdown/DropdownItem.tsx:42]: Sounds good - sorry for the misunderstanding!

Comment (nicolethoen) [reply packages/react-core/src/components/Dropdown/DropdownItem.tsx:42]: If it used to accept null, and now it's going to throw an error, is that a breaking change?

Comment (thatblindgeye) [reply packages/react-core/src/components/Dropdown/DropdownItem.tsx]: Titani did mention it would be. My recent commit just now adds back `null` types to the TreeviewListItem and DropdownItem components, and adds in an `Omit...` to both to resolve the TS error being flagged in strict mode

**Review by evwilkin — APPROVED** [review]
LGTM
