### PR TITLE
fix(react-integration): no implicit any

### LINKED ISSUE #3231: Some component demos don't meet "noImplicitAny" requirements
I noticed that when a consuming typescript app uses the noImplicitAny compiler option, errors are thrown during build time. I'm seeing this issue in the following component demos in react-integration:

- [x] AboutModal/AboutModalDemo.tsx
- [x] AccordionDemo/AccordionDemo.tsx
- [x] AlertDemo/AlertDemo.tsx
- [x] ApplicationLauncherDemo/ApplicationLauncherDemo.tsx
- [x] CheckboxDemo/CheckboxDemo.tsx
- [x] ChipGroupDemo/ChipGroupDefaultIsOpenDemo.tsx
- [x] ChipGroupDemo/ChipGroupDemo.tsx
- [x] ContextSelectorDemo/ContextSelectorDemo.tsx
- [x] DataToolbarDemo/DataToolbarDemo.tsx
- [x] DonutUtilizationChartDemo/DonutUtilizationGreenStaticRightDemo.tsx
- [x] DonutUtilizationChartDemo/DonutUtilizationInvertedRightDemo.tsx
- [x] DonutUtilizationChartDemo/DonutUtilizationSimpleRightDemo.tsx
- [x] DonutUtilizationChartDemo/DonutUtilizationSimpleRightGreenDemo.tsx
- [x] DonutUtilizationChartDemo/DonutUtilizationSmallRightDemo.tsx
- [x] DonutUtilizationChartDemo/DonutUtilizationSmallStaticRightDemo.tsx
- [x] DonutUtilizationChartDemo/DonutUtilizationStaticInvertedRightDemo.tsx
- [x] DonutUtilizationChartDemo/DonutUtilizationStaticRightDemo.tsx
- [x] FormDemo/FormDemo.tsx
- [x] FormSelectDemo/FormSelectDemo.tsx
- [x] InputGroupDemo/InputGroupDemo.tsx
- [x] NavDemo/NavDemo.tsx
- [x] NotificationBadgeDemo/NotificationBadgeDemo.tsx
- [x] OptionsMenuDemo/OptionsMenuDemo.tsx
- [x] OverflowMenuDemo/OverflowMenuDemo.tsx
- [x] PaginationDemo/PaginationDemo.tsx
- [x] RadioDemo/RadioDemo.tsx
- [x] SelectDemo/SelectDemo.tsx
- [x] SwitchDemo/SwitchDemo.tsx
- [x] TableDemo/TableSelectableDemo.tsx
- [x] TableDemo/TableSortableDemo.tsx
- [x] TableDemo/TableSortableForCompoundExpandableDemo.tsx
- [x] TabsDemo/TabsDemo.tsx
- [x] TabsDemo/TabsStringEventKeyDemo.tsx
- [x] TextInputDemo/TextInputDemo.ts

Below is an example of how the error can manifest:

Screen Shot 2019-10-28 at 9 08 08 PM

### PR DESCRIPTION
**Pull request by evwilkin**
**What**: Towards #3231

This PR updates the types within the react-integration package in order to resolve noImplicitAny errors that were occurring with that setting turned on.

### CODE REVIEW

**Comment by evwilkin** [comment]
Closing in order to created combined PR to cover https://github.com/patternfly/patternfly-react/issues/3223

**Comment by evwilkin** [comment]
Thanks for the feedback @seanforyou23 , I went back and typed the majority of the `any` types to something more specific.  LMK what you think of the updates, thanks!

File: packages/react-integration/demo-app-ts/src/components/demos/ContextSelectorDemo/ContextSelectorDemo.tsx [hunk 1]
```diff
@@ -10,12 +10,12 @@ interface ContextSelectorState {
 
 export class ContextSelectorDemo extends React.Component<{}, ContextSelectorState> {
   items: string[];
-  onToggle: (event: any, isOpen: any) => void;
+  onToggle: (event: any, isOpen: boolean) => void;
```
Comment (seanforyou23) [inline packages/react-integration/demo-app-ts/src/components/demos/ContextSelectorDemo/ContextSelectorDemo.tsx]: Instead of typing the event param as `any`, can we omit the type altogether for the time being? This will make it easier to identify places where we intentionally want to use the `any` type vs places where the types just haven't been defined yet.

File: packages/react-integration/demo-app-ts/src/components/demos/DataToolbarDemo/DataToolbarDemo.tsx [hunk 2]
```diff
@@ -67,35 +69,37 @@ export class DataToolbarDemo extends React.Component<DataToolbarProps, DataToolb
     }));
   };
 
-  onInputChange = newValue => {
+  onInputChange = (newValue: string) => {
     this.setState({ inputValue: newValue });
   };
 
-  onSelect = (type, event, selection) => {
+  onSelect = (type: string, event: any, selection: string | SelectOptionObject) => {
```
Comment (seanforyou23) [inline packages/react-integration/demo-app-ts/src/components/demos/DataToolbarDemo/DataToolbarDemo.tsx]: Same question about typing event as `any`

File: packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationInvertedRightDemo.tsx [hunk 3]
```diff
@@ -3,7 +3,7 @@ import { ChartDonutUtilization } from '@patternfly/react-charts';
 
 export class DonutUtilizationInvertedRightDemo extends React.Component<{}, { used: number; spacer: string }> {
   interval: any;
-  constructor(props) {
+  constructor(props: any) {
```
Comment (seanforyou23) [inline packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationInvertedRightDemo.tsx]: Think you can use `{}` type here

File: packages/react-integration/demo-app-ts/src/components/demos/ContextSelectorDemo/ContextSelectorDemo.tsx (hunk 1 above)
Comment (evwilkin) [reply packages/react-integration/demo-app-ts/src/components/demos/ContextSelectorDemo/ContextSelectorDemo.tsx]: Removed event type

File: packages/react-integration/demo-app-ts/src/components/demos/DataToolbarDemo/DataToolbarDemo.tsx (hunk 2 above)
Comment (evwilkin) [reply packages/react-integration/demo-app-ts/src/components/demos/DataToolbarDemo/DataToolbarDemo.tsx]: Removed event type

File: packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationInvertedRightDemo.tsx (hunk 3 above)
Comment (evwilkin) [reply packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationInvertedRightDemo.tsx]: Thanks - updated

File: packages/react-integration/demo-app-ts/src/components/demos/DataToolbarDemo/DataToolbarDemo.tsx [hunk 4]
```diff
@@ -67,35 +69,37 @@ export class DataToolbarDemo extends React.Component<DataToolbarProps, DataToolb
...
-  onRiskSelect = (event, selection) => {
+  onRiskSelect = (event: React.MouseEvent | React.ChangeEvent, selection: string | SelectOptionObject) => {
     this.onSelect('risk', event, selection);
   };
 
   onDelete = (type = '', id = '') => {
     if (type) {
       this.setState(prevState => {
-        prevState.filters[type.toLowerCase()] = prevState.filters[type.toLowerCase()].filter(s => s !== id);
+        prevState.filters[type.toLowerCase()] = prevState.filters[type.toLowerCase()].filter((s: string) => s !== id);
```
Comment (seanforyou23) [inline packages/react-integration/demo-app-ts/src/components/demos/DataToolbarDemo/DataToolbarDemo.tsx]: I think `prevState` is supposed to be readonly? You could try something like

`const newState = Object.assign(prevState);` and then replace references to prevState with newState like

```js
newState.filters[type.toLowerCase()] = newState.filters[type.toLowerCase()].filter((s: string) => s !== id);
return {
  filters: newState.filters
};
```

I think if you do this for both `onDelete` and `onSelect` then we'll no longer need the `[key: string]: string[];` entry in the `Filter` interface.

Comment (evwilkin) [reply packages/react-integration/demo-app-ts/src/components/demos/DataToolbarDemo/DataToolbarDemo.tsx]: Updated onDelete in this file and in core demo, onSelect should be good as it references prevState but doesn't change it like onDelete was doing.
