### PR TITLE
Fix/3223 integration ts

### LINKED ISSUE #3223: react-integration compiler options masks type issues
Currently, our react-integration pkg serves the purpose of ensuring our documentation examples will build and compile as expected. It works great, but I recently realized [strict type checking is turned off](https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-4/react-integration/demo-app-ts/tsconfig.json#L20-L21). Because of this, issues go undetected until they are happened upon by community members. Setting `strict` to `true` is standard practice and it doesn't make sense to suggest consumers lessen their compiler strictness just to be able to consume our components.

I've increased the strictness of the checks we can without making further changes in https://github.com/patternfly/patternfly-react/pull/3222.

This leaves us needing to work through changes required to enable the following compiler options:

- [ ] strictPropertyInitialization
- [x] [noImplicitAny](https://github.com/patternfly/patternfly-react/issues/3231)
- [ ] [strictNullChecks](https://github.com/patternfly/patternfly-react/issues/3230)
- [x] [strictFunctionTypes](https://github.com/patternfly/patternfly-react/issues/3224)

### LINKED ISSUE #3224: Some component demos don't meet "strictFunctionTypes" requirements
I noticed that when a consuming typescript app uses the `strictFunctionTypes` compiler option, following certain component examples causes errors to be thrown. Below is an example of what the error looks like, a typical type mismatch from what I can tell..

Screen Shot 2019-10-28 at 3 00 24 PM

These are the component demos in the react-integration package I see that are affected.

- [x] ContextSelectorDemo/ContextSelectorDemo.tsx
- [x] SelectDemo/SelectDemo.tsx
- [x] TableDemo/TableActionsDemo.tsx
- [x] TableDemo/TableCompactExpandableDemo.tsx
- [x] TableDemo/TableSortableForCompoundExpandableDemo.tsx
- [x] TabsDemo/TabsDemo.tsx
- [x] TabsDemo/TabsStringEventKeyDemo.tsx

### LINKED ISSUE #3230: Some component demos don't meet "strictNullChecks" requirements
I noticed that when a consuming typescript app uses the `strictNullChecks` compiler option, errors are thrown during build time. I'm seeing this issue in the following component demos in react-integration:

- [ ] AccordionDemo/AccordionDemo.tsx
- [ ] DonutUtilizationChartDemo/DonutUtilizationGreenStaticRightDemo.tsx
- [ ] DonutUtilizationChartDemo/DonutUtilizationInvertedRightDemo.tsx
- [ ] DonutUtilizationChartDemo/DonutUtilizationSimpleBottomDemo.tsx
- [ ] DonutUtilizationChartDemo/DonutUtilizationSimpleDemo.tsx
- [ ] DonutUtilizationChartDemo/DonutUtilizationSimpleRightDemo.tsx
- [ ] DonutUtilizationChartDemo/DonutUtilizationSimpleRightGreenDemo.tsx
- [ ] DonutUtilizationChartDemo/DonutUtilizationSmallDemo.tsx
- [ ] DonutUtilizationChartDemo/DonutUtilizationSmallRightDemo.tsx
- [ ] DonutUtilizationChartDemo/DonutUtilizationSmallStaticBottomDemo.tsx
- [ ] DonutUtilizationChartDemo/DonutUtilizationSmallStaticDemo.tsx
- [ ] DonutUtilizationChartDemo/DonutUtilizationSmallStaticRightDemo.tsx
- [ ] DonutUtilizationChartDemo/DonutUtilizationStaticBottomDemo.tsx
- [ ] DonutUtilizationChartDemo/DonutUtilizationStaticDemo.tsx
- [ ] DonutUtilizationChartDemo/DonutUtilizationStaticInvertedRightDemo.tsx
- [ ] DonutUtilizationChartDemo/DonutUtilizationStaticRightDemo.tsx
- [ ] SelectDemo/SelectDemo.tsx
- [ ] TableDemo/TableActionsDemo.tsx
- [ ] TableDemo/TableSortableForCompoundExpandableDemo.tsx

It seems like a big list, but I think the problem for charts is the same one repeated in all of the chart demos. That said, I don't guess this will be a trivial fix.

Below is an example of how the error can manifest:

Screen Shot 2019-10-28 at 8 19 20 PM

### LINKED ISSUE #3231: Some component demos don't meet "noImplicitAny" requirements
I noticed that when a consuming typescript app uses the noImplicitAny compiler option, errors are thrown during build time. I'm seeing this issue in the following component demos in react-integration:

- [x] AboutModal/AboutModalDemo.tsx
- [x] AccordionDemo/AccordionDemo.tsx
- [x] AlertDemo/AlertDemo.tsx
- [x] ApplicationLauncherDemo/ApplicationLauncherDemo.tsx
- [x] CheckboxDemo/CheckboxDemo.tsx
- [x] ChipGroupDemo/ChipGroupDefaultIsOpenDemo.tsx
- [x] ChipGroupDemo/ChipGroupDemo.tsx
- [x] ContextSelectorDemo/ContextSelectorDemo.tsx
- [x] DataToolbarDemo/DataToolbarDemo.tsx
- [x] DonutUtilizationChartDemo/DonutUtilizationGreenStaticRightDemo.tsx
- [x] DonutUtilizationChartDemo/DonutUtilizationInvertedRightDemo.tsx
- [x] DonutUtilizationChartDemo/DonutUtilizationSimpleRightDemo.tsx
- [x] DonutUtilizationChartDemo/DonutUtilizationSimpleRightGreenDemo.tsx
- [x] DonutUtilizationChartDemo/DonutUtilizationSmallRightDemo.tsx
- [x] DonutUtilizationChartDemo/DonutUtilizationSmallStaticRightDemo.tsx
- [x] DonutUtilizationChartDemo/DonutUtilizationStaticInvertedRightDemo.tsx
- [x] DonutUtilizationChartDemo/DonutUtilizationStaticRightDemo.tsx
- [x] FormDemo/FormDemo.tsx
- [x] FormSelectDemo/FormSelectDemo.tsx
- [x] InputGroupDemo/InputGroupDemo.tsx
- [x] NavDemo/NavDemo.tsx
- [x] NotificationBadgeDemo/NotificationBadgeDemo.tsx
- [x] OptionsMenuDemo/OptionsMenuDemo.tsx
- [x] OverflowMenuDemo/OverflowMenuDemo.tsx
- [x] PaginationDemo/PaginationDemo.tsx
- [x] RadioDemo/RadioDemo.tsx
- [x] SelectDemo/SelectDemo.tsx
- [x] SwitchDemo/SwitchDemo.tsx
- [x] TableDemo/TableSelectableDemo.tsx
- [x] TableDemo/TableSortableDemo.tsx
- [x] TableDemo/TableSortableForCompoundExpandableDemo.tsx
- [x] TabsDemo/TabsDemo.tsx
- [x] TabsDemo/TabsStringEventKeyDemo.tsx
- [x] TextInputDemo/TextInputDemo.ts

Below is an example of how the error can manifest:

Screen Shot 2019-10-28 at 9 08 08 PM

### PR DESCRIPTION
**Pull request by evwilkin**
**What**:
- Towards #3223 
- Closes #3231 
- Towards #3230 
- Towards #3224 

This PR resolves typescript errors within `react-integration/demo-app-ts` related to `strictFunctionTypes` and `noImplicitAny` and enables both of these options in the `tsconfig`. 

This PR also makes progress towards errors related to `strictPropertyInitialization` and `strictNullChecks`, though both had to remain disabled pending further decisions around `null` conflicts with Victory charts types.

### CODE REVIEW

File: packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationGreenStaticRightDemo.tsx [hunk 1]
```diff
@@ -42,7 +42,7 @@ export class DonutUtilizationGreenStaticRightDemo extends React.Component<{}, {
           >
             <ChartDonutUtilization
               data={{ x: 'Storage capacity', y: used }}
-              labels={({ datum }) => (datum.x ? `${datum.x}: ${datum.y}%` : null)}
+              labels={({ datum }) => (datum.x ? `${datum.x}: ${datum.y}%` : '')}
```
Comment (dlabrecq) [inline packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationGreenStaticRightDemo.tsx:45]: This is suppose to be null to prevent the tooltip from displaying in certain scenarios. 

It's possible that it could be undefined, but an empty string is not what we want here. An empty string will cause the tooltip to display an empty box.

File: packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationInvertedRightDemo.tsx [hunk 2]
```diff
@@ -36,7 +36,7 @@ export class DonutUtilizationInvertedRightDemo extends React.Component<{}, { use
           <ChartDonutUtilization
             data={{ x: 'GBps capacity', y: used }}
             invert
-            labels={({ datum }) => (datum.x ? `${datum.x}: ${datum.y}%` : null)}
+            labels={({ datum }) => (datum.x ? `${datum.x}: ${datum.y}%` : '')}
```
Comment (dlabrecq) [inline packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationInvertedRightDemo.tsx:39]: This is suppose to be null

File: packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationSimpleBottomDemo.tsx [hunk 3]
```diff
@@ -16,7 +16,7 @@ export class DonutUtilizationSimpleBottomDemo extends React.Component {
             constrainToVisibleArea
             data={{ x: 'Storage capacity', y: 45 }}
             height={275}
-            labels={({ datum }) => (datum.x ? `${datum.x}: ${datum.y}%` : null)}
+            labels={({ datum }) => (datum.x ? `${datum.x}: ${datum.y}%` : '')}
```
Comment (dlabrecq) [inline packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationSimpleBottomDemo.tsx:19]: This is suppose to be null

File: packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationSimpleDemo.tsx [hunk 4]
```diff
@@ -12,7 +12,7 @@ export class DonutUtilizationSimpleDemo extends React.Component {
         <div style={{ backgroundColor: 'white', height: '230px', width: '500px' }}>
           <ChartDonutUtilization
             data={{ x: 'GBps capacity', y: 75 }}
-            labels={({ datum }) => (datum.x ? `${datum.x} - ${datum.y}%` : null)}
```
Comment (dlabrecq) [inline packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationSimpleDemo.tsx:15]: This is suppose to be null

File: packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationSimpleRightDemo.tsx [hunk 5]
```diff
@@ -36,7 +36,7 @@ export class DonutUtilizationSimpleRightDemo extends React.Component<{}, { used:
         <div style={{ backgroundColor: 'white', height: '230px', width: '435px' }}>
           <ChartDonutUtilization
             data={{ x: 'GBps capacity', y: used }}
-            labels={({ datum }) => (datum.x ? `${datum.x}: ${datum.y}%` : null)}
+            labels={({ datum }) => (datum.x ? `${datum.x}: ${datum.y}%` : '')}
```
Comment (dlabrecq) [inline packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationSimpleRightDemo.tsx:39]: This is suppose to be null

File: packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationSimpleRightGreenDemo.tsx [hunk 6]
```diff
@@ -39,7 +39,7 @@ export class DonutUtilizationSimpleRightGreenDemo extends React.Component<{}, {
             constrainToVisibleArea
             data={{ x: 'Storage capacity', y: used }}
             height={300}
-            labels={({ datum }) => (datum.x ? `${datum.x}: ${datum.y}%` : null)}
+            labels={({ datum }) => (datum.x ? `${datum.x}: ${datum.y}%` : '')}
```
Comment (dlabrecq) [inline packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationSimpleRightGreenDemo.tsx:42]: This is suppose to be null

File: packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationSmallDemo.tsx [hunk 7]
```diff
@@ -12,7 +12,7 @@ export class DonutUtilizationSmallDemo extends React.Component {
           <ChartDonutUtilization
             data={{ x: 'Storage capacity', y: 75 }}
             height={150}
-            labels={({ datum }) => (datum.x ? `${datum.x}: ${datum.y}%` : null)}
+            labels={({ datum }) => (datum.x ? `${datum.x}: ${datum.y}%` : '')}
```
Comment (dlabrecq) [inline packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationSmallDemo.tsx:15]: This is suppose to be null

File: packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationSmallRightDemo.tsx [hunk 8]
```diff
@@ -36,7 +36,7 @@ export class DonutUtilizationSmallRightDemo extends React.Component<{}, { used:
           <ChartDonutUtilization
             data={{ x: 'Storage capacity', y: used }}
             height={150}
-            labels={({ datum }) => (datum.x ? `${datum.x}: ${datum.y}%` : null)}
+            labels={({ datum }) => (datum.x ? `${datum.x}: ${datum.y}%` : '')}
```
Comment (dlabrecq) [inline packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationSmallRightDemo.tsx:39]: This is suppose to be null

File: packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationSmallStaticDemo.tsx [hunk 9]
```diff
@@ -11,14 +11,17 @@ export class DonutUtilizationSmallStaticDemo extends React.Component {
...
+              { x: 'Danger at 90%', y: 90 }
+            ]}
             height={175}
             labels={({ datum }) => (datum.x ? datum.x : null)}
             width={175}
           >
             <ChartDonutUtilization
               data={{ x: 'Storage capacity', y: 45 }}
-              labels={({ datum }) => (datum.x ? `${datum.x}: ${datum.y}%` : null)}
+              labels={({ datum }) => (datum.x ? `${datum.x}: ${datum.y}%` : '')}
```
Comment (dlabrecq) [inline packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationSmallStaticDemo.tsx:24]: This is suppose to be null

File: packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationSmallStaticBottomDemo.tsx [hunk 10]
```diff
@@ -28,7 +28,7 @@ export class DonutUtilizationSmallStaticBottomDemo extends React.Component {
           >
             <ChartDonutUtilization
               data={{ x: 'Storage capacity', y: 45 }}
-              labels={({ datum }) => (datum.x ? `${datum.x}: ${datum.y}%` : null)}
+              labels={({ datum }) => (datum.x ? `${datum.x}: ${datum.y}%` : '')}
```
Comment (dlabrecq) [inline packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationSmallStaticBottomDemo.tsx:31]: This is suppose to be null

File: packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationSmallStaticRightDemo.tsx [hunk 11]
```diff
@@ -29,14 +29,17 @@ export class DonutUtilizationSmallStaticRightDemo extends React.Component<{}, {
...
+              { x: 'Danger at 90%', y: 90 }
+            ]}
             height={175}
             labels={({ datum }) => (datum.x ? datum.x : null)}
             width={425}
           >
             <ChartDonutUtilization
               data={{ x: 'Storage capacity', y: used }}
-              labels={({ datum }) => (datum.x ? `${datum.x}: ${datum.y}%` : null)}
+              labels={({ datum }) => (datum.x ? `${datum.x}: ${datum.y}%` : '')}
```
Comment (dlabrecq) [inline packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationSmallStaticRightDemo.tsx:42]: This is suppose to be null

File: packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationStaticDemo.tsx [hunk 12]
```diff
@@ -11,12 +11,15 @@ export class DonutUtilizationStaticDemo extends React.Component {
...
+            data={[
+              { x: 'Warning at 60%', y: 60 },
+              { x: 'Danger at 90%', y: 90 }
+            ]}
             labels={({ datum }) => (datum.x ? datum.x : null)}
           >
             <ChartDonutUtilization
               data={{ x: 'Storage capacity', y: 45 }}
-              labels={({ datum }) => (datum.x ? `${datum.x}: ${datum.y}%` : null)}
+              labels={({ datum }) => (datum.x ? `${datum.x}: ${datum.y}%` : '')}
```
Comment (dlabrecq) [inline packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationStaticDemo.tsx:22]: This is suppose to be null

File: packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationStaticInvertedRightDemo.tsx [hunk 13]
```diff
@@ -41,7 +41,7 @@ export class DonutUtilizationStaticInvertedRightDemo extends React.Component<{},
           >
             <ChartDonutUtilization
               data={{ x: 'Storage capacity', y: used }}
-              labels={({ datum }) => (datum.x ? `${datum.x}: ${datum.y}%` : null)}
+              labels={({ datum }) => (datum.x ? `${datum.x}: ${datum.y}%` : '')}
```
Comment (dlabrecq) [inline packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationStaticInvertedRightDemo.tsx:44]: This is suppose to be null

File: packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationStaticRightDemo.tsx [hunk 14]
```diff
@@ -35,7 +35,7 @@ export class DonutUtilizationStaticRightDemo extends React.Component<{}, { used:
           >
             <ChartDonutUtilization
               data={{ x: 'Storage capacity', y: used }}
-              labels={({ datum }) => (datum.x ? `${datum.x}: ${datum.y}%` : null)}
+              labels={({ datum }) => (datum.x ? `${datum.x}: ${datum.y}%` : '')}
```
Comment (dlabrecq) [inline packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationStaticRightDemo.tsx:38]: This is suppose to be null

File: packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationGreenStaticRightDemo.tsx (hunk 1 above)
Comment (evwilkin) [reply packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationGreenStaticRightDemo.tsx:45]: Got it - thanks for the feedback here, and in the related issues!  I'll update the type to allow for null and revert these back

**Comment by evwilkin** [comment]
@dlabrecq it looks like each change requested is around the `labels` prop of the `ChartDonutUtilization` component, which (with the added `strictNullChecks`) allows returning only a string or an array of strings:

`labels?: string[] | ((data: any) => string);`

Because of this, an error is thrown if I revert the code back to return null in the examples in this PR:

```
labels={({ datum }) => (datum.x ? '${datum.x}: ${datum.y}%' : null)}
// type 'null' is not assignable to type 'string'
```

I wanted to get your feedback based on your experience with react-charts on whether I should go ahead and update this `labels?` definition in the `ChartDonutUtilization` component to allow the function to return `null` as follows:

`labels?: string[] | ((data: any) => string | null);`

...or use a workaround for these issues for now as follows (assuming this still registers `null` as needed), and log a separate issue towards react-charts to update the type outside of this PR:

`labels={({ datum }) => (datum.x ? '${datum.x}: ${datum.y}%' : ((null as unknown) as string))}`

Thanks for taking a look!

**Comment by dlabrecq** [comment]
`null` is a valid for strings, it should not need to be cast. 

Does every prop need to accept null explicitly? I didn't realize strictNullChecks was added, can we omit it?

Like I said, `undefined` might also work, but `null` is valid

**Comment by dlabrecq** [comment]
Like I said, undefined might also work, but null is valid. It should not need to be cast.

Does every prop need to define null and undefined explicitly? I didn't realize strictNullChecks was added, can we omit it?

**Comment by evwilkin** [comment]
@seanforyou23 wanted to get your feedback on @dlabrecq's feedback above on `strictNullChecks` as it's directly related to the work in this PR towards #3230 .

From my understanding, it seems better to get it up and working across the board and explicitly define it as an option for the one component where it's breaking (`ChartDonutUtilization`, which should implicitly accept `null` as a return value) or type cast if needed, but I'm just looking at the scope of this PR and thought you may have a better understanding of implications on a bigger picture - thanks!

**Comment by dlabrecq** [comment]
Is this just an issue with the demo? That is, it's the demo that's requiring the `strictNullChecks`, correct? In that case, go ahead an cast `null` or use `undefined`.

FYI, it may be more of an issue if we turn this on for react-charts itself. There are many places where null is valid. That is, these types come directly from @types/victory. Typically, if the types are not exact, it won't compile.

File: packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationSimpleDemo.tsx [hunk 15]
```diff
@@ -12,7 +12,7 @@ export class DonutUtilizationSimpleDemo extends React.Component {
...
+            labels={({ datum }) => (datum.x ? `${datum.x} - ${datum.y}%` : '')}
```
Comment (seanforyou23) [inline packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationSimpleDemo.tsx:15]: Poking around and found that if we swap the type for [labels here](https://github.com/patternfly/patternfly-react/blob/v4/packages/react-charts/src/components/ChartDonutUtilization/ChartDonutUtilization.tsx#L326) to be `labels?: string[] | ((data: any) => string | null);` then users can specify `null` as a value without throwing errors and without showing the empty tooltip box.

WDYT? @dlabrecq would this cause any problems you're aware of?

Comment (dlabrecq) [reply packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationSimpleDemo.tsx:15]: My concern is that it's not the only place where `null` and `undefined` are valid. Yes, we could change this one prop, but it doesn't address any other (pass-thru) Victory props. The demo is only touching a single point here -- we're not testing anything else.

Does this mean all strings cannot be null, unless we explicitly add null to the type? This would be contrary to the types defined by @types/victory. 

Curious what happens when we use VictoryPie directly, instead of the ChartPie component?

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/victory/index.d.ts#L1550

Comment (dlabrecq) [reply packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationSimpleDemo.tsx:15]: My concern is that it's not the only place where `null` and `undefined` are valid. Yes, we could change this one prop, but it doesn't address any other (pass-thru) Victory props. The demo is only touching a single point here -- we're not testing anything else.

Does this mean all strings cannot be null, unless we explicitly add null to the type? This would be contrary to the types defined by @types/victory. 

Curious what we would do if using VictoryPie directly, instead of the underlying ChartPie component? It appears that VictoryPie would have the same issue with the demo's strict rules.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/victory/index.d.ts#L1550

Comment (seanforyou23) [reply packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationSimpleDemo.tsx:15]: > Does this mean all strings cannot be null, unless we explicitly add null to the type?

This is a great question, and it's exactly the understanding that I was _starting_ to formulate, but wanted to verify. That does seem like what this setting is geared toward enforcing.

> This would be contrary to the types defined by @types/victory

Yea, and while we do this in other places (create our own abstraction on third party lib props), I guess we've treated Victory/charts stuff differently to this point to keep things simple/pass-through in terms of api and documentation.

> it doesn't address any other (pass-thru) Victory props

What's an example of this? If we need to support this, then we could add to the integration app an example that exercises this code path. Is it something that's easily illustrated?

Comment (dlabrecq) [reply packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationSimpleDemo.tsx:15]: There are many Victory-based props that can accept null or undefined. Unfortunately, I do not know all the use-cases, but anything related to data. My point is that enabling strict mode may cause some breakage we haven't anticipated.

Comment (seanforyou23) [reply packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationSimpleDemo.tsx:15]: I see, thanks for explaining. I knew it would be a potentially challenging thing to achieve. It does raise good discussion though. If the incoming Victory types don't work out of box in strict mode, seems like we have the options of either continuing to expose these props as-is and for PF to not support this specific strict mode for chart components, or adjust our types as necessary and possibly reduce our support of the Victory props to the subset that we feel is worth supporting and relevant to PF needs.

Victory has a large API surface area, so just brainstorming to see how we can best align it with what we're supporting on our end.

Is there another path forward I'm not thinking of? Otherwise, let me know what you think :)

Comment (dlabrecq) [reply packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationSimpleDemo.tsx:15]: Omitting Victory props probably isn't a good option. Perhaps we should discuss offline, along with the infrastructure team?

**Comment by evwilkin** [comment]
@dlabrecq @seanforyou23 reverted Victory conflicts and disabled `strictNullChecks`, which threw an error for me to also disable `strictPropertyInitialization` as it requires strictNullChecks.  I've updated the PR description to reflect these updates.

File: packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationGreenStaticRightDemo.tsx (hunk 1 above)
Comment (evwilkin) [reply packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationGreenStaticRightDemo.tsx]: Reverted this

File: packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationSimpleBottomDemo.tsx (hunk 3 above)
Comment (evwilkin) [reply packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationSimpleBottomDemo.tsx]: Reverted this

File: packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationSimpleRightDemo.tsx (hunk 5 above)
Comment (evwilkin) [reply packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationSimpleRightDemo.tsx]: Reverted this

File: packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationInvertedRightDemo.tsx (hunk 2 above)
Comment (evwilkin) [reply packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationInvertedRightDemo.tsx]: Reverted this

File: packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationSimpleDemo.tsx (hunk 4 above)
Comment (evwilkin) [reply packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationSimpleDemo.tsx]: Reverted this

File: packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationSimpleRightGreenDemo.tsx (hunk 6 above)
Comment (evwilkin) [reply packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationSimpleRightGreenDemo.tsx]: Reverted this

File: packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationSmallDemo.tsx (hunk 7 above)
Comment (evwilkin) [reply packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationSmallDemo.tsx]: Reverted this

File: packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationSmallRightDemo.tsx (hunk 8 above)
Comment (evwilkin) [reply packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationSmallRightDemo.tsx]: Reverted this

File: packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationSmallStaticDemo.tsx (hunk 9 above)
Comment (evwilkin) [reply packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationSmallStaticDemo.tsx]: Reverted this

File: packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationSmallStaticBottomDemo.tsx (hunk 10 above)
Comment (evwilkin) [reply packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationSmallStaticBottomDemo.tsx]: Reverted this

File: packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationSmallStaticRightDemo.tsx (hunk 11 above)
Comment (evwilkin) [reply packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationSmallStaticRightDemo.tsx]: Reverted this

File: packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationStaticDemo.tsx (hunk 12 above)
Comment (evwilkin) [reply packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationStaticDemo.tsx]: Reverted this

File: packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationStaticInvertedRightDemo.tsx (hunk 13 above)
Comment (evwilkin) [reply packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationStaticInvertedRightDemo.tsx]: Reverted this

File: packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationStaticRightDemo.tsx (hunk 14 above)
Comment (evwilkin) [reply packages/react-integration/demo-app-ts/src/components/demos/DonutUtilizationChartDemo/DonutUtilizationStaticRightDemo.tsx]: Reverted this
