### PR TITLE
fix(DatePicker): resolved page scrolling bug

### LINKED ISSUE #9205: Bug - Date picker - Opening the calendar for a second time randomly scrolls page
**Describe the problem**
Opening the calendar for a first time works normally, however opening it for a second time scrolls page to a random position.

**How do you reproduce the problem?**
This is happening even on the 
https://www.patternfly.org/v4/components/date-picker

**Expected behavior**
Opening the calendar should NOT  scroll to a random position.

**Is this issue blocking you?**
UX is compromised

**Screenshots**
If applicable, add screenshots to help explain the issue.

**What is your environment?**
 - OS: Fedora linux 36
 - Browser Chrome
 - Version 112.0.5615.165 (Official Build) (64-bit)

**What is your product and what release date are you targeting?**

**Any other information?**

### PR DESCRIPTION
**Pull request by thatblindgeye**
**What**: Closes #9205 

- Also resolved a bug where DatePicker wasn't properly trapping focus
- CalendarMonth no longer handles focusing the date when the popover opens; instead the FocusTrap internal to Popover handles this
- Added a new Popover example to show custom focus

Had a couple alternative approaches, but this seemed a little more flexible and utilized some of FocusTrap's built in functionality rather than trying to get CalendarMonth to handle focus correctly.

I originally tested these updates based off of https://github.com/patternfly/patternfly-react/pull/9339 and things looked good with the changes made there.

**Additional issues**:

### CODE REVIEW

File: packages/react-core/src/components/Popover/Popover.tsx [hunk 1]
```diff
@@ -390,13 +395,25 @@ export const Popover: React.FunctionComponent<PopoverProps> = ({
...
+        // We want to prevent this in case false is ever passed in.
+        initialFocus: elementToFocus || undefined,
+        checkCanFocusTrap: (containers) => new Promise((resolve) => {
+            const interval = setInterval(() => {
+              if (containers.every((container) => getComputedStyle(container).visibility !== 'hidden')) {
+                resolve();
+                clearInterval(interval);
+              }
+            }, 10);
+          }),
```
Comment (thatblindgeye) [inline packages/react-core/src/components/Popover/Popover.tsx:416]: An alternative to this is delaying when the focus trap is set to active via timeout, but that causes a delay between clicking the button to open the Popover and the element inside Popover receiving focus. Using this which is similar to something the focus-trap docs show in a demo prevents such a delay.

**Review by kmcfaul — APPROVED** [review]

**Review by nicolethoen — COMMENTED** [review]
The only odd thing I'm noticing when interacting with the datepicker with keyboard, is that after I've selected a date and open the datepicker calendar again, it autofocuses on today rather than the day I had selected.

**Review by tlabaj — APPROVED** [review]

**Review by nicolethoen — APPROVED** [review]
