### PR TITLE
fix(composable typeahead select): updated accessibility

### LINKED ISSUE #8125: Composable multiple typeahead select: VO issue
The newer composable multiple typeahead select demo isn't quite working with VO and needs an update. It will require `aria-activedescendant` most likely or something similar to the original Select.

### PR DESCRIPTION
**Pull request by thatblindgeye**
**What**: Closes #8125 

[Composable typeahead select demo](https://patternfly-react-pr-8633.surge.sh/demos/composable-menu#composable-typeahead-select)

Parts of the linked issue should be resolved by https://github.com/patternfly/patternfly-react/pull/8496 (adding functionality for select menus in Menu components) getting merged into v5 from main, and https://github.com/patternfly/patternfly-react/pull/8623 (placing the menu closer to the toggle in the DOM).

@nicolethoen regarding having options announced, I think one potential caveat of that - either as they type or when the input receives focus - is that it could possibly lead to a very verbose output. In the composable typeahead examples it isn't too bad since they only show a few options, but if the typeahead has dozens of possible options, all of them getting announced each time a thing occurs (input focus or typing), it might be a lot to sit through/constantly have to stop the announcement manually. The same would most likely apply to the multi typeahead examples with the ChipGroup. This can be tested by passing `aria-live` and `aria-atomic="true"` to the MenuList (composable examples) or ChipGroup (Select Next examples).

Another possible issue I noticed is that the "No results found" item can't be navigated to in order to tell that there are no results found. It looks like that may be the expected (or at least common?) behavior if there is no menu rendered ([ARIA authoring practices editable combobox](https://www.w3.org/WAI/ARIA/apg/example-index/combobox/combobox-autocomplete-both.html) for an example), but since we opt to include a "No result found" in the menu I updated some logic to show an alternative approach (not make it disabled, but prevent it being selected).

**Additional issues**:

### CODE REVIEW

File: packages/react-core/src/demos/ComposableMenu/examples/ComposableTypeaheadSelect.tsx [hunk 1]
```diff
@@ -100,33 +108,41 @@ export const ComposableTypeaheadSelect: React.FunctionComponent = () => {
...
         setIsMenuOpen(false);
+        setActiveItem(null);
         break;
       case 'ArrowUp':
       case 'ArrowDown':
+        event.preventDefault();
         handleMenuArrowKeys(event.key);
         break;
       default:
         !isMenuOpen && setIsMenuOpen(true);
```
Comment (thatblindgeye) [inline packages/react-core/src/demos/ComposableMenu/examples/ComposableTypeaheadSelect.tsx:134]: Something I did locally based on other implementations of this sort of component, is I removed this default case for the switch and replaced it with the following outside the switch:

```
if (/^(\w|\s)?$/.test(event.key) && !isMenuOpen) {
      setIsMenuOpen(true);
}
```

Something like this would only cause the menu to expand when a valid key is pressed (alphanumeric or Space). Right now *any* key will trigger the expansion, so Shift, Ctrl, etc.

File: packages/react-core/src/next/components/Select/examples/SelectTypeahead.tsx [hunk 2]
```diff
@@ -26,6 +26,7 @@ export const SelectBasic: React.FunctionComponent = () => {
   const [filterValue, setFilterValue] = React.useState<string>('');
```
Comment (thatblindgeye) [inline packages/react-core/src/next/components/Select/examples/SelectTypeahead.tsx:26]: @kmcfaul It doesn't seem like we need both `filterValue` and `inputValue` in this example. Was there a use case for this when the example was originally written?

File: packages/react-core/src/demos/ComposableMenu/examples/ComposableTypeaheadSelect.tsx (hunk 1 above)
Comment (gitdallas) [reply packages/react-core/src/demos/ComposableMenu/examples/ComposableTypeaheadSelect.tsx:134]: makes sense to me, seems slightly odd if it pops open when they hit shift before typing a letter. capture group isn't necessary though and i don't think it needs to allow empty (`?` makes it optional).. probably just `/^[\w ]$/` would be fine. although would we want to allow symbols and quotes and stuff? could maybe also just test `event.key.length === 1`

also, would we want to open for Backspace/Delete as well?

Comment (thatblindgeye) [reply packages/react-core/src/demos/ComposableMenu/examples/ComposableTypeaheadSelect.tsx:134]: Ah yeah there's non alphanumeric/space keys it should open for. Maybe rather than handling the menu opening when the input is typed into here, we add a conditional to the useEffect on line 38:

```
if (!isMenuOpen) {
  setIsMenuOpen(true)
}
```

Then only actual typing in the input would open it. Pressing backspace/delete in an empty input won't open it, but that could be considered one expected behavior.

Comment (gitdallas) [reply packages/react-core/src/demos/ComposableMenu/examples/ComposableTypeaheadSelect.tsx:134]: would `onTextInputChange` make sense?

then totally remove the open menu logic from keydown?

**Review by gitdallas — APPROVED** [review]

**Review by nicolethoen — APPROVED** [review]

File: packages/react-core/src/next/components/Select/examples/SelectTypeahead.tsx (hunk 2 above)
Comment (kmcfaul) [reply packages/react-core/src/next/components/Select/examples/SelectTypeahead.tsx:26]: Hm yeah I think I was just separating them logically but it's unneeded in this example. It would be useful in the case where the filtering should be done after the full search term is typed in with a search button, rather than filtering as a user types (which is what this example shows).

Comment (kmcfaul) [reply packages/react-core/src/next/components/Select/examples/SelectTypeahead.tsx:26]: We can remove one or the other

**Comment by thatblindgeye** [comment]
@gitdallas @nicolethoen I added roles to the composable demos, and those + the Select Next demos should better show the functionality with main now merged in!

**Comment by nicolethoen** [comment]
I am really impressed with all that's communicated with VO here. It'd be an awesome candidate for user testing someday to see what screen reader users think - but I like it!

**Review by kmcfaul — APPROVED** [review]
LGTM!
