### PR TITLE
fix(Menu toggle): Remove pf-m-action modifier

### LINKED ISSUE #11095: Menu toggle: pf-m-action modifier no longer needed
**Please describe the issue**
follow up to PR https://github.com/patternfly/patternfly/pull/7100

remove the `pf-m-action` modifier from the split button menu toggle.  We no longer need the 'action` variant.  consider removing the `SplitButtonOptions.variant` prop all together.

### PR DESCRIPTION
**Pull request by tlabaj**
**What**: Closes #11095

This PR does the following:
- bumps core versions to latest
- Removed the `SplitButtonOptions` interface and prop since it is no longer needed because  there is no longer a variant.  Consumers will now pass items directly to `splitButtonItems` prop
- update all demos that are impacted by new API

### CODE REVIEW

**Review by mcoker — APPROVED** [review]
L🎃TM!

**Review by edonehoo — APPROVED** [review]
content looks good!

**Review by dlabaj — COMMENTED** [review]
React code looks good to me.

File: packages/react-core/src/components/MenuToggle/examples/MenuToggleSplitButtonAction.tsx [hunk 1]
```diff
@@ -4,46 +4,37 @@ import { MenuToggleAction, MenuToggle } from '@patternfly/react-core';
...
-          <MenuToggleAction
-            id="split-button-action-secondary-example-with-toggle-button"
-            key="split-action-secondary"
-            aria-label="Action"
-          >
-            Action
-          </MenuToggleAction>
-        ]
-      }}
+      SplitButtonItems={[
```
Comment (kmcfaul) [inline packages/react-core/src/components/MenuToggle/examples/MenuToggleSplitButtonAction.tsx:29]: Needs to be lower case `s`.

**Review by kmcfaul — CHANGES_REQUESTED** [review]
Just a minor example update to get it working, otherwise lgtm. Slider also looks like it's acting fine on the preview.

**Review by evwilkin — APPROVED** [review]
LGTM

**Review by kmcfaul — APPROVED** [review]
