### PR TITLE
fix(copyclipboard): add prop for expanded by default

### LINKED ISSUE #2886: Option/Prop to add to Clipboard copy so that its expanded by default
https://github.com/patternfly/patternfly-next/issues/2228

Information at this issue above ^

### PR DESCRIPTION
**Pull request by christiemolloy**
closes #2886

### CODE REVIEW

File: packages/patternfly-4/react-core/src/components/ClipboardCopy/ClipboardCopy.tsx [hunk 1]
```diff
@@ -44,6 +44,8 @@ export interface ClipboardCopyProps extends Omit<React.HTMLProps<HTMLDivElement>
   toggleAriaLabel?: string;
   /** Flag to show if the input is read only. */
   isReadOnly?: boolean;
+  /** Flag to determine if clipboard copy is in the expanded state initially */
+  isExpanded?: boolean;
```
Comment (tlabaj) [inline packages/patternfly-4/react-core/src/components/ClipboardCopy/ClipboardCopy.tsx]: you need to add a default for this prop in 'defaultProps`
