### PR TITLE
fix(Modal): Prevent auto aria-labelledby if aria-label is passed

### LINKED ISSUE #11011: Test error: Modal being returned by `getByLabelText` queries when it shouldn't
**Please describe the issue**
In Koku we're seeing Modal being returned by `getByLabelText` queries when it isn't labelled with the query term and wasn't returned with the old label. Specifically it appears that when a modal has an aria-label it's setting the aria-labelledby automatically in a way that is self referential and causes it to turn up in queries that it shouldn't.

**Are there visuals for this issue? Please provide screenshots**
Include screenshots or links to Marvel or other mockups.
image

**Could you point to a branch or draft PR where this issue exists? Please provide a link to the code**

One example query: https://github.com/dlabrecq/koku-ui/blob/3be30d4579ecd3d9fff9693b42e03f990d906df4/src/routes/settings/costModels/costModel/updateRateModel.test.tsx#L332

**Any other information?**

Discovered while working on #10926. CC @dlabrecq for awareness.

### PR DESCRIPTION
**Pull request by wise-king-sullyman**
**What**: Closes #11011 

**Additional issues**:

### CODE REVIEW

File: packages/react-core/src/components/Modal/ModalContent.tsx [hunk 1]
```diff
@@ -72,8 +72,12 @@ export const ModalContent: React.FunctionComponent<ModalContentProps> = ({
...
-      idRefList.push(ariaLabel && boxId);
+    if (ariaLabel) {
+      // we shouldn't set an aria-labelledby attribute if we have an aria-label
+      return undefined;
+    }
+    if (boxId) {
+      idRefList.push(boxId);
     }
     if (ariaLabelledby) {
       idRefList.push(ariaLabelledby);
```
Comment (thatblindgeye) [inline packages/react-core/src/components/Modal/ModalContent.tsx:83]: We may want to only allow either boxId or aria-labelledby to be pushed to idRefList, not both. Right now the `pf-v6-c-modal-box` wrapper element may have extraneous labeling if an aria-labelledby is passed and that value references an element inside the Modal (like the [basic modal example](https://patternfly-react-pr-11012.surge.sh/components/modal#basic-modals) is doing).

So right now in that basic example, the accessible name of the `dialog` is *everything* in it, followed by its title (which is already announced). Having the `boxId` act as a fallback if both aria-label and aria-labelledby would work better. Another thing, though, is that the check we're doing in the Modal code (~line 135) isn't really necessary, because if a consumer doesn't pass an ID to the Modal then we're constructing it, so we're always applying an aria-labelledby.

Unless I'm missing a case where that `boxId` would actually never be a valid value and aria-labelledby wouldn't automatically be applied or anything.

**Review by thatblindgeye — APPROVED** [review]

**Review by tlabaj — APPROVED** [review]
Was this issue found when moving from deprecated modal.  We may want to fix in v5 branch for other migrating... thoughts?
