### PR TITLE
fix(react-drag-drop): support dynamic root element IDs in DragDropCon…

### LINKED ISSUE #12217: Bug - DragDropSort/DragDropContainer - Cannot use if react root is not id="root"
**Describe the problem**
A clear and concise description of the problem. Which components are affected?

`@patternfly/react-drag-drop` DragDropSort

**How do you reproduce the problem?**
Provide steps to reproduce. A [codesandbox](https://codesandbox.io/s/serverless-cherry-q9t3f ) demonstrating the problem is appreciated.

Try using the component when with the react root being id='app' instead of id='root'

**Expected behavior**
A clear and concise description of the expected behavior.

It works

**Is this issue blocking you?**
List the workaround if there is one.

Yes, we cannot adopt `@patternfly/react-drag-drop` otherwise

**Screenshots**
If applicable, add screenshots to help explain the issue.

https://github.com/patternfly/patternfly-react/blob/884ad17d2ec8d71239e2f4f86b5fbc4fd4cc8196/packages/react-drag-drop/src/components/DragDrop/DragDropContainer.tsx#L302

**What is your product and what release date are you targeting?**

OCP 4.22

**Any other information?**

---

**Jira Issue:** [PF-3465](https://issues.redhat.com/browse/PF-3465)

### PR DESCRIPTION
**Pull request by arpanroy41**
Fixes #12217

- Replace hardcoded document.getElementById('root') with dynamic root element lookup
- Add getRootElement() helper that tries common root IDs: 'root', 'app', 'main', '__next'
- Fallback to document.body if no common root element is found
- Enables usage in applications with non-standard root element IDs (e.g., id="app")

This fix allows OCP 4.22 and other applications to use @patternfly/react-drag-drop regardless of their React root element configuration.

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved drag-and-drop overlay mounting by dynamically locating the app root for portal creation, ensuring overlays render correctly across different project setups and build configurations.

### CODE REVIEW

File: packages/react-drag-drop/src/components/DragDrop/DragDropContainer.tsx [hunk 1]
```diff
@@ -288,6 +288,21 @@ export const DragDropContainer: React.FunctionComponent<DragDropContainerProps>
...
+    const commonRootIds = ['root', 'app', 'main', '__next'];
+    for (const id of commonRootIds) {
+      const element = document.getElementById(id);
+      if (element) {
+        return element;
+      }
+    }
+    // Fallback to document.body if no common root is found
+    return document.body;
+  };
```
[the remark this answers is not in the document]
Comment (arpanroy41) [reply packages/react-drag-drop/src/components/DragDrop/DragDropContainer.tsx]: - Cases like `my-app` and `container` will be covered under the fallback approach `document.body`
- `main` as id is common for web applications. It represents the parent component. Thus Portaling into it will render the correct layout. But, we can test on various combinations although.

File: packages/react-drag-drop/src/components/DragDrop/DragDropContainer.tsx [hunk 2]
```diff
@@ -288,6 +288,21 @@ export const DragDropContainer: React.FunctionComponent<DragDropContainerProps>
   };
 
   const dragOverlay = <DragOverlay>{activeId && getDragOverlay()}</DragOverlay>;
+
+  // Find the React root element dynamically instead of hardcoding 'root'
+  const getRootElement = () => {
```
Comment (nicolethoen) [inline packages/react-drag-drop/src/components/DragDrop/DragDropContainer.tsx]: I am a little concerned that you are looking up the root id possibly over and over the way this is written when it shouldn't ever change. I think it can be memoized to be a bit more optimized:

```
  // Find the React root element dynamically instead of hardcoding 'root'
  const rootElement = useMemo(() => {
    // Try common root element IDs
    const commonRootIds = ['root', 'app', 'main', '__next'];
    for (const id of commonRootIds) {
      const element = document.getElementById(id);
      if (element) {
        return element;
      }
    }
    // Fallback to document.body if no common root is found
    return document.body;
  }, []); // Empty deps - root element doesn't change after mount

```

Comment (arpanroy41) [reply packages/react-drag-drop/src/components/DragDrop/DragDropContainer.tsx]: @nicolethoen This makes more sense. Yes we have to memoize this. let me modify the code

Comment (arpanroy41) [reply packages/react-drag-drop/src/components/DragDrop/DragDropContainer.tsx]: Pushed the new changes. Thank you for your suggestion @nicolethoen

**Comment by arpanroy41** [comment]
@nicolethoen Can you please rerun the `upload accessibility results` and `upload documentation` actions?

File: packages/react-drag-drop/src/components/DragDrop/DragDropContainer.tsx [hunk 3]
```diff
@@ -288,6 +288,25 @@ export const DragDropContainer: React.FunctionComponent<DragDropContainerProps>
...
   const dragOverlay = <DragOverlay>{activeId && getDragOverlay()}</DragOverlay>;
+
+  // Find the React root element dynamically instead of hardcoding 'root'
+  // Memoized to avoid looking up the root element on every render
+  const rootElement = useMemo(() => {
+    if (!canUseDOM) {
+      return null;
+    }
+    // Try common root element IDs
+    const commonRootIds = ['root', 'app', 'main', '__next'];
```
Comment (nicolethoen) [inline packages/react-drag-drop/src/components/DragDrop/DragDropContainer.tsx]: I've been thinking about this more. PatternFly's established pattern for this is an appendTo prop (used by Modal, Popover, Tooltip). This way we aren't trying to guess what the rootId would be at all.

A cleaner fix would be:

In the interface:
```
/** The parent container to append the drag overlay to. Defaults to
  document.body. */
  +  appendTo?: HTMLElement | (() => HTMLElement);
```

in the default props: 
` appendTo = () => document.body,`

In usage rather than lines 292 - 308:
```
  const portalTarget = appendTo
    ? (typeof appendTo === 'function' ? appendTo() : appendTo)
    : document.body;
```

then in the return statement, update line 321 to:
```
{canUseDOM && portalTarget ? ReactDOM.createPortal(dragOverlay,
  portalTarget) : dragOverlay}
```

Comment (arpanroy41) [reply packages/react-drag-drop/src/components/DragDrop/DragDropContainer.tsx]: I understood your point. This will make the component more dynamic and flexible. Changed the code accordingly.
