### PR TITLE
fix(CodeEditor): use codeEditorControls and clean up overall

### LINKED ISSUE #7884: Bug - CodeEditor - CodeEditorControl needs clean up
- [`<CodeEditor>` actions](https://github.com/patternfly/patternfly-react/blob/cbdc5af739f7e9d074dc0012497e85b1efa25180/packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx#L557-L568) are built using `<Tooltip>` and `<Button>` and we have this fancy pants [`<CodeEditorControl>` component](https://github.com/patternfly/patternfly-react/blob/main/packages/react-code-editor/src/components/CodeEditor/CodeEditorControl.tsx), so we have a lot of unnecessary duplication in the code editor, and in this example toolbar. Ideally we would use `<CodeEditorControl>` for all the things.
- `<CodeEditorControl>` has a lot of props that are redundantly redefined or different (that might not need to be?) from `<Tooltip>`'s defaults. For example
  - [entryDelay: 300](https://github.com/patternfly/patternfly-react/blob/cbdc5af739f7e9d074dc0012497e85b1efa25180/packages/react-code-editor/src/components/CodeEditor/CodeEditorControl.tsx#L48) is tooltip's default
  - [exitDelay: 0](https://github.com/patternfly/patternfly-react/blob/cbdc5af739f7e9d074dc0012497e85b1efa25180/packages/react-code-editor/src/components/CodeEditor/CodeEditorControl.tsx#L47) is different (tooltip's is 300) - does it need to be different?
  - [position: top](https://github.com/patternfly/patternfly-react/blob/cbdc5af739f7e9d074dc0012497e85b1efa25180/packages/react-code-editor/src/components/CodeEditor/CodeEditorControl.tsx#L50) is tooltip's default
  - and so on...
  - As a side note, ideally we would just leave all of these redundant props unset if they aren't passed, so `<CodeEditorControl>` stays in sync with `<Tooltip>`
- [`<CodeEditorControl>` hardcodes the tooltip's trigger prop](https://github.com/patternfly/patternfly-react/blob/cbdc5af739f7e9d074dc0012497e85b1efa25180/packages/react-code-editor/src/components/CodeEditor/CodeEditorControl.tsx#L63). That should be configurable with a trigger prop on `<CodeEditorControl>`.
- You should probably be able to pass tooltipProps or something to `<CodeEditorControl>` that gets passed along to `<Tooltip>`.
- Does `<CodeEditorControl>` need to set maxWidth: 100px? That's pretty narrow. Could that just use tooltip's default?
- It's probably covered with the context above, but the [example's copy code button](https://github.com/patternfly/patternfly-org/blob/9298e0ede6347f0b1ced12de5c2c924d8859d163/packages/documentation-framework/components/example/exampleToolbar.js#L89) needs a tooltip on focus at least.
- Why don't the exitDelay and "reset tooltip text" times sync up? They're different - they're 1600 exitDelay, and text resets at 2500. If you set them to the same, the text resets before the tooltip disappears. I found this in a few spots:
  - [Example toolbar exitDelay](https://github.com/patternfly/patternfly-org/blob/9298e0ede6347f0b1ced12de5c2c924d8859d163/packages/documentation-framework/components/example/exampleToolbar.js#L91) and [reset text](https://github.com/patternfly/patternfly-org/blob/9298e0ede6347f0b1ced12de5c2c924d8859d163/packages/documentation-framework/components/example/exampleToolbar.js#L52)
  - Code editor's [exitDelay](https://github.com/patternfly/patternfly-react/blob/cbdc5af739f7e9d074dc0012497e85b1efa25180/packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx#L262) and [reset text](https://github.com/patternfly/patternfly-react/blob/cbdc5af739f7e9d074dc0012497e85b1efa25180/packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx#L447)
  - Copy clipboard's [exitDelay](https://github.com/patternfly/patternfly-react/blob/cbdc5af739f7e9d074dc0012497e85b1efa25180/packages/react-core/src/components/ClipboardCopy/ClipboardCopy.tsx#L114) and [reset text](https://github.com/patternfly/patternfly-react/blob/cbdc5af739f7e9d074dc0012497e85b1efa25180/packages/react-core/src/components/ClipboardCopy/ClipboardCopy.tsx#L116) (I think that's it anyways, and it's 2000 instead of 2500)
- We use execCommand('copy') in all of these places, like https://github.com/patternfly/patternfly-org/blob/main/packages/documentation-framework/helpers/copy.js
  - That's officially deprecated - https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand
  - That method calls for adding a form element to the DOM, and calling .select() on it to copy the text. .select() steals the browser focus, so clicking on the copy button doesn't manage focus the same way other buttons do. IMO, unless the stuff you're copying is 1) in a form element already, and 2) visibly selected, focus should be maintained on the element that triggered the copy command. It's most visible when you click the copy button at the end of any of our examples, then hit tab - that uses copy.js linked above, which appends the form element to `<body>`, so hitting tab takes you to the "skip to content" button.
  - [navigator.clipboard()](https://github.com/patternfly/patternfly-org/pull/3162) seems widely supported for regular text anyways. Could we use that instead?
    - I made this codepen to test - https://codepen.io/mcoker/pen/MWVdOPE

### PR DESCRIPTION
**Pull request by nicolethoen**
**What**: Closes #7884 

- we now use `<CodeEditorControl>` for all dynamically built controls in CodeEditor.tsx.
- we now pass tooltipProps to `<CodeEditorControl>` that gets passed along to `<Tooltip>`.
- Code editor now uses tooltip's default prop values unless consumer overrides them with tooltipProps
- Deprecated the previous prop that were passed to the tooltip (they still work)
- Copy to clipboard button in the code editor now triggers with keyboard focus
- created a callback so that the 'copied to clipboard' success text can be reverted back only after the tooltip closes (prevents timings from getting out of sync and the text reverting back right before the tooltip closes)
- Updated copy functions to use `navigator.clipboard()` (keeps broswer focus on the copy button once clicked)
- adds similar features to the code block examples so the 'copied to clipboard!' text reverts back after the tooltip closes

### CODE REVIEW

**Review by thatblindgeye — APPROVED** [review]
This looks good! a11y wise the tooltips trigger when receiving focus (for code editor, I tested using the "With actions" example where the copy button appears after clicking "start from scratch"), and focus retention is definitely an improvement 💪🏼 

I had a couple of comments below, but neither are blocking

File: packages/react-core/src/components/Tooltip/Tooltip.tsx [hunk 1]
```diff
@@ -230,20 +230,27 @@ export const Tooltip: React.FunctionComponent<TooltipProps> = ({
...
   const show = () => {
     clearTimeouts([transitionTimerRef, hideTimerRef]);
     showTimerRef.current = setTimeout(() => {
       setVisible(true);
       setOpacity(1);
     }, entryDelay);
   };
-  const hide = () => {
-    clearTimeouts([showTimerRef]);
+  const hide = React.useCallback(() => {
```
[the remark this answers is not in the document]
Comment (nicolethoen) [reply packages/react-core/src/components/Tooltip/Tooltip.tsx:247]: `useCallback` is a way to memoize the execution of a function unless the value of one of its dependencies changes. 

In this case, I want to be sure that the _current_ hideTimerRef is always using the current `exitDelay`, and since that can be updated by the user dynamically (as in the case of the copy buttons) i need to basically redefine the body of this `hide` callback function whenever the `exitDelay` is updated.

[the remark this answers is not in the document]
Comment (thatblindgeye) [reply packages/react-core/src/components/Tooltip/Tooltip.tsx:247]: Gotcha, thanks for that info!

File: packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx [hunk 2]
```diff
@@ -438,8 +438,7 @@ export class CodeEditor extends React.Component<CodeEditorProps, CodeEditorState
       window.clearTimeout(this.timer);
       this.setState({ copied: false });
     }
-    this.editor?.focus();
-    document.execCommand('copy');
+    navigator.clipboard.writeText(this.state.value);
```
Comment (mcoker) [inline packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx:441]: 🥳

**Review by mcoker — COMMENTED** [review]
This is awesome! A few observations, not sure if any are problems.

Clipboard copy exit behavior is a bit different after you click to copy.
* When I click to copy, switch tabs, then come back to the tab with the tooltip, the tooltip shows.
  * Actually this is happening everywhere. Seems to be because the tooltip trigger has focus.
* If you click "copy" (the tooltip then displays "copied"), then wait a second before moving your mouse away, the text will change to "copy" again before hiding. Or for a really fun time, click it and keep moving your mouse on and off the button and the tooltip never goes away! I'm not sure if that's preferred over the current behavior? Or if that could be seen as a bug or a bug fix?
  * Code editor does this, too, but is doing that on main now currently, too.

This looks like a pre-existing thing, but the code block copy button's tooltip seems to always say "successfully copied to clipboard" after you click it - it never resets. Should it?

**Comment by nicolethoen** [comment]
> Clipboard copy exit behavior is a bit different after you click to copy.
> 
> * When I click to copy, switch tabs, then come back to the tab with the tooltip, the tooltip shows.
>   
>   * Actually this is happening everywhere. Seems to be because the tooltip trigger has focus.

I do believe that's happening because the timeout doesn't get triggered to start until you move focus off the tooltip, or mouseout of the tooltip. I think that's intended? 

> * If you click "copy" (the tooltip then displays "copied"), then wait a second before moving your mouse away, the text will change to "copy" again before hiding. Or for a really fun time, click it and keep moving your mouse on and off the button and the tooltip never goes away! I'm not sure if that's preferred over the current behavior? Or if that could be seen as a bug or a bug fix?
>
>   * Code editor does this, too, but is doing that on main now currently, too.

I can tweak the timeouts of the updated text a little further. 

> This looks like a pre-existing thing, but the code block copy button's tooltip seems to always say "successfully copied to clipboard" after you click it - it never resets. Should it?

hm... that might be out of scope. But I can see how easy that'd be to update. Maybe I can roll it in.

**Comment by nicolethoen** [comment]
> > Clipboard copy exit behavior is a bit different after you click to copy.
> > 
> > * When I click to copy, switch tabs, then come back to the tab with the tooltip, the tooltip shows.
> >   
> >   * Actually this is happening everywhere. Seems to be because the tooltip trigger has focus.
> 
> I do believe that's happening because the timeout doesn't get triggered to start until you move focus off the tooltip, or mouseout of the tooltip. I think that's intended?
> 
> > * If you click "copy" (the tooltip then displays "copied"), then wait a second before moving your mouse away, the text will change to "copy" again before hiding. Or for a really fun time, click it and keep moving your mouse on and off the button and the tooltip never goes away! I'm not sure if that's preferred over the current behavior? Or if that could be seen as a bug or a bug fix?
> >   
> >   * Code editor does this, too, but is doing that on main now currently, too.
> 
> Given that the 'Copied' text is on its own timer, and it does not get reset when you do things like move your mouse away from the trigger or move focus off the trigger, it's inevitable that the more time you spend restarting the tooltip hide timer by moving your mouse over the trigger, or by returning focus to the trigger, that the 'copied' text will timeout before the tooltip itself.
> 
> > This looks like a pre-existing thing, but the code block copy button's tooltip seems to always say "successfully copied to clipboard" after you click it - it never resets. Should it?
> 
> hm... that might be out of scope. And the setting of the 'copied' text is completely consumer controlled. So it's completely configurable.

**Comment by mcoker** [comment]
> I do believe that's happening because the timeout doesn't get triggered to start until you move focus off the tooltip, or mouseout of the tooltip. I think that's intended?

Yeah it makes sense why it's happening, it's just a bit odd? In case I didn't describe it well, here's a recording. I'm just clicking to copy, waiting for the tooltip to disappear, then going to another tab and coming back - the tooltip fires again when I switch back.

**Comment by mcoker** [comment]
> Given that the 'Copied' text is on its own timer, and it does not get reset when you do things like move your mouse away from the trigger or move focus off the trigger, it's inevitable that the more time you spend restarting the tooltip hide timer by moving your mouse over the trigger, or by returning focus to the trigger, that the 'copied' text will timeout before the tooltip itself.

Works for me and makes sense, it's just different than the current behavior. Seems like the current timeout for the "copied" text closes the tooltip without considering any hover behavior that would reset the tooltip timer as it does now.

**Review by mcoker — COMMENTED** [review]
LGTM, though I'm still seeing the behavior where I focus on something to show a tooltip (click a button), mouse away (tooltip hides), switch tabs, then switch back to the tab with the tooltip, and the tooltip fires after whatever the `entryDelay` is because it still has focus and doesn't disappear until I do something to trigger it to hide (mouse my mouse over/off of it, focus somewhere else, etc) - even though it was previously hidden. I think that's going to be unexpected and potentially like a bug.

**Comment by nicolethoen** [comment]
I'll dig a little deeper

**Review by mcoker — APPROVED** [review]
This is awesome! As discussed, the copy button tooltips re-appearing when you are focused on an element and switch browser tab focus is likely a bug fix and is consistent with how the tooltip component works now.

**Review by kmcfaul — APPROVED** [review]
Looks good! Just needs a minor lint fix for the build

**Review by wise-king-sullyman — APPROVED** [review]
Looks great to me as well other than the small changes needed to pass CI!

**Review by thatblindgeye — APPROVED** [review]

File: packages/react-code-editor/src/components/CodeEditor/CodeEditorControl.tsx [hunk 3]
```diff
@@ -7,19 +7,19 @@ import { CodeEditorContext } from './CodeEditorUtils';
  */
 
 export interface CodeEditorControlProps extends Omit<ButtonProps, 'onClick'> {
-  /** Accessible label for the code editor control. */
+  /** Accessible label for the code editor control */
   'aria-label'?: string;
   /** Additional classes added to the code editor control. */
   className?: string;
-  /** Delay in ms before the tooltip appears. */
+  /** @deprecated  Delay in ms before the tooltip appears. */
```
Comment (tlabaj) [inline packages/react-code-editor/src/components/CodeEditor/CodeEditorControl.tsx:14]: Can you open an issue to remove these for breaking change release please.

File: packages/react-core/src/components/ClipboardCopy/ClipboardCopy.tsx [hunk 4]
```diff
@@ -76,7 +70,7 @@ export interface ClipboardCopyProps extends Omit<React.HTMLProps<HTMLDivElement>
   exitDelay?: number;
   /** Delay in ms before the tooltip appears. */
   entryDelay?: number;
-  /** Delay in ms before the tooltip message switch to hover tip. */
+  /** @deprecated Delay in ms before the tooltip message switch to hover tip. */
```
Comment (tlabaj) [inline packages/react-core/src/components/ClipboardCopy/ClipboardCopy.tsx:73]: Why is this being deprecated?  Was its only purpose for the Code editor.  Could consumers be relying on it?

**Review by tlabaj — CHANGES_REQUESTED** [review]

File: packages/react-core/src/components/ClipboardCopy/ClipboardCopy.tsx (hunk 4 above)
Comment (nicolethoen) [reply packages/react-core/src/components/ClipboardCopy/ClipboardCopy.tsx:73]: It's being deprecated because of a subtle change in how the three components with a copy feature are handling toggling their tooltip text between 'copy' and 'copied' (or some similar variant).

Before this change, each of the three copy components were handling it differently. CodeBlock was never changing its 'copied' text back to 'copy'. CodeEditor had it hardcoded so that the text changed after 2500 milliseconds. And ClipBoardCopy was using this switchDelay value. 

In the later two cases, these timers caused some weird cases where the 'copied' text would switch back before the tooltip closed and cause the text to quickly update before it closed (sometimes with barely enough time for a user to read it, and that is a bit jarring when it happens). I spent some time trying to tweak timers to figure out how to avoid it, but ultimately, since the user can keep the tooltip open for an indeterminate amount of time by interacting with the tooltip's toggle, it was never going to work ideally with timers.

My solution was to wire all three components to trigger the switch between the 'copied' and 'copy' text only when the close transition has completed. That's now handled internally by the function passed to the `onTooltipHidden` on line 210 of clipboardCopy.tsx. So the switchDelay prop no longer does anything in ClipboardCopy.

**Comment by nicolethoen** [comment]
@tlabaj I added the console warnings, but also will address [this org issue](https://github.com/patternfly/patternfly-org/issues/3235) I created as soon as this merges to suppress those console warnings coming from the documentation-framework. 
It was a first attempt at clean up work from a month ago in the documentation-framework that prompted this clean up in the first place.

File: packages/react-code-editor/src/components/CodeEditor/CodeEditorControl.tsx [hunk 5]
```diff
@@ -35,41 +35,84 @@ export interface CodeEditorControlProps extends Omit<ButtonProps, 'onClick'> {
...
   isVisible = true,
+  tooltipProps = {},
   ...props
 }: CodeEditorControlProps) => {
   const context = React.useContext(CodeEditorContext);
 
+  if (entryDelay !== undefined) {
+    // eslint-disable-next-line no-console
+    console.warn(
+      'The CodeEditorControl entryDelay prop has been deprecated. ' +
```
Comment (tlabaj) [inline packages/react-code-editor/src/components/CodeEditor/CodeEditorControl.tsx:67]:
```suggestion
      'CodeEditorControl: entryDelay prop has been deprecated. ' +
```

File: packages/react-code-editor/src/components/CodeEditor/CodeEditorControl.tsx [hunk 6]
```diff
@@ -35,41 +35,84 @@ export interface CodeEditorControlProps extends Omit<ButtonProps, 'onClick'> {
...
+        'Pass the entryDelay via the tooltipProps prop instead.'
+    );
+  }
+
+  if (exitDelay !== undefined) {
+    // eslint-disable-next-line no-console
+    console.warn(
+      'The CodeEditorControl exitDelay prop has been deprecated. ' +
```
Comment (tlabaj) [inline packages/react-code-editor/src/components/CodeEditor/CodeEditorControl.tsx:75]:
```suggestion
      'CodeEditorControl: exitDelay prop has been deprecated. ' +
```

File: packages/react-code-editor/src/components/CodeEditor/CodeEditorControl.tsx [hunk 7]
```diff
@@ -35,41 +35,84 @@ export interface CodeEditorControlProps extends Omit<ButtonProps, 'onClick'> {
...
+        'Pass the exitDelay via the tooltipProps prop instead.'
+    );
+  }
+
+  if (maxWidth !== undefined) {
+    // eslint-disable-next-line no-console
+    console.warn(
+      'The CodeEditorControl maxWidth prop has been deprecated. ' +
```
Comment (tlabaj) [inline packages/react-code-editor/src/components/CodeEditor/CodeEditorControl.tsx:83]:
```suggestion
      'CodeEditorControl: maxWidth prop has been deprecated. ' +
```

File: packages/react-code-editor/src/components/CodeEditor/CodeEditorControl.tsx [hunk 8]
```diff
@@ -35,41 +35,84 @@ export interface CodeEditorControlProps extends Omit<ButtonProps, 'onClick'> {
...
+    console.warn(
+      'The CodeEditorControl position prop has been deprecated. ' +
+        'Pass the position via the tooltipProps prop instead.'
+    );
+  }
+
+  if (toolTipText !== undefined) {
+    // eslint-disable-next-line no-console
+    console.warn(
+      'The CodeEditorControl toolTipText prop has been deprecated. ' +
```
Comment (tlabaj) [inline packages/react-code-editor/src/components/CodeEditor/CodeEditorControl.tsx:99]:
```suggestion
      'CodeEditorControl: toolTipText prop has been deprecated. ' +
```

File: packages/react-code-editor/src/components/CodeEditor/CodeEditorControl.tsx [hunk 9]
```diff
@@ -35,41 +35,84 @@ export interface CodeEditorControlProps extends Omit<ButtonProps, 'onClick'> {
...
+    console.warn(
+      'The CodeEditorControl maxWidth prop has been deprecated. ' +
+        'Pass the maxWidth via the tooltipProps prop instead.'
+    );
+  }
+
+  if (position !== undefined) {
+    // eslint-disable-next-line no-console
+    console.warn(
+      'The CodeEditorControl position prop has been deprecated. ' +
```
Comment (tlabaj) [inline packages/react-code-editor/src/components/CodeEditor/CodeEditorControl.tsx:91]:
```suggestion
      'CodeEditorControl: position prop has been deprecated. ' +
```

File: packages/react-core/src/components/ClipboardCopy/ClipboardCopy.tsx [hunk 10]
```diff
@@ -100,6 +94,14 @@ export class ClipboardCopy extends React.Component<ClipboardCopyProps, Clipboard
       expanded: this.props.isExpanded,
       copied: false
     };
+
+    if (this.props.switchDelay !== undefined) {
+      // eslint-disable-next-line no-console
+      console.warn(
+        'The ClipboardCopy switchDelay prop has been deprecated. ' +
```
Comment (tlabaj) [inline packages/react-core/src/components/ClipboardCopy/ClipboardCopy.tsx:101]:
```suggestion
        'ClipboardCopy: switchDelay prop has been deprecated. ' +
```

**Review by tlabaj — CHANGES_REQUESTED** [review]
a few nit comments

**Review by tlabaj — APPROVED** [review]
LGTM!
