### PR TITLE
fix(button): component type should accept react-router Link

### LINKED ISSUE #2980: Button shows error in console on reload
When I go to a page that has a button the page loads fine without any error in the console.  However, when I refresh the page I get a console error. `Warning: Failed prop type: Invalid prop component supplied to `Button`, expected a ReactNode.`

Button Bug

### PR DESCRIPTION
**Pull request by boaz0**
**What**:

closes #2980 

ReactNode is any of the following types: `ReactChild`, `ReactFragment`, `ReactPortal`, `boolean`, `null`, `undefined`.[1]

While `Link` is a component type: `ComponentClass` or `FunctionComponent`.[2]

This PR adds `ComponentType` to the type of `component`. I did set it to `any` to allow other router components in the future or a custom router link. But if we want to support only react-router `Link` I can add a specific type to the component type there.

[1]https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L191
[2]https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L71

//cc @AlexSCorey

### CODE REVIEW

File: packages/patternfly-4/react-core/src/components/Button/Button.tsx [hunk 1]
```diff
@@ -25,7 +25,7 @@ export interface ButtonProps extends React.HTMLProps<HTMLButtonElement> {
   /** Additional classes added to the button */
   className?: string;
   /** Sets the base component to render. defaults to button */
-  component?: React.ReactNode;
+  component?: React.ReactNode | React.ComponentType<any>;
```
Comment (redallen) [inline packages/patternfly-4/react-core/src/components/Button/Button.tsx]: Does just `component?: React.Element` work? I _think_ it should and that it's the better type to use.

Comment (boaz0) [reply packages/patternfly-4/react-core/src/components/Button/Button.tsx]: I assume you meant `React.ElementType`.

Comment (redallen) [reply packages/patternfly-4/react-core/src/components/Button/Button.tsx]: Yessir!
