### PR TITLE
fix(Select): display selections data properly

### LINKED ISSUE #2828: [PF4] Changing selections value outside Select does not update correctly in Select component
Changing the `selections` prop outside the Select component does not update the component correctly. In typeahead, it shows the clear icon but does not show the text for the selected item. Clicking dropdown and then closing it makes it show up.

## Expected Results
Selected item is shown

## Actual results
Selected item is not shown

## Reproducible sandbox
This sandbox has a timeout of 2 seconds after mounted where it changes the selection. This is reflected in the UI with the clear icon showing.
https://codesandbox.io/s/modern-sky-2zhnh

### PR DESCRIPTION
**Pull request by SpyTec**
**What**: This fixes `selections` prop being properly displayed if updated externally.

**Additional issues**: Fixes #2828

### CODE REVIEW

File: packages/patternfly-4/react-core/src/components/Select/Select.tsx [hunk 1]
```diff
@@ -120,6 +120,12 @@ export class Select extends React.Component<SelectProps, SelectState> {
         typeaheadFilteredChildren: React.Children.toArray(this.props.children)
       });
     }
+
+    if (prevProps.selections !== this.props.selections) {
```
Comment (redallen) [inline packages/patternfly-4/react-core/src/components/Select/Select.tsx]: Change to `if (prevProps.selections !== this.props.selections && this.state.typeaheadActiveChild) {`

File: packages/patternfly-4/react-core/src/components/Select/Select.tsx [hunk 2]
```diff
@@ -120,6 +120,12 @@ export class Select extends React.Component<SelectProps, SelectState> {
...
+      this.setState({
+        typeaheadInputValue: (this.state.typeaheadActiveChild && this.state.typeaheadActiveChild.innerText)
```
Comment (redallen) [inline packages/patternfly-4/react-core/src/components/Select/Select.tsx]: Change to `typeaheadInputValue: this.state.typeaheadActiveChild.innerText`.

**Comment by SpyTec** [comment]
Thanks @redallen, moved check in the latest commit :)
