### PR TITLE
fix(ProgressStepper): added onTriggerEnter prop to Popover

### LINKED ISSUE #7200: ProgressStepper - Popovers should be interactive via keyboard
**Is this a new component or an extension of an existing one?**
Existing

**Describe the feature**
For the [Progress Stepper with Popover](https://www.patternfly.org/v4/components/progress-stepper#with-help-popover) example, the popovers can only be opened via mouse click or with Voice Over's VO + Space keyboard interaction (which acts as a click event I believe). Using just the keyboard, the popover cannot be opened with the Enter or Space keys like a button normally should.

The issue might be due to the fact that when a Popover is rendered for a ProgressStep it renders a `<span>` with a role attribute and value of "button" rather than a native `<button>` element. Using a `<button>` element might require a similar fix to be made in Core, however.

**Are there visuals for this feature? If applicable, please include examples for each state and for varying widths**
N/A

**Any other information?**
N/A

### PR DESCRIPTION
**Pull request by andyyvo**
**What**: Closes #7200 . The `Popover` for the `ProgressStepper` component can now be accessed via the keyboard using **Space** and **Enter** keys. The issue was due to the `Popover` component not utilizing the `onTriggerEnter` prop in **Popover.tsx**. It now works like a native button but in a discussion with @thatblindgeye , this issue could be resolved in core by changing the `span` element to a `button` element.

**Additional issues**: No issues but read above. There are alternative solutions that may be easier resolutions. Another point to consider is simplifying the code for the `onTriggerEnter` cases.

### CODE REVIEW

**Review by nicolethoen — COMMENTED** [review]
I think this solution is good - I don't think we can change the span element to a button before the breaking change release since Progress stepper is not a beta component. Maybe we should open an issue in the core repo to document the thought for the breaking change release.

Can you also add a unit test to make sure that this onTriggerEnter prop continues working and we don't reintroduce this issue in the future?

**Comment by nicolethoen** [comment]
Edit: Progress stepper is still beta - idk what I was looking at. 
I did open the issue in core, so maybe we can ask @mcoker and @tlabaj if they think it's better to do it on the core side first rather than pull this in.

**Review by tlabaj — COMMENTED** [review]
Progress Stepper is still beta so we should be able to change the structure.  I think we should discuss with @mcoker if there are any concerns on the core side and wait for them to fix it there first so we stay in sync. 
cc @mcarrano

**Review by tlabaj — CHANGES_REQUESTED** [review]
We should wait for https://github.com/patternfly/patternfly/issues/4898
 to be resolved before we take this one in.

**Comment by mcoker** [comment]
@andyyvo yep! I just verified the changes needed to support this from core are in the main branch of the patternfly-react repo. The core change is just to add `border: 0` to the step-title element so that you can use a `<button>` HTML element there instead of a `<span>`. You can also remove the `tabindex` and `role` attribute when you switch the element to a `<button>` as those are redundant for the button element, though be sure and leave `type="button"` since a button's `type` is `submit` by default, and these buttons that trigger a popover are not submit buttons.

Screen Shot 2022-06-21 at 3 48 55 PM

File: packages/react-core/src/components/Popover/Popover.tsx [hunk 1]
```diff
@@ -368,6 +368,24 @@ export const Popover: React.FunctionComponent<PopoverProps> = ({
...
+        }
+      } else {
+        if (visible) {
+          hide();
+        } else {
+          show(true);
+        }
+      }
+    }
+  };
```
Comment (thatblindgeye) [inline packages/react-core/src/components/Popover/Popover.tsx:388]: I'm wondering if we still need this addition to Popover now that Progress Stepper is using a button. @tlabaj what do you think? I could see it being useful if someone *is* using a Popover on a non-button element at the very least.

**Review by thatblindgeye — CHANGES_REQUESTED** [review]
Starting to look good! Left some comments/changes below.

File: packages/react-core/src/components/ProgressStepper/ProgressStep.tsx [hunk 2]
```diff
@@ -92,6 +92,7 @@ export const ProgressStep: React.FunctionComponent<ProgressStepProps> = ({
           ref={stepRef}
           {...(popoverRender && { tabIndex: 0, role: 'button', type: 'button' })}
```
[the remark this answers is not in the document]
Comment (andyyvo) [reply packages/react-core/src/components/ProgressStepper/ProgressStep.tsx]: just made these changes

File: packages/react-core/src/components/Popover/Popover.tsx (hunk 1 above)
Comment (andyyvo) [reply packages/react-core/src/components/Popover/Popover.tsx:388]: I've pushed everything except for this suggested change (keep or remove). Let me know what the final verdict is and we should be all good to go on this!

**Review by tlabaj — APPROVED** [review]

**Review by thatblindgeye — APPROVED** [review]
Awesome work on this, especially for implementing that original logic to trigger the Popover on keyboard interaction! 💪🏼

**Review by nicolethoen — APPROVED** [review]

**Review by mcoker — APPROVED** [review]
Nice work!!
