### PR TITLE
fix(Nav): added role presentation to NavItemSeparator

### LINKED ISSUE #11717: Bug - NavItemSeparator - causes axe error inside NavLists
**Describe the problem**
A NavItemSeparator raises an axe error when used inside a NavList, due to it having `role="separator"` (from the Divider component being used) and NavList's `<ul>` expecting only `<li>`/`role="listitem"` children. This was raised during 6.2 testing in OCP Console.

**How do you reproduce the problem?**
Go to a Nav example and add a NavItemSeparator between 2 NavItems, then inspect the page and run a full page scan with axe. You should get the error "Certain ARIA roles must contain particular children"

**Expected behavior**
Axe doesn't have this error raised. Ideally we should:

- Create an interface for NavItemSeparator and explicitly expose props
- We should expose`component` and `role` as props for the sub-component, with the `component` default value able to remain an `li` and the `role` default value should be "presentation".
- The `component` prop type should match Divider (li, div, or hr), while the `role` prop type should probably only be "presentation" and "separator" (Divider handles logic to apply this role, and will only apply it if the component is anything except `hr` since that is semantically a separator role already).
- If we can, we should also think about exposing the `role` prop in Divider as well, with the same types as the above bullet and applying it on line ~53 of Divider code (where we're hardcoding the "separator" role)

**Is this issue blocking you?**
No, it can be worked around by manually passing a `role` to NavItemSeparator

**Screenshots**
If applicable, add screenshots to help explain the issue.

**What is your environment?**

**What is your product and what release date are you targeting?**

**Any other information?**

### PR DESCRIPTION
**Pull request by thatblindgeye**
**What**: Closes #11717 

Opted to not create an interface to expose for NavItemSeparator, as I'm wondering if we should consider deprecating it and just using the Divider component. Right now NavItemSeparator is just a wordier wrapper for Divider, and we're not doing anything special within it. One purpose of keeping this would be to have documentation explicitly about when to set the props to what (assuming we intend for this component to be used as either a separator between NavItems or just anywhere within a Nav; if the intent is only for between NavItems, then we should consider not allowing role or component to be customized).

**Additional issues**:

### CODE REVIEW

File: packages/react-core/src/components/Toolbar/ToolbarItem.tsx [hunk 1]
```diff
@@ -188,6 +188,8 @@ export const ToolbarItem: React.FunctionComponent<ToolbarItemProps> = ({
   ...props
 }: ToolbarItemProps) => {
   if (variant === ToolbarItemVariant.separator) {
+    // TODO: consider removing spread props here so we can update Divider role prop to union of
```
Comment (dlabaj) [inline packages/react-core/src/components/Toolbar/ToolbarItem.tsx:191]: Do we have an issue for this? Otherwise should we remove this comment?

**Review by dlabaj — APPROVED** [review]
LGTM just a comment about the TODO.

File: packages/react-core/src/components/Toolbar/ToolbarItem.tsx (hunk 1 above)
Comment (thatblindgeye) [reply packages/react-core/src/components/Toolbar/ToolbarItem.tsx]: I updated some logic to have the union type on the new prop so removed this comment

**Comment by kmcfaul** [comment]
I'd be in favor of moving to Divider long term
